import type {Metadata} from "next";
import {ContentPage,Section} from "@/components/content-page";
import {getServerI18n} from "@/lib/server-locale";

const copy={
 ru:{metaTitle:"Вакансии в Atlas One",metaDescription:"Карьера в Atlas One: продукт, разработка, продажи, поддержка организаторов и работа на мероприятиях.",eyebrow:"Карьера · Careers",title:"Работайте с нами",intro:"Мы строим билетную платформу для живых событий в Израиле и постепенно расширяем команду.",open:"Открытые позиции",none:"Сейчас публичных вакансий нет. Мы публикуем здесь только реальные открытые позиции с описанием обязанностей, условий и процесса подачи заявки.",people:"Какие специалисты нам интересны",peopleText:"Разработка и продукт, дизайн, работа с организаторами, продажи, клиентская поддержка, контент, маркетинг и операционная работа на мероприятиях.",apply:"Отклик",applyText:"Можно отправить краткое представление о себе через страницу контактов с темой «Карьера»."},
 he:{metaTitle:"דרושים ב-Atlas One",metaDescription:"קריירה ב-Atlas One: מוצר, פיתוח, מכירות, תמיכה במפיקים ותפעול אירועים.",eyebrow:"דרושים · Careers",title:"בואו לעבוד איתנו",intro:"אנחנו בונים פלטפורמת כרטוס לאירועים חיים בישראל ומרחיבים את הצוות בהדרגה.",open:"משרות פתוחות",none:"כרגע אין משרות פתוחות שפורסמו לציבור. בעמוד הזה נפרסם רק משרות אמיתיות עם פירוט התפקיד, התנאים ותהליך הגשת המועמדות.",people:"אילו אנשי מקצוע מעניינים אותנו",peopleText:"פיתוח ומוצר, עיצוב, עבודה עם מפיקים, מכירות, שירות לקוחות, תוכן, שיווק ותפעול בשטח באירועים.",apply:"הגשת מועמדות",applyText:"אפשר לשלוח הצגה קצרה דרך עמוד יצירת הקשר ולציין בנושא ההודעה ״קריירה״."},
 en:{metaTitle:"Careers at Atlas One",metaDescription:"Careers at Atlas One across product, engineering, sales, organizer support and live event operations.",eyebrow:"Careers",title:"Work with us",intro:"We are building a ticketing platform for live events in Israel and gradually expanding the team.",open:"Open positions",none:"There are currently no publicly listed openings. We use this page only for real roles with clear responsibilities, terms and an application process.",people:"The people we are interested in meeting",peopleText:"Engineering and product, design, organizer success, sales, customer support, content, marketing and live event operations.",apply:"Apply",applyText:"You can send a short introduction through the contact page and use “Careers” as the subject."}
} as const;

export async function generateMetadata():Promise<Metadata>{const{locale}=await getServerI18n();const t=copy[locale];return{title:t.metaTitle,description:t.metaDescription,alternates:{canonical:"/careers"}}}
export default async function CareersPage(){const{locale}=await getServerI18n();const t=copy[locale];return <ContentPage eyebrow={t.eyebrow} title={t.title} intro={t.intro}><Section title={t.open}><p>{t.none}</p></Section><Section title={t.people}><p>{t.peopleText}</p></Section><Section title={t.apply}><p>{t.applyText}</p></Section></ContentPage>}
