import type { User } from "@prisma/client";
import { db } from "@/lib/db";
import { writeAudit } from "@/lib/audit";
import { sendOrderRejectionEmail, sendOrderTicketEmail } from "@/lib/order-email";
import { captureTestAuthorization, voidTestAuthorization } from "@/lib/payment-authorization";
import { captureHypAuthorization, cancelHypAuthorization } from "@/lib/hyp-creditguard";
import { commitReservation, releaseReservation } from "@/lib/reservation";
import { cancelOrderTickets, issueTicketsForOrder } from "@/lib/ticket-engine";
import { parseEventRejectionMessage } from "@/lib/event-approval-message";

type Actor = Pick<User, "id" | "organizationId">;
export type OrderReviewAction = "approve" | "reject";
export type OrderReviewInput = { action: OrderReviewAction; note?: string };
type LegacyRuntimeRow = { exists: number | bigint };
type AuthorizationRow = { id:string; provider:string; status:string; amountMinor:number; currency:string; hypTransId:string|null; hypCaptureTransId:string|null };

let hypColumnsReady: Promise<void> | undefined;
function ensureHypApprovalColumns(){hypColumnsReady??=(async()=>{for(const statement of [`ALTER TABLE "PaymentAuthorization" ADD COLUMN IF NOT EXISTS "hypTransId" TEXT`,`ALTER TABLE "PaymentAuthorization" ADD COLUMN IF NOT EXISTS "hypAuthorizationTransId" TEXT`,`ALTER TABLE "PaymentAuthorization" ADD COLUMN IF NOT EXISTS "hypCaptureTransId" TEXT`,`ALTER TABLE "PaymentAuthorization" ADD COLUMN IF NOT EXISTS "hypCancelTransId" TEXT`,`ALTER TABLE "PaymentAuthorization" ADD COLUMN IF NOT EXISTS "hypCapturePayloadJson" TEXT`,`ALTER TABLE "PaymentAuthorization" ADD COLUMN IF NOT EXISTS "hypCancelPayloadJson" TEXT`])await db.$executeRawUnsafe(statement);})().catch(error=>{hypColumnsReady=undefined;throw error;});return hypColumnsReady;}
async function runtimeRecordExists(table:"PaymentAuthorization"|"Reservation",orderId:string,tx:typeof db){const rows=table==="PaymentAuthorization"?await tx.$queryRaw<LegacyRuntimeRow[]>`SELECT COUNT(*) AS exists FROM PaymentAuthorization WHERE orderId = ${orderId}`:await tx.$queryRaw<LegacyRuntimeRow[]>`SELECT COUNT(*) AS exists FROM Reservation WHERE orderId = ${orderId}`;return Number(rows[0]?.exists??0)>0;}
async function getAuthorization(orderId:string):Promise<AuthorizationRow|null>{await ensureHypApprovalColumns();const rows=await db.$queryRawUnsafe<AuthorizationRow[]>(`SELECT "id","provider","status","amountMinor","currency","hypTransId","hypCaptureTransId" FROM "PaymentAuthorization" WHERE "orderId"=$1 LIMIT 1`,orderId);return rows[0]??null;}
async function captureProviderAuthorization(authorization:AuthorizationRow){if(authorization.provider==="ATLAS_TEST")return;if(authorization.provider!=="HYP")throw new Error(`Неподдерживаемый провайдер авторизации: ${authorization.provider}`);if(authorization.status==="CAPTURED"&&authorization.hypCaptureTransId)return;if(authorization.status!=="AUTHORIZED"&&!(authorization.status==="CAPTURED"&&!authorization.hypCaptureTransId))throw new Error(`HYP-авторизация недоступна для списания: ${authorization.status}`);if(!authorization.hypTransId)throw new Error("HYP TransId не сохранён для завершения Postpone");const previousStatus=authorization.status;const claimed=await db.$executeRawUnsafe(`UPDATE "PaymentAuthorization" SET "status"='CAPTURING',"updatedAt"=CURRENT_TIMESTAMP WHERE "id"=$1 AND "status"=$2 AND "hypCaptureTransId" IS NULL`,authorization.id,previousStatus);if(claimed!==1)throw new Error("Эта заявка уже обрабатывается или уже была списана");try{const result=await captureHypAuthorization({transactionId:authorization.hypTransId,amountMinor:authorization.amountMinor,description:"Atlas organizer approval"});const updated=await db.$executeRawUnsafe(`UPDATE "PaymentAuthorization" SET "status"='CAPTURED',"hypAuthorizationTransId"=COALESCE("hypAuthorizationTransId","hypTransId"),"hypCaptureTransId"=NULLIF($2,''),"providerReference"=COALESCE(NULLIF($2,''),"providerReference"),"hypCapturePayloadJson"=$3,"capturedAt"=CURRENT_TIMESTAMP,"updatedAt"=CURRENT_TIMESTAMP WHERE "id"=$1 AND "status"='CAPTURING'`,authorization.id,result.captureTranId,result.rawResponse);if(updated!==1)throw new Error("Не удалось сохранить подтверждение списания HYP");console.info("hyp.approval.capture_completed",{authorizationId:authorization.id,sourceTransId:authorization.hypTransId,captureTransId:result.captureTranId});}catch(error){await db.$executeRawUnsafe(`UPDATE "PaymentAuthorization" SET "status"=$2,"updatedAt"=CURRENT_TIMESTAMP WHERE "id"=$1 AND "status"='CAPTURING'`,authorization.id,previousStatus).catch(()=>undefined);throw error;}}
async function cancelProviderAuthorization(authorization:AuthorizationRow){if(authorization.provider==="ATLAS_TEST")return;if(authorization.provider!=="HYP")throw new Error(`Неподдерживаемый провайдер авторизации: ${authorization.provider}`);if(authorization.status==="VOIDED")return;if(authorization.status==="CAPTURED")throw new Error("Оплата уже списана. Используйте возврат, а не отклонение заявки");if(authorization.status!=="AUTHORIZED")throw new Error(`HYP-авторизация недоступна для отмены: ${authorization.status}`);if(!authorization.hypTransId)throw new Error("HYP TransId не сохранён для отклонения Postpone");const claimed=await db.$executeRawUnsafe(`UPDATE "PaymentAuthorization" SET "status"='CANCELLING',"updatedAt"=CURRENT_TIMESTAMP WHERE "id"=$1 AND "status"='AUTHORIZED'`,authorization.id);if(claimed!==1)throw new Error("Эта заявка уже обрабатывается");try{const result=await cancelHypAuthorization({transactionId:authorization.hypTransId});await db.$executeRawUnsafe(`UPDATE "PaymentAuthorization" SET "status"='VOIDED',"hypAuthorizationTransId"=COALESCE("hypAuthorizationTransId","hypTransId"),"hypCancelTransId"=NULLIF($2,''),"hypCancelPayloadJson"=$3,"voidedAt"=CURRENT_TIMESTAMP,"updatedAt"=CURRENT_TIMESTAMP WHERE "id"=$1 AND "status"='CANCELLING'`,authorization.id,result.cancelTranId,result.rawResponse);}catch(error){await db.$executeRawUnsafe(`UPDATE "PaymentAuthorization" SET "status"='AUTHORIZED',"updatedAt"=CURRENT_TIMESTAMP WHERE "id"=$1 AND "status"='CANCELLING'`,authorization.id).catch(()=>undefined);throw error;}}

export async function reviewOrder(publicId:string,input:OrderReviewInput,actor:Actor){
 const target=await db.order.findUnique({where:{publicId},select:{id:true,eventId:true,customerName:true,status:true,totalMinor:true}});if(!target)throw new Error("Заявка не найдена");const authorization=await getAuthorization(target.id);
 if(input.action==="approve"&&target.status==="PAID"){if(!authorization||authorization.provider!=="HYP"||authorization.hypCaptureTransId)throw new Error("Эта заявка уже рассмотрена");if(authorization.amountMinor!==target.totalMinor)throw new Error("Сумма авторизации не совпадает с суммой заказа");await captureProviderAuthorization(authorization);let emailSent=false;let emailError:string|undefined;try{await sendOrderTicketEmail(publicId);emailSent=true;}catch(error){emailError=error instanceof Error?error.message:"Ошибка отправки билета";console.error("hyp.recovery.ticket_email_failed",{publicId,message:emailError});}await writeAudit(actor,{action:"REQUEST_CAPTURE_RECOVERED",entityType:"Order",entityId:target.id,summary:`Восстановлено реальное HYP-списание по заявке ${target.customerName}`,metadata:{publicId}});return{status:"PAID",emailSent,emailError,recoveredCapture:true,legacyDemoOrder:false};}
 if(target.status!=="PENDING_APPROVAL")throw new Error("Эта заявка уже рассмотрена");const hasReservation=await runtimeRecordExists("Reservation",target.id,db);const freeReservedOrder=!authorization&&hasReservation&&target.totalMinor===0;const legacyDemoOrder=!authorization&&!hasReservation;if(!legacyDemoOrder&&!freeReservedOrder&&!authorization)throw new Error("Предварительная авторизация оплаты не найдена");if(authorization&&authorization.amountMinor!==target.totalMinor)throw new Error("Сумма авторизации не совпадает с суммой заказа");
 if(input.action==="approve"&&!legacyDemoOrder){const active=await db.$queryRaw<Array<{exists:number|bigint}>>`SELECT COUNT(*) AS exists FROM Reservation WHERE orderId = ${target.id} AND status = 'ACTIVE' AND expiresAt > CURRENT_TIMESTAMP`;if(Number(active[0]?.exists??0)!==1)throw new Error("Срок резерва заявки истёк. Нельзя списывать оплату или выпускать билет");}
 if(authorization){if(input.action==="approve")await captureProviderAuthorization(authorization);else await cancelProviderAuthorization(authorization);}
 const order=await db.$transaction(async tx=>{
  const current=await tx.order.findUnique({where:{publicId},include:{event:{select:{description:true}},items:{include:{table:true,seat:true}},tickets:true}});if(!current||current.status!=="PENDING_APPROVAL")throw new Error("Эта заявка уже рассмотрена");
  const[hasAuthorization,reservationExists]=await Promise.all([runtimeRecordExists("PaymentAuthorization",current.id,tx as typeof db),runtimeRecordExists("Reservation",current.id,tx as typeof db)]);const authRows=hasAuthorization?await tx.$queryRaw<Array<{provider:string;status:string;hypCaptureTransId:string|null}>>`SELECT provider, status, "hypCaptureTransId" FROM PaymentAuthorization WHERE orderId = ${current.id} LIMIT 1`:[];const auth=authRows[0];
  if(input.action==="reject"){if(reservationExists)await releaseReservation(current.id,tx);if(auth?.provider==="ATLAS_TEST")await voidTestAuthorization(current.id,tx);if(auth?.provider==="HYP"&&auth.status!=="VOIDED")throw new Error("HYP Postpone не был закрыт без списания");await cancelOrderTickets(current.id,tx);const rejectionMessage=parseEventRejectionMessage(current.event.description);return tx.order.update({where:{id:current.id},data:{status:"REJECTED",reviewNote:input.note?.trim()||rejectionMessage,reviewedAt:new Date(),paymentDueAt:null}});}
  if(auth?.provider==="ATLAS_TEST")await captureTestAuthorization(current.id,tx);if(auth?.provider==="HYP"&&(auth.status!=="CAPTURED"||!auth.hypCaptureTransId))throw new Error("HYP не подтвердил реальное списание оплаты");if(reservationExists)await commitReservation(current.id,tx);
  for(const item of current.items){const category=await tx.ticketCategory.findUnique({where:{eventId_name:{eventId:current.eventId,name:item.categoryName}}});if(!category||category.sold+item.quantity>category.capacity)throw new Error(`Недостаточно мест в категории ${item.categoryName}`);if(item.seatId){const claimed=await tx.seat.updateMany({where:{id:item.seatId,status:"AVAILABLE"},data:{status:"RESERVED"}});if(claimed.count!==1)throw new Error("Выбранное место уже занято");}else if(item.tableId){const claimed=await tx.table.updateMany({where:{id:item.tableId,reserved:false},data:{reserved:true}});if(claimed.count!==1)throw new Error("Выбранный стол уже занят");}await tx.ticketCategory.update({where:{id:category.id},data:{sold:{increment:item.quantity}}});}
  const paid=await tx.order.update({where:{id:current.id},data:{status:"PAID",reviewNote:input.note||(legacyDemoOrder?"Одобрено как демо-заказ без авторизации оплаты":freeReservedOrder?"Одобрено бесплатное приглашение":null),reviewedAt:new Date(),paymentDueAt:null}});await issueTicketsForOrder(current.id,tx);return paid;
 });
 const auditAction=input.action==="approve"?(legacyDemoOrder?"LEGACY_REQUEST_APPROVED":freeReservedOrder?"FREE_GUEST_REQUEST_APPROVED":"REQUEST_APPROVED_AND_CAPTURED"):"REQUEST_REJECTED_WITHOUT_COMMIT";await writeAudit(actor,{action:auditAction,entityType:"Order",entityId:target.id,summary:`${input.action==="approve"?"Одобрена":"Отклонена"} заявка ${target.customerName}${legacyDemoOrder?" (демо-заказ без оплаты)":freeReservedOrder?" (бесплатное приглашение)":""}`,metadata:{publicId,legacyDemoOrder,freeReservedOrder,paymentProvider:authorization?.provider||null}});
 let emailSent=false;let emailError:string|undefined;try{if(order.status==="PAID"){await sendOrderTicketEmail(publicId);emailSent=true;}else if(order.status==="REJECTED"){await sendOrderRejectionEmail(publicId);emailSent=true;}}catch(error){emailError=error instanceof Error?error.message:"Ошибка отправки уведомления";}return{status:order.status,emailSent,emailError,legacyDemoOrder,recoveredCapture:false};
}
