import { createHash,randomBytes,scrypt as scryptCb,timingSafeEqual } from "node:crypto";
import { promisify } from "node:util";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import { db } from "@/lib/db";
import { ensurePromoterV2Runtime,getPromoterV2 } from "@/lib/promoter-v2";

const scrypt=promisify(scryptCb),COOKIE="atlas_promoter_v2_session";let ready:Promise<void>|null=null;
type Account={promoterId:string;email:string;passwordHash:string|null;status:string;activatedAt:Date|null;lastLoginAt:Date|null};
function origin(){if(process.env.VERCEL_ENV==="preview"&&process.env.VERCEL_URL)return `https://${process.env.VERCEL_URL}`;return(process.env.PUBLIC_APP_URL||"https://www.atlas-one.co").replace(/\/$/,"")}
function hash(v:string){return createHash("sha256").update(v).digest("hex")}
async function passwordHash(p:string){if(p.length<8)throw new Error("Пароль должен содержать минимум 8 символов");const salt=randomBytes(16).toString("hex"),derived=await scrypt(p,salt,64) as Buffer;return`scrypt$${salt}$${derived.toString("hex")}`}
async function verify(p:string,v:string){const[a,s,h]=v.split("$");if(a!=="scrypt"||!s||!h)return false;const d=await scrypt(p,s,64) as Buffer,b=Buffer.from(h,"hex");return b.length===d.length&&timingSafeEqual(b,d)}
function esc(v:string){return v.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]||c))}
async function mail(to:string,subject:string,html:string){const key=process.env.RESEND_API_KEY;if(!key)throw new Error("RESEND_NOT_CONFIGURED");const configured=process.env.RESEND_FROM_EMAIL?.trim(),from=configured&&configured.includes("@")&&!configured.startsWith("re_")?configured:"Atlas One <tickets@mail.atlas-one.co>";const recipient=process.env.RESEND_TEST_TO||to;const r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({from,to:[recipient],subject,html})});if(!r.ok)throw new Error(`EMAIL_${r.status}`)}

export async function ensurePromoterAuthV2Runtime(){if(!ready)ready=(async()=>{await ensurePromoterV2Runtime();await db.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "PromoterAccountV2" ("promoterId" TEXT PRIMARY KEY,"email" TEXT NOT NULL,"passwordHash" TEXT,"status" TEXT NOT NULL DEFAULT 'PENDING',"activatedAt" TIMESTAMP(3),"lastLoginAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "PromoterAccountV2_promoter_fkey" FOREIGN KEY ("promoterId") REFERENCES "PromoterV2"("id") ON DELETE RESTRICT ON UPDATE CASCADE)`);await db.$executeRawUnsafe(`CREATE UNIQUE INDEX IF NOT EXISTS "PromoterAccountV2_email_key" ON "PromoterAccountV2"(LOWER("email"))`);await db.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "PromoterAuthTokenV2" ("id" TEXT PRIMARY KEY,"promoterId" TEXT NOT NULL,"tokenHash" TEXT NOT NULL UNIQUE,"purpose" TEXT NOT NULL,"expiresAt" TIMESTAMP(3) NOT NULL,"usedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "PromoterAuthTokenV2_promoter_fkey" FOREIGN KEY ("promoterId") REFERENCES "PromoterV2"("id") ON DELETE RESTRICT ON UPDATE CASCADE)`);await db.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "PromoterSessionV2" ("id" TEXT PRIMARY KEY,"promoterId" TEXT NOT NULL,"tokenHash" TEXT NOT NULL UNIQUE,"expiresAt" TIMESTAMP(3) NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"lastSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "PromoterSessionV2_promoter_fkey" FOREIGN KEY ("promoterId") REFERENCES "PromoterV2"("id") ON DELETE RESTRICT ON UPDATE CASCADE)`);})().catch(e=>{ready=null;throw e});return ready}
async function account(promoterId:string){await ensurePromoterAuthV2Runtime();const r=await db.$queryRawUnsafe<Account[]>(`SELECT "promoterId","email","passwordHash","status","activatedAt","lastLoginAt" FROM "PromoterAccountV2" WHERE "promoterId"=$1 LIMIT 1`,promoterId);return r[0]||null}
export async function promoterAccountV2State(promoterId:string){return(await account(promoterId))?.status||"NOT_INVITED"}
async function issue(promoterId:string,purpose:"ACTIVATION"|"RESET",hours:number){await ensurePromoterAuthV2Runtime();const token=randomBytes(32).toString("base64url"),expires=new Date(Date.now()+hours*3600000);if(purpose==="RESET")await db.$executeRawUnsafe(`UPDATE "PromoterAuthTokenV2" SET "usedAt"=CURRENT_TIMESTAMP WHERE "promoterId"=$1 AND "purpose"=$2 AND "usedAt" IS NULL`,promoterId,purpose);await db.$executeRawUnsafe(`INSERT INTO "PromoterAuthTokenV2" ("id","promoterId","tokenHash","purpose","expiresAt") VALUES ($1,$2,$3,$4,$5)`,randomBytes(16).toString("hex"),promoterId,hash(token),purpose,expires);return token}
export async function invitePromoterV2(promoterId:string,force=false){await ensurePromoterAuthV2Runtime();const p=await getPromoterV2(promoterId);if(!p||!p.active)throw new Error("PROMOTER_NOT_FOUND");const existing=await account(p.id);if(existing?.status==="ACTIVE"&&!force)return{status:"ACTIVE"};await db.$executeRawUnsafe(`INSERT INTO "PromoterAccountV2" ("promoterId","email","status") VALUES ($1,$2,'PENDING') ON CONFLICT ("promoterId") DO UPDATE SET "email"=EXCLUDED."email","status"=CASE WHEN "PromoterAccountV2"."status"='ACTIVE' THEN 'ACTIVE' ELSE 'PENDING' END,"updatedAt"=CURRENT_TIMESTAMP`,p.id,p.email.toLowerCase());const token=await issue(p.id,"ACTIVATION",72),url=`${origin()}/promoter/activate?token=${encodeURIComponent(token)}`;const org=await db.organization.findUnique({where:{id:p.organizationId},select:{name:true}});await mail(p.email,"Welcome to Atlas One - activate your promoter account",`<div style="font-family:Arial;max-width:620px;margin:auto"><h1>Welcome to Atlas One</h1><p>Привет, ${esc(p.name)}!</p><p>${esc(org?.name||"Организатор")} добавил вас как промоутера.</p><p>Создайте пароль для защищённого кабинета. Ссылка действует 72 часа.</p><p><a href="${url}" style="display:inline-block;padding:14px 20px;background:#ff5c45;color:white;text-decoration:none;border-radius:10px">Активировать аккаунт</a></p></div>`);return{status:"PENDING"}}
async function validate(token:string,purpose:"ACTIVATION"|"RESET"){await ensurePromoterAuthV2Runtime();const r=await db.$queryRawUnsafe<Array<{promoterId:string;expiresAt:Date;usedAt:Date|null}>>(`SELECT "promoterId","expiresAt","usedAt" FROM "PromoterAuthTokenV2" WHERE "tokenHash"=$1 AND "purpose"=$2 LIMIT 1`,hash(token),purpose),x=r[0];return!x||x.usedAt||new Date(x.expiresAt).getTime()<Date.now()?null:x.promoterId}
export async function activatePromoterV2(token:string,password:string){const id=await validate(token,"ACTIVATION");if(!id)throw new Error("Ссылка активации недействительна или истекла");const ph=await passwordHash(password);await db.$transaction(async tx=>{await tx.$executeRawUnsafe(`UPDATE "PromoterAccountV2" SET "passwordHash"=$2,"status"='ACTIVE',"activatedAt"=COALESCE("activatedAt",CURRENT_TIMESTAMP),"updatedAt"=CURRENT_TIMESTAMP WHERE "promoterId"=$1`,id,ph);await tx.$executeRawUnsafe(`UPDATE "PromoterAuthTokenV2" SET "usedAt"=CURRENT_TIMESTAMP WHERE "promoterId"=$1 AND "purpose"='ACTIVATION' AND "usedAt" IS NULL`,id)});return id}
export async function createPromoterV2Session(id:string){await ensurePromoterAuthV2Runtime();const token=randomBytes(32).toString("base64url"),exp=new Date(Date.now()+30*86400000);await db.$executeRawUnsafe(`INSERT INTO "PromoterSessionV2" ("id","promoterId","tokenHash","expiresAt") VALUES ($1,$2,$3,$4)`,randomBytes(16).toString("hex"),id,hash(token),exp);await db.$executeRawUnsafe(`UPDATE "PromoterAccountV2" SET "lastLoginAt"=CURRENT_TIMESTAMP WHERE "promoterId"=$1`,id);const c=await cookies();c.set(COOKIE,token,{httpOnly:true,secure:true,sameSite:"lax",path:"/",expires:exp})}
export async function loginPromoterV2(email:string,password:string){await ensurePromoterAuthV2Runtime();const r=await db.$queryRawUnsafe<Account[]>(`SELECT "promoterId","email","passwordHash","status","activatedAt","lastLoginAt" FROM "PromoterAccountV2" WHERE LOWER("email")=LOWER($1) LIMIT 1`,email.trim()),a=r[0];if(!a||a.status!=="ACTIVE"||!a.passwordHash||!(await verify(password,a.passwordHash)))throw new Error("Неверный email или пароль");const p=await getPromoterV2(a.promoterId);if(!p?.active)throw new Error("Доступ к кабинету отключён");await createPromoterV2Session(p.id);return p.id}
export async function forgotPromoterV2(email:string){await ensurePromoterAuthV2Runtime();const r=await db.$queryRawUnsafe<Account[]>(`SELECT "promoterId","email","passwordHash","status","activatedAt","lastLoginAt" FROM "PromoterAccountV2" WHERE LOWER("email")=LOWER($1) LIMIT 1`,email.trim()),a=r[0];if(!a||a.status!=="ACTIVE")return;const token=await issue(a.promoterId,"RESET",2),url=`${origin()}/promoter/reset-password?token=${encodeURIComponent(token)}`;await mail(a.email,"Atlas One - password reset",`<div style="font-family:Arial"><h1>Сброс пароля</h1><p><a href="${url}">Создать новый пароль</a></p><p>Ссылка действует 2 часа.</p></div>`)}
export async function resetPromoterV2(token:string,password:string){const id=await validate(token,"RESET");if(!id)throw new Error("Ссылка сброса недействительна или истекла");const ph=await passwordHash(password);await db.$transaction(async tx=>{await tx.$executeRawUnsafe(`UPDATE "PromoterAccountV2" SET "passwordHash"=$2 WHERE "promoterId"=$1`,id,ph);await tx.$executeRawUnsafe(`UPDATE "PromoterAuthTokenV2" SET "usedAt"=CURRENT_TIMESTAMP WHERE "tokenHash"=$1`,hash(token));await tx.$executeRawUnsafe(`DELETE FROM "PromoterSessionV2" WHERE "promoterId"=$1`,id)});return id}
export async function logoutPromoterV2(){const c=await cookies(),token=c.get(COOKIE)?.value;if(token){await ensurePromoterAuthV2Runtime();await db.$executeRawUnsafe(`DELETE FROM "PromoterSessionV2" WHERE "tokenHash"=$1`,hash(token))}c.delete(COOKIE)}
export async function currentPromoterV2(){await ensurePromoterAuthV2Runtime();const c=await cookies(),token=c.get(COOKIE)?.value;if(!token)return null;const r=await db.$queryRawUnsafe<Array<{promoterId:string}>>(`SELECT "promoterId" FROM "PromoterSessionV2" WHERE "tokenHash"=$1 AND "expiresAt">CURRENT_TIMESTAMP LIMIT 1`,hash(token));if(!r[0])return null;const p=await getPromoterV2(r[0].promoterId);return p?.active?p:null}
export async function requirePromoterV2(){const p=await currentPromoterV2();if(!p)redirect("/promoter/login");return p}
