import { createHash,randomBytes,scrypt as scryptCb,timingSafeEqual } from "node:crypto";
import { promisify } from "node:util";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import { db } from "@/lib/db";
import { ensurePromoterV2Runtime,getPromoterV2 } from "@/lib/promoter-v2";
import { localeConfig,normalizeLocale,type Locale } from "@/lib/i18n";

const scrypt=promisify(scryptCb),COOKIE="atlas_promoter_v2_session";let ready:Promise<void>|null=null;
type Account={promoterId:string;email:string;passwordHash:string|null;status:string;activatedAt:Date|null;lastLoginAt:Date|null};
const authMailCopy={
 ru:{inviteSubject:"Atlas One - активация аккаунта промоутера",inviteTitle:"Добро пожаловать в Atlas One",inviteHello:"Здравствуйте",inviteAdded:"добавил вас как промоутера.",inviteText:"Создайте пароль для защищённого кабинета. Ссылка действует 72 часа.",inviteButton:"Активировать аккаунт",resetSubject:"Atlas One - восстановление пароля",resetTitle:"Восстановление пароля",resetText:"Создайте новый пароль для аккаунта промоутера.",resetButton:"Создать новый пароль",resetExpiry:"Ссылка действует 2 часа."},
 he:{inviteSubject:"Atlas One - הפעלת חשבון פרומוטר",inviteTitle:"ברוכים הבאים ל-Atlas One",inviteHello:"שלום",inviteAdded:"צירף אתכם כפרומוטרים.",inviteText:"כדי להיכנס לפורטל המאובטח, צרו סיסמה אישית. הקישור תקף למשך 72 שעות.",inviteButton:"הפעלת החשבון",resetSubject:"Atlas One - שחזור סיסמה",resetTitle:"שחזור סיסמה",resetText:"צרו סיסמה חדשה לחשבון הפרומוטר.",resetButton:"יצירת סיסמה חדשה",resetExpiry:"הקישור תקף למשך שעתיים."},
 en:{inviteSubject:"Atlas One - activate your promoter account",inviteTitle:"Welcome to Atlas One",inviteHello:"Hello",inviteAdded:"added you as a promoter.",inviteText:"Create a personal password for your secure portal. The link is valid for 72 hours.",inviteButton:"Activate account",resetSubject:"Atlas One - password reset",resetTitle:"Reset your password",resetText:"Create a new password for your promoter account.",resetButton:"Create new password",resetExpiry:"The link is valid for 2 hours."}
} as const;
function origin(){if(process.env.VERCEL_ENV==="preview"&&process.env.VERCEL_URL)return `https://${process.env.VERCEL_URL}`;return(process.env.PUBLIC_APP_URL||"https://www.atlas-one.co").replace(/\/$/,"")}
function hash(v:string){return createHash("sha256").update(v).digest("hex")}
async function passwordHash(p:string){if(p.length<8)throw new Error("PASSWORD_TOO_SHORT");const salt=randomBytes(16).toString("hex"),derived=await scrypt(p,salt,64) as Buffer;return`scrypt$${salt}$${derived.toString("hex")}`}
async function verify(p:string,v:string){const[a,s,h]=v.split("$");if(a!=="scrypt"||!s||!h)return false;const d=await scrypt(p,s,64) as Buffer,b=Buffer.from(h,"hex");return b.length===d.length&&timingSafeEqual(b,d)}
function esc(v:string){return v.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]||c))}
async function mail(to:string,subject:string,html:string){const key=process.env.RESEND_API_KEY;if(!key)throw new Error("RESEND_NOT_CONFIGURED");const configured=process.env.RESEND_FROM_EMAIL?.trim(),from=configured&&configured.includes("@")&&!configured.startsWith("re_")?configured:"Atlas One <tickets@mail.atlas-one.co>";const recipient=process.env.RESEND_TEST_TO||to;const r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({from,to:[recipient],subject,html})});if(!r.ok)throw new Error(`EMAIL_${r.status}`)}
async function organizationLocale(organizationId:string){const org=await db.organization.findUnique({where:{id:organizationId},select:{defaultStaffLocale:true}});return normalizeLocale(org?.defaultStaffLocale)}
function mailShell(locale:Locale,title:string,body:string){const cfg=localeConfig[locale];return `<div lang="${cfg.tag}" dir="${cfg.dir}" style="font-family:Arial,sans-serif;max-width:620px;margin:auto;color:#101828"><div style="background:#081426;color:#fff;padding:26px"><strong>Atlas One</strong><h1 style="margin:12px 0 0">${esc(title)}</h1></div><div style="padding:26px;border:1px solid #eaecf0;border-top:0">${body}</div></div>`}

export async function ensurePromoterAuthV2Runtime(){if(!ready)ready=(async()=>{await ensurePromoterV2Runtime();await db.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "PromoterAccountV2" ("promoterId" TEXT PRIMARY KEY,"email" TEXT NOT NULL,"passwordHash" TEXT,"status" TEXT NOT NULL DEFAULT 'PENDING',"activatedAt" TIMESTAMP(3),"lastLoginAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "PromoterAccountV2_promoter_fkey" FOREIGN KEY ("promoterId") REFERENCES "PromoterV2"("id") ON DELETE RESTRICT ON UPDATE CASCADE)`);await db.$executeRawUnsafe(`CREATE UNIQUE INDEX IF NOT EXISTS "PromoterAccountV2_email_key" ON "PromoterAccountV2"(LOWER("email"))`);await db.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "PromoterAuthTokenV2" ("id" TEXT PRIMARY KEY,"promoterId" TEXT NOT NULL,"tokenHash" TEXT NOT NULL UNIQUE,"purpose" TEXT NOT NULL,"expiresAt" TIMESTAMP(3) NOT NULL,"usedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "PromoterAuthTokenV2_promoter_fkey" FOREIGN KEY ("promoterId") REFERENCES "PromoterV2"("id") ON DELETE RESTRICT ON UPDATE CASCADE)`);await db.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "PromoterSessionV2" ("id" TEXT PRIMARY KEY,"promoterId" TEXT NOT NULL,"tokenHash" TEXT NOT NULL UNIQUE,"expiresAt" TIMESTAMP(3) NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"lastSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "PromoterSessionV2_promoter_fkey" FOREIGN KEY ("promoterId") REFERENCES "PromoterV2"("id") ON DELETE RESTRICT ON UPDATE CASCADE)`);})().catch(e=>{ready=null;throw e});return ready}
async function account(promoterId:string){await ensurePromoterAuthV2Runtime();const r=await db.$queryRawUnsafe<Account[]>(`SELECT "promoterId","email","passwordHash","status","activatedAt","lastLoginAt" FROM "PromoterAccountV2" WHERE "promoterId"=$1 LIMIT 1`,promoterId);return r[0]||null}
export async function promoterAccountV2State(promoterId:string){return(await account(promoterId))?.status||"NOT_INVITED"}
async function issue(promoterId:string,purpose:"ACTIVATION"|"RESET",hours:number){await ensurePromoterAuthV2Runtime();const token=randomBytes(32).toString("base64url"),expires=new Date(Date.now()+hours*3600000);if(purpose==="RESET")await db.$executeRawUnsafe(`UPDATE "PromoterAuthTokenV2" SET "usedAt"=CURRENT_TIMESTAMP WHERE "promoterId"=$1 AND "purpose"=$2 AND "usedAt" IS NULL`,promoterId,purpose);await db.$executeRawUnsafe(`INSERT INTO "PromoterAuthTokenV2" ("id","promoterId","tokenHash","purpose","expiresAt") VALUES ($1,$2,$3,$4,$5)`,randomBytes(16).toString("hex"),promoterId,hash(token),purpose,expires);return token}
export async function invitePromoterV2(promoterId:string,force=false){await ensurePromoterAuthV2Runtime();const p=await getPromoterV2(promoterId);if(!p||!p.active)throw new Error("PROMOTER_NOT_FOUND");const existing=await account(p.id);if(existing?.status==="ACTIVE"&&!force)return{status:"ACTIVE"};await db.$executeRawUnsafe(`INSERT INTO "PromoterAccountV2" ("promoterId","email","status") VALUES ($1,$2,'PENDING') ON CONFLICT ("promoterId") DO UPDATE SET "email"=EXCLUDED."email","status"=CASE WHEN "PromoterAccountV2"."status"='ACTIVE' THEN 'ACTIVE' ELSE 'PENDING' END,"updatedAt"=CURRENT_TIMESTAMP`,p.id,p.email.toLowerCase());const token=await issue(p.id,"ACTIVATION",72),url=`${origin()}/promoter/activate?token=${encodeURIComponent(token)}`;const org=await db.organization.findUnique({where:{id:p.organizationId},select:{name:true,defaultStaffLocale:true}});const locale=normalizeLocale(org?.defaultStaffLocale);const c=authMailCopy[locale];const body=`<p>${c.inviteHello}, ${esc(p.name)}.</p><p><strong>${esc(org?.name||"Atlas One")}</strong> ${c.inviteAdded}</p><p>${c.inviteText}</p><p style="text-align:center;margin:28px 0"><a href="${url}" style="display:inline-block;padding:14px 20px;background:#ff5c45;color:white;text-decoration:none;border-radius:10px;font-weight:700">${c.inviteButton}</a></p>`;await mail(p.email,c.inviteSubject,mailShell(locale,c.inviteTitle,body));return{status:"PENDING"}}
async function validate(token:string,purpose:"ACTIVATION"|"RESET"){await ensurePromoterAuthV2Runtime();const r=await db.$queryRawUnsafe<Array<{promoterId:string;expiresAt:Date;usedAt:Date|null}>>(`SELECT "promoterId","expiresAt","usedAt" FROM "PromoterAuthTokenV2" WHERE "tokenHash"=$1 AND "purpose"=$2 LIMIT 1`,hash(token),purpose),x=r[0];return!x||x.usedAt||new Date(x.expiresAt).getTime()<Date.now()?null:x.promoterId}
export async function activatePromoterV2(token:string,password:string){const id=await validate(token,"ACTIVATION");if(!id)throw new Error("PROMOTER_ACTIVATION_INVALID");const ph=await passwordHash(password);await db.$transaction(async tx=>{await tx.$executeRawUnsafe(`UPDATE "PromoterAccountV2" SET "passwordHash"=$2,"status"='ACTIVE',"activatedAt"=COALESCE("activatedAt",CURRENT_TIMESTAMP),"updatedAt"=CURRENT_TIMESTAMP WHERE "promoterId"=$1`,id,ph);await tx.$executeRawUnsafe(`UPDATE "PromoterAuthTokenV2" SET "usedAt"=CURRENT_TIMESTAMP WHERE "promoterId"=$1 AND "purpose"='ACTIVATION' AND "usedAt" IS NULL`,id)});return id}
export async function createPromoterV2Session(id:string){await ensurePromoterAuthV2Runtime();const token=randomBytes(32).toString("base64url"),exp=new Date(Date.now()+30*86400000);await db.$executeRawUnsafe(`INSERT INTO "PromoterSessionV2" ("id","promoterId","tokenHash","expiresAt") VALUES ($1,$2,$3,$4)`,randomBytes(16).toString("hex"),id,hash(token),exp);await db.$executeRawUnsafe(`UPDATE "PromoterAccountV2" SET "lastLoginAt"=CURRENT_TIMESTAMP WHERE "promoterId"=$1`,id);const c=await cookies();c.set(COOKIE,token,{httpOnly:true,secure:true,sameSite:"lax",path:"/",expires:exp})}
export async function loginPromoterV2(email:string,password:string){await ensurePromoterAuthV2Runtime();const r=await db.$queryRawUnsafe<Account[]>(`SELECT "promoterId","email","passwordHash","status","activatedAt","lastLoginAt" FROM "PromoterAccountV2" WHERE LOWER("email")=LOWER($1) LIMIT 1`,email.trim()),a=r[0];if(!a||a.status!=="ACTIVE"||!a.passwordHash||!(await verify(password,a.passwordHash)))throw new Error("PROMOTER_LOGIN_INVALID");const p=await getPromoterV2(a.promoterId);if(!p?.active)throw new Error("PROMOTER_ACCESS_DISABLED");await createPromoterV2Session(p.id);return p.id}
export async function forgotPromoterV2(email:string,requestedLocale?:string){await ensurePromoterAuthV2Runtime();const r=await db.$queryRawUnsafe<Account[]>(`SELECT "promoterId","email","passwordHash","status","activatedAt","lastLoginAt" FROM "PromoterAccountV2" WHERE LOWER("email")=LOWER($1) LIMIT 1`,email.trim()),a=r[0];if(!a||a.status!=="ACTIVE")return;const p=await getPromoterV2(a.promoterId);const locale=requestedLocale?normalizeLocale(requestedLocale):p?await organizationLocale(p.organizationId):"ru";const c=authMailCopy[locale];const token=await issue(a.promoterId,"RESET",2),url=`${origin()}/promoter/reset-password?token=${encodeURIComponent(token)}`;const body=`<p>${c.resetText}</p><p style="text-align:center;margin:28px 0"><a href="${url}" style="display:inline-block;padding:14px 20px;background:#ff5c45;color:white;text-decoration:none;border-radius:10px;font-weight:700">${c.resetButton}</a></p><p>${c.resetExpiry}</p>`;await mail(a.email,c.resetSubject,mailShell(locale,c.resetTitle,body))}
export async function resetPromoterV2(token:string,password:string){const id=await validate(token,"RESET");if(!id)throw new Error("PROMOTER_RESET_INVALID");const ph=await passwordHash(password);await db.$transaction(async tx=>{await tx.$executeRawUnsafe(`UPDATE "PromoterAccountV2" SET "passwordHash"=$2 WHERE "promoterId"=$1`,id,ph);await tx.$executeRawUnsafe(`UPDATE "PromoterAuthTokenV2" SET "usedAt"=CURRENT_TIMESTAMP WHERE "tokenHash"=$1`,hash(token));await tx.$executeRawUnsafe(`DELETE FROM "PromoterSessionV2" WHERE "promoterId"=$1`,id)});return id}
export async function logoutPromoterV2(){const c=await cookies(),token=c.get(COOKIE)?.value;if(token){await ensurePromoterAuthV2Runtime();await db.$executeRawUnsafe(`DELETE FROM "PromoterSessionV2" WHERE "tokenHash"=$1`,hash(token))}c.delete(COOKIE)}
export async function currentPromoterV2(){await ensurePromoterAuthV2Runtime();const c=await cookies(),token=c.get(COOKIE)?.value;if(!token)return null;const r=await db.$queryRawUnsafe<Array<{promoterId:string}>>(`SELECT "promoterId" FROM "PromoterSessionV2" WHERE "tokenHash"=$1 AND "expiresAt">CURRENT_TIMESTAMP LIMIT 1`,hash(token));if(!r[0])return null;const p=await getPromoterV2(r[0].promoterId);return p?.active?p:null}
export async function requirePromoterV2(){const p=await currentPromoterV2();if(!p)redirect("/promoter/login");return p}
