import { db } from "@/lib/db";
import { decryptIntegrationSecret } from "@/lib/integration-secrets";
import { ensureOrganizationIntegrationsTable } from "@/lib/organization-integrations";

type IntegrationRow={enabled:boolean;credentialsEncrypted:string|null};
export type ValueCardMember={memberId:number|null;cardNumber:string|null;fullName:string|null};
function phoneVariants(input:string){const digits=input.replace(/\D/g,"");const values=new Set<string>();if(!digits)return [];values.add(digits);if(digits.startsWith("972")&&digits.length>=11)values.add(`0${digits.slice(3)}`);if(digits.startsWith("0"))values.add(`972${digits.slice(1)}`);return [...values];}
function parsePayload(text:string):unknown{let payload:unknown=text;for(let i=0;i<2;i++){if(typeof payload!=="string")break;const trimmed=payload.trim();if(!trimmed||(!trimmed.startsWith("{")&&!trimmed.startsWith("[")&&!trimmed.startsWith('"')))break;try{payload=JSON.parse(trimmed);}catch{break;}}return payload;}
function commonInfo(value:unknown){if(!value||typeof value!=="object"||Array.isArray(value))return null;const obj=value as Record<string,unknown>;const common=(obj.common??obj.Common) as Record<string,unknown>|undefined;if(!common||typeof common!=="object")return null;return {isError:common.isError??common.IsError??null,returnCode:common.returnCode??common.ReturnCode??null,httpCode:common.httpCode??common.HttpCode??null};}
function findMember(value:unknown):ValueCardMember|null{if(!value)return null;if(Array.isArray(value)){for(const item of value){const found=findMember(item);if(found)return found;}return null;}if(typeof value!=="object")return null;const obj=value as Record<string,unknown>;const common=(obj.common??obj.Common) as Record<string,unknown>|undefined;if(common&&(common.isError===true||common.IsError===true))return null;const idValue=obj.memberId??obj.MemberId??obj.memberID??obj.MemberID??obj.MemberKey??obj.memberKey;const cardValue=obj.memberCardNumber??obj.MemberCardNumber??obj.cardNumber??obj.CardNumber??obj.cardNum??obj.CardNum;if(idValue!==undefined||cardValue!==undefined){const parsed=typeof idValue==="number"?idValue:Number(idValue);return {memberId:Number.isFinite(parsed)&&parsed>0?parsed:null,cardNumber:cardValue?String(cardValue):null,fullName:String(obj.memberFullName??obj.MemberFullName??obj.fullName??obj.FullName??obj.name??obj.Name??"")||null};}for(const [key,nested] of Object.entries(obj)){if(key.toLowerCase()==="common")continue;if(nested&&typeof nested==="object"){const found=findMember(nested);if(found)return found;}}return null;}
export async function getValueCardToken(organizationId:string){await ensureOrganizationIntegrationsTable();const rows=await db.$queryRaw<IntegrationRow[]>`SELECT "enabled","credentialsEncrypted" FROM "OrganizationIntegration" WHERE "organizationId"=${organizationId} AND "provider"='VALUECARD' LIMIT 1`;const row=rows[0];if(!row?.enabled||!row.credentialsEncrypted){console.info("valuecard.lookup.disabled",{organizationId,enabled:Boolean(row?.enabled),configured:Boolean(row?.credentialsEncrypted)});return null;}return decryptIntegrationSecret(row.credentialsEncrypted);}
export async function searchValueCardMember(organizationId:string,phone:string):Promise<ValueCardMember|null>{const token=await getValueCardToken(organizationId);if(!token)return null;const variants=phoneVariants(phone);for(let index=0;index<variants.length;index++){const cellPhone=variants[index];const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),5000);try{const url=new URL("https://valuecard.co.il/api/pos/club_member/SearchClubMember");url.searchParams.set("cellPhone",cellPhone);const response=await fetch(url,{headers:{Authorization:token.toLowerCase().startsWith("bearer ")?token:`Bearer ${token}`,Accept:"application/json, text/plain"},cache:"no-store",signal:controller.signal});const contentType=response.headers.get("content-type")||"";if(!response.ok){console.info("valuecard.lookup.http_error",{organizationId,status:response.status,contentType,variant:index+1});continue;}const text=await response.text();if(!text){console.info("valuecard.lookup.empty",{organizationId,status:response.status,contentType,variant:index+1});continue;}const payload=parsePayload(text);const member=findMember(payload);const common=commonInfo(payload);console.info("valuecard.lookup.result",{organizationId,status:response.status,contentType,variant:index+1,found:Boolean(member),common});if(member)return member;}catch(error){console.info("valuecard.lookup.exception",{organizationId,variant:index+1,message:error instanceof Error?error.message:"Unknown error"});}finally{clearTimeout(timer);}}return null;}
export async function searchValueCardMembers(organizationId:string,phones:string[]){const unique=[...new Set(phones.filter(Boolean))];const pairs=await Promise.all(unique.map(async phone=>[phone,await searchValueCardMember(organizationId,phone)] as const));return new Map(pairs);}
