import { randomBytes } from "node:crypto";
import { PKPass } from "passkit-generator";
import { PNG } from "pngjs";
import { db } from "@/lib/db";
import { parseTicketDesign } from "@/lib/ticket-template";

export function walletConfigured(){return Boolean(process.env.APPLE_WALLET_PASS_TYPE_ID&&process.env.APPLE_WALLET_TEAM_ID&&process.env.APPLE_WALLET_SIGNER_CERT_BASE64&&process.env.APPLE_WALLET_SIGNER_KEY_BASE64&&process.env.APPLE_WALLET_WWDR_CERT_BASE64)}
function solidIcon(hex:string){const clean=hex.replace("#","");const [r,g,b]=[0,2,4].map(index=>Number.parseInt(clean.slice(index,index+2),16));const png=new PNG({width:87,height:87});for(let i=0;i<png.data.length;i+=4){png.data[i]=r;png.data[i+1]=g;png.data[i+2]=b;png.data[i+3]=255}return PNG.sync.write(png)}
function rgbColor(hex:string){const clean=hex.replace("#","");return `rgb(${Number.parseInt(clean.slice(0,2),16)}, ${Number.parseInt(clean.slice(2,4),16)}, ${Number.parseInt(clean.slice(4,6),16)})`}

export async function ensureWalletIdentity(ticketId:string){const current=await db.ticket.findUniqueOrThrow({where:{id:ticketId}});if(current.walletSerial&&current.walletAuthToken)return current;return db.ticket.update({where:{id:ticketId},data:{walletSerial:current.walletSerial??`ATL-${randomBytes(8).toString("hex")}`,walletAuthToken:current.walletAuthToken??randomBytes(24).toString("base64url"),walletUpdatedAt:new Date()}})}

export async function buildWalletPass(ticketId:string){if(!walletConfigured())throw new Error("Apple Wallet не подключён: добавьте Pass Type ID и сертификаты");const identity=await ensureWalletIdentity(ticketId);const ticket=await db.ticket.findUniqueOrThrow({where:{id:ticketId},include:{category:true,order:{include:{event:{include:{venue:true,ticketTemplate:true}}}}}});const event=ticket.order.event;const design=parseTicketDesign(event.ticketTemplate);const webServiceURL=process.env.APPLE_WALLET_WEB_SERVICE_URL||`${process.env.NEXT_PUBLIC_APP_URL}/api/wallet`;const icon=solidIcon(design.accentColor);const pass=new PKPass({"icon.png":icon,"icon@2x.png":icon},{wwdr:Buffer.from(process.env.APPLE_WALLET_WWDR_CERT_BASE64!,"base64"),signerCert:Buffer.from(process.env.APPLE_WALLET_SIGNER_CERT_BASE64!,"base64"),signerKey:Buffer.from(process.env.APPLE_WALLET_SIGNER_KEY_BASE64!,"base64"),signerKeyPassphrase:process.env.APPLE_WALLET_SIGNER_KEY_PASSPHRASE},{formatVersion:1,serialNumber:identity.walletSerial!,description:`Билет на ${event.title}`,organizationName:event.organizationId?"Atlas Tickets":"Atlas",passTypeIdentifier:process.env.APPLE_WALLET_PASS_TYPE_ID!,teamIdentifier:process.env.APPLE_WALLET_TEAM_ID!,logoText:"ATLAS",backgroundColor:rgbColor(design.backgroundColor),foregroundColor:rgbColor(design.textColor),labelColor:rgbColor(design.accentColor),webServiceURL,authenticationToken:identity.walletAuthToken!,voided:ticket.status==="CANCELLED"||ticket.status==="USED",groupingIdentifier:ticket.order.publicId});pass.type="eventTicket";pass.primaryFields.push({key:"event",label:"СОБЫТИЕ",value:event.title});pass.secondaryFields.push({key:"date",label:"ДАТА",value:event.startsAt.toISOString(),dateStyle:"PKDateStyleMedium",timeStyle:"PKDateStyleShort",changeMessage:"Дата мероприятия изменена: %@"});pass.auxiliaryFields.push({key:"ticket",label:"БИЛЕТ",value:ticket.category.name},{key:"holder",label:"ГОСТЬ",value:ticket.holderName});pass.backFields.push({key:"venue",label:"Площадка",value:`${event.venue.name}, ${event.venue.address}`,changeMessage:"Площадка изменена: %@"},{key:"order",label:"Заказ",value:ticket.order.publicId},{key:"code",label:"Код билета",value:ticket.publicCode},{key:"support",label:"Важно",value:"QR-код действителен для одного прохода. Передача билета третьим лицам регулируется организатором."});pass.setBarcodes({format:"PKBarcodeFormatQR",message:ticket.publicCode,messageEncoding:"iso-8859-1",altText:ticket.publicCode.slice(0,18)});pass.setRelevantDate(event.startsAt);pass.setExpirationDate(new Date(event.startsAt.getTime()+18*60*60*1000));return pass.getAsBuffer()}

export function walletAuthorization(request:Request,token:string|null){return Boolean(token&&request.headers.get("authorization")===`ApplePass ${token}`)}
