import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import { checkoutSchema } from "@/lib/schemas";
import { effectiveTicketPrice, orderNumber } from "@/lib/ticketing";
import { guestFieldKeys, parseGuestFields } from "@/lib/event-guest-fields";
import { assertInventoryAvailable, createReservation, type ReservationItemInput } from "@/lib/reservation";
import { createHypPaymentLink } from "@/lib/hyp-yaadpay";
import { createHypApprovalPaymentPage } from "@/lib/hyp-creditguard";
import { ensureMarketingRuntime, parseMarketingCookie, saveOrderAttribution } from "@/lib/marketing-runtime";
import { getEffectiveEventTerms } from "@/lib/commercial-terms";
import { calculateServiceFee } from "@/lib/service-fee";
import { linkAbandonedCheckoutToOrder } from "@/lib/abandoned-order-attribution";

const CANONICAL_APP_URL="https://www.atlas-one.co";
function normalizePhone(value:string){const digits=value.replace(/\D/g,"");if(!digits)return "";if(digits.startsWith("972"))return `+${digits}`;if(digits.startsWith("0"))return `+972${digits.slice(1)}`;return `+972${digits}`;}
function launchUrl(paymentUrl:string){return `/payments/hyp/launch?target=${encodeURIComponent(paymentUrl)}`;}

async function createPaymentUrl(input:{salesMode:"INSTANT"|"APPROVAL_REQUIRED";totalMinor:number;publicId:string;eventTitle:string;customerName:string;customerEmail:string;customerPhone:string;language:"HEB"|"ENG"}){
  if(input.salesMode==="APPROVAL_REQUIRED"){
    return createHypApprovalPaymentPage({amountMinor:input.totalMinor,orderId:input.publicId,callbackPath:"/api/payments/hyp/approval",language:input.language,customerName:input.customerName,customerEmail:input.customerEmail,customerPhone:input.customerPhone});
  }
  return createHypPaymentLink({amountIls:input.totalMinor/100,orderId:input.publicId,description:input.eventTitle,customerName:input.customerName,customerEmail:input.customerEmail,customerPhone:input.customerPhone,returnUrl:`${CANONICAL_APP_URL}/api/payments/hyp/order`,language:input.language});
}

export async function POST(req:Request){
  try{
    await ensureMarketingRuntime();
    const attribution=parseMarketingCookie(req.headers.get("cookie"));
    const input=checkoutSchema.parse(await req.json());
    const language=input.locale==="he"?"HEB" as const:"ENG" as const;
    const existing=await db.order.findUnique({where:{idempotencyKey:input.idempotencyKey},include:{event:true}});
    if(existing){
      await linkAbandonedCheckoutToOrder(input.abandonToken, existing.id);
      if(existing.status==="PENDING"){
        const paymentUrl=await createPaymentUrl({salesMode:existing.event.salesMode,totalMinor:existing.totalMinor,publicId:existing.publicId,eventTitle:existing.event.title,customerName:existing.customerName,customerEmail:existing.customerEmail,customerPhone:existing.customerPhone,language});
        return NextResponse.json({orderId:existing.publicId,status:existing.status,paymentUrl:launchUrl(paymentUrl)});
      }
      return NextResponse.json({orderId:existing.publicId,status:existing.status});
    }
    const result=await db.$transaction(async tx=>{
      const event=await tx.event.findUnique({where:{id:input.eventId}});if(!event||event.status!=="PUBLISHED")throw new Error("Мероприятие недоступно для продажи");
      const fields=parseGuestFields(event.description);for(const key of guestFieldKeys){const value=String(input.customer[key]||"").trim();if(fields[key].visible&&fields[key].required&&!value)throw new Error(`Заполните обязательное поле: ${key}`);}if(input.customer.email&&!/^\S+@\S+\.\S+$/.test(input.customer.email))throw new Error("Укажите корректный email");
      const category=await tx.ticketCategory.findUnique({where:{id:input.categoryId},include:{priceTiers:true}});if(!category||category.eventId!==input.eventId)throw new Error("Категория не найдена");if(category.hidden)throw new Error("Этот тариф недоступен");const categoryPrice=effectiveTicketPrice(category);
      const table=input.tableId?await tx.table.findUnique({where:{id:input.tableId},include:{zone:true,category:{include:{priceTiers:true}}}}):null;if(table&&table.zone.eventId!==input.eventId)throw new Error("Стол не относится к событию");if(table?.reserved)throw new Error("Этот стол уже занят");if(table&&(table.priceMode!=="WHOLE_TABLE"||!table.category))throw new Error("Для этого объекта не назначен билет для продажи целиком");
      const seats=input.seatIds?.length?await tx.seat.findMany({where:{id:{in:input.seatIds}},include:{category:{include:{priceTiers:true}},table:{include:{zone:true}}}}):[];if(input.seatIds?.length&&seats.length!==input.seatIds.length)throw new Error("Некоторые выбранные места не найдены");if(seats.some(seat=>seat.table.zone.eventId!==input.eventId||!seat.category))throw new Error("Место не относится к мероприятию или для него не назначен билет");if(seats.some(seat=>seat.table.priceMode!=="PER_SEAT"))throw new Error("Этот объект продаётся только целиком");if(seats.some(seat=>seat.status!=="AVAILABLE"))throw new Error("Одно из выбранных мест уже занято");if(table&&seats.length)throw new Error("Нельзя одновременно выбрать объект целиком и отдельные места");
      const promoterLink=input.referralCode?await tx.promoterLink.findUnique({where:{code:input.referralCode.toUpperCase()},include:{orders:{where:{status:{notIn:["CANCELLED","REJECTED"]}},include:{items:true}}}}):null;const legacyReferral=input.referralCode&&!promoterLink?await tx.referral.findUnique({where:{code:input.referralCode}}):null;const now=new Date();if(input.referralCode&&!promoterLink&&!legacyReferral)throw new Error("Персональная ссылка недействительна");if(promoterLink){if(!promoterLink.active||promoterLink.eventId!==input.eventId||(promoterLink.startsAt&&promoterLink.startsAt>now)||(promoterLink.endsAt&&promoterLink.endsAt<now))throw new Error("Персональная ссылка больше недоступна");if(promoterLink.allocationType==="TABLE"&&promoterLink.tableId!==table?.id)throw new Error("Эта ссылка предназначена для другого стола");if(promoterLink.allocationType==="CATEGORY"&&promoterLink.categoryId!==category.id)throw new Error("Эта ссылка предназначена для другой категории");}
      if(!promoterLink){const guestOnlyPromoter={OR:[{name:{startsWith:"__GUEST_LIST__:"}},{name:{startsWith:"__CHANNEL__:GUEST:"}}]};if(table){const locked=await tx.promoterLink.findFirst({where:{eventId:input.eventId,tableId:table.id,allocationType:"TABLE",exclusive:true,active:true,promoter:guestOnlyPromoter,OR:[{startsAt:null},{startsAt:{lte:now}}],AND:[{OR:[{endsAt:null},{endsAt:{gte:now}}]}]}});if(locked)throw new Error("Этот стол доступен только по персональной ссылке");}else{const locked=await tx.promoterLink.findFirst({where:{eventId:input.eventId,categoryId:category.id,allocationType:"CATEGORY",exclusive:true,active:true,promoter:guestOnlyPromoter,OR:[{startsAt:null},{startsAt:{lte:now}}],AND:[{OR:[{endsAt:null},{endsAt:{gte:now}}]}]}});if(locked)throw new Error("Эта категория доступна только по персональной ссылке");}}
      const quantity=table?table.seats:seats.length||input.quantity;if(!table&&!seats.length&&(quantity<category.minPerOrder||quantity>category.maxPerOrder))throw new Error(`В одном заказе можно выбрать от ${category.minPerOrder} до ${category.maxPerOrder} билетов`);if(promoterLink&&quantity>promoterLink.maxPerOrder)throw new Error(`По этой ссылке можно купить не более ${promoterLink.maxPerOrder} билетов за заказ`);if(promoterLink?.guestLimit){const allocated=promoterLink.orders.flatMap(item=>item.items).reduce((sum,item)=>sum+item.quantity,0);if(allocated+quantity>promoterLink.guestLimit)throw new Error("Квота этой персональной ссылки исчерпана");}
      const requested=new Map<string,{category:typeof category;quantity:number;price:number}>();if(table?.category)requested.set(table.category.id,{category:table.category,quantity:table.seats,price:effectiveTicketPrice(table.category)});else if(seats.length)for(const seat of seats){const assigned=seat.category!;const current=requested.get(assigned.id);requested.set(assigned.id,{category:assigned,quantity:(current?.quantity??0)+1,price:effectiveTicketPrice(assigned)});}else requested.set(category.id,{category,quantity,price:categoryPrice});
      const reservationItems:ReservationItemInput[]=seats.length?seats.map(seat=>({categoryId:seat.category!.id,quantity:1,seatId:seat.id,tableId:null})):table?.category?[{categoryId:table.category.id,quantity:table.seats,tableId:table.id,seatId:null}]:[{categoryId:category.id,quantity,tableId:null,seatId:null}];
      const capacities=new Map([...requested.values()].map(item=>[item.category.id,{sold:item.category.sold,capacity:item.category.capacity,name:item.category.name}]));await assertInventoryAvailable({items:reservationItems,capacities,executor:tx});
      let discount=0;if(input.promoCode){const promo=await tx.promoCode.findUnique({where:{eventId_code:{eventId:input.eventId,code:input.promoCode.toUpperCase()}}});if(promo?.active)discount=promo.discountPercent;}const standardSubtotal=[...requested.values()].reduce((sum,item)=>sum+item.price*(table?1:item.quantity),0);const promoterSubtotal=promoterLink?.customPriceMinor!==null&&promoterLink?.customPriceMinor!==undefined?(promoterLink.allocationType==="TABLE"?promoterLink.customPriceMinor:promoterLink.customPriceMinor*quantity):null;const subtotal=Math.round(((promoterSubtotal??standardSubtotal)*(100-discount))/100);
      const terms=await getEffectiveEventTerms(event.id,event.organizationId);const pricing=calculateServiceFee(subtotal,{salesFeePercentBps:terms.organizer.salesFeePercentBps,salesFeeFixedMinor:terms.organizer.salesFeeFixedMinor,serviceFeePayer:terms.serviceFeePayer});
      const firstName=input.customer.firstName.trim()||"Гость";const lastName=input.customer.lastName.trim();const fullName=`${firstName} ${lastName}`.trim();const email=(input.customer.email||`guest-${crypto.randomUUID()}@guest.atlas.local`).toLowerCase();const rawPhone=input.customer.phone.trim();const phone=normalizePhone(rawPhone)||`guest-${crypto.randomUUID()}`;const birthDate=input.customer.birthDate?new Date(input.customer.birthDate):new Date("1900-01-01T00:00:00.000Z");
      const guest=await tx.guestProfile.upsert({where:{organizationId_phone:{organizationId:event.organizationId,phone}},create:{organizationId:event.organizationId,firstName,lastName,phone,email,birthDate,city:input.customer.city||"",facebook:input.customer.facebook||"",instagram:input.customer.instagram||""},update:{firstName,lastName,email,birthDate,city:input.customer.city||"",facebook:input.customer.facebook||"",instagram:input.customer.instagram||""}});
      const created=await tx.order.create({data:{publicId:orderNumber(),idempotencyKey:input.idempotencyKey,customerName:fullName,customerEmail:email,customerPhone:rawPhone?phone:"",customerFirstName:input.customer.firstName||null,customerLastName:lastName||null,customerBirthDate:input.customer.birthDate?birthDate:null,customerCity:input.customer.city||null,customerFacebook:input.customer.facebook||null,customerInstagram:input.customer.instagram||null,guestId:guest.id,eligibilityAnswer:input.eligibilityAnswer||null,totalMinor:pricing.buyerTotalMinor,status:"PENDING",eventId:input.eventId,referralId:legacyReferral?.id,promoterLinkId:promoterLink?.id,items:{create:seats.length?seats.map(seat=>({quantity:1,unitPriceMinor:promoterLink?.customPriceMinor??effectiveTicketPrice(seat.category!),categoryName:seat.category!.name,tableId:seat.tableId,seatId:seat.id})):[{quantity,unitPriceMinor:promoterLink?.customPriceMinor!==null&&promoterLink?.customPriceMinor!==undefined?(promoterLink.allocationType==="TABLE"?Math.round(promoterLink.customPriceMinor/quantity):promoterLink.customPriceMinor):table?.category?Math.round(effectiveTicketPrice(table.category)/quantity):categoryPrice,categoryName:table?.category?.name??category.name,tableId:table?.id}]}}});
      await tx.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "OrderCommercialSnapshot" ("orderId" TEXT PRIMARY KEY,"subtotalMinor" INTEGER NOT NULL,"serviceFeeMinor" INTEGER NOT NULL,"buyerTotalMinor" INTEGER NOT NULL,"organizerNetMinor" INTEGER NOT NULL,"serviceFeePayer" TEXT NOT NULL,"salesFeePercentBps" INTEGER NOT NULL,"salesFeeFixedMinor" INTEGER NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP)`);
      await tx.$executeRawUnsafe(`INSERT INTO "OrderCommercialSnapshot" ("orderId","subtotalMinor","serviceFeeMinor","buyerTotalMinor","organizerNetMinor","serviceFeePayer","salesFeePercentBps","salesFeeFixedMinor") VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT ("orderId") DO NOTHING`,created.id,pricing.subtotalMinor,pricing.serviceFeeMinor,pricing.buyerTotalMinor,pricing.organizerNetMinor,terms.serviceFeePayer,terms.organizer.salesFeePercentBps,terms.organizer.salesFeeFixedMinor);
      await saveOrderAttribution(tx,created.id,attribution);
      await createReservation({orderId:created.id,items:reservationItems,ttlMinutes:event.salesMode==="INSTANT"?15:24*60,executor:tx});
      return {order:created,eventTitle:event.title,salesMode:event.salesMode};
    });
    await linkAbandonedCheckoutToOrder(input.abandonToken, result.order.id);
    const paymentUrl=await createPaymentUrl({salesMode:result.salesMode,totalMinor:result.order.totalMinor,publicId:result.order.publicId,eventTitle:result.eventTitle,customerName:result.order.customerName,customerEmail:result.order.customerEmail,customerPhone:result.order.customerPhone,language});
    return NextResponse.json({orderId:result.order.publicId,status:result.order.status,paymentUrl:launchUrl(paymentUrl)},{status:201});
  }catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Некорректный запрос"},{status:400});}
}
