import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import { checkoutSchema } from "@/lib/schemas";
import { effectiveTicketPrice, orderNumber } from "@/lib/ticketing";
import { guestFieldKeys, parseGuestFields } from "@/lib/event-guest-fields";
import { assertInventoryAvailable, createReservation, type ReservationItemInput } from "@/lib/reservation";
import { createHypPaymentLink } from "@/lib/hyp-yaadpay";
import { createHypApprovalPaymentPage } from "@/lib/hyp-creditguard";
import { ensureMarketingRuntime, parseMarketingCookie, saveOrderAttribution } from "@/lib/marketing-runtime";
import { getEffectiveEventTerms } from "@/lib/commercial-terms";
import { calculateServiceFee } from "@/lib/service-fee";
import { linkAbandonedCheckoutToOrder } from "@/lib/abandoned-order-attribution";
import { getActiveGuestSeatLocks, isGuestListPromoter } from "@/lib/guest-links";
import { rememberPendingCheckoutOwner } from "@/lib/cart-checkout-owner";
import { localeConfig, normalizeLocale, type Locale } from "@/lib/i18n";

const CANONICAL_APP_URL="https://www.atlas-one.co";
function normalizePhone(value:string){const digits=value.replace(/\D/g,"");if(!digits)return "";if(digits.startsWith("972"))return `+${digits}`;if(digits.startsWith("0"))return `+972${digits.slice(1)}`;return `+972${digits}`;}
function launchUrl(paymentUrl:string){return `/payments/hyp/launch?target=${encodeURIComponent(paymentUrl)}`;}
function checkoutCartSessionId(req:Request){const raw=req.headers.get("cookie")||"";for(const part of raw.split(";")){const [key,...rest]=part.trim().split("=");if(key==="atlas_cart_session")return decodeURIComponent(rest.join("="));}return "";}
async function rememberCheckoutOwner(req:Request,orderPublicId:string){const sessionId=checkoutCartSessionId(req);if(!sessionId)return;await rememberPendingCheckoutOwner({sessionId,orderPublicId}).catch(()=>undefined);}
async function orderSalesMode(orderId:string){const rows=await db.$queryRawUnsafe<Array<{salesFlow:string}>>(`SELECT "salesFlow" FROM "Order" WHERE "id"=$1 LIMIT 1`,orderId);return rows[0]?.salesFlow==="APPROVAL"?"APPROVAL_REQUIRED" as const:"INSTANT" as const;}
async function createPaymentUrl(input:{salesMode:"INSTANT"|"APPROVAL_REQUIRED";totalMinor:number;publicId:string;eventTitle:string;customerName:string;customerEmail:string;customerPhone:string;language:"HEB"|"ENG"}){if(input.salesMode==="APPROVAL_REQUIRED")return createHypApprovalPaymentPage({amountMinor:input.totalMinor,orderId:input.publicId,callbackPath:"/api/payments/hyp/approval",language:input.language,customerName:input.customerName,customerEmail:input.customerEmail,customerPhone:input.customerPhone});return createHypPaymentLink({amountIls:input.totalMinor/100,orderId:input.publicId,description:input.eventTitle,customerName:input.customerName,customerEmail:input.customerEmail,customerPhone:input.customerPhone,returnUrl:`${CANONICAL_APP_URL}/api/payments/hyp/order`,language:input.language});}

const checkoutErrorCopy={
 ru:{generic:"Не удалось подготовить оплату",event:"Мероприятие недоступно для продажи",required:"Заполните все обязательные поля",email:"Укажите корректный email",category:"Категория билета недоступна",tariff:"Этот тариф недоступен",tableWrong:"Стол не относится к мероприятию",tableTaken:"Этот стол уже занят",wholeMissing:"Для этого объекта не назначен билет для продажи целиком",seatsMissing:"Некоторые выбранные места не найдены",seatWrong:"Выбранное место недоступно для этого мероприятия",wholeOnly:"Этот объект продаётся только целиком",seatTaken:"Одно из выбранных мест уже занято",selection:"Нельзя одновременно выбрать объект целиком и отдельные места",linkInvalid:"Персональная ссылка недействительна",guestReserved:"Это место зарезервировано для гостевой ссылки",linkUnavailable:"Персональная ссылка больше недоступна",otherTable:"Эта ссылка предназначена для другого стола",guestCategory:"Эта гостевая ссылка предназначена для другой категории",otherCategory:"Эта ссылка предназначена для другой категории",guestSeat:"Это место недоступно по данной гостевой ссылке",exclusiveTable:"Этот стол доступен только по персональной ссылке",exclusiveCategory:"Эта категория доступна только по персональной ссылке",quota:"Квота этой персональной ссылки исчерпана",inventory:"Недостаточно доступных билетов",tempTable:"Этот стол уже временно забронирован",tempSeat:"Это место уже временно забронировано"},
 he:{generic:"לא ניתן להכין את התשלום",event:"האירוע אינו זמין כרגע למכירה",required:"יש למלא את כל שדות החובה",email:"יש להזין כתובת Email תקינה",category:"קטגוריית הכרטיס אינה זמינה",tariff:"סוג הכרטיס הזה אינו זמין",tableWrong:"השולחן אינו שייך לאירוע",tableTaken:"השולחן כבר תפוס",wholeMissing:"לא הוגדר כרטיס למכירת האובייקט בשלמותו",seatsMissing:"חלק מהמקומות שנבחרו לא נמצאו",seatWrong:"המקום שנבחר אינו זמין לאירוע הזה",wholeOnly:"האובייקט הזה נמכר בשלמותו בלבד",seatTaken:"אחד המקומות שנבחרו כבר תפוס",selection:"לא ניתן לבחור גם אובייקט שלם וגם מקומות בודדים",linkInvalid:"הקישור האישי אינו תקף",guestReserved:"המקום הזה שמור לקישור אורחים",linkUnavailable:"הקישור האישי אינו זמין עוד",otherTable:"הקישור הזה מיועד לשולחן אחר",guestCategory:"קישור האורחים הזה מיועד לקטגוריה אחרת",otherCategory:"הקישור הזה מיועד לקטגוריה אחרת",guestSeat:"המקום הזה אינו זמין דרך קישור האורחים",exclusiveTable:"השולחן הזה זמין רק דרך קישור אישי",exclusiveCategory:"הקטגוריה הזו זמינה רק דרך קישור אישי",quota:"המכסה של הקישור האישי נוצלה",inventory:"אין מספיק כרטיסים זמינים",tempTable:"השולחן כבר שמור זמנית",tempSeat:"המקום כבר שמור זמנית"},
 en:{generic:"Could not prepare payment",event:"This event is not currently available for sale",required:"Complete all required fields",email:"Enter a valid email address",category:"The ticket category is unavailable",tariff:"This ticket type is unavailable",tableWrong:"This table does not belong to the event",tableTaken:"This table is already taken",wholeMissing:"No whole-object ticket is assigned to this item",seatsMissing:"Some selected seats could not be found",seatWrong:"The selected seat is unavailable for this event",wholeOnly:"This item can only be sold as a whole",seatTaken:"One of the selected seats is already taken",selection:"You cannot select a whole item and individual seats at the same time",linkInvalid:"The personal link is invalid",guestReserved:"This seat is reserved for a guest link",linkUnavailable:"The personal link is no longer available",otherTable:"This link is assigned to a different table",guestCategory:"This guest link is assigned to a different category",otherCategory:"This link is assigned to a different category",guestSeat:"This seat is not available through this guest link",exclusiveTable:"This table is available only through a personal link",exclusiveCategory:"This category is available only through a personal link",quota:"The quota for this personal link has been reached",inventory:"Not enough tickets are available",tempTable:"This table is temporarily reserved",tempSeat:"This seat is temporarily reserved"}
} as const;
function localizeCheckoutError(error:unknown,locale:Locale){const raw=error instanceof Error?error.message:"";const c=checkoutErrorCopy[locale];
 if(raw.includes("Мероприятие недоступно"))return c.event;if(raw.startsWith("Заполните обязательное поле"))return c.required;if(raw.includes("корректный email"))return c.email;if(raw.includes("Категория билета не найдена")||raw==="Категория не найдена")return c.category;if(raw.includes("тариф недоступен"))return c.tariff;if(raw.includes("Стол не относится"))return c.tableWrong;if(raw==="Этот стол уже занят")return c.tableTaken;if(raw.includes("не назначен билет для продажи целиком"))return c.wholeMissing;if(raw.includes("выбранные места не найдены"))return c.seatsMissing;if(raw.includes("Место не относится к мероприятию"))return c.seatWrong;if(raw.includes("продаётся только целиком"))return c.wholeOnly;if(raw.includes("Одно из выбранных мест уже занято"))return c.seatTaken;if(raw.includes("одновременно выбрать объект"))return c.selection;if(raw.includes("Персональная ссылка недействительна"))return c.linkInvalid;if(raw.includes("зарезервировано для гостевой ссылки"))return c.guestReserved;if(raw.includes("Персональная ссылка больше недоступна"))return c.linkUnavailable;if(raw.includes("предназначена для другого стола"))return c.otherTable;if(raw.includes("гостевая ссылка предназначена для другой категории"))return c.guestCategory;if(raw.includes("предназначена для другой категории"))return c.otherCategory;if(raw.includes("недоступно по данной гостевой ссылке"))return c.guestSeat;if(raw.includes("стол доступен только по персональной ссылке"))return c.exclusiveTable;if(raw.includes("категория доступна только по персональной ссылке"))return c.exclusiveCategory;if(raw.includes("Квота этой персональной ссылки"))return c.quota;if(raw.startsWith("Недостаточно доступных билетов")){const name=raw.replace("Недостаточно доступных билетов","").trim();return name?`${c.inventory}: ${name}`:c.inventory;}if(raw.includes("стол уже временно забронирован")||raw.includes("стол только что был временно забронирован"))return c.tempTable;if(raw.includes("место уже временно забронировано")||raw.includes("место только что было временно забронировано"))return c.tempSeat;
 const range=/В одном заказе можно выбрать от (\d+) до (\d+) билетов/.exec(raw);if(range)return locale==="he"?`ניתן לבחור בין ${range[1]} ל-${range[2]} כרטיסים בהזמנה`:locale==="en"?`You can select between ${range[1]} and ${range[2]} tickets per order`:`В одном заказе можно выбрать от ${range[1]} до ${range[2]} билетов`;
 const max=/По этой ссылке можно купить не более (\d+) билетов/.exec(raw);if(max)return locale==="he"?`דרך הקישור הזה ניתן לרכוש עד ${max[1]} כרטיסים בהזמנה`:locale==="en"?`This link allows up to ${max[1]} tickets per order`:`По этой ссылке можно купить не более ${max[1]} билетов за заказ`;
 return c.generic;}

export async function POST(req:Request){
 let responseLocale:Locale="ru";
 try{
  await ensureMarketingRuntime();const attribution=parseMarketingCookie(req.headers.get("cookie"));const raw=await req.json();responseLocale=normalizeLocale((raw as {locale?:string})?.locale);const input=checkoutSchema.parse(raw);const guestSeatLocks=input.seatIds?.length?await getActiveGuestSeatLocks(input.eventId):new Map<string,string>();
  const existing=await db.order.findUnique({where:{idempotencyKey:input.idempotencyKey},include:{event:true}});if(existing){const existingLocale=normalizeLocale(existing.communicationLocale);responseLocale=existingLocale;const language=localeConfig[existingLocale].hypLanguage;await linkAbandonedCheckoutToOrder(input.abandonToken,existing.id);if(existing.status==="PENDING"){await rememberCheckoutOwner(req,existing.publicId);const persistedSalesMode=await orderSalesMode(existing.id);const paymentUrl=await createPaymentUrl({salesMode:persistedSalesMode,totalMinor:existing.totalMinor,publicId:existing.publicId,eventTitle:existing.event.title,customerName:existing.customerName,customerEmail:existing.customerEmail,customerPhone:existing.customerPhone,language});return NextResponse.json({orderId:existing.publicId,status:existing.status,paymentUrl:launchUrl(paymentUrl),locale:existingLocale});}return NextResponse.json({orderId:existing.publicId,status:existing.status,locale:existingLocale});}
  const result=await db.$transaction(async tx=>{
   const event=await tx.event.findUnique({where:{id:input.eventId}});if(!event||event.status!=="PUBLISHED")throw new Error("Мероприятие недоступно для продажи");const eventLocale=normalizeLocale(event.customerCommunicationLocale);responseLocale=eventLocale;const fields=parseGuestFields(event.description);for(const key of guestFieldKeys){const value=String(input.customer[key]||"").trim();if(fields[key].visible&&fields[key].required&&!value)throw new Error(`Заполните обязательное поле: ${key}`);}if(input.customer.email&&!/^\S+@\S+\.\S+$/.test(input.customer.email))throw new Error("Укажите корректный email");
   const category=await tx.ticketCategory.findUnique({where:{id:input.categoryId},include:{priceTiers:true}});if(!category||category.eventId!==input.eventId)throw new Error("Категория не найдена");if(category.hidden)throw new Error("Этот тариф недоступен");const categoryPrice=effectiveTicketPrice(category);
   const table=input.tableId?await tx.table.findUnique({where:{id:input.tableId},include:{zone:true,category:{include:{priceTiers:true}}}}):null;if(table&&table.zone.eventId!==input.eventId)throw new Error("Стол не относится к событию");if(table?.reserved)throw new Error("Этот стол уже занят");if(table&&(table.priceMode!=="WHOLE_TABLE"||!table.category))throw new Error("Для этого объекта не назначен билет для продажи целиком");
   const seats=input.seatIds?.length?await tx.seat.findMany({where:{id:{in:input.seatIds}},include:{category:{include:{priceTiers:true}},table:{include:{zone:true}}}}):[];if(input.seatIds?.length&&seats.length!==input.seatIds.length)throw new Error("Некоторые выбранные места не найдены");if(seats.some(seat=>seat.table.zone.eventId!==input.eventId||!seat.category))throw new Error("Место не относится к мероприятию или для него не назначен билет");if(seats.some(seat=>seat.table.priceMode!=="PER_SEAT"))throw new Error("Этот объект продаётся только целиком");if(seats.some(seat=>seat.status!=="AVAILABLE"))throw new Error("Одно из выбранных мест уже занято");if(table&&seats.length)throw new Error("Нельзя одновременно выбрать объект целиком и отдельные места");
   const promoterLink=input.referralCode?await tx.promoterLink.findUnique({where:{code:input.referralCode.toUpperCase()},include:{promoter:true,table:true,orders:{where:{status:{notIn:["CANCELLED","REJECTED"]}},include:{items:true}}}}):null;const legacyReferral=input.referralCode&&!promoterLink?await tx.referral.findUnique({where:{code:input.referralCode}}):null;const now=new Date();if(input.referralCode&&!promoterLink&&!legacyReferral)throw new Error("Персональная ссылка недействительна");const guestPromoterLink=Boolean(promoterLink&&isGuestListPromoter(promoterLink.promoter.name));
   if(seats.some(seat=>{const owner=guestSeatLocks.get(seat.id);return Boolean(owner&&owner!==promoterLink?.id);}))throw new Error("Это место зарезервировано для гостевой ссылки");
   if(promoterLink){if(!promoterLink.active||promoterLink.eventId!==input.eventId||(promoterLink.startsAt&&promoterLink.startsAt>now)||(promoterLink.endsAt&&promoterLink.endsAt<now))throw new Error("Персональная ссылка больше недоступна");if(promoterLink.allocationType==="TABLE"&&!guestPromoterLink&&promoterLink.tableId!==table?.id)throw new Error("Эта ссылка предназначена для другого стола");if(promoterLink.allocationType==="TABLE"&&guestPromoterLink&&promoterLink.table?.categoryId&&promoterLink.table.categoryId!==category.id)throw new Error("Эта гостевая ссылка предназначена для другой категории стола");if(promoterLink.allocationType==="CATEGORY"&&promoterLink.categoryId!==category.id)throw new Error("Эта ссылка предназначена для другой категории");}
   if(guestPromoterLink&&promoterLink){const rows=await tx.$queryRawUnsafe<Array<{seatIdsJson:string|null}>>(`SELECT "seatIdsJson" FROM "GuestLinkSettings" WHERE "linkId"=$1 LIMIT 1`,promoterLink.id).catch(()=>[]);let allowedSeatIds:string[]=[];try{const parsed=rows[0]?.seatIdsJson?JSON.parse(rows[0].seatIdsJson):[];if(Array.isArray(parsed))allowedSeatIds=parsed.filter((item):item is string=>typeof item==="string");}catch{}if(allowedSeatIds.length){if(seats.length!==1||!allowedSeatIds.includes(seats[0].id))throw new Error("Это место недоступно по данной гостевой ссылке");}}
   if(!promoterLink){if(table){const locked=await tx.promoterLink.findFirst({where:{eventId:input.eventId,tableId:table.id,allocationType:"TABLE",exclusive:true,active:true,OR:[{startsAt:null},{startsAt:{lte:now}}],AND:[{OR:[{endsAt:null},{endsAt:{gte:now}}]}]}});if(locked)throw new Error("Этот стол доступен только по персональной ссылке");}else{const locked=await tx.promoterLink.findFirst({where:{eventId:input.eventId,categoryId:category.id,allocationType:"CATEGORY",exclusive:true,active:true,OR:[{startsAt:null},{startsAt:{lte:now}}],AND:[{OR:[{endsAt:null},{endsAt:{gte:now}}]}]}});if(locked)throw new Error("Эта категория доступна только по персональной ссылке");}}
   const quantity=table?table.seats:seats.length||input.quantity;if(!table&&!seats.length&&(quantity<category.minPerOrder||quantity>category.maxPerOrder))throw new Error(`В одном заказе можно выбрать от ${category.minPerOrder} до ${category.maxPerOrder} билетов`);if(promoterLink&&quantity>promoterLink.maxPerOrder)throw new Error(`По этой ссылке можно купить не более ${promoterLink.maxPerOrder} билетов за заказ`);if(promoterLink?.guestLimit){const allocated=promoterLink.orders.flatMap(item=>item.items).reduce((sum,item)=>sum+item.quantity,0);if(allocated+quantity>promoterLink.guestLimit)throw new Error("Квота этой персональной ссылки исчерпана");}
   const requested=new Map<string,{category:typeof category;quantity:number;price:number}>();if(table?.category)requested.set(table.category.id,{category:table.category,quantity:table.seats,price:effectiveTicketPrice(table.category)});else if(seats.length)for(const seat of seats){const assigned=seat.category!;const current=requested.get(assigned.id);requested.set(assigned.id,{category:assigned,quantity:(current?.quantity??0)+1,price:effectiveTicketPrice(assigned)});}else requested.set(category.id,{category,quantity,price:categoryPrice});
   const reservationItems:ReservationItemInput[]=seats.length?seats.map(seat=>({categoryId:seat.category!.id,quantity:1,seatId:seat.id,tableId:null})):table?.category?[{categoryId:table.category.id,quantity:table.seats,tableId:table.id,seatId:null}]:[{categoryId:category.id,quantity,tableId:null,seatId:null}];const capacities=new Map([...requested.values()].map(item=>[item.category.id,{sold:item.category.sold,capacity:item.category.capacity,name:item.category.name}]));await assertInventoryAvailable({items:reservationItems,capacities,executor:tx});
   let discount=0;if(input.promoCode){const promo=await tx.promoCode.findUnique({where:{eventId_code:{eventId:input.eventId,code:input.promoCode.toUpperCase()}}});if(promo?.active)discount=promo.discountPercent;}const standardSubtotal=[...requested.values()].reduce((sum,item)=>sum+item.price*(table?1:item.quantity),0);const promoterSubtotal=promoterLink?.customPriceMinor!==null&&promoterLink?.customPriceMinor!==undefined?(promoterLink.allocationType==="TABLE"&&!guestPromoterLink?promoterLink.customPriceMinor:promoterLink.customPriceMinor*quantity):null;const subtotal=Math.round(((promoterSubtotal??standardSubtotal)*(100-discount))/100);const terms=await getEffectiveEventTerms(event.id,event.organizationId);const pricing=calculateServiceFee(subtotal,{salesFeePercentBps:terms.organizer.salesFeePercentBps,salesFeeFixedMinor:terms.organizer.salesFeeFixedMinor,serviceFeePayer:terms.serviceFeePayer});
   const firstName=input.customer.firstName.trim()||"Гость";const lastName=input.customer.lastName.trim();const fullName=`${firstName} ${lastName}`.trim();const email=(input.customer.email||`guest-${crypto.randomUUID()}@guest.atlas.local`).toLowerCase();const rawPhone=input.customer.phone.trim();const phone=normalizePhone(rawPhone)||`guest-${crypto.randomUUID()}`;const birthDate=input.customer.birthDate?new Date(input.customer.birthDate):new Date("1900-01-01T00:00:00.000Z");const guest=await tx.guestProfile.upsert({where:{organizationId_phone:{organizationId:event.organizationId,phone}},create:{organizationId:event.organizationId,firstName,lastName,phone,email,birthDate,city:input.customer.city||"",facebook:input.customer.facebook||"",instagram:input.customer.instagram||""},update:{firstName,lastName,email,birthDate,city:input.customer.city||"",facebook:input.customer.facebook||"",instagram:input.customer.instagram||""}});
   const created=await tx.order.create({data:{publicId:orderNumber(),idempotencyKey:input.idempotencyKey,communicationLocale:eventLocale,customerName:fullName,customerEmail:email,customerPhone:rawPhone?phone:"",customerFirstName:input.customer.firstName||null,customerLastName:lastName||null,customerBirthDate:input.customer.birthDate?birthDate:null,customerCity:input.customer.city||null,customerFacebook:input.customer.facebook||null,customerInstagram:input.customer.instagram||null,guestId:guest.id,eligibilityAnswer:input.eligibilityAnswer||null,totalMinor:pricing.buyerTotalMinor,status:"PENDING",salesFlow:event.salesMode==="APPROVAL_REQUIRED"?"APPROVAL":"DIRECT",eventId:input.eventId,referralId:legacyReferral?.id,promoterLinkId:promoterLink?.id,items:{create:seats.length?seats.map(seat=>({quantity:1,unitPriceMinor:promoterLink?.customPriceMinor??effectiveTicketPrice(seat.category!),categoryName:seat.category!.name,tableId:seat.tableId,seatId:seat.id})):[{quantity,unitPriceMinor:promoterLink?.customPriceMinor!==null&&promoterLink?.customPriceMinor!==undefined?(promoterLink.allocationType==="TABLE"&&!guestPromoterLink?Math.round(promoterLink.customPriceMinor/quantity):promoterLink.customPriceMinor):table?.category?Math.round(effectiveTicketPrice(table.category)/quantity):categoryPrice,categoryName:table?.category?.name??category.name,tableId:table?.id}]}}});
   await tx.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "OrderCommercialSnapshot" ("orderId" TEXT PRIMARY KEY,"subtotalMinor" INTEGER NOT NULL,"serviceFeeMinor" INTEGER NOT NULL,"buyerTotalMinor" INTEGER NOT NULL,"organizerNetMinor" INTEGER NOT NULL,"serviceFeePayer" TEXT NOT NULL,"salesFeePercentBps" INTEGER NOT NULL,"salesFeeFixedMinor" INTEGER NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP)`);await tx.$executeRawUnsafe(`INSERT INTO "OrderCommercialSnapshot" ("orderId","subtotalMinor","serviceFeeMinor","buyerTotalMinor","organizerNetMinor","serviceFeePayer","salesFeePercentBps","salesFeeFixedMinor") VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT ("orderId") DO NOTHING`,created.id,pricing.subtotalMinor,pricing.serviceFeeMinor,pricing.buyerTotalMinor,pricing.organizerNetMinor,terms.serviceFeePayer,terms.organizer.salesFeePercentBps,terms.organizer.salesFeeFixedMinor);await saveOrderAttribution(tx,created.id,attribution);await createReservation({orderId:created.id,items:reservationItems,ttlMinutes:event.salesMode==="INSTANT"?15:24*60,executor:tx});return {order:created,eventTitle:event.title,salesMode:event.salesMode,eventLocale};
  });
  await linkAbandonedCheckoutToOrder(input.abandonToken,result.order.id);await rememberCheckoutOwner(req,result.order.publicId);const paymentUrl=await createPaymentUrl({salesMode:result.salesMode,totalMinor:result.order.totalMinor,publicId:result.order.publicId,eventTitle:result.eventTitle,customerName:result.order.customerName,customerEmail:result.order.customerEmail,customerPhone:result.order.customerPhone,language:localeConfig[result.eventLocale].hypLanguage});return NextResponse.json({orderId:result.order.publicId,status:result.order.status,paymentUrl:launchUrl(paymentUrl),locale:result.eventLocale},{status:201});
 }catch(error){console.error("[checkout]",error);return NextResponse.json({error:localizeCheckoutError(error,responseLocale)},{status:400});}
}
