import type { Metadata } from "next";
import { ContentPage, Section } from "@/components/content-page";
import { getServerI18n } from "@/lib/server-locale";
import type { Locale } from "@/lib/i18n";

const copy = {
  ru: { title:"FAQ - вопросы о билетах и мероприятиях",description:"Ответы Atlas One о покупке, оплате, получении билета, возврате, переносе мероприятия и входе по QR-коду.",eyebrow:"Помощь",heading:"Частые вопросы",intro:"Короткие ответы о покупке билетов, оплате, возвратах и посещении мероприятий.",faqs:[["Когда я получу билет?","После успешной оплаты электронный билет формируется автоматически и доступен в подтверждении заказа и разделе «Мои билеты»."],["Нужно ли регистрироваться?","Для покупки достаточно заполнить данные, которые запросил организатор конкретного мероприятия."],["Где вводятся данные карты?","Банковские данные вводятся только на защищённой странице платёжного провайдера. Atlas One не хранит данные карты."],["Что делать, если билет не пришёл?","Проверьте папки «Спам» и «Промоакции», затем обратитесь в поддержку и укажите email и данные заказа."],["Можно ли вернуть билет?","Возврат зависит от условий мероприятия и применимого законодательства. Запрос можно направить через поддержку."],["Что происходит при переносе события?","Организатор публикует новую дату и сообщает доступные варианты: сохранить билет или запросить возврат, если это предусмотрено."],["Как проходит вход?","Покажите QR-код билета на телефоне. После успешного сканирования билет отмечается как использованный."],["Можно ли передать билет другому человеку?","Это зависит от правил мероприятия. Не публикуйте QR-код: его может использовать другой человек."]]},
  he: { title:"שאלות נפוצות על כרטיסים ואירועים",description:"תשובות של Atlas One על רכישה, תשלום, קבלת כרטיס, ביטולים, שינוי מועד וכניסה עם קוד QR.",eyebrow:"עזרה",heading:"שאלות נפוצות",intro:"תשובות קצרות על רכישת כרטיסים, תשלום, ביטולים והגעה לאירוע.",faqs:[["מתי אקבל את הכרטיס?","לאחר שהתשלום מאושר, הכרטיס הדיגיטלי מופק אוטומטית וזמין באישור ההזמנה ובאזור ״הכרטיסים שלי״."],["צריך להירשם כדי לקנות?","לא. מספיק למלא את הפרטים שמפיק האירוע ביקש בתהליך הרכישה."],["איפה מזינים את פרטי האשראי?","פרטי האשראי מוזנים רק בעמוד המאובטח של ספק התשלומים. Atlas One אינה שומרת את פרטי הכרטיס."],["הכרטיס לא הגיע. מה עושים?","בדקו את תיקיות הספאם וקידומי המכירות. אם הכרטיס עדיין לא נמצא, פנו לתמיכה עם כתובת האימייל ופרטי ההזמנה."],["אפשר לבטל כרטיס?","אפשרות הביטול תלויה בתנאי האירוע ובהוראות הדין. ניתן לשלוח בקשה דרך התמיכה."],["מה קורה אם מועד האירוע משתנה?","המפיק מפרסם את המועד החדש ומעדכן אילו אפשרויות זמינות, כגון שמירת הכרטיס או בקשת החזר, בהתאם לתנאים."],["איך נכנסים לאירוע?","מציגים בטלפון את קוד ה-QR של הכרטיס. לאחר סריקה מוצלחת הכרטיס מסומן ככרטיס שנוצל."],["אפשר להעביר את הכרטיס למישהו אחר?","הדבר תלוי בכללי האירוע. אל תפרסמו את קוד ה-QR, משום שאדם אחר עלול להשתמש בו."]]},
  en: { title:"Ticket and event FAQ",description:"Atlas One answers about ticket purchase, payment, delivery, cancellations, rescheduling, and QR admission.",eyebrow:"Help",heading:"Frequently asked questions",intro:"Short answers about buying tickets, payments, cancellations, and attending events.",faqs:[["When will I receive my ticket?","After a successful payment, your digital ticket is created automatically and is available in the order confirmation and My Tickets."],["Do I need to register?","No. You only need to provide the details requested by the organizer for that event."],["Where do I enter my card details?","Card details are entered only on the payment provider's secure page. Atlas One does not store them."],["What if my ticket did not arrive?","Check your spam and promotions folders. If it is still missing, contact support with your email and order details."],["Can I cancel a ticket?","Cancellation depends on the event terms and applicable law. You can submit a request through support."],["What happens if an event is rescheduled?","The organizer publishes the new date and explains the available options, such as keeping the ticket or requesting a refund when applicable."],["How does admission work?","Show the ticket's QR code on your phone. After a successful scan, the ticket is marked as used."],["Can I give my ticket to someone else?","This depends on the event rules. Do not publish the QR code because another person could use it."]]},
} satisfies Record<Locale,{title:string;description:string;eyebrow:string;heading:string;intro:string;faqs:string[][]}>;

export async function generateMetadata():Promise<Metadata>{const{locale}=await getServerI18n();const text=copy[locale];return{title:text.title,description:text.description,alternates:{canonical:"/faq"}};}
export default async function FaqPage(){const{locale}=await getServerI18n();const text=copy[locale];const schema={"@context":"https://schema.org","@type":"FAQPage",inLanguage:locale,mainEntity:text.faqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))};return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><ContentPage eyebrow={text.eyebrow} title={text.heading} intro={text.intro}>{text.faqs.map(([q,a])=><Section key={q} title={q}><p>{a}</p></Section>)}</ContentPage></>}
