import { AdminShell } from "@/components/admin-shell";
import { OrganizerAgreementAcceptance } from "@/components/organizer-agreement-acceptance";
import { OrganizerDocumentsForm } from "@/components/organizer-documents-form";
import { OrganizerTermsForm } from "@/components/organizer-terms-form";
import { requirePermission } from "@/lib/auth";
import { getOrganizerTerms } from "@/lib/commercial-terms";
import { contractReference, getOrganizerAgreementHistory, getOrganizerCompliance, isCurrentOrganizerAgreement, payoutReadiness } from "@/lib/organizer-compliance";
import { localeTag, resolveStaffLocale } from "@/lib/i18n";

export const dynamic="force-dynamic";
const copy={
  ru:{eyebrow:"Компания и договор",description:"Действующие условия Atlas, сохранённый договор и готовность документов для будущих выплат.",organizer:"Организатор",role:"Роль",roleValue:"Управление организацией",agreementStatus:"Статус договора",current:"Актуален",update:"Нужно обновить",required:"Требуется",notAccepted:"Договор ещё не принят",payoutReady:"Готовность к выплатам",ready:"Готов",needDocs:"Нужны документы",registration:"Регистрацию это не блокирует",agreementPayouts:"Договор и выплаты",compliance:"Статус compliance",done:"Готово",beforePayout:"Потребуется до выплаты",version:"версия",signed:"Подписал",open:"Открыть сохранённую версию договора",history:"История принятых договоров",show:"Показать текст версии",warning:"Актуальный договор, банковский документ и ניכוי מס במקור можно завершить после регистрации. Пока checklist не готов, Atlas не позволит финально зафиксировать выплату."},
  he:{eyebrow:"חברה והסכם",description:"תנאי Atlas הפעילים, ההסכם שנשמר ומוכנות המסמכים לתשלומים עתידיים.",organizer:"מפיק",role:"תפקיד",roleValue:"ניהול הארגון",agreementStatus:"סטטוס ההסכם",current:"בתוקף",update:"נדרש עדכון",required:"נדרש",notAccepted:"ההסכם עדיין לא אושר",payoutReady:"מוכנות לתשלומים",ready:"מוכן",needDocs:"חסרים מסמכים",registration:"הדבר אינו חוסם הרשמה",agreementPayouts:"הסכם ותשלומים",compliance:"סטטוס תאימות",done:"מוכן",beforePayout:"יידרש לפני תשלום",version:"גרסה",signed:"אושר על ידי",open:"פתיחת הגרסה השמורה של ההסכם",history:"היסטוריית הסכמים שאושרו",show:"הצגת טקסט הגרסה",warning:"אפשר להשלים את ההסכם העדכני, אישור ניהול החשבון וניכוי מס במקור לאחר ההרשמה. כל עוד רשימת הבדיקות אינה מלאה, Atlas לא תאפשר להשלים תשלום סופי."},
  en:{eyebrow:"Company and agreement",description:"Current Atlas terms, the stored agreement, and document readiness for future payouts.",organizer:"Organizer",role:"Role",roleValue:"Organization management",agreementStatus:"Agreement status",current:"Current",update:"Update required",required:"Required",notAccepted:"Agreement has not been accepted yet",payoutReady:"Payout readiness",ready:"Ready",needDocs:"Documents required",registration:"This does not block registration",agreementPayouts:"Agreement and payouts",compliance:"Compliance status",done:"Ready",beforePayout:"Required before payout",version:"version",signed:"Accepted by",open:"Open stored agreement version",history:"Accepted agreement history",show:"Show version text",warning:"The current agreement, bank document, and tax withholding certificate can be completed after registration. Until the checklist is complete, Atlas will not allow a payout to be finalized."}
} as const;

export default async function OrganizerCompanyPage(){
  const staff=await requirePermission("TEAM_MANAGE");const organizationId=staff.organizationId!;
  const locale=resolveStaffLocale({memberOverride:staff.interfaceLocaleOverride,userPreference:staff.preferredLocale,organizationDefault:staff.organization?.defaultStaffLocale});const text=copy[locale];
  const formatDate=(date:Date|null,withTime=false)=>date?new Intl.DateTimeFormat(localeTag(locale),withTime?{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit",timeZone:"Asia/Jerusalem"}:{day:"2-digit",month:"2-digit",year:"numeric",timeZone:"Asia/Jerusalem"}).format(date):"-";
  const [terms,compliance,agreementHistory]=await Promise.all([getOrganizerTerms(organizationId),getOrganizerCompliance(organizationId),getOrganizerAgreementHistory(organizationId)]);
  const readiness=payoutReadiness(compliance);const agreementCurrent=isCurrentOrganizerAgreement(compliance);
  return <AdminShell><div className="office-page-heading"><div><span className="eyebrow">{text.eyebrow}</span><h1>{staff.organization?.name}</h1><p>{text.description}</p></div><span className="pill">{text.organizer}</span></div><div className="stats"><div className="stat"><span className="muted">{text.role}</span><strong style={{fontSize:20}}>{text.roleValue}</strong></div><div className="stat"><span className="muted">{text.agreementStatus}</span><strong style={{fontSize:20,color:agreementCurrent?"#15803d":"#b42318"}}>{agreementCurrent?text.current:compliance.agreementStatus==="ACCEPTED"?text.update:text.required}</strong><small>{compliance.agreementStatus==="ACCEPTED"?<bdi>{contractReference(organizationId,compliance.acceptedAt)}</bdi>:text.notAccepted}</small></div><div className="stat"><span className="muted">{text.payoutReady}</span><strong style={{fontSize:20,color:readiness.ready?"#15803d":"#a16207"}}>{readiness.ready?text.ready:text.needDocs}</strong><small>{text.registration}</small></div></div>
  <OrganizerTermsForm organizationId={organizationId} readOnly initial={{salesFeePercentBps:terms.salesFeePercentBps,salesFeeFixedMinor:terms.salesFeeFixedMinor,serviceFeePayer:terms.serviceFeePayer,refundsEnabled:terms.refundsEnabled,refundFeePercentBps:terms.refundFeePercentBps,refundFeeFixedMinor:terms.refundFeeFixedMinor,refundDeadlineHours:terms.refundDeadlineHours,transferRefundWindowDays:terms.transferRefundWindowDays}}/>
  <OrganizerDocumentsForm organizationId={organizationId} bank={{provided:Boolean(compliance.bankDocumentPath),name:compliance.bankDocumentName,updatedAt:compliance.bankAccountUpdatedAt?formatDate(compliance.bankAccountUpdatedAt):null}} tax={{provided:Boolean(compliance.taxDocumentPath),name:compliance.taxDocumentName,updatedAt:compliance.taxDocumentUpdatedAt?formatDate(compliance.taxDocumentUpdatedAt):null}}/>
  <section className="platform-section-card"><span className="eyebrow">{text.agreementPayouts}</span><h2>{text.compliance}</h2><div className="platform-readiness-grid">{readiness.checks.map(check=><div key={check.key} className={`platform-readiness-item ${check.ready?"ready":"missing"}`}><b>{check.ready?"✓":"!"}</b><div><strong>{check.label}</strong><small>{check.ready?text.done:text.beforePayout}</small></div></div>)}</div>
  {compliance.agreementStatus==="ACCEPTED"&&<div className="platform-contract-card"><div><strong>{compliance.agreementTitle}</strong><small><bdi>{contractReference(organizationId,compliance.acceptedAt)}</bdi> · {text.version} <bdi>{compliance.agreementVersion}</bdi></small></div><div><span>{text.signed}: {compliance.acceptedByName} · <bdi>{compliance.acceptedByEmail}</bdi></span><small><bdi>{formatDate(compliance.acceptedAt,true)}</bdi></small></div><details><summary>{text.open}</summary><pre dir="auto">{compliance.agreementText}</pre></details></div>}
  {!agreementCurrent&&<OrganizerAgreementAcceptance/>}
  {agreementHistory.length>0&&<details className="platform-contract-card"><summary style={{cursor:"pointer",fontWeight:800}}>{text.history} ({agreementHistory.length})</summary>{agreementHistory.map(item=><div key={item.id} style={{padding:"10px 0",borderTop:"1px solid #e5e7eb"}}><strong><bdi>{item.version}</bdi></strong><br/><small><bdi>{formatDate(item.acceptedAt,true)}</bdi> · {item.acceptedByName} · <bdi>{item.acceptedByEmail}</bdi></small><details><summary>{text.show}</summary><pre dir="auto">{item.text}</pre></details></div>)}</details>}
  {!readiness.ready&&<p className="muted">{text.warning}</p>}</section></AdminShell>;
}
