import Link from "next/link";
import { AdminShell } from "@/components/admin-shell";
import { MarketingLinkBuilder } from "@/components/marketing-link-builder";
import { MarketingSettingsForm } from "@/components/marketing-settings-form";
import { MarketingPromoManager } from "@/components/marketing-promo-manager";
import { MarketingAudienceManager } from "@/components/marketing-audience-manager";
import { MarketingCampaignBuilder } from "@/components/marketing-campaign-builder";
import { MarketingCampaignList } from "@/components/marketing-campaign-list";
import { PromoterManager } from "@/components/promoter-manager";
import { requirePermission } from "@/lib/auth";
import { db } from "@/lib/db";
import { money } from "@/lib/format";
import { marketingIdentityKey } from "@/lib/marketing-compliance";
import { ensureMarketingRuntime } from "@/lib/marketing-runtime";
import { resolveStaffLocale } from "@/lib/i18n";

export const dynamic = "force-dynamic";
type Channel="EMAIL"|"SMS"|"WHATSAPP";type AttributionRow={source:string|null;medium:string|null;campaign:string|null;orders:number;revenue:number};type CampaignListRow={id:string;name:string;channel:Channel;status:string;estimatedRecipients:number;estimatedCostMinor:number;createdAt:string;contentJson:string};type SettingsRow={metaPixelId:string|null;googleAnalyticsId:string|null;googleAdsId:string|null;tiktokPixelId:string|null};type ConsentRow={guestId:string;channel:Channel;status:"GRANTED"|"REVOKED"|"UNKNOWN"};type SuppressionRow={guestId:string;channel:Channel|null};type AudienceCustomer={key:string;guestId:string|null;name:string;email:string;phone:string;city:string|null;orders:number;totalMinor:number;lastPurchaseAt:Date};const GUEST_LIST_PREFIX="__GUEST_LIST__:";
const copy={
ru:{title:"Рассылки, автоматизации и реклама",description:"Единый кабинет клиентской базы, согласий, Email, SMS, WhatsApp, рекламных ссылок и атрибуции продаж.",drafts:"Черновики доступны",legal:"Правовой контроль",safe:"Безопасный режим включён",providers:"Провайдеры отключены",legalHelp:"История покупок сохраняется полностью и не считается согласием на рекламу. Отписка меняет только маркетинговый статус клиента.",history:"Клиенты в истории",unique:"уникальные покупатели",email:"Email разрешён",sms:"SMS разрешён",wa:"WhatsApp разрешён",paid:"Оплаченные продажи",orders:"заказов",average:"Средний заказ",seven:"Продажи за 7 дней",partners:"Партнёрские ссылки",partnersCount:"партнёров",sources:"Источники продаж",campaigns:"Кампании и выручка",working:"Работает",tracking:"Atlas сохраняет UTM-источник при переходе и связывает его с заказом в момент checkout.",source:"Источник",campaign:"Кампания",ordersCol:"Заказы",revenue:"Выручка",direct:"Прямые продажи",withoutTag:"Без рекламной метки",unknown:"Не указан",unnamed:"Без названия",partnerSales:"Продажи через партнёров",promoters:"Промокоды, блогеры и промоутеры",analytics:"Расширенная аналитика →",activeCodes:"Активные промокоды",code:"Код",event:"Событие",discount:"Скидка",noCodes:"Промокодов пока нет.",results:"Партнёрские результаты",latest:"Последние ссылки",partner:"Партнёр",clicks:"Клики",noLinks:"Партнёрских ссылок пока нет."},
he:{title:"דיוור, אוטומציות ופרסום",description:"מרכז אחד לניהול בסיס הלקוחות, הסכמות, Email, SMS, WhatsApp, קישורי פרסום וייחוס מכירות.",drafts:"טיוטות זמינות",legal:"בקרה משפטית",safe:"מצב בטוח פעיל",providers:"הספקים מושבתים",legalHelp:"היסטוריית הרכישות נשמרת במלואה ואינה נחשבת להסכמה לפרסום. הסרה משנה רק את הסטטוס השיווקי של הלקוח.",history:"לקוחות בהיסטוריה",unique:"רוכשים ייחודיים",email:"Email מאושר",sms:"SMS מאושר",wa:"WhatsApp מאושר",paid:"מכירות ששולמו",orders:"הזמנות",average:"הזמנה ממוצעת",seven:"מכירות ב־7 ימים",partners:"קישורי שותפים",partnersCount:"שותפים",sources:"מקורות מכירה",campaigns:"קמפיינים והכנסות",working:"פעיל",tracking:"Atlas שומרת את מקור ה־UTM בעת הכניסה ומקשרת אותו להזמנה בזמן checkout.",source:"מקור",campaign:"קמפיין",ordersCol:"הזמנות",revenue:"הכנסות",direct:"מכירות ישירות",withoutTag:"ללא תג פרסום",unknown:"לא צוין",unnamed:"ללא שם",partnerSales:"מכירות דרך שותפים",promoters:"קודי קופון, בלוגרים ומקדמים",analytics:"אנליטיקה מורחבת ←",activeCodes:"קודי קופון פעילים",code:"קוד",event:"אירוע",discount:"הנחה",noCodes:"עדיין אין קודי קופון.",results:"תוצאות שותפים",latest:"קישורים אחרונים",partner:"שותף",clicks:"קליקים",noLinks:"עדיין אין קישורי שותפים."},
en:{title:"Campaigns, automation, and advertising",description:"One workspace for the customer base, consents, Email, SMS, WhatsApp, campaign links, and sales attribution.",drafts:"Drafts available",legal:"Legal controls",safe:"Safe mode enabled",providers:"Providers disabled",legalHelp:"Purchase history is preserved in full and is not treated as advertising consent. Unsubscribing changes only the customer's marketing status.",history:"Customers in history",unique:"unique buyers",email:"Email allowed",sms:"SMS allowed",wa:"WhatsApp allowed",paid:"Paid sales",orders:"orders",average:"Average order",seven:"Sales in 7 days",partners:"Partner links",partnersCount:"partners",sources:"Sales sources",campaigns:"Campaigns and revenue",working:"Active",tracking:"Atlas stores the UTM source on entry and links it to the order at checkout.",source:"Source",campaign:"Campaign",ordersCol:"Orders",revenue:"Revenue",direct:"Direct sales",withoutTag:"No campaign tag",unknown:"Not specified",unnamed:"Unnamed",partnerSales:"Partner sales",promoters:"Promo codes, bloggers, and promoters",analytics:"Advanced analytics →",activeCodes:"Active promo codes",code:"Code",event:"Event",discount:"Discount",noCodes:"No promo codes yet.",results:"Partner results",latest:"Latest links",partner:"Partner",clicks:"Clicks",noLinks:"No partner links yet."}
} as const;

export default async function MarketingPage() {
  const staff=await requirePermission("ANALYTICS_VIEW");const locale=resolveStaffLocale({memberOverride:staff.interfaceLocaleOverride,userPreference:staff.preferredLocale,organizationDefault:staff.organization?.defaultStaffLocale});const text=copy[locale];const organizationId=staff.organizationId!;await ensureMarketingRuntime();
  const [events,paidOrders,recentOrders,attribution,settings,customerOrders,promoters,partnerLinks,promoCodes,consents,suppressions,campaignRows]=await Promise.all([
    db.event.findMany({where:{organizationId},orderBy:{startsAt:"desc"},take:30,include:{categories:true,zones:{include:{tables:true}}}}),db.order.aggregate({where:{status:"PAID",event:{organizationId}},_sum:{totalMinor:true},_count:{_all:true}}),db.order.findMany({where:{status:"PAID",event:{organizationId}},orderBy:{createdAt:"desc"},take:100,select:{totalMinor:true,createdAt:true}}),db.$queryRawUnsafe<AttributionRow[]>(`SELECT a."source", a."medium", a."campaign", COUNT(o."id") AS orders, COALESCE(SUM(o."totalMinor"),0) AS revenue FROM "OrderMarketingAttribution" a JOIN "Order" o ON o."id"=a."orderId" JOIN "Event" e ON e."id"=o."eventId" WHERE e."organizationId"=$1 AND o."status"='PAID' GROUP BY a."source",a."medium",a."campaign" ORDER BY revenue DESC`,organizationId),db.$queryRawUnsafe<SettingsRow[]>(`SELECT "metaPixelId","googleAnalyticsId","googleAdsId","tiktokPixelId" FROM "OrganizationMarketingSettings" WHERE "organizationId"=$1 LIMIT 1`,organizationId),db.order.findMany({where:{status:"PAID",event:{organizationId}},orderBy:{createdAt:"desc"},select:{customerName:true,customerEmail:true,customerPhone:true,customerCity:true,totalMinor:true,createdAt:true,guestId:true}}),db.promoter.findMany({where:{organizationId,NOT:{name:{startsWith:GUEST_LIST_PREFIX}}},orderBy:{name:"asc"}}),db.promoterLink.findMany({where:{event:{organizationId},promoter:{NOT:{name:{startsWith:GUEST_LIST_PREFIX}}}},orderBy:{createdAt:"desc"},include:{promoter:true,event:true,visits:{select:{id:true}},orders:{where:{status:{notIn:["CANCELLED","REJECTED"]}},include:{items:true}}}}),db.promoCode.findMany({where:{event:{organizationId}},orderBy:{id:"desc"},include:{event:true}}),db.$queryRawUnsafe<ConsentRow[]>(`SELECT "guestId","channel","status" FROM "MarketingConsent" WHERE "organizationId"=$1 AND "purpose"='MARKETING'`,organizationId),db.$queryRawUnsafe<SuppressionRow[]>(`SELECT "guestId","channel" FROM "MarketingSuppression" WHERE "organizationId"=$1 AND "releasedAt" IS NULL`,organizationId),db.$queryRawUnsafe<CampaignListRow[]>(`SELECT "id","name","channel","status","estimatedRecipients","estimatedCostMinor","createdAt","contentJson" FROM "MarketingCampaign" WHERE "organizationId"=$1 ORDER BY "createdAt" DESC LIMIT 100`,organizationId)]);
  const audience=new Map<string,AudienceCustomer>();for(const order of customerOrders){const key=marketingIdentityKey({guestId:order.guestId,email:order.customerEmail,phone:order.customerPhone});const previous=audience.get(key);audience.set(key,{key,guestId:previous?.guestId??order.guestId,name:previous?.name??order.customerName,email:previous?.email??order.customerEmail,phone:previous?.phone??order.customerPhone,city:previous?.city??order.customerCity,orders:(previous?.orders??0)+1,totalMinor:(previous?.totalMinor??0)+order.totalMinor,lastPurchaseAt:previous&&previous.lastPurchaseAt>order.createdAt?previous.lastPurchaseAt:order.createdAt});}
  const consentMap=new Map<string,Partial<Record<Channel,"GRANTED"|"REVOKED"|"UNKNOWN">>>();for(const row of consents)consentMap.set(row.guestId,{...consentMap.get(row.guestId),[row.channel]:row.status});const suppressionMap=new Map<string,{channels:Channel[];all:boolean}>();for(const row of suppressions){const current=suppressionMap.get(row.guestId)??{channels:[],all:false};if(row.channel)current.channels.push(row.channel);else current.all=true;suppressionMap.set(row.guestId,current);}
  const customers=[...audience.values()].sort((a,b)=>b.lastPurchaseAt.getTime()-a.lastPurchaseAt.getTime()).map(customer=>({guestId:customer.guestId,name:customer.name,email:customer.email,phone:customer.phone,city:customer.city,orders:customer.orders,totalMinor:customer.totalMinor,lastPurchaseAt:customer.lastPurchaseAt.toISOString(),consents:customer.guestId?consentMap.get(customer.guestId)??{}:{},suppressed:customer.guestId?suppressionMap.get(customer.guestId)?.channels??[]:[],fullySuppressed:customer.guestId?suppressionMap.get(customer.guestId)?.all??false:false}));const allowed=(channel:Channel)=>customers.filter(customer=>customer.consents[channel]==="GRANTED"&&!customer.fullySuppressed&&!customer.suppressed.includes(channel)).length;
  const campaignList=campaignRows.map(row=>{let message="";try{message=(JSON.parse(row.contentJson) as {message?:string}).message??"";}catch{}return{...row,createdAt:String(row.createdAt),message};});const revenue=paidOrders._sum.totalMinor??0;const orderCount=paidOrders._count._all;const averageOrder=orderCount?Math.round(revenue/orderCount):0;const last7Days=recentOrders.filter(order=>order.createdAt.getTime()>=Date.now()-7*86400000);const last7Revenue=last7Days.reduce((sum,order)=>sum+order.totalMinor,0);const attributedOrders=attribution.reduce((sum,row)=>sum+Number(row.orders),0);const directOrders=Math.max(0,orderCount-attributedOrders);const attributedRevenue=attribution.reduce((sum,row)=>sum+Number(row.revenue),0);const directRevenue=Math.max(0,revenue-attributedRevenue);const saved=settings[0];
  return <AdminShell>
    <div className="row between"><div><span className="eyebrow">Atlas Marketing</span><h1>{text.title}</h1><p className="muted">{text.description}</p></div><span className="pill">{text.drafts}</span></div>
    <div className="card" style={{borderInlineStart:"4px solid #f59e0b"}}><div className="row between"><div><span className="eyebrow">{text.legal}</span><h2>{text.safe}</h2></div><span className="pill">{text.providers}</span></div><p className="muted">{text.legalHelp}</p></div>
    <div className="stats"><div className="stat"><span className="muted">{text.history}</span><strong>{customers.length}</strong><small>{text.unique}</small></div><div className="stat"><span className="muted">{text.email}</span><strong>{allowed("EMAIL")}</strong></div><div className="stat"><span className="muted">{text.sms}</span><strong>{allowed("SMS")}</strong></div><div className="stat"><span className="muted">{text.wa}</span><strong>{allowed("WHATSAPP")}</strong></div></div>
    <MarketingAudienceManager customers={customers}/><MarketingCampaignBuilder customers={customers} events={events.map(event=>({id:event.id,title:event.title}))}/><MarketingCampaignList campaigns={campaignList}/>
    <div className="stats"><div className="stat"><span className="muted">{text.paid}</span><strong><bdi>{money(revenue)}</bdi></strong><small>{orderCount} {text.orders}</small></div><div className="stat"><span className="muted">{text.average}</span><strong><bdi>{money(averageOrder)}</bdi></strong></div><div className="stat"><span className="muted">{text.seven}</span><strong><bdi>{money(last7Revenue)}</bdi></strong></div><div className="stat"><span className="muted">{text.partners}</span><strong>{partnerLinks.length}</strong><small>{promoters.length} {text.partnersCount}</small></div></div>
    <div className="card"><div className="row between"><div><span className="eyebrow">{text.sources}</span><h2>{text.campaigns}</h2></div><span className="pill">{text.working}</span></div><p className="muted">{text.tracking}</p><div className="table-wrap"><table><thead><tr><th>{text.source}</th><th>{text.campaign}</th><th>{text.ordersCol}</th><th>{text.revenue}</th></tr></thead><tbody><tr><td><strong>{text.direct}</strong><br/><small>{text.withoutTag}</small></td><td>-</td><td>{directOrders}</td><td><bdi>{money(directRevenue)}</bdi></td></tr>{attribution.map((row,index)=><tr key={`${row.source}-${row.campaign}-${index}`}><td><strong><bdi>{row.source||text.unknown}</bdi></strong><br/><small><bdi>{row.medium||"-"}</bdi></small></td><td><bdi>{row.campaign||text.unnamed}</bdi></td><td>{Number(row.orders)}</td><td><bdi>{money(Number(row.revenue))}</bdi></td></tr>)}</tbody></table></div></div>
    <div id="utm"><MarketingLinkBuilder events={events.map(event=>({id:event.id,title:event.title,publicUrl:`/events/${event.slug}`}))}/></div><MarketingSettingsForm initial={{metaPixelId:saved?.metaPixelId??"",googleAnalyticsId:saved?.googleAnalyticsId??"",googleAdsId:saved?.googleAdsId??"",tiktokPixelId:saved?.tiktokPixelId??""}}/>
    <div className="row between"><div><span className="eyebrow">{text.partnerSales}</span><h2 className="section-title">{text.promoters}</h2></div><Link href="/office/promoters">{text.analytics}</Link></div>
    {staff.permissionSet.has("EVENT_MANAGE")&&<><MarketingPromoManager events={events.map(event=>({id:event.id,title:event.title}))}/><PromoterManager promoters={promoters.map(item=>({id:item.id,name:item.name,defaultCommissionBps:item.defaultCommissionBps}))} events={events.map(event=>({id:event.id,title:event.title,categories:event.categories.map(item=>({id:item.id,name:item.name})),tables:event.zones.flatMap(zone=>zone.tables.map(item=>({id:item.id,label:`${zone.name} · ${item.label}`})))}))}/></>}
    <div className="grid-2"><div className="card"><span className="eyebrow">{text.activeCodes}</span><h2>{promoCodes.length}</h2><div className="table-wrap"><table><thead><tr><th>{text.code}</th><th>{text.event}</th><th>{text.discount}</th></tr></thead><tbody>{promoCodes.slice(0,10).map(promo=><tr key={promo.id}><td><strong><bdi>{promo.code}</bdi></strong></td><td>{promo.event.title}</td><td><bdi>{promo.discountPercent}%</bdi></td></tr>)}{!promoCodes.length&&<tr><td colSpan={3}>{text.noCodes}</td></tr>}</tbody></table></div></div><div className="card"><span className="eyebrow">{text.results}</span><h2>{text.latest}</h2><div className="table-wrap"><table><thead><tr><th>{text.partner}</th><th>{text.clicks}</th><th>{text.ordersCol}</th><th>{text.revenue}</th></tr></thead><tbody>{partnerLinks.slice(0,10).map(link=>{const linkRevenue=link.orders.reduce((sum,order)=>sum+order.totalMinor,0);return <tr key={link.id}><td><strong>{link.promoter.name}</strong><br/><small>{link.label}</small></td><td>{link.visits.length}</td><td>{link.orders.length}</td><td><bdi>{money(linkRevenue)}</bdi></td></tr>})}{!partnerLinks.length&&<tr><td colSpan={4}>{text.noLinks}</td></tr>}</tbody></table></div></div></div>
  </AdminShell>;
}
