import Link from "next/link";
import {notFound} from "next/navigation";
import {PlatformShell} from "@/components/platform-shell";
import {FinanceReportActions} from "@/components/finance-report-actions";
import {requirePlatformAdmin} from "@/lib/auth";
import {db} from "@/lib/db";
import {organizerFinanceEvent} from "@/lib/finance";
import {eventDate,money} from "@/lib/format";
import {getServerI18n} from "@/lib/server-locale";
import {localeConfig} from "@/lib/i18n";

export const dynamic="force-dynamic";
const copy={ru:{eyebrow:"Отчёт организатора",help:"Версия отчёта, которую можно показать организатору. Внутренние комиссии и маржа Atlas здесь намеренно не раскрываются.",earned:"Заработок организатора",refunds:"Возвраты",services:"Доп. сервисы",balance:"Остаток",balanceHelp:"после уже произведённых выплат",paid:"Уже выплачено",available:"Доступно сейчас",settlement:"Ожидает settlement",flow:"Движение средств",date:"Дата",operation:"Операция",number:"Номер",description:"Описание",amount:"Сумма",empty:"Операций пока нет.",types:{SALE:"Продажа",REFUND:"Возврат",SERVICE:"Услуга",PAYOUT:"Выплата"}},he:{eyebrow:"דוח מפיק",help:"גרסת הדוח שניתן להציג למפיק. עמלות פנימיות ומרווחי Atlas אינם מוצגים כאן בכוונה.",earned:"הכנסות המפיק",refunds:"החזרים",services:"שירותים נוספים",balance:"יתרה",balanceHelp:"לאחר תשלומים שכבר בוצעו",paid:"כבר שולם",available:"זמין כעת",settlement:"ממתין ל-settlement",flow:"תנועות כספיות",date:"תאריך",operation:"פעולה",number:"מספר",description:"תיאור",amount:"סכום",empty:"עדיין אין פעולות.",types:{SALE:"מכירה",REFUND:"החזר",SERVICE:"שירות",PAYOUT:"תשלום"}},en:{eyebrow:"Organizer report",help:"This report can be shared with the organizer. Internal Atlas fees and margin are intentionally not disclosed here.",earned:"Organizer earnings",refunds:"Refunds",services:"Additional services",balance:"Balance",balanceHelp:"after payouts already made",paid:"Already paid",available:"Available now",settlement:"Awaiting settlement",flow:"Money movements",date:"Date",operation:"Operation",number:"Number",description:"Description",amount:"Amount",empty:"No operations yet.",types:{SALE:"Sale",REFUND:"Refund",SERVICE:"Service",PAYOUT:"Payout"}}} as const;
function dateTime(date:Date,tag:string){return new Intl.DateTimeFormat(tag,{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit",timeZone:"Asia/Jerusalem"}).format(date)}
export default async function PlatformEventReport({params}:{params:Promise<{eventId:string}>}){await requirePlatformAdmin();const[{eventId},{locale}]=await Promise.all([params,getServerI18n()]);const t=copy[locale];const source=await db.event.findUnique({where:{id:eventId},select:{organizationId:true,organization:{select:{name:true}}}});if(!source)notFound();const data=await organizerFinanceEvent(source.organizationId,eventId);if(!data)notFound();const{event,transactions}=data;const typeLabel=(type:string)=>type==="SALE"?t.types.SALE:type==="REFUND"?t.types.REFUND:type==="SERVICE"?t.types.SERVICE:t.types.PAYOUT;return <PlatformShell><div className="platform-heading"><div><Link href={`/platform/organizers/${source.organizationId}`} className="muted">← {source.organization.name}</Link><span className="eyebrow" style={{display:"block",marginTop:12}}>{t.eyebrow} · <bdi>{eventDate(event.eventStartsAt,locale)}</bdi></span><h1>{event.eventTitle}</h1><p>{t.help}</p></div><FinanceReportActions eventId={eventId} locale={locale}/></div><div className="stats"><div className="stat"><span className="muted">{t.earned}</span><strong><bdi>{money(event.salesMinor,"ILS",locale)}</bdi></strong></div><div className="stat"><span className="muted">{t.refunds}</span><strong><bdi>{money(event.refundsMinor,"ILS",locale)}</bdi></strong></div><div className="stat"><span className="muted">{t.services}</span><strong><bdi>{money(event.servicesMinor,"ILS",locale)}</bdi></strong></div><div className="stat"><span className="muted">{t.balance}</span><strong><bdi>{money(event.balanceMinor-event.paidOutMinor,"ILS",locale)}</bdi></strong><small>{t.balanceHelp}</small></div></div><div className="platform-section-card"><div className="row between" style={{gap:18,flexWrap:"wrap"}}><div><span className="muted">{t.paid}</span><h2><bdi>{money(event.paidOutMinor,"ILS",locale)}</bdi></h2></div><div><span className="muted">{t.available}</span><h2><bdi>{money(event.availableMinor,"ILS",locale)}</bdi></h2></div><div><span className="muted">{t.settlement}</span><h2><bdi>{money(Math.max(0,event.awaitingSettlementMinor),"ILS",locale)}</bdi></h2></div></div></div><h2 className="section-title">{t.flow}</h2><div className="table-wrap platform-table-fit"><table><thead><tr><th>{t.date}</th><th>{t.operation}</th><th>{t.number}</th><th>{t.description}</th><th>{t.amount}</th></tr></thead><tbody>{transactions.map(tx=><tr key={`${tx.type}-${tx.id}`}><td><bdi>{dateTime(tx.createdAt,localeConfig[locale].tag)}</bdi></td><td>{typeLabel(tx.type)}</td><td><strong><bdi>{tx.publicId}</bdi></strong></td><td dir="auto">{tx.description}</td><td style={{fontWeight:800,color:tx.amountMinor>=0?"#15803d":"#b42318"}}><bdi>{tx.amountMinor>=0?"+":""}{money(tx.amountMinor,"ILS",locale)}</bdi></td></tr>)}{!transactions.length&&<tr><td colSpan={5}>{t.empty}</td></tr>}</tbody></table></div></PlatformShell>}
