import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin-shell";
import { requirePermission } from "@/lib/auth";
import { CancellationReviewPrototype } from "@/components/cancellation-review-prototype";
import { getCancellationRequest } from "@/lib/cancellations";
import { money, eventDate, israelDateTime } from "@/lib/format";
import { resolveStaffLocale } from "@/lib/i18n";

export const dynamic = "force-dynamic";
const copy={
ru:{eyebrow:"Заявка на отмену",description:"Проверка реальной заявки клиента и выбор суммы возврата.",back:"Назад к отменам",customer:"Клиент и заказ",order:"Номер заказа",email:"Email",phone:"Телефон",purchase:"Дата покупки",request:"Заявка на отмену",reason:"Причина клиента",event:"Мероприятие",date:"Дата",tickets:"Билеты",ticketsFallback:"Билеты заказа",amount:"Сумма заказа",special:"Льготная категория",check:"Проверка Atlas",decision:"Принятое решение",status:"Статус",refund:"Сумма возврата",organizer:"За счёт организатора",legal:{STANDARD_ELIGIBLE:"Возврат предварительно положен по стандартной политике",SPECIAL_REVIEW:"Требуется специальная проверка",OTHER:"Стандартное право на возврат автоматически не подтверждено"}},
he:{eyebrow:"בקשת ביטול",description:"בדיקת בקשת הביטול של הלקוח ובחירת סכום ההחזר.",back:"חזרה לביטולים",customer:"לקוח והזמנה",order:"מספר הזמנה",email:"Email",phone:"טלפון",purchase:"תאריך רכישה",request:"בקשת ביטול",reason:"סיבת הלקוח",event:"אירוע",date:"תאריך",tickets:"כרטיסים",ticketsFallback:"כרטיסי ההזמנה",amount:"סכום ההזמנה",special:"קטגוריה מזכה",check:"בדיקת Atlas",decision:"החלטה שהתקבלה",status:"סטטוס",refund:"סכום ההחזר",organizer:"על חשבון המפיק",legal:{STANDARD_ELIGIBLE:"קיימת זכאות ראשונית להחזר לפי המדיניות הרגילה",SPECIAL_REVIEW:"נדרשת בדיקה מיוחדת",OTHER:"הזכאות הרגילה להחזר לא אושרה אוטומטית"}},
en:{eyebrow:"Cancellation request",description:"Review the customer's real cancellation request and choose the refund amount.",back:"Back to cancellations",customer:"Customer and order",order:"Order number",email:"Email",phone:"Phone",purchase:"Purchase date",request:"Cancellation request",reason:"Customer reason",event:"Event",date:"Date",tickets:"Tickets",ticketsFallback:"Order tickets",amount:"Order amount",special:"Eligible category",check:"Atlas review",decision:"Recorded decision",status:"Status",refund:"Refund amount",organizer:"Organizer-paid",legal:{STANDARD_ELIGIBLE:"Preliminarily eligible under the standard policy",SPECIAL_REVIEW:"Special review required",OTHER:"Standard refund eligibility was not automatically confirmed"}}
} as const;

export default async function CancellationDetail({params}:{params:Promise<{id:string}>}){
  const staff=await requirePermission("ORDER_VIEW");const locale=resolveStaffLocale({memberOverride:staff.interfaceLocaleOverride,userPreference:staff.preferredLocale,organizationDefault:staff.organization?.defaultStaffLocale});const text=copy[locale];const {id}=await params;const eventIds=staff.eventAccess.map(item=>item.eventId);const row=await getCancellationRequest(id,staff.organizationId!,eventIds.length?eventIds:undefined);if(!row)notFound();const legalTitle=(value:string)=>value==="STANDARD_ELIGIBLE"?text.legal.STANDARD_ELIGIBLE:value==="SPECIAL_REVIEW"?text.legal.SPECIAL_REVIEW:text.legal.OTHER;
  return <AdminShell><div className="office-page-heading"><div><span className="eyebrow">{text.eyebrow}</span><h1><bdi>{row.publicId}</bdi></h1><p>{text.description}</p></div><Link className="btn secondary" href="/office/cancellations">{text.back}</Link></div><div className="form-grid two" style={{alignItems:"start"}}><div className="stack">
    <section className="panel stack"><div><span className="eyebrow">{text.customer}</span><h2>{row.customerName}</h2></div><div className="row between"><span className="muted">{text.order}</span><strong><bdi>{row.orderPublicId}</bdi></strong></div><div className="row between"><span className="muted">{text.email}</span><strong><bdi>{row.customerEmail}</bdi></strong></div><div className="row between"><span className="muted">{text.phone}</span><strong><bdi>{row.customerPhone}</bdi></strong></div><div className="row between"><span className="muted">{text.purchase}</span><strong><bdi>{israelDateTime(row.orderCreatedAt)}</bdi></strong></div><div className="row between"><span className="muted">{text.request}</span><strong><bdi>{israelDateTime(row.createdAt)}</bdi></strong></div>{row.reason&&<div><span className="muted">{text.reason}</span><p style={{marginBottom:0}}>{row.reason}</p></div>}</section>
    <section className="panel stack"><div><span className="eyebrow">{text.event}</span><h2>{row.eventTitle}</h2></div><div className="row between"><span className="muted">{text.date}</span><strong>{eventDate(row.eventStartsAt)}</strong></div><div className="row between"><span className="muted">{text.tickets}</span><strong>{row.itemSummary||text.ticketsFallback}</strong></div><div className="row between"><span className="muted">{text.amount}</span><strong><bdi>{money(row.orderAmountMinor)}</bdi></strong></div>{row.specialCategory&&<div className="row between"><span className="muted">{text.special}</span><strong>{row.specialCategory}</strong></div>}</section>
    <section className="panel" style={{background:row.legalStatus==="STANDARD_ELIGIBLE"?"#f0fdf4":row.legalStatus==="SPECIAL_REVIEW"?"#fffbeb":"#fff7ed",borderColor:row.legalStatus==="STANDARD_ELIGIBLE"?"#bbf7d0":row.legalStatus==="SPECIAL_REVIEW"?"#fde68a":"#fed7aa"}}><span className="eyebrow">{text.check}</span><h3 style={{marginTop:6}}>{legalTitle(row.legalStatus)}</h3><p className="muted" style={{marginBottom:0}}>{row.legalReason}</p></section>
    {row.reviewedAt&&<section className="panel stack"><span className="eyebrow">{text.decision}</span><div className="row between"><span className="muted">{text.status}</span><strong><bdi>{row.status}</bdi></strong></div>{row.refundAmountMinor!==null&&<div className="row between"><span className="muted">{text.refund}</span><strong><bdi>{money(row.refundAmountMinor)}</bdi></strong></div>}{row.organizerChargeMinor!==null&&<div className="row between"><span className="muted">{text.organizer}</span><strong><bdi>{money(row.organizerChargeMinor)}</bdi></strong></div>}{row.decisionNote&&<p>{row.decisionNote}</p>}</section>}
  </div><CancellationReviewPrototype id={row.id} orderAmountMinor={row.orderAmountMinor} statutoryFeeMinor={row.statutoryFeeMinor} status={row.status}/></div></AdminShell>;
}
