import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin-shell";
import { FinanceReportActions } from "@/components/finance-report-actions";
import { requirePermission, canAccessEvent } from "@/lib/auth";
import { organizerFinanceEvent } from "@/lib/finance";
import { eventDate, money } from "@/lib/format";
import { localeTag, resolveStaffLocale } from "@/lib/i18n";

export const dynamic="force-dynamic";

const copy={
  ru:{back:"← Все мероприятия",description:"Финансовый результат и движение средств по этому мероприятию. Этот экран можно передать бухгалтерии как прозрачный отчёт.",sales:"Продажи",salesHelp:"ваш доход от билетов",refunds:"Возвраты",refundsHelp:"уменьшают ваш баланс",services:"Доп. услуги",servicesHelp:"только платные дополнительные сервисы",balance:"Текущий баланс",balanceHelp:"после возвратов, услуг и выплат",paid:"Уже выплачено",paidHelp:"по этому мероприятию",available:"Доступно к выплате",availableHelp:"Сумма открывается только после наступления стандартного payout-cycle 7-го числа.",awaiting:"Ожидает поступления",awaitingHelp:"Будет учтено после расчётного цикла платёжной системы 6-го числа.",payout:"Плановая выплата",payoutHelp:"Следующий стандартный цикл после проведения мероприятия.",movement:"Движение средств",columns:["Дата","Операция","Номер","Описание","Сумма"],empty:"Операций пока нет.",how:"Как считается этот отчёт?",howText:"Продажи показывают только сумму, принадлежащую вашей организации. Внутренние комиссии Atlas не раскрываются. Фактические возвраты, комиссии отмены, заказанные дополнительные услуги и уже произведённые выплаты уменьшают текущий остаток.",types:{SALE:"Продажа",REFUND:"Возврат",SERVICE:"Услуга",PAYOUT:"Выплата"}},
  he:{back:"← לכל האירועים",description:"תוצאה פיננסית ותנועת הכספים של האירוע. אפשר להעביר את המסך הזה להנהלת החשבונות כדוח שקוף וברור.",sales:"מכירות",salesHelp:"ההכנסה שלכם ממכירת כרטיסים",refunds:"החזרים",refundsHelp:"מפחיתים את היתרה שלכם",services:"שירותים נוספים",servicesHelp:"רק שירותים נוספים בתשלום",balance:"יתרה נוכחית",balanceHelp:"לאחר החזרים, שירותים ותשלומים",paid:"כבר שולם",paidHelp:"עבור האירוע הזה",available:"זמין לתשלום",availableHelp:"הסכום נפתח רק לאחר מחזור התשלום הסטנדרטי ב־7 בחודש.",awaiting:"ממתין להתחשבנות",awaitingHelp:"ייכלל לאחר מחזור ההתחשבנות של חברת הסליקה ב־6 בחודש.",payout:"תשלום מתוכנן",payoutHelp:"מחזור התשלום הסטנדרטי הבא לאחר קיום האירוע.",movement:"תנועת כספים",columns:["תאריך","פעולה","מספר","תיאור","סכום"],empty:"עדיין אין פעולות.",how:"איך מחושב הדוח?",howText:"המכירות מציגות רק את הסכום השייך לארגון שלכם. העמלות הפנימיות של Atlas אינן מוצגות. החזרים שבוצעו בפועל, עמלות ביטול, שירותים נוספים שהוזמנו ותשלומים שכבר בוצעו מפחיתים את היתרה הנוכחית.",types:{SALE:"מכירה",REFUND:"החזר",SERVICE:"שירות",PAYOUT:"תשלום"}},
  en:{back:"← All events",description:"Financial result and cash movement for this event. This screen can be shared with accounting as a transparent report.",sales:"Sales",salesHelp:"your ticket revenue",refunds:"Refunds",refundsHelp:"reduce your balance",services:"Additional services",servicesHelp:"paid add-on services only",balance:"Current balance",balanceHelp:"after refunds, services and payouts",paid:"Already paid",paidHelp:"for this event",available:"Available for payout",availableHelp:"Funds become available only after the standard payout cycle on the 7th.",awaiting:"Awaiting settlement",awaitingHelp:"Included after the payment provider settlement cycle on the 6th.",payout:"Scheduled payout",payoutHelp:"Next standard cycle after the event takes place.",movement:"Cash movement",columns:["Date","Operation","Number","Description","Amount"],empty:"No transactions yet.",how:"How is this report calculated?",howText:"Sales show only the amount belonging to your organization. Atlas internal fees are not disclosed. Actual refunds, cancellation fees, ordered add-on services and completed payouts reduce the current balance.",types:{SALE:"Sale",REFUND:"Refund",SERVICE:"Service",PAYOUT:"Payout"}}
} as const;

export default async function EventFinancePage({params}:{params:Promise<{eventId:string}>}){
  const {eventId}=await params;
  const staff=await requirePermission("FINANCE_VIEW");
  if(!canAccessEvent(staff,eventId))notFound();
  const locale=resolveStaffLocale({memberOverride:staff.interfaceLocaleOverride,userPreference:staff.preferredLocale,organizationDefault:staff.organization?.defaultStaffLocale});
  const text=copy[locale];
  const data=await organizerFinanceEvent(staff.organizationId!,eventId);
  if(!data)notFound();
  const {event,transactions}=data;
  const dateTime=(date:Date)=>new Intl.DateTimeFormat(localeTag(locale),{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit",timeZone:"Asia/Jerusalem"}).format(date);
  const dateLabel=(date:Date)=>new Intl.DateTimeFormat(localeTag(locale),{day:"numeric",month:"long",year:"numeric",timeZone:"Asia/Jerusalem"}).format(date);
  const typeLabel=(type:string)=>text.types[type as keyof typeof text.types]??type;

  return <AdminShell>
    <div className="office-page-heading"><div><Link href="/office/finance" className="muted">{text.back}</Link><span className="eyebrow" style={{display:"block",marginTop:12}}>Finance · {eventDate(event.eventStartsAt)}</span><h1>{event.eventTitle}</h1><p>{text.description}</p></div><FinanceReportActions eventId={eventId} locale={locale}/></div>
    <div className="stats"><div className="stat"><span className="muted">{text.sales}</span><strong><bdi>{money(event.salesMinor)}</bdi></strong><small>{text.salesHelp}</small></div><div className="stat"><span className="muted">{text.refunds}</span><strong><bdi>{money(event.refundsMinor)}</bdi></strong><small>{text.refundsHelp}</small></div><div className="stat"><span className="muted">{text.services}</span><strong><bdi>{money(event.servicesMinor)}</bdi></strong><small>{text.servicesHelp}</small></div><div className="stat"><span className="muted">{text.balance}</span><strong><bdi>{money(event.balanceMinor-event.paidOutMinor)}</bdi></strong><small>{text.balanceHelp}</small></div><div className="stat"><span className="muted">{text.paid}</span><strong><bdi>{money(event.paidOutMinor)}</bdi></strong><small>{text.paidHelp}</small></div></div>
    <section className="panel" style={{marginBottom:20}}><div className="row between" style={{alignItems:"stretch",gap:16,flexWrap:"wrap"}}><div style={{flex:"1 1 260px",padding:16,border:"1px solid #dbe7dc",borderRadius:14,background:"#f6fff8"}}><span className="muted">{text.available}</span><h2 style={{margin:"6px 0",color:"#15803d"}}><bdi>{money(event.availableMinor)}</bdi></h2><small>{text.availableHelp}</small></div><div style={{flex:"1 1 260px",padding:16,border:"1px solid #f0dfb8",borderRadius:14,background:"#fffaf0"}}><span className="muted">{text.awaiting}</span><h2 style={{margin:"6px 0",color:"#a16207"}}><bdi>{money(Math.max(0,event.awaitingSettlementMinor))}</bdi></h2><small>{text.awaitingHelp}</small></div><div style={{flex:"1 1 260px",padding:16,border:"1px solid #d9e4f8",borderRadius:14,background:"#f7faff"}}><span className="muted">{text.payout}</span><h2 style={{margin:"6px 0",color:"#1d4ed8"}}>{dateLabel(event.payoutDate)}</h2><small>{text.payoutHelp}</small></div></div></section>
    <h2 className="section-title">{text.movement}</h2>
    <div className="table-wrap"><table><thead><tr>{text.columns.map(column=><th key={column}>{column}</th>)}</tr></thead><tbody>{transactions.map(tx=><tr key={`${tx.type}-${tx.id}`}><td>{dateTime(tx.createdAt)}</td><td><span className="pill">{typeLabel(tx.type)}</span></td><td><strong><bdi>{tx.publicId}</bdi></strong></td><td>{tx.description}</td><td style={{fontWeight:800,color:tx.amountMinor>=0?"#15803d":"#b42318"}}><bdi>{tx.amountMinor>=0?"+":""}{money(tx.amountMinor)}</bdi></td></tr>)}{!transactions.length&&<tr><td colSpan={5}>{text.empty}</td></tr>}</tbody></table></div>
    <section className="panel" style={{marginTop:20}}><strong>{text.how}</strong><p className="muted" style={{marginBottom:0}}>{text.howText}</p></section>
  </AdminShell>;
}
