const fs = require("node:fs");
const path = require("node:path");
const base = require("./app.json");

const iconBase64 = "iVBORw0KGgoAAAANSUhEUgAABAAAAAQACAIAAADwf7zUAAAZCUlEQVR42u3d61UjSRKA0WIO5yAHwBQwq23BLNqUtoCf86NnukFIoh75iox7LditllT5RSS7dw+PzwsAAJDDPx4BAAAIAAAAQAAAAAACAAAAEAAAAIAAAAAABAAAACAAAAAAAQAAAAgAAABAAAAAAAIAAAAEAAAAIAAAAAABAAAACAAAAEAAAAAAAgAAABAAAACAAAAAAAQAAAAgAAAAAAEAAAACAAAAEAAAAIAAAAAABAAAACAAAAAAAQAAAAgAAABAAAAAAAIAAAAQAAAAgAAAAAABAAAACAAAAEAAAAAAAgAAABAAAACAAAAAAAQAAAAgAAAAAAEAAAAIAAAAQAAAAIAAAAAABAAAACAAAAAAAQAAAAgAAABAAAAAAAIAAAAQAAAAgAAAAAAEAAAAIAAAAAABAAAAAgAAABAAAACAAAAAAAQAAAAgAAAAAAEAAAAIAAAAQAAAAAACAAAAEAAAAIAAAAAAAQAAAAgAAABAAAAAAAIAAAAQAAAAgAAAAAAEAAAAIAAAAAABAAAACAAAAEAAAACAAAAAAAQAAAAgAAAAAAEAAAAIAAAAQAAAAAACAAAAEAAAAIAAAAAABAAAACAAAABAAAAAAAIAAAAQAAAAgAAAAAAEAAAAIAAAAAABAAAACAAAAEAAAAAAAgAAABAAAAAgAAAAAAEAAAAIAAAAQAAAAAACAAAAEAAAAIAAAAAABAAAACAAAAAAAQAAAAgAAABAAAAAgAAAAAAEAAAAIAAAAAABAAAACAAAAEAAAAAAAgAAABAAAACAAAAAAAQAAAAgAAAAQAAAAAACAAAAEAAAAIAAAAAABAAAACAAAAAAAQAAAAgAAABAAAAAAAIAAAAQAAAAIAAAAAABAAAACAAAAEAAAAAAAgAAABAAAACAAAAAAAQAAAAgAAAAAAEAAAAIAAAAEAAAAIAAAAAABAAAACAAAAAAAQAAAAgAAABAAAAAAAIAAAAQAAAAgAAAAAAEAAAACAAAAEAAAAAAAgAAABAAAACAAAAAAAQAAAAgAAAAAAEAAAAIAAAAQAAAAADX/QtC4o57zNkkzwAAAABJRU5ErkJggg==";

const generatedDir = path.join(__dirname, ".generated");
const iconPath = path.join(generatedDir, "atlas-office-icon.png");
fs.mkdirSync(generatedDir, { recursive: true });
if (!fs.existsSync(iconPath)) fs.writeFileSync(iconPath, Buffer.from(iconBase64, "base64"));

module.exports = {
  expo: {
    ...base.expo,
    icon: "./.generated/atlas-office-icon.png",
    ios: {
      ...base.expo.ios,
      icon: "./.generated/atlas-office-icon.png",
    },
    android: {
      ...base.expo.android,
      icon: "./.generated/atlas-office-icon.png",
    },
  },
};
