import { useRef, useState } from "react";
import { ActivityIndicator, Alert, Keyboard, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { patchEventEditor, type EventEditorState } from "@/lib/event-editor-api";

const AGE = ["Без ограничений", "Детское", "3+", "6+", "12+", "14+", "16+", "18+"];
const LANG = [{ id: "RU", label: "Русский" }, { id: "HE", label: "Иврит" }, { id: "EN", label: "Английский" }, { id: "AR", label: "Арабский" }, { id: "MULTILINGUAL", label: "Несколько языков" }, { id: "NO_LANGUAGE_BARRIER", label: "Без языкового барьера" }, { id: "OTHER", label: "Другой" }];
const VIS = [{ id: "PUBLIC", label: "Всем" }, { id: "TARGETED", label: "По языку" }, { id: "DIRECT_ONLY", label: "Только по ссылке" }];
const TYPES = [{ id: "SOLO_CONCERT", label: "Сольный концерт" }, { id: "LIVE_MUSIC", label: "Живая музыка" }, { id: "CLASSICAL_CONCERT", label: "Классический концерт" }, { id: "FESTIVAL", label: "Фестиваль" }, { id: "PARTY", label: "Вечеринка" }, { id: "DJ_SET", label: "DJ-сет" }, { id: "THEATRE", label: "Спектакль" }, { id: "COMEDY", label: "Стендап" }, { id: "CHILDREN_SHOW", label: "Детское" }, { id: "SPORT", label: "Спорт" }, { id: "LECTURE", label: "Лекция" }, { id: "CONFERENCE", label: "Конференция" }, { id: "EXHIBITION", label: "Выставка" }, { id: "WORKSHOP", label: "Мастер-класс" }, { id: "OTHER", label: "Другое" }];
const DRAFT_DEFAULTS = { title: "Новое мероприятие", description: "Добавьте описание мероприятия", venueName: "Новая площадка", city: "Город", address: "Адрес площадки" };

type ErrorKey = "title" | "description" | "date" | "time" | "venue" | "city" | "address" | "types" | "doors";
type Errors = Partial<Record<ErrorKey, string>>;

function localDateTime(iso: string) { const d = new Date(iso); if (Number.isNaN(d.getTime())) return { date: "", time: "" }; const p = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Jerusalem", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(d); const v = Object.fromEntries(p.map((x) => [x.type, x.value])); return { date: `${v.year}-${v.month}-${v.day}`, time: `${v.hour}:${v.minute}` }; }
function visible(value: string, technical: string, draft: boolean) { return draft && value === technical ? "" : value; }
function Chip({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <TouchableOpacity onPress={onPress} style={[s.chip, selected && s.chipOn]}><Text style={[s.chipText, selected && s.chipTextOn]}>{label}</Text></TouchableOpacity>; }
function Field({ label, required = false, error, children }: { label: string; required?: boolean; error?: string; children: React.ReactNode }) {
  return <View style={{ marginBottom: 13 }}><Text style={s.label}>{label}{required && <Text style={s.required}> *</Text>}</Text>{children}{error ? <Text style={s.errorText}>{error}</Text> : null}</View>;
}

export function AboutTab({ eventId, state, onState }: { eventId: string; state: EventEditorState; onState: (v: EventEditorState) => void }) {
  const e = state.event; const isDraft = e.status === "DRAFT"; const local = localDateTime(e.startsAt);
  const scrollRef = useRef<ScrollView>(null);
  const positions = useRef<Partial<Record<ErrorKey, number>>>({});
  const [title, setTitle] = useState(visible(e.title, DRAFT_DEFAULTS.title, isDraft)); const [short, setShort] = useState(e.presentation.shortDescription || ""); const [description, setDescription] = useState(visible(e.description, DRAFT_DEFAULTS.description, isDraft)); const [date, setDate] = useState(local.date); const [time, setTime] = useState(local.time); const [doors, setDoors] = useState(e.presentation.doorsOpenTime || "");
  const [venue, setVenue] = useState(visible(e.venue.name, DRAFT_DEFAULTS.venueName, isDraft)); const [city, setCity] = useState(visible(e.venue.city, DRAFT_DEFAULTS.city, isDraft)); const [address, setAddress] = useState(visible(e.venue.address, DRAFT_DEFAULTS.address, isDraft));
  const [age, setAge] = useState(e.presentation.ageRestriction || "Без ограничений"); const [runtime, setRuntime] = useState(String(e.presentation.runtimeMinutes || 0)); const [intermission, setIntermission] = useState(String(e.presentation.intermissionCount || 0)); const [language, setLanguage] = useState(e.language.primaryLanguage); const [visibility, setVisibility] = useState(e.language.catalogVisibility); const [types, setTypes] = useState<string[]>(e.eventTypes.length ? e.eventTypes : ["OTHER"]);
  const [video, setVideo] = useState(e.media.find((x) => x.type === "VIDEO")?.url || ""); const [links, setLinks] = useState(e.media.filter((x) => x.type === "LINK").map((x) => x.url).join("\n")); const [gallery, setGallery] = useState(e.presentation.galleryUrls.join("\n")); const [faq, setFaq] = useState(e.presentation.faq); const [busy, setBusy] = useState(false); const [errors, setErrors] = useState<Errors>({});

  function mark(key: ErrorKey) { return (event: { nativeEvent: { layout: { y: number } } }) => { positions.current[key] = event.nativeEvent.layout.y; }; }
  function clear(key: ErrorKey) { setErrors((current) => current[key] ? { ...current, [key]: undefined } : current); }
  function toggleType(id: string) { clear("types"); setTypes((current) => current.includes(id) ? (current.length > 1 ? current.filter((x) => x !== id) : current) : [...current.filter((x) => x !== "OTHER"), id]); }
  function validate() {
    const next: Errors = {};
    if (title.trim().length < 3) next.title = "Укажите название, минимум 3 символа.";
    if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) next.date = "Укажите дату в формате YYYY-MM-DD.";
    if (!/^\d{2}:\d{2}$/.test(time)) next.time = "Укажите время в формате HH:MM.";
    if (doors && !/^\d{2}:\d{2}$/.test(doors)) next.doors = "Используйте формат HH:MM.";
    if (venue.trim().length < 2) next.venue = "Укажите площадку.";
    if (city.trim().length < 2) next.city = "Укажите город.";
    if (address.trim().length < 3) next.address = "Укажите полный адрес.";
    if (!types.length) next.types = "Выберите хотя бы один тип мероприятия.";
    if (description.trim().length < 20) next.description = "Полное описание должно содержать минимум 20 символов.";
    return next;
  }
  async function save() {
    if (!state.permissions.includes("EVENT_MANAGE")) return Alert.alert("Нет доступа", "Нужен EVENT_MANAGE.");
    const nextErrors = validate();
    setErrors(nextErrors);
    const first = (["title", "date", "time", "doors", "venue", "city", "address", "types", "description"] as ErrorKey[]).find((key) => nextErrors[key]);
    if (first) {
      Keyboard.dismiss();
      requestAnimationFrame(() => scrollRef.current?.scrollTo({ y: Math.max(0, (positions.current[first] || 0) - 18), animated: true }));
      return;
    }
    const startsAt = new Date(`${date}T${time}:00+03:00`); const galleries = gallery.split(/\r?\n/).map((x) => x.trim()).filter(Boolean); const linkItems = links.split(/\r?\n/).map((x) => x.trim()).filter(Boolean).map((url) => ({ type: "LINK" as const, url })); const media = [...(video.trim() ? [{ type: "VIDEO" as const, url: video.trim() }] : []), ...linkItems];
    setBusy(true); try { const next = await patchEventEditor(eventId, { action: "basics", title: title.trim(), description: description.trim(), posterUrl: e.posterUrl, startsAt: startsAt.toISOString(), venueName: venue.trim(), city: city.trim(), address: address.trim(), presentation: { shortDescription: short.trim(), ageRestriction: age, doorsOpenTime: doors, runtimeMinutes: Number(runtime || 0), intermissionCount: Number(intermission || 0), galleryEnabled: galleries.length > 0, galleryUrls: galleries, faqEnabled: faq.some((x) => x.question.trim() && x.answer.trim()), faq: faq.filter((x) => x.question.trim() || x.answer.trim()) }, media, eventTypes: types, language: { primaryLanguage: language, catalogVisibility: visibility } }); onState(next); Alert.alert("Сохранено", "Раздел «О мероприятии» обновлён."); } catch (err) { Alert.alert("Не удалось сохранить", err instanceof Error ? err.message : "Ошибка"); } finally { setBusy(false); }
  }
  return <ScrollView ref={scrollRef} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled" keyboardDismissMode={Platform.OS === "ios" ? "interactive" : "on-drag"} automaticallyAdjustKeyboardInsets={Platform.OS === "ios"}>
    <Text style={s.title}>О мероприятии</Text><Text style={s.help}>Поля со знаком <Text style={s.required}>*</Text> обязательны. После сохранения мы покажем, что именно нужно исправить.</Text>
    <View onLayout={mark("title")}><Field label="Официальное название" required error={errors.title}><TextInput style={[s.input, errors.title && s.inputError]} value={title} onChangeText={(v) => { setTitle(v); clear("title"); }} maxLength={50} returnKeyType="next" /></Field></View>
    <Field label="Краткое описание"><TextInput style={s.input} value={short} onChangeText={setShort} maxLength={100} returnKeyType="next" /></Field>
    <View style={s.row}><View style={s.half} onLayout={mark("date")}><Field label="Дата" required error={errors.date}><TextInput style={[s.input, errors.date && s.inputError]} value={date} onChangeText={(v) => { setDate(v); clear("date"); }} placeholder="YYYY-MM-DD" returnKeyType="next" /></Field></View><View style={s.half} onLayout={mark("time")}><Field label="Начало" required error={errors.time}><TextInput style={[s.input, errors.time && s.inputError]} value={time} onChangeText={(v) => { setTime(v); clear("time"); }} placeholder="HH:MM" returnKeyType="next" /></Field></View></View>
    <View onLayout={mark("doors")}><Field label="Открытие дверей" error={errors.doors}><TextInput style={[s.input, errors.doors && s.inputError]} value={doors} onChangeText={(v) => { setDoors(v); clear("doors"); }} placeholder="HH:MM" returnKeyType="next" /></Field></View>
    <View onLayout={mark("venue")}><Field label="Зал" required error={errors.venue}><TextInput style={[s.input, errors.venue && s.inputError]} value={venue} onChangeText={(v) => { setVenue(v); clear("venue"); }} returnKeyType="next" /></Field></View>
    <View onLayout={mark("city")}><Field label="Город" required error={errors.city}><TextInput style={[s.input, errors.city && s.inputError]} value={city} onChangeText={(v) => { setCity(v); clear("city"); }} returnKeyType="next" /></Field></View>
    <View onLayout={mark("address")}><Field label="Полный адрес" required error={errors.address}><TextInput style={[s.input, errors.address && s.inputError]} value={address} onChangeText={(v) => { setAddress(v); clear("address"); }} returnKeyType="done" /></Field></View>
    <Text style={s.group}>Возрастное ограничение</Text><View style={s.chips}>{AGE.map((x) => <Chip key={x} label={x} selected={age === x} onPress={() => setAge(x)} />)}</View><View style={s.row}><View style={s.half}><Field label="Продолжительность, мин"><TextInput style={s.input} keyboardType="number-pad" value={runtime} onChangeText={setRuntime} /></Field></View><View style={s.half}><Field label="Антрактов"><TextInput style={s.input} keyboardType="number-pad" value={intermission} onChangeText={setIntermission} /></Field></View></View>
    <Text style={s.group}>Язык мероприятия</Text><View style={s.chips}>{LANG.map((x) => <Chip key={x.id} label={x.label} selected={language === x.id} onPress={() => setLanguage(x.id)} />)}</View><Text style={s.group}>Видимость в каталоге</Text><View style={s.chips}>{VIS.map((x) => <Chip key={x.id} label={x.label} selected={visibility === x.id} onPress={() => setVisibility(x.id)} />)}</View>
    <View onLayout={mark("types")}><Text style={s.group}>Тип мероприятия <Text style={s.required}>*</Text></Text><View style={[s.chips, errors.types && s.choiceError]}>{TYPES.map((x) => <Chip key={x.id} label={x.label} selected={types.includes(x.id)} onPress={() => toggleType(x.id)} />)}</View>{errors.types ? <Text style={s.errorText}>{errors.types}</Text> : null}</View>
    <View style={s.note}><Text style={s.noteTitle}>Главная афиша</Text><Text style={s.help}>Текущий poster сохраняется. Native upload с камеры/галереи подключается отдельным media-flow.</Text></View><Field label="Видео YouTube / Vimeo"><TextInput style={s.input} value={video} onChangeText={setVideo} autoCapitalize="none" keyboardType="url" /></Field><Field label="Галерея - URL по одному в строке"><TextInput style={[s.input, s.multiSmall]} multiline value={gallery} onChangeText={setGallery} autoCapitalize="none" textAlignVertical="top" /></Field><Field label="Дополнительные ссылки"><TextInput style={[s.input, s.multiSmall]} multiline value={links} onChangeText={setLinks} autoCapitalize="none" textAlignVertical="top" /></Field>
    <View onLayout={mark("description")}><Field label="Полное описание" required error={errors.description}><TextInput style={[s.input, s.multi, errors.description && s.inputError]} multiline value={description} onChangeText={(v) => { setDescription(v); clear("description"); }} textAlignVertical="top" scrollEnabled /></Field></View>
    <View style={s.between}><Text style={s.group}>FAQ</Text>{faq.length < 15 && <TouchableOpacity onPress={() => setFaq((items) => [...items, { question: "", answer: "" }])}><Text style={s.link}>+ Вопрос</Text></TouchableOpacity>}</View>{faq.map((item, index) => <View key={index} style={s.faq}><TextInput style={s.input} placeholder={`Вопрос ${index + 1}`} value={item.question} onChangeText={(question) => setFaq((items) => items.map((x, i) => i === index ? { ...x, question } : x))} /><TextInput style={[s.input, s.multiSmall]} multiline placeholder="Ответ" value={item.answer} onChangeText={(answer) => setFaq((items) => items.map((x, i) => i === index ? { ...x, answer } : x))} textAlignVertical="top" /><TouchableOpacity onPress={() => setFaq((items) => items.filter((_, i) => i !== index))}><Text style={s.remove}>Удалить</Text></TouchableOpacity></View>)}
    <TouchableOpacity style={s.save} disabled={busy} onPress={save}>{busy ? <ActivityIndicator color="#fff" /> : <Text style={s.saveText}>Сохранить изменения</Text>}</TouchableOpacity>
  </ScrollView>;
}
const s = StyleSheet.create({ content: { padding: 18, paddingBottom: 180 }, title: { fontSize: 28, fontWeight: "900", color: "#17213C" }, help: { color: "#7B8498", lineHeight: 19, marginTop: 4, marginBottom: 14 }, label: { fontSize: 12, fontWeight: "800", color: "#5C667B", marginBottom: 6 }, required: { color: "#D92D20", fontWeight: "900" }, errorText: { color: "#D92D20", fontSize: 11.5, fontWeight: "700", marginTop: 5, lineHeight: 16 }, input: { minHeight: 47, borderWidth: 1, borderColor: "#DDE1EA", backgroundColor: "#fff", borderRadius: 12, paddingHorizontal: 12, color: "#17213C" }, inputError: { borderColor: "#D92D20", borderWidth: 1.5, backgroundColor: "#FFF7F6" }, choiceError: { borderWidth: 1, borderColor: "#D92D20", borderRadius: 12, padding: 8, backgroundColor: "#FFF7F6" }, multi: { minHeight: 170, paddingTop: 12, paddingBottom: 12 }, multiSmall: { minHeight: 90, paddingTop: 10, paddingBottom: 10 }, row: { flexDirection: "row", gap: 10 }, half: { flex: 1 }, group: { fontWeight: "900", color: "#17213C", fontSize: 16, marginTop: 4, marginBottom: 9 }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginBottom: 13 }, chip: { borderRadius: 18, paddingHorizontal: 10, paddingVertical: 8, backgroundColor: "#EEF0F5" }, chipOn: { backgroundColor: "#EEE9FF", borderWidth: 1, borderColor: "#6D45FF" }, chipText: { fontSize: 11, fontWeight: "700", color: "#596378" }, chipTextOn: { color: "#5437DD" }, note: { backgroundColor: "#EEE9FF", borderRadius: 14, padding: 14, marginBottom: 14 }, noteTitle: { fontWeight: "900", color: "#5437DD" }, between: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, link: { color: "#6D45FF", fontWeight: "900" }, faq: { gap: 8, marginBottom: 13, backgroundColor: "#F8F9FC", padding: 12, borderRadius: 13 }, remove: { color: "#C33", fontWeight: "800", textAlign: "right" }, save: { minHeight: 55, backgroundColor: "#6D45FF", borderRadius: 15, alignItems: "center", justifyContent: "center", marginTop: 10 }, saveText: { color: "#fff", fontWeight: "900", fontSize: 16 } });
