import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { patchEventEditor, type EventEditorState } from "@/lib/event-editor-api";

const AGE = ["Без ограничений", "Детское", "3+", "6+", "12+", "14+", "16+", "18+"];
const LANG = [{ id: "RU", label: "Русский" }, { id: "HE", label: "Иврит" }, { id: "EN", label: "Английский" }, { id: "AR", label: "Арабский" }, { id: "MULTILINGUAL", label: "Несколько языков" }, { id: "NO_LANGUAGE_BARRIER", label: "Без языкового барьера" }, { id: "OTHER", label: "Другой" }];
const VIS = [{ id: "PUBLIC", label: "Всем" }, { id: "TARGETED", label: "По языку" }, { id: "DIRECT_ONLY", label: "Только по ссылке" }];
const TYPES = [{ id: "SOLO_CONCERT", label: "Сольный концерт" }, { id: "LIVE_MUSIC", label: "Живая музыка" }, { id: "CLASSICAL_CONCERT", label: "Классический концерт" }, { id: "FESTIVAL", label: "Фестиваль" }, { id: "PARTY", label: "Вечеринка" }, { id: "DJ_SET", label: "DJ-сет" }, { id: "THEATRE", label: "Спектакль" }, { id: "COMEDY", label: "Стендап" }, { id: "CHILDREN_SHOW", label: "Детское" }, { id: "SPORT", label: "Спорт" }, { id: "LECTURE", label: "Лекция" }, { id: "CONFERENCE", label: "Конференция" }, { id: "EXHIBITION", label: "Выставка" }, { id: "WORKSHOP", label: "Мастер-класс" }, { id: "OTHER", label: "Другое" }];
const DRAFT_DEFAULTS = { title: "Новое мероприятие", description: "Добавьте описание мероприятия", venueName: "Новая площадка", city: "Город", address: "Адрес площадки" };
function localDateTime(iso: string) { const d = new Date(iso); if (Number.isNaN(d.getTime())) return { date: "", time: "" }; const p = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Jerusalem", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(d); const v = Object.fromEntries(p.map((x) => [x.type, x.value])); return { date: `${v.year}-${v.month}-${v.day}`, time: `${v.hour}:${v.minute}` }; }
function visible(value: string, technical: string, draft: boolean) { return draft && value === technical ? "" : value; }
function Chip({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <TouchableOpacity onPress={onPress} style={[s.chip, selected && s.chipOn]}><Text style={[s.chipText, selected && s.chipTextOn]}>{label}</Text></TouchableOpacity>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <View style={{ marginBottom: 13 }}><Text style={s.label}>{label}</Text>{children}</View>; }

export function AboutTab({ eventId, state, onState }: { eventId: string; state: EventEditorState; onState: (v: EventEditorState) => void }) {
  const e = state.event; const isDraft = e.status === "DRAFT"; const local = localDateTime(e.startsAt);
  const [title, setTitle] = useState(visible(e.title, DRAFT_DEFAULTS.title, isDraft)); const [short, setShort] = useState(e.presentation.shortDescription || ""); const [description, setDescription] = useState(visible(e.description, DRAFT_DEFAULTS.description, isDraft)); const [date, setDate] = useState(local.date); const [time, setTime] = useState(local.time); const [doors, setDoors] = useState(e.presentation.doorsOpenTime || "");
  const [venue, setVenue] = useState(visible(e.venue.name, DRAFT_DEFAULTS.venueName, isDraft)); const [city, setCity] = useState(visible(e.venue.city, DRAFT_DEFAULTS.city, isDraft)); const [address, setAddress] = useState(visible(e.venue.address, DRAFT_DEFAULTS.address, isDraft));
  const [age, setAge] = useState(e.presentation.ageRestriction || "Без ограничений"); const [runtime, setRuntime] = useState(String(e.presentation.runtimeMinutes || 0)); const [intermission, setIntermission] = useState(String(e.presentation.intermissionCount || 0)); const [language, setLanguage] = useState(e.language.primaryLanguage); const [visibility, setVisibility] = useState(e.language.catalogVisibility); const [types, setTypes] = useState<string[]>(e.eventTypes.length ? e.eventTypes : ["OTHER"]);
  const [video, setVideo] = useState(e.media.find((x) => x.type === "VIDEO")?.url || ""); const [links, setLinks] = useState(e.media.filter((x) => x.type === "LINK").map((x) => x.url).join("\n")); const [gallery, setGallery] = useState(e.presentation.galleryUrls.join("\n")); const [faq, setFaq] = useState(e.presentation.faq); const [busy, setBusy] = useState(false);
  useEffect(() => {}, [state.event.id]);
  function toggleType(id: string) { setTypes((current) => current.includes(id) ? (current.length > 1 ? current.filter((x) => x !== id) : current) : [...current.filter((x) => x !== "OTHER"), id]); }
  async function save() {
    if (!state.permissions.includes("EVENT_MANAGE")) return Alert.alert("Нет доступа", "Нужен EVENT_MANAGE."); if (title.trim().length < 3) return Alert.alert("Проверьте название", "Минимум 3 символа."); if (description.trim().length < 20) return Alert.alert("Проверьте описание", "Минимум 20 символов."); if (!/^\d{4}-\d{2}-\d{2}$/.test(date) || !/^\d{2}:\d{2}$/.test(time)) return Alert.alert("Проверьте дату", "Используйте YYYY-MM-DD и HH:MM."); if (doors && !/^\d{2}:\d{2}$/.test(doors)) return Alert.alert("Проверьте открытие дверей", "Используйте HH:MM.");
    const startsAt = new Date(`${date}T${time}:00+03:00`); const galleries = gallery.split(/\r?\n/).map((x) => x.trim()).filter(Boolean); const linkItems = links.split(/\r?\n/).map((x) => x.trim()).filter(Boolean).map((url) => ({ type: "LINK" as const, url })); const media = [...(video.trim() ? [{ type: "VIDEO" as const, url: video.trim() }] : []), ...linkItems];
    setBusy(true); try { const next = await patchEventEditor(eventId, { action: "basics", title: title.trim(), description: description.trim(), posterUrl: e.posterUrl, startsAt: startsAt.toISOString(), venueName: venue.trim(), city: city.trim(), address: address.trim(), presentation: { shortDescription: short.trim(), ageRestriction: age, doorsOpenTime: doors, runtimeMinutes: Number(runtime || 0), intermissionCount: Number(intermission || 0), galleryEnabled: galleries.length > 0, galleryUrls: galleries, faqEnabled: faq.some((x) => x.question.trim() && x.answer.trim()), faq: faq.filter((x) => x.question.trim() || x.answer.trim()) }, media, eventTypes: types, language: { primaryLanguage: language, catalogVisibility: visibility } }); onState(next); Alert.alert("Сохранено", "Раздел «О мероприятии» обновлён."); } catch (err) { Alert.alert("Не удалось сохранить", err instanceof Error ? err.message : "Ошибка"); } finally { setBusy(false); }
  }
  return <ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Text style={s.title}>О мероприятии</Text><Text style={s.help}>Поля соответствуют web back office.</Text>
    <Field label="Официальное название"><TextInput style={s.input} value={title} onChangeText={setTitle} maxLength={50} /></Field><Field label="Краткое описание"><TextInput style={s.input} value={short} onChangeText={setShort} maxLength={100} /></Field>
    <View style={s.row}><View style={s.half}><Field label="Дата"><TextInput style={s.input} value={date} onChangeText={setDate} /></Field></View><View style={s.half}><Field label="Начало"><TextInput style={s.input} value={time} onChangeText={setTime} /></Field></View></View><Field label="Открытие дверей"><TextInput style={s.input} value={doors} onChangeText={setDoors} placeholder="HH:MM" /></Field>
    <Field label="Зал"><TextInput style={s.input} value={venue} onChangeText={setVenue} /></Field><Field label="Город"><TextInput style={s.input} value={city} onChangeText={setCity} /></Field><Field label="Полный адрес"><TextInput style={s.input} value={address} onChangeText={setAddress} /></Field>
    <Text style={s.group}>Возрастное ограничение</Text><View style={s.chips}>{AGE.map((x) => <Chip key={x} label={x} selected={age === x} onPress={() => setAge(x)} />)}</View><View style={s.row}><View style={s.half}><Field label="Продолжительность, мин"><TextInput style={s.input} keyboardType="number-pad" value={runtime} onChangeText={setRuntime} /></Field></View><View style={s.half}><Field label="Антрактов"><TextInput style={s.input} keyboardType="number-pad" value={intermission} onChangeText={setIntermission} /></Field></View></View>
    <Text style={s.group}>Язык мероприятия</Text><View style={s.chips}>{LANG.map((x) => <Chip key={x.id} label={x.label} selected={language === x.id} onPress={() => setLanguage(x.id)} />)}</View><Text style={s.group}>Видимость в каталоге</Text><View style={s.chips}>{VIS.map((x) => <Chip key={x.id} label={x.label} selected={visibility === x.id} onPress={() => setVisibility(x.id)} />)}</View><Text style={s.group}>Тип мероприятия</Text><View style={s.chips}>{TYPES.map((x) => <Chip key={x.id} label={x.label} selected={types.includes(x.id)} onPress={() => toggleType(x.id)} />)}</View>
    <View style={s.note}><Text style={s.noteTitle}>Главная афиша</Text><Text style={s.help}>Текущий poster сохраняется. Native upload с камеры/галереи подключается отдельным media-flow.</Text></View><Field label="Видео YouTube / Vimeo"><TextInput style={s.input} value={video} onChangeText={setVideo} autoCapitalize="none" /></Field><Field label="Галерея - URL по одному в строке"><TextInput style={[s.input, s.multiSmall]} multiline value={gallery} onChangeText={setGallery} autoCapitalize="none" /></Field><Field label="Дополнительные ссылки"><TextInput style={[s.input, s.multiSmall]} multiline value={links} onChangeText={setLinks} autoCapitalize="none" /></Field>
    <Field label="Полное описание"><TextInput style={[s.input, s.multi]} multiline value={description} onChangeText={setDescription} textAlignVertical="top" /></Field><View style={s.between}><Text style={s.group}>FAQ</Text>{faq.length < 15 && <TouchableOpacity onPress={() => setFaq((items) => [...items, { question: "", answer: "" }])}><Text style={s.link}>+ Вопрос</Text></TouchableOpacity>}</View>{faq.map((item, index) => <View key={index} style={s.faq}><TextInput style={s.input} placeholder={`Вопрос ${index + 1}`} value={item.question} onChangeText={(question) => setFaq((items) => items.map((x, i) => i === index ? { ...x, question } : x))} /><TextInput style={[s.input, s.multiSmall]} multiline placeholder="Ответ" value={item.answer} onChangeText={(answer) => setFaq((items) => items.map((x, i) => i === index ? { ...x, answer } : x))} /><TouchableOpacity onPress={() => setFaq((items) => items.filter((_, i) => i !== index))}><Text style={s.remove}>Удалить</Text></TouchableOpacity></View>)}
    <TouchableOpacity style={s.save} disabled={busy} onPress={save}>{busy ? <ActivityIndicator color="#fff" /> : <Text style={s.saveText}>Сохранить изменения</Text>}</TouchableOpacity>
  </ScrollView>;
}
const s = StyleSheet.create({ content: { padding: 18, paddingBottom: 90 }, title: { fontSize: 28, fontWeight: "900", color: "#17213C" }, help: { color: "#7B8498", lineHeight: 19, marginTop: 4, marginBottom: 14 }, label: { fontSize: 12, fontWeight: "800", color: "#5C667B", marginBottom: 6 }, input: { minHeight: 47, borderWidth: 1, borderColor: "#DDE1EA", backgroundColor: "#fff", borderRadius: 12, paddingHorizontal: 12, color: "#17213C" }, multi: { minHeight: 130, paddingTop: 10 }, multiSmall: { minHeight: 76, paddingTop: 10 }, row: { flexDirection: "row", gap: 10 }, half: { flex: 1 }, group: { fontWeight: "900", color: "#17213C", fontSize: 16, marginTop: 4, marginBottom: 9 }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginBottom: 13 }, chip: { borderRadius: 18, paddingHorizontal: 10, paddingVertical: 8, backgroundColor: "#EEF0F5" }, chipOn: { backgroundColor: "#EEE9FF", borderWidth: 1, borderColor: "#6D45FF" }, chipText: { fontSize: 11, fontWeight: "700", color: "#596378" }, chipTextOn: { color: "#5437DD" }, note: { backgroundColor: "#EEE9FF", borderRadius: 14, padding: 14, marginBottom: 14 }, noteTitle: { fontWeight: "900", color: "#5437DD" }, between: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, link: { color: "#6D45FF", fontWeight: "900" }, faq: { gap: 8, marginBottom: 13, backgroundColor: "#F8F9FC", padding: 12, borderRadius: 13 }, remove: { color: "#C33", fontWeight: "800", textAlign: "right" }, save: { minHeight: 55, backgroundColor: "#6D45FF", borderRadius: 15, alignItems: "center", justifyContent: "center", marginTop: 10 }, saveText: { color: "#fff", fontWeight: "900", fontSize: 16 } });
