import { useState } from "react";
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from "react-native";
import { patchEventEditor, type BuyerQuestion, type EventEditorState, type GuestFieldKey, type GuestFields } from "@/lib/event-editor-api";

const guestLabels: Record<GuestFieldKey, string> = { firstName: "Имя", lastName: "Фамилия", phone: "Телефон", email: "Email", birthDate: "Дата рождения", city: "Город проживания", facebook: "Facebook", instagram: "Instagram" };
const questionTypes: Array<{ id: BuyerQuestion["type"]; label: string }> = [{ id: "TEXT", label: "Короткий текст" }, { id: "TEXTAREA", label: "Длинный текст" }, { id: "SELECT", label: "Список" }, { id: "CHECKBOX", label: "Чекбокс" }, { id: "PHONE", label: "Телефон" }, { id: "EMAIL", label: "Email" }, { id: "DATE", label: "Дата" }];
function Chip({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <TouchableOpacity onPress={onPress} style={[s.chip, selected && s.chipOn]}><Text style={[s.chipText, selected && s.chipTextOn]}>{label}</Text></TouchableOpacity>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <View style={{ marginBottom: 12 }}><Text style={s.label}>{label}</Text>{children}</View>; }

export function CheckoutTab({ eventId, state, onState }: { eventId: string; state: EventEditorState; onState: (v: EventEditorState) => void }) {
  const canEdit = state.permissions.includes("EVENT_MANAGE");
  const [salesMode, setSalesMode] = useState(state.checkout.salesMode);
  const [instructions, setInstructions] = useState(state.checkout.approvalInstructions);
  const [rejection, setRejection] = useState(state.checkout.rejectionMessage);
  const [guestFields, setGuestFields] = useState<GuestFields>(state.checkout.guestFields);
  const [questions, setQuestions] = useState<BuyerQuestion[]>(state.checkout.questions);
  const [useDefaults, setUseDefaults] = useState(state.checkout.commercial.useOrganizerDefaults);
  const [payer, setPayer] = useState<"BUYER" | "ORGANIZER">(state.checkout.commercial.serviceFeePayer);
  const [busy, setBusy] = useState("");

  async function run(key: string, action: Record<string, unknown>, message: string) { if (!canEdit) return Alert.alert("Нет доступа", "Нужен EVENT_MANAGE."); setBusy(key); try { const next = await patchEventEditor(eventId, action); onState(next); Alert.alert("Сохранено", message); } catch (e) { Alert.alert("Не удалось сохранить", e instanceof Error ? e.message : "Ошибка"); } finally { setBusy(""); } }
  function guest(key: GuestFieldKey, part: "visible" | "required", value: boolean) { setGuestFields((current) => ({ ...current, [key]: { ...current[key], [part]: value, ...(part === "visible" && !value ? { required: false } : {}) } })); }
  function updateQuestion(index: number, part: Partial<BuyerQuestion>) { setQuestions((items) => items.map((q, i) => i === index ? { ...q, ...part } : q)); }
  function addQuestion() { setQuestions((items) => [...items, { id: `mobile-${Date.now()}-${items.length}`, label: "", type: "TEXT", required: false, placeholder: "" }]); }
  function move(index: number, delta: number) { setQuestions((items) => { const target = index + delta; if (target < 0 || target >= items.length) return items; const copy = [...items]; [copy[index], copy[target]] = [copy[target], copy[index]]; return copy; }); }
  function validateQuestions() { for (const q of questions) { if (!q.label.trim()) return "У каждого дополнительного вопроса должен быть текст."; if (q.type === "SELECT" && (!q.options || !q.options.length)) return `Добавьте варианты для «${q.label}».`; } return null; }

  const commercial = state.checkout.commercial;
  const feeLabel = `${(commercial.salesFeePercentBps / 100).toFixed(2).replace(/\.00$/, "")}%${commercial.salesFeeFixedMinor ? ` + ${(commercial.salesFeeFixedMinor / 100).toFixed(2)} ₪` : ""}`;
  return <ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
    <Text style={s.title}>Покупатель</Text><Text style={s.help}>Способ продажи, данные гостя, дополнительные вопросы и сервисный сбор.</Text>

    <View style={s.card}><Text style={s.cardTitle}>Способ продажи</Text><View style={s.choiceRow}><TouchableOpacity style={[s.choice, salesMode === "INSTANT" && s.choiceOn]} onPress={() => setSalesMode("INSTANT")}><Text style={s.choiceTitle}>⚡ Автоматически</Text><Text style={s.choiceText}>Оплата и билет сразу</Text></TouchableOpacity><TouchableOpacity style={[s.choice, salesMode === "APPROVAL_REQUIRED" && s.choiceOn]} onPress={() => setSalesMode("APPROVAL_REQUIRED")}><Text style={s.choiceTitle}>✓ После одобрения</Text><Text style={s.choiceText}>Сначала заявка</Text></TouchableOpacity></View>
      {salesMode === "APPROVAL_REQUIRED" && <><Field label="Что клиент должен указать в заявке"><TextInput style={[s.input, s.multi]} multiline value={instructions} onChangeText={setInstructions} /></Field><Field label="Сообщение при отказе"><TextInput style={[s.input, s.multi]} multiline value={rejection} onChangeText={setRejection} /></Field></>}
      <Save busy={busy === "sales"} onPress={() => run("sales", { action: "sales", salesMode, approvalInstructions: instructions, rejectionMessage: rejection }, "Способ продажи сохранён.")} label="Сохранить способ продажи" />
    </View>

    <View style={s.card}><Text style={s.cardTitle}>Основные данные гостя</Text><Text style={s.help}>Совпадает с формой оформления web back office.</Text>{(Object.keys(guestLabels) as GuestFieldKey[]).map((key) => <View key={key} style={s.guestRow}><Text style={s.guestName}>{guestLabels[key]}</Text><View style={s.toggleBlock}><Text style={s.small}>Показывать</Text><Switch value={guestFields[key].visible} onValueChange={(v) => guest(key, "visible", v)} /></View><View style={s.toggleBlock}><Text style={s.small}>Обязательно</Text><Switch disabled={!guestFields[key].visible} value={guestFields[key].required} onValueChange={(v) => guest(key, "required", v)} /></View></View>)}</View>

    <View style={s.card}><View style={s.between}><View style={{ flex: 1 }}><Text style={s.cardTitle}>Дополнительные вопросы</Text><Text style={s.help}>После основных данных гостя.</Text></View><TouchableOpacity style={s.add} onPress={addQuestion}><Text style={s.addText}>+ Вопрос</Text></TouchableOpacity></View>
      {questions.map((q, index) => <View key={q.id} style={s.question}><View style={s.between}><Text style={s.questionTitle}>Вопрос {index + 1}</Text><View style={s.actions}><TouchableOpacity disabled={index === 0} onPress={() => move(index, -1)}><Text style={s.link}>↑</Text></TouchableOpacity><TouchableOpacity disabled={index === questions.length - 1} onPress={() => move(index, 1)}><Text style={s.link}>↓</Text></TouchableOpacity><TouchableOpacity onPress={() => setQuestions((items) => items.filter((_, i) => i !== index))}><Text style={s.remove}>Удалить</Text></TouchableOpacity></View></View>
        <Field label="Текст вопроса"><TextInput style={s.input} value={q.label} onChangeText={(label) => updateQuestion(index, { label })} /></Field><Text style={s.label}>Тип ответа</Text><View style={s.chips}>{questionTypes.map((t) => <Chip key={t.id} label={t.label} selected={q.type === t.id} onPress={() => updateQuestion(index, { type: t.id })} />)}</View>
        {q.type === "SELECT" && <Field label="Варианты, по одному в строке"><TextInput style={[s.input, s.multi]} multiline value={(q.options || []).join("\n")} onChangeText={(v) => updateQuestion(index, { options: v.split(/\r?\n/).map((x) => x.trim()).filter(Boolean) })} /></Field>}
        <Field label="Подсказка"><TextInput style={s.input} value={q.placeholder || ""} onChangeText={(placeholder) => updateQuestion(index, { placeholder })} /></Field><View style={s.switchLine}><Text style={{ flex: 1 }}>Обязательный вопрос</Text><Switch value={q.required} onValueChange={(required) => updateQuestion(index, { required })} /></View>
      </View>)}
      <Save busy={busy === "form"} onPress={() => { const error = validateQuestions(); if (error) return Alert.alert("Проверьте вопросы", error); run("form", { action: "checkout-form", guestFields, questions }, "Форма оформления сохранена."); }} label="Сохранить форму оформления" />
    </View>

    <View style={s.card}><Text style={s.cardTitle}>Сервисный сбор</Text><Text style={s.fee}>Размер: {feeLabel}</Text><Text style={s.help}>Размер комиссии задаётся условиями организатора. Здесь выбирается только плательщик.</Text><View style={s.switchLine}><Text style={{ flex: 1, fontWeight: "700" }}>Использовать стандартное правило организатора</Text><Switch value={useDefaults} onValueChange={setUseDefaults} /></View>{!useDefaults && <View style={s.choiceRow}><TouchableOpacity style={[s.choice, payer === "BUYER" && s.choiceOn]} onPress={() => setPayer("BUYER")}><Text style={s.choiceTitle}>Покупатель</Text><Text style={s.choiceText}>Сбор добавляется сверху</Text></TouchableOpacity><TouchableOpacity style={[s.choice, payer === "ORGANIZER" && s.choiceOn]} onPress={() => setPayer("ORGANIZER")}><Text style={s.choiceTitle}>Организатор</Text><Text style={s.choiceText}>Сбор удерживается из выплаты</Text></TouchableOpacity></View>}<Text style={s.result}>Итог: {(useDefaults ? commercial.organizerServiceFeePayer : payer) === "BUYER" ? "платит покупатель" : "платит организатор"}</Text><Save busy={busy === "commercial"} onPress={() => run("commercial", { action: "commercial", useOrganizerDefaults: useDefaults, serviceFeePayer: payer }, "Условия продажи сохранены.")} label="Сохранить условия" /></View>
  </ScrollView>;
}
function Save({ busy, onPress, label }: { busy: boolean; onPress: () => void; label: string }) { return <TouchableOpacity style={s.save} disabled={busy} onPress={onPress}>{busy ? <ActivityIndicator color="#fff" /> : <Text style={s.saveText}>{label}</Text>}</TouchableOpacity>; }
const s = StyleSheet.create({ content: { padding: 18, paddingBottom: 90 }, title: { fontSize: 28, fontWeight: "900", color: "#17213C" }, help: { color: "#7B8498", lineHeight: 19, marginTop: 4, marginBottom: 14 }, card: { backgroundColor: "#fff", borderWidth: 1, borderColor: "#E1E4EC", borderRadius: 18, padding: 16, marginBottom: 14 }, cardTitle: { fontSize: 19, fontWeight: "900", color: "#17213C", marginBottom: 10 }, choiceRow: { flexDirection: "row", gap: 9, marginBottom: 12 }, choice: { flex: 1, minHeight: 88, borderWidth: 1, borderColor: "#DFE3EB", borderRadius: 14, padding: 12, backgroundColor: "#F9FAFC" }, choiceOn: { borderWidth: 2, borderColor: "#6D45FF", backgroundColor: "#F2EEFF" }, choiceTitle: { fontWeight: "900", color: "#17213C" }, choiceText: { color: "#6E778A", fontSize: 12, marginTop: 5 }, label: { fontSize: 12, fontWeight: "800", color: "#5C667B", marginBottom: 6 }, input: { minHeight: 45, borderWidth: 1, borderColor: "#DDE1EA", borderRadius: 11, paddingHorizontal: 11, color: "#17213C", backgroundColor: "#fff" }, multi: { minHeight: 76, paddingTop: 10 }, save: { minHeight: 50, backgroundColor: "#6D45FF", borderRadius: 14, alignItems: "center", justifyContent: "center", marginTop: 12 }, saveText: { color: "#fff", fontWeight: "900" }, guestRow: { minHeight: 62, flexDirection: "row", alignItems: "center", borderBottomWidth: 1, borderBottomColor: "#ECEEF3" }, guestName: { flex: 1, fontWeight: "700", color: "#27314B" }, toggleBlock: { alignItems: "center", marginLeft: 8 }, small: { fontSize: 9, color: "#81899A" }, between: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 10 }, add: { backgroundColor: "#EEE9FF", paddingHorizontal: 12, paddingVertical: 9, borderRadius: 12 }, addText: { color: "#5B3EE2", fontWeight: "900" }, question: { backgroundColor: "#F8F9FC", borderRadius: 14, padding: 13, marginBottom: 12 }, questionTitle: { fontWeight: "900", color: "#17213C" }, actions: { flexDirection: "row", gap: 13 }, link: { color: "#6D45FF", fontWeight: "900" }, remove: { color: "#C33", fontWeight: "800" }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginBottom: 12 }, chip: { borderRadius: 17, backgroundColor: "#EEF0F5", paddingHorizontal: 10, paddingVertical: 8 }, chipOn: { backgroundColor: "#EEE9FF", borderWidth: 1, borderColor: "#6D45FF" }, chipText: { fontSize: 11, fontWeight: "700", color: "#596378" }, chipTextOn: { color: "#5437DD" }, switchLine: { minHeight: 50, flexDirection: "row", alignItems: "center", borderTopWidth: 1, borderTopColor: "#ECEEF3", marginTop: 8 }, fee: { fontSize: 22, fontWeight: "900", color: "#17213C" }, result: { marginTop: 6, fontWeight: "900", color: "#4F2FE3" } });
