import { useMemo, useState } from "react";
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { patchEventEditor, type EditorLayoutObject, type EventEditorState } from "@/lib/event-editor-api";

type DraftObject = Omit<EditorLayoutObject, "id" | "zoneName" | "reserved"> & { id?: string };
const typeLabels: Record<DraftObject["objectType"], string> = { TABLE: "Стол", ROUND_TABLE: "Круглый стол", SOFA: "Диван", ROW: "Ряд", ZONE: "Зона", STAGE: "Сцена", BAR: "Бар", TEXT: "Текст" };
function emptyObject(index: number): DraftObject { return { label: `Объект ${index + 1}`, objectType: "TABLE", seats: 4, priceMode: "WHOLE_TABLE", priceMinor: 0, x: 20, y: 20, rotation: 0, width: 120, height: 80, categoryId: null, seatAssignments: [] }; }
function Chip({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <TouchableOpacity onPress={onPress} style={[s.chip, selected && s.chipOn]}><Text style={[s.chipText, selected && s.chipTextOn]}>{label}</Text></TouchableOpacity>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <View style={{ marginBottom: 10 }}><Text style={s.label}>{label}</Text>{children}</View>; }

export function MapTab({ eventId, state, onState }: { eventId: string; state: EventEditorState; onState: (v: EventEditorState) => void }) {
  const canManage = state.permissions.includes("EVENT_MANAGE") || state.permissions.includes("TICKET_MANAGE");
  const canTickets = state.permissions.includes("TICKET_MANAGE");
  const [objects, setObjects] = useState<DraftObject[]>(state.map.objects.map((o) => ({ ...o })));
  const [busy, setBusy] = useState(false);
  const changed = useMemo(() => JSON.stringify(objects) !== JSON.stringify(state.map.objects.map((o) => ({ ...o }))), [objects, state.map.objects]);
  async function admission(next: boolean) { if (!canManage) return; setBusy(true); try { const result = await patchEventEditor(eventId, { action: "admission", mapEnabled: next }); onState(result); setObjects(result.map.objects.map((o) => ({ ...o }))); } catch (e) { Alert.alert("Не удалось изменить формат", e instanceof Error ? e.message : "Ошибка"); } finally { setBusy(false); } }
  function update(index: number, part: Partial<DraftObject>) { setObjects((items) => items.map((item, i) => i === index ? { ...item, ...part } : item)); }
  function remove(index: number) { if (state.map.locked) return Alert.alert("Карта заблокирована", "После появления заказов карту нельзя полностью перестраивать."); setObjects((items) => items.filter((_, i) => i !== index)); }
  async function save() { if (!canTickets) return Alert.alert("Нет доступа", "Для карты нужен TICKET_MANAGE."); if (state.map.locked) return Alert.alert("Карта заблокирована", "После появления заказов карту нельзя полностью перестраивать."); for (const item of objects) { if (!item.label.trim()) return Alert.alert("Проверьте карту", "У каждого объекта должно быть название."); if (["TABLE", "ROUND_TABLE", "SOFA", "ROW"].includes(item.objectType) && item.seats < 1) return Alert.alert("Проверьте карту", "Для продаваемого объекта нужно хотя бы одно место."); }
    setBusy(true); try { const result = await patchEventEditor(eventId, { action: "layout", objects: objects.map((o) => ({ ...o, label: o.label.trim(), seats: Number(o.seats), priceMinor: Number(o.priceMinor), x: Number(o.x), y: Number(o.y), rotation: Number(o.rotation), width: Number(o.width), height: Number(o.height) })) }); onState(result); setObjects(result.map.objects.map((o) => ({ ...o }))); Alert.alert("Сохранено", "Карта сохранена в том же мероприятии Atlas."); } catch (e) { Alert.alert("Не удалось сохранить карту", e instanceof Error ? e.message : "Ошибка"); } finally { setBusy(false); }
  }
  return <ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
    <Text style={s.title}>Места и карта</Text><Text style={s.help}>Тот же admission mode и layout, что в web back office.</Text>
    <View style={s.choiceRow}><TouchableOpacity disabled={busy || !canManage} onPress={() => admission(false)} style={[s.choice, !state.map.enabled && s.choiceOn]}><Text style={s.choiceTitle}>Без схемы</Text><Text style={s.choiceText}>Тип и количество билетов</Text></TouchableOpacity><TouchableOpacity disabled={busy || !canManage} onPress={() => admission(true)} style={[s.choice, state.map.enabled && s.choiceOn]}><Text style={s.choiceTitle}>С выбором мест</Text><Text style={s.choiceText}>Столы, диваны, ряды и зоны</Text></TouchableOpacity></View>
    {!state.map.enabled ? <View style={s.note}><Text style={s.noteTitle}>Карта не используется</Text><Text style={s.help}>Покупатель выбирает категорию и количество билетов.</Text></View> : <>
      {state.map.locked && <View style={s.warning}><Text style={s.warningTitle}>Карта заблокирована для полной перестройки</Text><Text>Уже есть заказы или зарезервированные места. Это правило совпадает с web back office.</Text></View>}
      {objects.map((o, index) => <View key={o.id || `new-${index}`} style={s.card}><View style={s.between}><Text style={s.cardTitle}>{o.label || `Объект ${index + 1}`}</Text>{!state.map.locked && <TouchableOpacity onPress={() => remove(index)}><Text style={s.remove}>Удалить</Text></TouchableOpacity>}</View>
        <Field label="Название"><TextInput style={s.input} value={o.label} onChangeText={(label) => update(index, { label })} /></Field>
        <Text style={s.label}>Тип объекта</Text><View style={s.chips}>{(Object.keys(typeLabels) as DraftObject["objectType"][]).map((t) => <Chip key={t} label={typeLabels[t]} selected={o.objectType === t} onPress={() => update(index, { objectType: t, seats: ["TABLE", "ROUND_TABLE", "SOFA", "ROW"].includes(t) ? Math.max(1, o.seats) : 0 })} />)}</View>
        <View style={s.row}><View style={s.half}><Field label="Мест"><TextInput style={s.input} keyboardType="number-pad" value={String(o.seats)} onChangeText={(v) => update(index, { seats: Number(v || 0) })} /></Field></View><View style={s.half}><Field label="Цена объекта, ₪"><TextInput style={s.input} keyboardType="decimal-pad" value={String(o.priceMinor / 100)} onChangeText={(v) => update(index, { priceMinor: Math.round(Number(v || 0) * 100) })} /></Field></View></View>
        <Text style={s.label}>Цена</Text><View style={s.chips}><Chip label="За весь объект" selected={o.priceMode === "WHOLE_TABLE"} onPress={() => update(index, { priceMode: "WHOLE_TABLE" })} /><Chip label="За место" selected={o.priceMode === "PER_SEAT"} onPress={() => update(index, { priceMode: "PER_SEAT" })} /></View>
        <Text style={s.label}>Категория билета</Text><View style={s.chips}><Chip label="Не назначена" selected={!o.categoryId} onPress={() => update(index, { categoryId: null })} />{state.tickets.categories.map((c) => <Chip key={c.id} label={c.name} selected={o.categoryId === c.id} onPress={() => update(index, { categoryId: c.id })} />)}</View>
        <Text style={s.subTitle}>Положение и размер</Text><View style={s.grid}><Num label="X %" value={o.x} onChange={(x) => update(index, { x })} /><Num label="Y %" value={o.y} onChange={(y) => update(index, { y })} /><Num label="Поворот°" value={o.rotation} onChange={(rotation) => update(index, { rotation })} /><Num label="Ширина" value={o.width} onChange={(width) => update(index, { width })} /><Num label="Высота" value={o.height} onChange={(height) => update(index, { height })} /></View>
      </View>)}
      {!state.map.locked && <TouchableOpacity style={s.add} onPress={() => setObjects((items) => [...items, emptyObject(items.length)])}><Text style={s.addText}>+ Добавить объект</Text></TouchableOpacity>}
      {canTickets && <TouchableOpacity disabled={busy || !changed || state.map.locked} style={[s.save, (busy || !changed || state.map.locked) && { opacity: .45 }]} onPress={save}>{busy ? <ActivityIndicator color="#fff" /> : <Text style={s.saveText}>Сохранить карту</Text>}</TouchableOpacity>}
    </>}
  </ScrollView>;
}
function Num({ label, value, onChange }: { label: string; value: number; onChange: (v: number) => void }) { return <View style={s.num}><Text style={s.label}>{label}</Text><TextInput style={s.input} keyboardType="number-pad" value={String(value)} onChangeText={(v) => onChange(Number(v || 0))} /></View>; }
const s = StyleSheet.create({ content: { padding: 18, paddingBottom: 90 }, title: { fontSize: 28, fontWeight: "900", color: "#17213C" }, help: { color: "#7B8498", lineHeight: 19, marginTop: 4, marginBottom: 16 }, choiceRow: { flexDirection: "row", gap: 10, marginBottom: 16 }, choice: { flex: 1, minHeight: 100, borderRadius: 16, borderWidth: 1, borderColor: "#DFE3EB", backgroundColor: "#fff", padding: 14 }, choiceOn: { borderWidth: 2, borderColor: "#6D45FF", backgroundColor: "#F3EFFF" }, choiceTitle: { fontWeight: "900", color: "#17213C", fontSize: 16 }, choiceText: { color: "#6D7688", fontSize: 12, marginTop: 5 }, note: { backgroundColor: "#fff", borderRadius: 16, padding: 18 }, noteTitle: { fontWeight: "900", color: "#17213C" }, warning: { backgroundColor: "#FFF7E8", borderWidth: 1, borderColor: "#F2C36B", borderRadius: 14, padding: 14, marginBottom: 14 }, warningTitle: { fontWeight: "900", marginBottom: 4 }, card: { backgroundColor: "#fff", borderWidth: 1, borderColor: "#E1E4EC", borderRadius: 18, padding: 15, marginBottom: 13 }, between: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 10 }, cardTitle: { fontWeight: "900", fontSize: 17, color: "#17213C" }, remove: { color: "#C33", fontWeight: "800" }, label: { fontSize: 12, fontWeight: "800", color: "#5C667B", marginBottom: 5 }, input: { minHeight: 44, borderWidth: 1, borderColor: "#DDE1EA", backgroundColor: "#fff", borderRadius: 11, paddingHorizontal: 11, color: "#17213C" }, row: { flexDirection: "row", gap: 10 }, half: { flex: 1 }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginBottom: 12 }, chip: { borderRadius: 18, paddingHorizontal: 10, paddingVertical: 8, backgroundColor: "#EEF0F5" }, chipOn: { backgroundColor: "#EEE9FF", borderWidth: 1, borderColor: "#6D45FF" }, chipText: { fontSize: 11, fontWeight: "700", color: "#596378" }, chipTextOn: { color: "#5437DD" }, subTitle: { fontWeight: "900", color: "#17213C", marginTop: 4, marginBottom: 9 }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, num: { width: "31%" }, add: { minHeight: 48, borderRadius: 14, borderWidth: 1, borderStyle: "dashed", borderColor: "#6D45FF", alignItems: "center", justifyContent: "center", marginBottom: 12 }, addText: { color: "#6D45FF", fontWeight: "900" }, save: { minHeight: 54, backgroundColor: "#6D45FF", borderRadius: 15, alignItems: "center", justifyContent: "center" }, saveText: { color: "#fff", fontWeight: "900", fontSize: 16 } });
