import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin-shell";
import { GuestListDetailManager } from "@/components/guest-list-detail-manager";
import { requirePermission } from "@/lib/auth";
import { resolveStaffLocale } from "@/lib/i18n";
import { db } from "@/lib/db";
import { getGuestLinkSettings, guestManagementToken, isGuestListPromoter } from "@/lib/guest-links";

export const dynamic="force-dynamic";
const copy={
 ru:{back:"← Гостевые ссылки",active:"Активна",disabled:"Отключена",guests:"Гостей",of:"из",remaining:"Осталось мест",filled:"заполнено",checked:"Прошли",guestShare:"гостей",opens:"Уникальные открытия",publicLink:"публичной ссылки",orders:"Заказов",activeOrders:"активных",state:"Состояние",fillTitle:"Заполнение ссылки",occupied:"мест занято",seatAllocation:(n:number)=>`${n} мест с карты`,table:(name:string)=>`Стол: ${name}`,ticket:(name:string)=>`Билет: ${name}`,all:"Всё мероприятие"},
 he:{back:"← קישורי אורחים",active:"פעיל",disabled:"מושבת",guests:"אורחים",of:"מתוך",remaining:"מקומות שנותרו",filled:"תפוסה",checked:"נכנסו",guestShare:"מהאורחים",opens:"פתיחות ייחודיות",publicLink:"של הקישור הציבורי",orders:"הזמנות",activeOrders:"פעילות",state:"מצב",fillTitle:"תפוסת הקישור",occupied:"מקומות תפוסים",seatAllocation:(n:number)=>`${n} מקומות מהמפה`,table:(name:string)=>`שולחן: ${name}`,ticket:(name:string)=>`כרטיס: ${name}`,all:"כל האירוע"},
 en:{back:"← Guest links",active:"Active",disabled:"Disabled",guests:"Guests",of:"of",remaining:"Seats remaining",filled:"filled",checked:"Checked in",guestShare:"of guests",opens:"Unique opens",publicLink:"of the public link",orders:"Orders",activeOrders:"active",state:"Status",fillTitle:"Link occupancy",occupied:"seats occupied",seatAllocation:(n:number)=>`${n} seats from the map`,table:(name:string)=>`Table: ${name}`,ticket:(name:string)=>`Ticket: ${name}`,all:"Entire event"}
} as const;
export default async function GuestListDetailPage({params}:{params:Promise<{id:string}>}){
 const staff=await requirePermission("EVENT_MANAGE");const locale=resolveStaffLocale({memberOverride:staff.interfaceLocaleOverride,userPreference:staff.preferredLocale,organizationDefault:staff.organization?.defaultStaffLocale});const text=copy[locale];const{id}=await params;
 const list=await db.promoterLink.findFirst({where:{id,event:{organizationId:staff.organizationId!}},include:{promoter:true,event:true,category:true,table:true,visits:{select:{id:true}},orders:{where:{status:{notIn:["CANCELLED","REJECTED"]}},orderBy:{createdAt:"desc"},include:{items:true,tickets:true}}}});if(!list||!isGuestListPromoter(list.promoter.name))notFound();if(staff.eventAccess.length&&!staff.eventAccess.some(item=>item.eventId===list.eventId))notFound();
 const settings=await getGuestLinkSettings(list.id);const guests=list.orders.reduce((sum,order)=>sum+order.items.reduce((s,item)=>s+item.quantity,0),0);const checkins=list.orders.flatMap(order=>order.tickets).filter(ticket=>ticket.status==="USED").length;const limit=settings.seatIds.length?settings.seatIds.length:list.guestLimit??list.table?.seats??list.category?.capacity??Math.max(guests,1);const remaining=Math.max(limit-guests,0);const fill=limit?Math.min(100,Math.round(guests/limit*100)):null;const allocation=settings.seatIds.length?text.seatAllocation(settings.seatIds.length):list.table?text.table(list.table.label):list.category?text.ticket(list.category.name):text.all;const publicPath=`/g/${list.code}`;const managePath=`${publicPath}?token=${guestManagementToken(list.id)}`;
 return <AdminShell><div className="office-page-heading"><div><Link href="/office/guest-lists">{text.back}</Link><span className="eyebrow">Guest link</span><h1>{list.label}</h1><p className="muted">{list.event.title} · {allocation}</p></div><span className="pill" style={list.active?{background:"#dcfae6",color:"#067647"}:{}}>{list.active?text.active:text.disabled}</span></div><div className="stats"><div className="stat"><span className="muted">{text.guests}</span><strong>{guests}</strong><small>{text.of} {limit}</small></div><div className="stat"><span className="muted">{text.remaining}</span><strong>{remaining}</strong><small>{fill!==null?`${fill}% ${text.filled}`:""}</small></div><div className="stat"><span className="muted">{text.checked}</span><strong>{checkins}</strong><small>{guests?`${Math.round(checkins/guests*100)}% ${text.guestShare}`:"0%"}</small></div><div className="stat"><span className="muted">{text.opens}</span><strong>{list.visits.length}</strong><small>{text.publicLink}</small></div><div className="stat"><span className="muted">{text.orders}</span><strong>{list.orders.length}</strong><small>{text.activeOrders}</small></div></div><div className="panel" style={{marginTop:24}}><span className="eyebrow">{text.state}</span><h2 style={{marginBottom:8}}>{text.fillTitle}</h2><p className="muted">{guests} {text.of} {limit} {text.occupied}.</p>{fill!==null&&<div style={{height:10,borderRadius:999,background:"#eaecf0",overflow:"hidden"}}><div style={{height:"100%",width:`${fill}%`,background:"#12b76a"}}/></div>}</div><div style={{marginTop:24}}><GuestListDetailManager list={{id:list.id,label:list.label,active:list.active,publicPath,managePath,guestLimit:limit,maxPerOrder:list.maxPerOrder,showAttendees:settings.showAttendees,seatPoolLocked:settings.seatIds.length>0,startsAt:list.startsAt?.toISOString()??null,endsAt:list.endsAt?.toISOString()??null}} guests={list.orders.map(order=>({id:order.id,publicId:order.publicId,name:order.customerName,email:order.customerEmail,phone:order.customerPhone,tickets:order.tickets.length,used:order.tickets.filter(ticket=>ticket.status==="USED").length}))}/></div></AdminShell>
}
