import Link from "next/link";
import { AtlasLogo } from "@/components/atlas-logo";
import { ORGANIZER_AGREEMENT_VERSION } from "@/lib/organizer-compliance";
import { getServerI18n } from "@/lib/server-locale";
import { localeConfig } from "@/lib/i18n";

const copy={
ru:{exists:"Аккаунт с таким email уже существует.",generic:"Проверьте заполненные данные.",eyebrow:"Регистрация организатора",title:"Создайте рабочий кабинет",help:"Договор Atlas подписывается электронным подтверждением при регистрации. Банковские реквизиты и налоговые документы можно добавить позже, они понадобятся только перед первой выплатой.",first:"Имя",last:"Фамилия",phone:"Телефон",email:"Email",password:"Пароль",passwordHelp:"Минимум 10 символов.",organization:"Название организации или бизнеса",type:"Тип бизнеса",select:"Выберите",types:["Индивидуальный предприниматель","Компания","Некоммерческая организация","Частное лицо"],country:"Страна",agreement:"Подписываю договор Atlas One",agreementHelp:"Нажимая подтверждение, я принимаю",terms:"условия для организаторов",and:"и",privacy:"политику конфиденциальности",record:"Atlas сохранит имя, email, дату и время принятия, версию договора",hash:"и цифровой хэш текста.",submit:"Подписать и создать кабинет",login:"Уже есть аккаунт? Войти"},
he:{exists:"כבר קיים חשבון עם כתובת ה־Email הזו.",generic:"בדקו את הפרטים שהוזנו.",eyebrow:"הרשמת מפיק",title:"יצירת אזור עבודה",help:"הסכם Atlas מאושר דיגיטלית במהלך ההרשמה. אפשר להוסיף פרטי בנק ומסמכי מס מאוחר יותר, לפני התשלום הראשון.",first:"שם פרטי",last:"שם משפחה",phone:"טלפון",email:"Email",password:"סיסמה",passwordHelp:"לפחות 10 תווים.",organization:"שם הארגון או העסק",type:"סוג העסק",select:"בחרו",types:["עוסק עצמאי","חברה","עמותה / מלכ״ר","אדם פרטי"],country:"מדינה",agreement:"אני מאשר/ת את הסכם Atlas One",agreementHelp:"באישור ההרשמה אני מקבל/ת את",terms:"התנאים למפיקים",and:"ואת",privacy:"מדיניות הפרטיות",record:"Atlas תשמור את השם, כתובת ה־Email, מועד האישור, גרסת ההסכם",hash:"וחתימה דיגיטלית של הטקסט.",submit:"אישור ויצירת אזור העבודה",login:"כבר יש חשבון? כניסה"},
en:{exists:"An account with this email already exists.",generic:"Check the information you entered.",eyebrow:"Organizer registration",title:"Create your workspace",help:"The Atlas agreement is accepted electronically during registration. Bank and tax documents can be added later and are required only before the first payout.",first:"First name",last:"Last name",phone:"Phone",email:"Email",password:"Password",passwordHelp:"At least 10 characters.",organization:"Organization or business name",type:"Business type",select:"Select",types:["Sole proprietor","Company","Nonprofit organization","Individual"],country:"Country",agreement:"I accept the Atlas One agreement",agreementHelp:"By confirming, I accept the",terms:"organizer terms",and:"and",privacy:"privacy policy",record:"Atlas will store the name, email, acceptance date and time, agreement version",hash:"and a digital hash of the text.",submit:"Accept and create workspace",login:"Already have an account? Log in"}
} as const;
export default async function OfficeRegisterPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){const [{locale},params]=await Promise.all([getServerI18n(),searchParams]);const text=copy[locale];const error=params.error==="EMAIL_EXISTS"?text.exists:params.error?text.generic:"";return <main lang={localeConfig[locale].tag} dir={localeConfig[locale].dir} className="container" style={{maxWidth:760,paddingTop:48,paddingBottom:80}}><div className="panel form" style={{padding:32}}><AtlasLogo office/><div><span className="eyebrow">{text.eyebrow}</span><h1>{text.title}</h1><p className="muted">{text.help}</p></div>{error&&<div className="toast" style={{background:"#fff1f0",color:"#b42318"}}>{error}</div>}<form method="post" action="/api/office/auth/register" className="form"><div className="form-grid two"><div className="field"><label>{text.first}</label><input className="input" name="firstName" autoComplete="given-name" required/></div><div className="field"><label>{text.last}</label><input className="input" name="lastName" autoComplete="family-name" required/></div></div><div className="form-grid two"><div className="field"><label>{text.phone}</label><input className="input" dir="ltr" style={{textAlign:"left"}} type="tel" name="phone" autoComplete="tel" required/></div><div className="field"><label>{text.email}</label><input className="input" dir="ltr" style={{textAlign:"left"}} type="email" name="email" autoComplete="email" required/></div></div><div className="field"><label>{text.password}</label><input className="input" dir="ltr" style={{textAlign:"left"}} type="password" name="password" minLength={10} autoComplete="new-password" required/><small className="muted">{text.passwordHelp}</small></div><div className="field"><label>{text.organization}</label><input className="input" name="organizationName" required/></div><div className="form-grid two"><div className="field"><label>{text.type}</label><select name="businessType" required defaultValue=""><option value="" disabled>{text.select}</option>{text.types.map(value=><option key={value} value={value}>{value}</option>)}</select></div><div className="field"><label>{text.country}</label><input className="input" name="country" defaultValue="Israel" required/></div></div><label className="option" style={{alignItems:"flex-start"}}><span><strong>{text.agreement}</strong><small>{text.agreementHelp} <Link href="/legal/organizer-terms" target="_blank" style={{textDecoration:"underline"}}>{text.terms}</Link> {text.and} <Link href="/legal/privacy" target="_blank" style={{textDecoration:"underline"}}>{text.privacy}</Link>. {text.record} <bdi>{ORGANIZER_AGREEMENT_VERSION}</bdi> {text.hash}</small></span><input type="checkbox" name="acceptedTerms" required/></label><button className="btn dark">{text.submit}</button></form><Link href="/office/login">{text.login}</Link></div></main>;}
