import type { Metadata } from "next";
import { ContentPage, Section } from "@/components/content-page";
import { getServerI18n } from "@/lib/server-locale";
import type { Locale } from "@/lib/i18n";

const copy={
  ru:{meta:"Контакты Atlas One",description:"Связаться с Atlas One по вопросам билетов, возвратов, мероприятий и подключения организаторов.",eyebrow:"Связь",title:"Контакты",intro:"Напишите нам по вопросу заказа, возврата, мероприятия или подключения организатора.",customers:"Покупателям",customersText:"Укажите email, с которым оформлялся заказ, название мероприятия и номер заказа, если он у вас есть.",organizers:"Организаторам",organizersText:"Опишите формат мероприятий, предполагаемый объём продаж и функции, которые вам нужны."},
  he:{meta:"יצירת קשר עם Atlas One",description:"יצירת קשר עם Atlas One בנושאי כרטיסים, ביטולים, אירועים והצטרפות מפיקים.",eyebrow:"אנחנו כאן בשבילכם",title:"יצירת קשר",intro:"פנו אלינו בכל שאלה על הזמנה, ביטול, אירוע או הצטרפות כמפיקים.",customers:"לרוכשי כרטיסים",customersText:"ציינו את כתובת האימייל ששימשה להזמנה, את שם האירוע ואת מספר ההזמנה, אם הוא זמין.",organizers:"למפיקים",organizersText:"ספרו לנו אילו אירועים אתם מפיקים, מה היקף המכירות הצפוי ואילו כלים חשובים לכם."},
  en:{meta:"Contact Atlas One",description:"Contact Atlas One about tickets, cancellations, events, or organizer onboarding.",eyebrow:"Get in touch",title:"Contact us",intro:"Write to us about an order, cancellation, event, or joining Atlas One as an organizer.",customers:"Ticket buyers",customersText:"Include the email used for the order, the event name, and the order number if available.",organizers:"Organizers",organizersText:"Tell us about your event format, expected sales volume, and the tools you need."},
} satisfies Record<Locale,Record<string,string>>;
export async function generateMetadata():Promise<Metadata>{const{locale}=await getServerI18n();const text=copy[locale];return{title:text.meta,description:text.description,alternates:{canonical:"/contact"}};}
export default async function ContactPage(){const{locale}=await getServerI18n();const text=copy[locale];return <ContentPage eyebrow={text.eyebrow} title={text.title} intro={text.intro}><Section title={text.customers}><p>{text.customersText}</p></Section><Section title={text.organizers}><p>{text.organizersText}</p></Section><Section title="Email"><p><a href="mailto:support@atlas-one.co" dir="ltr">support@atlas-one.co</a></p></Section></ContentPage>}
