import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin-shell";
import { EventEditorWorkspace } from "@/components/event-editor-workspace";
import { EventDetailsManager } from "@/components/event-details-manager";
import { EventSalesModeManager } from "@/components/event-sales-mode-manager";
import { EventArchiveControl } from "@/components/event-archive-control";
import { EventPublishControl } from "@/components/event-publish-control";
import { EventTypeManager } from "@/components/event-type-manager";
import { EventLanguageManager } from "@/components/event-language-manager";
import { EventAtlasAssistant } from "@/components/event-atlas-assistant";
import { VenueMapEditor } from "@/components/venue-map-editor";
import { FullscreenMapPanel } from "@/components/fullscreen-map-panel";
import { PricingStrategyManager } from "@/components/pricing-strategy-manager";
import { CategoryManagerWithCreate } from "@/components/category-manager-with-create";
import { CheckoutFormManager } from "@/components/checkout-form-manager";
import { EventCommercialTermsForm } from "@/components/event-commercial-terms-form";
import { AdmissionModeManager } from "@/components/admission-mode-manager";
import { db } from "@/lib/db";
import { describeCategoryPrice } from "@/lib/ticketing";
import { requireEventAccess } from "@/lib/auth";
import { getEffectiveEventTerms } from "@/lib/commercial-terms";
import { parseEventMedia,stripEventMedia } from "@/lib/event-media";
import { parseEventRejectionMessage,stripEventRejectionMessage } from "@/lib/event-approval-message";
import { parseBuyerQuestions,stripBuyerQuestions } from "@/lib/buyer-questions";
import { parseGuestFields,stripEventMarkers } from "@/lib/event-guest-fields";
import { parsePricingMarketingStrategy } from "@/lib/ticket-pricing-strategy";
import { parseEventTypes,stripEventType } from "@/lib/event-type";
import { getEventLanguageSettings } from "@/lib/event-language-server";
import { isEventArchived } from "@/lib/event-archive";
import { isReadingVenue, readingVenuePreset } from "@/lib/venue-map-presets";
import { resolveStaffLocale } from "@/lib/i18n";

export const dynamic="force-dynamic";
type TabId="about"|"tickets"|"map"|"checkout"|"review";
const copy={
 ru:{editor:"Единый редактор мероприятия",description:"Каждая настройка находится только в одном разделе.",mapEyebrow:"Схема зала",mapHelp:"Карта площадки редактируется ниже. Назначение цветов происходит через типы билетов.",noMapAccess:"У вас нет доступа к редактированию карты.",mapOff:"Карта не используется",mapOffHelp:"Покупатель выбирает тип и количество билетов без выбора места.",buyerTicket:"Билет покупателя",ticketDesign:"Дизайн и выдача билета",ticketHelp:"Настройте внешний вид билета и данные, которые получает покупатель.",openTicket:"Открыть редактор билета",review:"Проверка",status:"Статус",format:"Формат",withSeats:"С выбором мест",withoutMap:"Без схемы",categories:"Категорий билетов",preview:"Предварительный просмотр",links:"Продажи и гостевые ссылки",public:"Открыть публичную страницу"},
 he:{editor:"עורך אירוע מאוחד",description:"כל הגדרה נמצאת במקום אחד בלבד.",mapEyebrow:"מפת אולם",mapHelp:"מפת המתחם נערכת בהמשך. שיוך הצבעים מתבצע דרך סוגי הכרטיסים.",noMapAccess:"אין לכם הרשאה לערוך את המפה.",mapOff:"אין שימוש במפה",mapOffHelp:"הרוכש בוחר סוג וכמות כרטיסים ללא בחירת מקום.",buyerTicket:"כרטיס ללקוח",ticketDesign:"עיצוב והנפקת כרטיס",ticketHelp:"הגדירו את מראה הכרטיס ואת המידע שהלקוח מקבל.",openTicket:"פתיחת עורך הכרטיס",review:"בדיקה",status:"סטטוס",format:"פורמט",withSeats:"עם בחירת מקומות",withoutMap:"ללא מפה",categories:"קטגוריות כרטיסים",preview:"תצוגה מקדימה",links:"מכירות וקישורי אורחים",public:"פתיחת העמוד הציבורי"},
 en:{editor:"Unified event editor",description:"Each setting appears in one section only.",mapEyebrow:"Venue map",mapHelp:"Edit the venue map below. Colors are assigned through ticket types.",noMapAccess:"You do not have access to edit the map.",mapOff:"Map is not used",mapOffHelp:"The buyer chooses ticket type and quantity without selecting a seat.",buyerTicket:"Buyer ticket",ticketDesign:"Ticket design and delivery",ticketHelp:"Configure the ticket appearance and the information the buyer receives.",openTicket:"Open ticket editor",review:"Review",status:"Status",format:"Format",withSeats:"Seat selection",withoutMap:"No map",categories:"Ticket categories",preview:"Preview",links:"Sales and guest links",public:"Open public page"}
} as const;

export default async function ManageEvent({params,searchParams}:{params:Promise<{id:string}>;searchParams?:Promise<{tab?:string}>}){
 const{id}=await params;const query=searchParams?await searchParams:{};const staff=await requireEventAccess("EVENT_VIEW",id);const locale=resolveStaffLocale({memberOverride:staff.interfaceLocaleOverride,userPreference:staff.preferredLocale,organizationDefault:staff.organization?.defaultStaffLocale});const text=copy[locale];
 const event=await db.event.findUnique({where:{id},include:{organization:true,venue:true,categories:{include:{priceTiers:true}},zones:{include:{tables:{include:{seatItems:true}}}}}});if(!event)notFound();
 const[commercialTerms,languageSettings,archived]=await Promise.all([getEffectiveEventTerms(event.id,event.organizationId),getEventLanguageSettings(event.id),isEventArchived(event.id)]);const now=new Date();
 const managedCategories=event.categories.map(category=>{const status=describeCategoryPrice(category,now);return{id:category.id,name:category.name,description:category.description,priceMinor:category.priceMinor,pricingMode:category.pricingMode,capacity:category.capacity,sold:category.sold,hidden:category.hidden,colorHex:category.colorHex,maxPerOrder:category.maxPerOrder,salesStart:category.salesStart?.toISOString()??null,salesEnd:category.salesEnd?.toISOString()??null,priceTiers:category.priceTiers.map(tier=>({id:tier.id,label:tier.label,priceMinor:tier.priceMinor,startsAt:tier.startsAt.toISOString(),endsAt:tier.endsAt.toISOString()})),currentPriceMinor:status.currentPriceMinor,statusLabel:status.statusLabel,nextTierPriceMinor:status.nextTier?.priceMinor,nextTierStartsAt:status.nextTier?.startsAt.toISOString()};});
 const media=parseEventMedia(event.description);const buyerQuestions=parseBuyerQuestions(event.description);const guestFields=parseGuestFields(event.description);const eventTypes=parseEventTypes(event.description);const cleanDescription=stripEventType(stripEventMarkers(stripBuyerQuestions(stripEventRejectionMessage(stripEventMedia(event.description)))));const rejectionMessage=parseEventRejectionMessage(event.description);const canManage=staff.permissionSet.has("EVENT_MANAGE");const canTickets=staff.permissionSet.has("TICKET_MANAGE");const allowedTabs=new Set<TabId>(["about","tickets","map","checkout","review"]);const initialTab=allowedTabs.has(query.tab as TabId)?query.tab as TabId:"about";
 const storedMapObjects=event.zones.flatMap(zone=>zone.tables.map(item=>({id:item.id,label:item.label,objectType:item.objectType,seats:item.seats,priceMode:item.priceMode,priceMinor:item.priceMinor,x:item.x,y:item.y,rotation:item.rotation,width:item.width,height:item.height,categoryId:item.categoryId,reserved:item.reserved||item.seatItems.some(seat=>seat.status!=="AVAILABLE"),seatAssignments:item.seatItems.map(seat=>({position:seat.position,categoryId:seat.categoryId}))})));const readingStarterPlaceholder=isReadingVenue(event.venue.name)&&storedMapObjects.length<=2&&storedMapObjects.every(item=>!item.reserved)&&storedMapObjects.some(item=>item.label.trim().toLowerCase()==="r1"||item.objectType==="ROW");const initialMapObjects=isReadingVenue(event.venue.name)&&(storedMapObjects.length===0||readingStarterPlaceholder)?readingVenuePreset():storedMapObjects;
 const about=<div className="stack">{canManage&&<EventDetailsManager event={{id:event.id,title:event.title,description:cleanDescription,posterUrl:event.posterUrl,media,startsAt:event.startsAt.toISOString(),venueName:event.venue.name,city:event.venue.city,address:event.venue.address}}/>}{canManage&&<EventLanguageManager eventId={event.id} initial={languageSettings}/>} {canManage&&<EventTypeManager eventId={event.id} initialTypes={eventTypes}/>}</div>;
 const tickets=<div className="stack">{canTickets&&<CategoryManagerWithCreate eventId={event.id} categories={managedCategories}/>} {canTickets&&<PricingStrategyManager eventId={event.id} categories={event.categories.map(item=>({id:item.id,name:item.name,pricingMode:item.pricingMode,strategy:parsePricingMarketingStrategy(item.description)}))}/>}</div>;
 const map=<div className="stack">{(canManage||canTickets)&&<AdmissionModeManager eventId={event.id} initialMapEnabled={event.mapEnabled}/>} {event.mapEnabled&&canTickets?<><section className="panel venue-map-context"><span className="eyebrow">{text.mapEyebrow}</span><h2>{event.venue.name}</h2><p className="muted">{text.mapHelp}</p></section><FullscreenMapPanel><VenueMapEditor eventId={event.id} venueName={event.venue.name} categories={event.categories.map(category=>({id:category.id,name:category.name,priceMinor:category.priceMinor,colorHex:category.colorHex}))} initialObjects={initialMapObjects}/></FullscreenMapPanel></>:event.mapEnabled?<div className="panel">{text.noMapAccess}</div>:<section className="panel"><h2>{text.mapOff}</h2><p className="muted">{text.mapOffHelp}</p></section>}</div>;
 const checkout=<div className="stack">{canManage&&<EventSalesModeManager eventId={event.id} initialMode={event.salesMode} initialInstructions={event.approvalInstructions} initialRejectionMessage={rejectionMessage}/>} {canManage&&<CheckoutFormManager eventId={event.id} initialGuestFields={guestFields} initialQuestions={buyerQuestions}/>} {canManage&&<EventCommercialTermsForm eventId={event.id} organizerName={event.organization.name} isSuperAdmin={staff.role==="ADMIN"} initial={{useOrganizerDefaults:commercialTerms.useOrganizerDefaults,serviceFeePayer:commercialTerms.serviceFeePayer,organizerServiceFeePayer:commercialTerms.organizer.serviceFeePayer}}/>} {canTickets&&<section className="panel"><span className="eyebrow">{text.buyerTicket}</span><h2>{text.ticketDesign}</h2><p className="muted">{text.ticketHelp}</p><Link className="btn" href={`/office/events/${event.id}/ticket-design`}>{text.openTicket}</Link></section>}</div>;
 const review=<div className="stack"><section className="panel"><span className="eyebrow">{text.review}</span><h2>{event.title}</h2><div className="stats"><div className="stat"><span className="muted">{text.status}</span><strong><bdi>{archived?"ARCHIVED":event.status}</bdi></strong></div><div className="stat"><span className="muted">{text.format}</span><strong>{event.mapEnabled?text.withSeats:text.withoutMap}</strong></div><div className="stat"><span className="muted">{text.categories}</span><strong>{event.categories.length}</strong></div></div><div className="row" style={{flexWrap:"wrap"}}><Link className="btn dark" href={`/office/events/${event.id}/preview`}>{text.preview}</Link>{canManage&&<Link className="btn secondary" href={`/office/events/${event.id}/links`}>{text.links}</Link>}{event.status==="PUBLISHED"&&<Link className="btn secondary" href={`/events/${event.slug}`}>{text.public}</Link>}</div></section>{canManage&&<EventPublishControl eventId={event.id} status={event.status as "DRAFT"|"PUBLISHED"}/>} {(canManage||canTickets)&&<EventAtlasAssistant event={{id:event.id,title:event.title,status:archived?"ARCHIVED":event.status,salesMode:event.salesMode,startsAt:event.startsAt.toISOString(),venue:`${event.venue.name}, ${event.venue.city}`,categories:event.categories.map(item=>({id:item.id,name:item.name,priceMinor:item.priceMinor,capacity:item.capacity,sold:item.sold,pricingMode:item.pricingMode}))}}/>}{canManage&&<EventArchiveControl eventId={event.id} eventTitle={event.title} status={event.status as "DRAFT"|"PUBLISHED"} archived={archived}/>}</div>;
 return <AdminShell><div className="row between"><div><span className="eyebrow">{text.editor}</span><h1>{event.title}</h1><p className="muted">{text.description}</p></div><span className="pill"><bdi>{event.status}</bdi></span></div><EventEditorWorkspace initialTab={initialTab} about={about} tickets={tickets} map={map} checkout={checkout} review={review}/></AdminShell>;
}
