import "./workspace.css";
import Link from "next/link";
import { db } from "@/lib/db";
import { money, eventDate } from "@/lib/format";
import { AdminShell } from "@/components/admin-shell";
import { requirePermission } from "@/lib/auth";
import { recoveryDashboard } from "@/lib/abandoned-checkout";
import { localeConfig, resolveStaffLocale, type Locale } from "@/lib/i18n";

export const dynamic = "force-dynamic";
const startOfDay = (date = new Date()) => new Date(date.getFullYear(), date.getMonth(), date.getDate());
const startOfMonth = (date = new Date()) => new Date(date.getFullYear(), date.getMonth(), 1);
const dashboardCopy = {
  ru: { morning:"Доброе утро", afternoon:"Добрый день", evening:"Добрый вечер", organizer:"организатор", intro:"Вот что происходит с доступными вам событиями сегодня.", newEvent:"Новое мероприятие", kpis:"Ключевые показатели", salesToday:"Продажи сегодня", ticketsShort:"бил.", potential:"Потенциальная выручка", lostCheckouts:"потерянных оформлений", monthRevenue:"Выручка за месяц", paidOrders:"оплаченных заказов", average:"Средний чек", currentMonth:"За текущий месяц", events:"Ваши мероприятия", eventsHelp:"Ближайшие события в рамках выданного вам доступа.", allEvents:"Все мероприятия", poster:"Афиша", today:"Сегодня", inDays:(days:number)=>`Через ${days} дн.`, sold:"продано", revenue:"выручка", left:"осталось", noEvents:"Нет доступных ближайших мероприятий", noEventsHelp:"Попросите владельца изменить область доступа, если здесь должно быть событие.", activity:"Последняя активность", activityHelp:"Только данные, разрешённые вашей ролью", showAll:"Показать всё", sale:"Новая продажа", orderUpdate:"Обновление заказа", justNow:"только что", minutesAgo:(value:number)=>`${value} мин назад`, hoursAgo:(value:number)=>`${value} ч назад`, daysAgo:(value:number)=>`${value} дн назад`, dynamics:"Динамика продаж", lastSeven:"Последние 7 дней", chartLabel:"Линейный график выручки за семь дней", sevenRevenue:"Выручка за 7 дней", allOrders:"Всего заказов", important:"Важное сейчас", importantHelp:"Разделы, где требуется действие", requests:"заявок на рассмотрении", awaiting:"Ожидают решения", potentially:"Потенциально" },
  he: { morning:"בוקר טוב", afternoon:"צהריים טובים", evening:"ערב טוב", organizer:"מפיקים", intro:"זה מה שקורה היום באירועים שיש לכם גישה אליהם.", newEvent:"אירוע חדש", kpis:"נתונים מרכזיים", salesToday:"מכירות היום", ticketsShort:"כרטיסים", potential:"הכנסה פוטנציאלית", lostCheckouts:"תהליכי רכישה שלא הושלמו", monthRevenue:"הכנסות החודש", paidOrders:"הזמנות ששולמו", average:"ממוצע להזמנה", currentMonth:"בחודש הנוכחי", events:"האירועים שלכם", eventsHelp:"האירועים הקרובים שנכללים בהרשאות שלכם.", allEvents:"לכל האירועים", poster:"פוסטר של", today:"היום", inDays:(days:number)=>`בעוד ${days} ימים`, sold:"נמכרו", revenue:"הכנסות", left:"נותרו", noEvents:"אין אירועים קרובים זמינים", noEventsHelp:"אם אמור להופיע כאן אירוע, בקשו מבעלי הארגון לעדכן את ההרשאות שלכם.", activity:"פעילות אחרונה", activityHelp:"מוצג רק מידע שההרשאה שלכם מאפשרת", showAll:"הצגת הכול", sale:"מכירה חדשה", orderUpdate:"עדכון הזמנה", justNow:"ממש עכשיו", minutesAgo:(value:number)=>`לפני ${value} דק׳`, hoursAgo:(value:number)=>`לפני ${value} שעות`, daysAgo:(value:number)=>`לפני ${value} ימים`, dynamics:"מגמת מכירות", lastSeven:"7 הימים האחרונים", chartLabel:"גרף הכנסות בשבעת הימים האחרונים", sevenRevenue:"הכנסות ב-7 ימים", allOrders:"סך ההזמנות", important:"מה דורש טיפול", importantHelp:"נושאים שממתינים לפעולה שלכם", requests:"בקשות לבדיקה", awaiting:"ממתינות להחלטה", potentially:"פוטנציאל" },
  en: { morning:"Good morning", afternoon:"Good afternoon", evening:"Good evening", organizer:"organizer", intro:"Here is what is happening across the events you can access today.", newEvent:"New event", kpis:"Key metrics", salesToday:"Sales today", ticketsShort:"tickets", potential:"Potential revenue", lostCheckouts:"incomplete checkouts", monthRevenue:"Revenue this month", paidOrders:"paid orders", average:"Average order", currentMonth:"Current month", events:"Your events", eventsHelp:"Upcoming events within your access scope.", allEvents:"All events", poster:"Poster for", today:"Today", inDays:(days:number)=>`In ${days} days`, sold:"sold", revenue:"revenue", left:"remaining", noEvents:"No upcoming events available", noEventsHelp:"Ask the owner to update your access scope if an event should appear here.", activity:"Latest activity", activityHelp:"Only data permitted by your role", showAll:"Show all", sale:"New sale", orderUpdate:"Order update", justNow:"just now", minutesAgo:(value:number)=>`${value} min ago`, hoursAgo:(value:number)=>`${value} hr ago`, daysAgo:(value:number)=>`${value} days ago`, dynamics:"Sales trend", lastSeven:"Last 7 days", chartLabel:"Revenue line chart for the last seven days", sevenRevenue:"Revenue over 7 days", allOrders:"Total orders", important:"Needs attention", importantHelp:"Areas waiting for action", requests:"requests to review", awaiting:"Awaiting a decision", potentially:"Potential" },
} as const;

function greetingForIsrael(locale:Locale){const hour=Number(new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Jerusalem",hour:"2-digit",hourCycle:"h23"}).format(new Date()));const text=dashboardCopy[locale];if(hour>=5&&hour<12)return text.morning;if(hour>=12&&hour<18)return text.afternoon;return text.evening;}
function relativeTime(date:Date,locale:Locale){const text=dashboardCopy[locale];const minutes=Math.max(0,Math.floor((Date.now()-date.getTime())/60000));if(minutes<1)return text.justNow;if(minutes<60)return text.minutesAgo(minutes);const hours=Math.floor(minutes/60);if(hours<24)return text.hoursAgo(hours);return text.daysAgo(Math.floor(hours/24));}
function daysUntil(date:Date){return Math.ceil((date.getTime()-Date.now())/86400000);}
function shortDay(date:Date,locale:Locale){return new Intl.DateTimeFormat(localeConfig[locale].tag,{day:"numeric",month:"short",timeZone:"Asia/Jerusalem"}).format(date);}

export default async function Admin(){
  const staff=await requirePermission("EVENT_VIEW");
  const locale=resolveStaffLocale({memberOverride:staff.interfaceLocaleOverride,userPreference:staff.preferredLocale,organizationDefault:staff.organization?.defaultStaffLocale});
  const text=dashboardCopy[locale];
  const canAnalytics=staff.permissionSet.has("ANALYTICS_VIEW");
  const canOrders=staff.permissionSet.has("ORDER_VIEW");
  const canReview=staff.permissionSet.has("REQUEST_REVIEW");
  const canAudit=staff.permissionSet.has("TEAM_MANAGE");
  const canRecovery=canAnalytics&&staff.eventScope==="ALL";
  const eventIds=staff.eventAccess.map(item=>item.eventId);
  const scopedIds=staff.eventScope==="ALL"?undefined:eventIds;
  const eventWhere={organizationId:staff.organizationId!,...(scopedIds?{id:{in:scopedIds}}:{})};
  // This dynamic server page intentionally takes one request-time clock snapshot.
  // eslint-disable-next-line react-hooks/purity
  const today=startOfDay();const monthStart=startOfMonth();const sevenDaysAgo=startOfDay(new Date(Date.now()-6*86400000));
  const events=await db.event.findMany({where:eventWhere,include:{venue:true,categories:true},orderBy:{startsAt:"asc"}});
  const accessibleEventIds=events.map(event=>event.id);
  const orderScope={eventId:{in:accessibleEventIds}};
  const [todayOrders,monthOrders,recentOrders,approvalCount,auditLogs,recovery,sevenDayOrders,revenueRows]=await Promise.all([
    canAnalytics&&accessibleEventIds.length?db.order.findMany({where:{status:"PAID",createdAt:{gte:today},...orderScope},select:{totalMinor:true}}):Promise.resolve([]),
    canAnalytics&&accessibleEventIds.length?db.order.findMany({where:{status:"PAID",createdAt:{gte:monthStart},...orderScope},select:{totalMinor:true}}):Promise.resolve([]),
    canOrders&&accessibleEventIds.length?db.order.findMany({where:orderScope,take:8,orderBy:{createdAt:"desc"},include:{event:true,tickets:true}}):Promise.resolve([]),
    canReview&&accessibleEventIds.length?db.order.count({where:{status:"PENDING_APPROVAL",...orderScope}}):Promise.resolve(0),
    canAudit?db.auditLog.findMany({where:{organizationId:staff.organizationId!},take:6,orderBy:{createdAt:"desc"}}):Promise.resolve([]),
    canRecovery?recoveryDashboard(staff.organizationId!):Promise.resolve(null),
    canAnalytics&&accessibleEventIds.length?db.order.findMany({where:{status:"PAID",createdAt:{gte:sevenDaysAgo},...orderScope},select:{totalMinor:true,createdAt:true}}):Promise.resolve([]),
    canAnalytics&&accessibleEventIds.length?db.order.groupBy({by:["eventId"],where:{status:"PAID",...orderScope},_sum:{totalMinor:true}}):Promise.resolve([]),
  ]);
  const upcomingEvents=events.filter(event=>event.startsAt>=today).slice(0,8);
  const revenueByEvent=new Map(revenueRows.map(row=>[row.eventId,row._sum.totalMinor||0]));
  const todayRevenue=todayOrders.reduce((sum,order)=>sum+order.totalMinor,0);const monthRevenue=monthOrders.reduce((sum,order)=>sum+order.totalMinor,0);const averageCheck=monthOrders.length?Math.round(monthRevenue/monthOrders.length):0;
  const abandonedCount=Number(recovery?.totals.activeCount||0);const potentialMinor=Number(recovery?.totals.potentialMinor||0);const attentionCount=(canReview?approvalCount:0)+(canRecovery?abandonedCount:0);
  const firstName=staff.name?.split(" ")[0]||text.organizer;const greeting=greetingForIsrael(locale);
  const dailySales=Array.from({length:7},(_,index)=>{const date=new Date(sevenDaysAgo);date.setDate(date.getDate()+index);const next=new Date(date);next.setDate(next.getDate()+1);const orders=sevenDayOrders.filter(order=>order.createdAt>=date&&order.createdAt<next);return{date,count:orders.length,revenue:orders.reduce((sum,order)=>sum+order.totalMinor,0)}});
  const maxDailyRevenue=Math.max(1,...dailySales.map(day=>day.revenue));const sevenDayRevenue=dailySales.reduce((sum,day)=>sum+day.revenue,0);const sevenDayTickets=dailySales.reduce((sum,day)=>sum+day.count,0);const chartPoints=dailySales.map((day,index)=>({ ...day,x:36+index*104,y:168-Math.round((day.revenue/maxDailyRevenue)*126)}));const linePoints=chartPoints.map(point=>`${point.x},${point.y}`).join(" ");const areaPoints=`36,168 ${linePoints} 660,168`;

  return <AdminShell>
    <section className="workspace-hero">
      <div><h1>{greeting}, {firstName}! <span aria-hidden="true">👋</span></h1><p>{text.intro}</p></div>
      {staff.permissionSet.has("EVENT_MANAGE")&&<Link href="/office/events/new" className="btn">+ {text.newEvent}</Link>}
    </section>
    {canAnalytics&&<section className="workspace-kpis" aria-label={text.kpis}>
      <Link href="/office/orders" className="workspace-kpi workspace-kpi-sales"><span className="workspace-kpi-icon">↗</span><small>{text.salesToday}</small><strong>{todayOrders.length} <em>{text.ticketsShort}</em></strong><p>{money(todayRevenue,"ILS",locale)}</p></Link>
      {canRecovery&&<Link href="/office/abandoned" className="workspace-kpi workspace-kpi-lost"><span className="workspace-kpi-icon">◫</span><small>{text.potential}</small><strong>{money(potentialMinor,"ILS",locale)}</strong><p>{abandonedCount} {text.lostCheckouts}</p></Link>}
      <Link href="/office/orders" className="workspace-kpi workspace-kpi-revenue"><span className="workspace-kpi-icon">◎</span><small>{text.monthRevenue}</small><strong>{money(monthRevenue,"ILS",locale)}</strong><p>{monthOrders.length} {text.paidOrders}</p></Link>
      <Link href="/office/orders" className="workspace-kpi workspace-kpi-check"><span className="workspace-kpi-icon">₪</span><small>{text.average}</small><strong>{money(averageCheck,"ILS",locale)}</strong><p>{text.currentMonth}</p></Link>
    </section>}
    <section className="workspace-events-section">
      <div className="workspace-section-head"><div><h2>{text.events}</h2><p>{text.eventsHelp}</p></div><Link href="/office/events">{text.allEvents} →</Link></div>
      <div className="workspace-event-grid">{upcomingEvents.map(event=>{const sold=event.categories.reduce((sum,category)=>sum+category.sold,0);const capacity=event.categories.reduce((sum,category)=>sum+category.capacity,0);const fill=capacity?Math.min(100,Math.round((sold/capacity)*100)):0;const days=daysUntil(event.startsAt);return <Link href={`/office/events/${event.id}`} className="workspace-event-card" key={event.id}><div className="workspace-event-image"><img src={event.posterUrl} alt={`${text.poster} ${event.title}`}/><span>{days<=0?text.today:text.inDays(days)}</span></div><div className="workspace-event-body"><small>{eventDate(event.startsAt,locale)} · {event.venue.name}</small><h3>{event.title}</h3><div className="workspace-event-metrics"><span><b>{sold} / {capacity}</b><small>{text.sold}</small></span>{canAnalytics&&<span><b>{money(revenueByEvent.get(event.id)||0,"ILS",locale)}</b><small>{text.revenue}</small></span>}<span><b>{Math.max(0,capacity-sold)}</b><small>{text.left}</small></span></div><div className="workspace-progress"><i style={{width:`${fill}%`}}/></div></div></Link>})}{!upcomingEvents.length&&<div className="office-empty"><h3>{text.noEvents}</h3><p>{text.noEventsHelp}</p></div>}</div>
    </section>
    {(canOrders||canAudit)&&<details className="workspace-activity-panel"><summary><span><strong>{text.activity}</strong><small>{text.activityHelp}</small></span><b>{text.showAll}</b></summary><div className="workspace-activity-grid">{canOrders&&recentOrders.slice(0,5).map(order=><Link href={`/office/orders/${order.publicId}`} key={order.id}><i>{order.status==="PAID"?"₪":"•"}</i><div><strong>{order.status==="PAID"?text.sale:text.orderUpdate}</strong><small>{order.event.title} · {order.tickets.length} {text.ticketsShort}</small></div><time>{relativeTime(order.createdAt,locale)}</time></Link>)}{canAudit&&auditLogs.slice(0,3).map(log=><div key={log.id}><i>↻</i><div><strong>{log.summary}</strong><small>{log.entityType}</small></div><time>{relativeTime(log.createdAt,locale)}</time></div>)}</div></details>}
    {(canAnalytics||canReview||canRecovery)&&<section className="workspace-bottom-grid">{canAnalytics&&<article className="workspace-chart-panel"><div className="workspace-panel-head"><div><h2>{text.dynamics}</h2><p>{text.lastSeven}</p></div><span>{money(sevenDayRevenue,"ILS",locale)}</span></div><div className="workspace-line-chart"><svg viewBox="0 0 700 205" role="img" aria-label={text.chartLabel}><defs><linearGradient id="salesArea" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#2463eb" stopOpacity=".22"/><stop offset="100%" stopColor="#2463eb" stopOpacity="0"/></linearGradient></defs>{[42,84,126,168].map(y=><line key={y} x1="36" y1={y} x2="660" y2={y} className="chart-grid-line"/>)}<polygon points={areaPoints} fill="url(#salesArea)"/><polyline points={linePoints} className="chart-sales-line"/>{chartPoints.map(point=><g key={point.date.toISOString()}><circle cx={point.x} cy={point.y} r="5" className="chart-sales-point"/><text x={point.x} y="194" textAnchor="middle" className="chart-label">{shortDay(point.date,locale)}</text></g>)}</svg></div><footer><span><b>{money(sevenDayRevenue,"ILS",locale)}</b><small>{text.sevenRevenue}</small></span><span><b>{sevenDayTickets}</b><small>{text.allOrders}</small></span></footer></article>}{(canReview||canRecovery)&&<article className="workspace-attention-panel"><div className="workspace-panel-head"><div><h2>{text.important}</h2><p>{text.importantHelp}</p></div>{attentionCount>0&&<span className="workspace-count">{attentionCount}</span>}</div>{canRecovery&&<Link href="/office/abandoned" className="workspace-action"><i>🛒</i><div><strong>{abandonedCount} {text.lostCheckouts}</strong><small>{text.potentially} {money(potentialMinor,"ILS",locale)}</small></div><b>›</b></Link>}{canReview&&<Link href="/office/requests" className="workspace-action"><i>✓</i><div><strong>{approvalCount} {text.requests}</strong><small>{text.awaiting}</small></div><b>›</b></Link>}</article>}</section>}
  </AdminShell>;
}
