import { Ionicons } from "@expo/vector-icons";
import { useLocalSearchParams, useRouter } from "expo-router";
import * as SecureStore from "expo-secure-store";
import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Linking, ScrollView, Share, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

const API=(process.env.EXPO_PUBLIC_API_BASE_URL||"https://www.atlas-one.co").replace(/\/$/,"");const TOKEN_KEY="atlas-office-session";
type Category={id:string;name:string;priceMinor:number};type Table={id:string;label:string;seats:number;categoryId:string|null};type Seat={id:string;label:string;position:number;status:string;categoryId:string|null};type MapObject={id:string;label:string;objectType:string;priceMode:string;seats:number;categoryId:string|null;reserved:boolean;seatItems:Seat[]};
type LinkRow={id:string;label:string;code:string;active:boolean;allocation:string;allocationType:"EVENT"|"CATEGORY"|"TABLE"|"SEATS";categoryId:string|null;tableId:string|null;seatIds:string[];customPriceMinor:number|null;priceLabel:string;limit:number;used:number;maxPerOrder:number;showAttendees:boolean;startsAt:string|null;endsAt:string|null;publicUrl:string;manageUrl:string};
type Payload={event:{id:string;title:string};categories:Category[];tables:Table[];mapObjects:MapObject[];links:LinkRow[]};
async function headers(){const token=await SecureStore.getItemAsync(TOKEN_KEY);return{"content-type":"application/json",...(token?{authorization:`Bearer ${token}`}:{})};}
async function request<T>(eventId:string,body?:unknown){const r=await fetch(`${API}/api/mobile/events/${encodeURIComponent(eventId)}/guest-links`,{method:body?"POST":"GET",headers:await headers(),body:body?JSON.stringify(body):undefined});const text=await r.text();let data:any={};try{data=text?JSON.parse(text):{}}catch{}if(!r.ok)throw new Error(data.error||`HTTP_${r.status}`);return data as T;}
const money=(minor:number)=>`${(minor/100).toFixed(2)} ₪`;

export default function GuestLinksScreen(){
 const router=useRouter();const{id}=useLocalSearchParams<{id:string}>();const eventId=String(id||"");const[data,setData]=useState<Payload|null>(null);const[busy,setBusy]=useState("");const[creating,setCreating]=useState(false);const[editing,setEditing]=useState<string|null>(null);
 const[name,setName]=useState("");const[code,setCode]=useState("");const[allocation,setAllocation]=useState<"EVENT"|"CATEGORY"|"TABLE"|"SEATS">("EVENT");const[categoryId,setCategoryId]=useState("");const[tableId,setTableId]=useState("");const[seatIds,setSeatIds]=useState<string[]>([]);const[priceMode,setPriceMode]=useState<"FULL"|"FREE"|"CUSTOM">("FREE");const[customPrice,setCustomPrice]=useState("");const[limit,setLimit]=useState("1");const[maxPerOrder,setMaxPerOrder]=useState("1");const[showAttendees,setShowAttendees]=useState(false);const[startsAt,setStartsAt]=useState("");const[endsAt,setEndsAt]=useState("");
 useEffect(()=>{request<Payload>(eventId).then(setData).catch(e=>Alert.alert("Не удалось загрузить ссылки",e.message));},[eventId]);
 const availableSeats=useMemo(()=>data?.mapObjects.flatMap(o=>o.priceMode==="PER_SEAT"?o.seatItems.filter(s=>s.status==="AVAILABLE").map(s=>({object:o,id:s.id,label:`${o.label} · ${s.label||`место ${s.position}`}`})):[])||[],[data]);
 function reset(){setName("");setCode("");setAllocation("EVENT");setCategoryId("");setTableId("");setSeatIds([]);setPriceMode("FREE");setCustomPrice("");setLimit("1");setMaxPerOrder("1");setShowAttendees(false);setStartsAt("");setEndsAt("");}
 async function run(key:string,body:unknown){setBusy(key);try{const next=await request<Payload>(eventId,body);setData(next);return true}catch(e){Alert.alert("Не удалось выполнить действие",e instanceof Error?e.message:"Ошибка");return false}finally{setBusy("")}}
 async function create(){if(name.trim().length<2)return Alert.alert("Название","Укажите название ссылки.");const actualLimit=allocation==="SEATS"?seatIds.length:Number(limit);if(!actualLimit)return Alert.alert("Лимит","Укажите количество приглашений.");if(allocation==="CATEGORY"&&!categoryId)return Alert.alert("Категория","Выберите категорию.");if(allocation==="TABLE"&&!tableId)return Alert.alert("Стол","Выберите стол.");if(allocation==="SEATS"&&!seatIds.length)return Alert.alert("Места","Выберите хотя бы одно место.");const ok=await run("create",{displayName:name.trim(),code:code.trim()||undefined,allocationType:allocation,categoryId:allocation==="CATEGORY"?categoryId:null,tableId:allocation==="TABLE"?tableId:null,seatIds:allocation==="SEATS"?seatIds:undefined,priceMode,customPriceMinor:priceMode==="CUSTOM"?Math.round(Number(customPrice||0)*100):null,guestLimit:actualLimit,maxPerOrder:allocation==="SEATS"?1:Number(maxPerOrder||1),showAttendees,startsAt:startsAt||null,endsAt:endsAt||null});if(ok){reset();setCreating(false)}}
 if(!data)return <SafeAreaView style={s.center}><ActivityIndicator size="large"/></SafeAreaView>;
 return <SafeAreaView style={s.safe} edges={["top"]}><View style={s.header}><TouchableOpacity style={s.icon} onPress={()=>router.back()}><Ionicons name="chevron-back" size={27} color="#17213C"/></TouchableOpacity><View style={{flex:1}}><Text style={s.headerTitle}>Гостевые ссылки</Text><Text style={s.meta} numberOfLines={1}>{data.event.title}</Text></View><TouchableOpacity style={s.addTop} onPress={()=>setCreating(v=>!v)}><Ionicons name={creating?"close":"add"} size={23} color="#fff"/></TouchableOpacity></View><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
  {creating&&<View style={s.card}><Text style={s.cardTitle}>Новая гостевая ссылка</Text><Field label="Название"><TextInput style={s.input} value={name} onChangeText={setName} placeholder="VIP friends"/></Field><Field label="Короткий код - необязательно"><TextInput style={s.input} value={code} onChangeText={setCode} autoCapitalize="characters" placeholder="VIPFRIENDS"/></Field><Text style={s.label}>Какие билеты доступны</Text><View style={s.chips}>{(["EVENT","CATEGORY","TABLE","SEATS"] as const).map(x=><Chip key={x} label={{EVENT:"Все билеты",CATEGORY:"Категория",TABLE:"Стол",SEATS:"Места"}[x]} selected={allocation===x} onPress={()=>{setAllocation(x);setSeatIds([])}} disabled={(x==="TABLE"&&!data.tables.length)||(x==="SEATS"&&!availableSeats.length)}/>)}</View>{allocation==="CATEGORY"&&<><Text style={s.label}>Категория</Text><View style={s.chips}>{data.categories.map(c=><Chip key={c.id} label={`${c.name} · ${money(c.priceMinor)}`} selected={categoryId===c.id} onPress={()=>setCategoryId(c.id)}/>)}</View></>}{allocation==="TABLE"&&<><Text style={s.label}>Стол</Text><View style={s.chips}>{data.tables.map(t=><Chip key={t.id} label={`${t.label} · ${t.seats}`} selected={tableId===t.id} onPress={()=>setTableId(t.id)}/>)}</View></>}{allocation==="SEATS"&&<><Text style={s.label}>Места</Text><View style={s.seats}>{availableSeats.map(seat=><TouchableOpacity key={seat.id} style={[s.seat,seatIds.includes(seat.id)&&s.seatOn]} onPress={()=>setSeatIds(v=>v.includes(seat.id)?v.filter(x=>x!==seat.id):[...v,seat.id])}><Text style={[s.seatText,seatIds.includes(seat.id)&&s.seatTextOn]}>{seat.label}</Text></TouchableOpacity>)}</View></>}
  <Text style={s.label}>Цена</Text><View style={s.chips}><Chip label="Бесплатно" selected={priceMode==="FREE"} onPress={()=>setPriceMode("FREE")}/><Chip label="Обычная" selected={priceMode==="FULL"} onPress={()=>setPriceMode("FULL")}/><Chip label="Своя" selected={priceMode==="CUSTOM"} onPress={()=>setPriceMode("CUSTOM")}/></View>{priceMode==="CUSTOM"&&<Field label="Цена, ₪"><TextInput style={s.input} keyboardType="decimal-pad" value={customPrice} onChangeText={setCustomPrice}/></Field>}<View style={s.row}><View style={s.half}><Field label="Лимит"><TextInput editable={allocation!=="SEATS"} style={s.input} keyboardType="number-pad" value={allocation==="SEATS"?String(seatIds.length):limit} onChangeText={setLimit}/></Field></View><View style={s.half}><Field label="Макс/регистрация"><TextInput editable={allocation!=="SEATS"} style={s.input} keyboardType="number-pad" value={allocation==="SEATS"?"1":maxPerOrder} onChangeText={setMaxPerOrder}/></Field></View></View><Toggle label="Показывать гостям список участников" value={showAttendees} onChange={setShowAttendees}/><Field label="Активна с - ISO/дата"><TextInput style={s.input} value={startsAt} onChangeText={setStartsAt} placeholder="2026-08-20T20:00:00+03:00"/></Field><Field label="Активна до - ISO/дата"><TextInput style={s.input} value={endsAt} onChangeText={setEndsAt} placeholder="2026-08-21T05:00:00+03:00"/></Field><TouchableOpacity disabled={busy==="create"} style={s.primary} onPress={create}>{busy==="create"?<ActivityIndicator color="#fff"/>:<Text style={s.primaryText}>Создать ссылку</Text>}</TouchableOpacity></View>}
  <View style={s.heading}><Text style={s.title}>Сохранённые ссылки</Text><Text style={s.count}>{data.links.length}</Text></View>{!data.links.length&&<View style={s.empty}><Text style={s.emptyText}>Гостевых ссылок пока нет.</Text></View>}
  {data.links.map(link=><View key={link.id} style={[s.card,!link.active&&{opacity:.62}]}><View style={s.between}><View style={{flex:1}}><Text style={s.cardTitle}>{link.label}</Text><Text style={s.sub}>{link.allocation} · {link.priceLabel}</Text><Text style={s.sub}>{link.used}/{link.limit} зарегистрировано · код {link.code}</Text></View><Switch value={link.active} disabled={!!busy} onValueChange={(active)=>void run(`toggle-${link.id}`,{action:"toggle",linkId:link.id,active})}/></View><View style={s.actions}><Small label="Открыть" onPress={()=>Linking.openURL(link.publicUrl)}/><Small label="Поделиться" onPress={()=>Share.share({message:link.publicUrl})}/><Small label="Управление" onPress={()=>Linking.openURL(link.manageUrl)}/><Small label={editing===link.id?"Закрыть":"Настроить"} onPress={()=>setEditing(editing===link.id?null:link.id)}/></View>{editing===link.id&&<Edit link={link} busy={busy===`save-${link.id}`} onSave={async v=>{const ok=await run(`save-${link.id}`,{action:"update",linkId:link.id,...v});if(ok)setEditing(null)}} onDelete={()=>Alert.alert("Удалить ссылку?",link.label,[{text:"Отмена",style:"cancel"},{text:"Удалить",style:"destructive",onPress:()=>void run(`delete-${link.id}`,{action:"delete",linkId:link.id})}])}/>}</View>)}
 </ScrollView></SafeAreaView>;
}
function Edit({link,busy,onSave,onDelete}:{link:LinkRow;busy:boolean;onSave:(v:any)=>void;onDelete:()=>void}){const[name,setName]=useState(link.label);const[limit,setLimit]=useState(String(link.limit));const[max,setMax]=useState(String(link.maxPerOrder));const[show,setShow]=useState(link.showAttendees);const[start,setStart]=useState(link.startsAt||"");const[end,setEnd]=useState(link.endsAt||"");return <View style={s.edit}><Field label="Название"><TextInput style={s.input} value={name} onChangeText={setName}/></Field><View style={s.row}><View style={s.half}><Field label="Лимит"><TextInput style={s.input} keyboardType="number-pad" value={limit} onChangeText={setLimit}/></Field></View><View style={s.half}><Field label="Макс/регистрация"><TextInput style={s.input} keyboardType="number-pad" value={max} onChangeText={setMax}/></Field></View></View><Toggle label="Показывать участников" value={show} onChange={setShow}/><Field label="Активна с"><TextInput style={s.input} value={start} onChangeText={setStart}/></Field><Field label="Активна до"><TextInput style={s.input} value={end} onChangeText={setEnd}/></Field><View style={s.row}><TouchableOpacity style={s.deleteBtn} onPress={onDelete}><Text style={s.deleteText}>Удалить</Text></TouchableOpacity><TouchableOpacity disabled={busy} style={s.primaryFlex} onPress={()=>onSave({displayName:name.trim(),guestLimit:Number(limit),maxPerOrder:Number(max),showAttendees:show,startsAt:start||null,endsAt:end||null})}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.primaryText}>Сохранить</Text>}</TouchableOpacity></View></View>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <View style={{marginBottom:11}}><Text style={s.label}>{label}</Text>{children}</View>};function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <View style={s.toggle}><Text style={{flex:1,fontWeight:"700",color:"#344054"}}>{label}</Text><Switch value={value} onValueChange={onChange}/></View>};function Chip({label,selected,onPress,disabled=false}:{label:string;selected:boolean;onPress:()=>void;disabled?:boolean}){return <TouchableOpacity disabled={disabled} onPress={onPress} style={[s.chip,selected&&s.chipOn,disabled&&{opacity:.35}]}><Text style={[s.chipText,selected&&s.chipTextOn]}>{label}</Text></TouchableOpacity>};function Small({label,onPress}:{label:string;onPress:()=>void}){return <TouchableOpacity style={s.small} onPress={onPress}><Text style={s.smallText}>{label}</Text></TouchableOpacity>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#F5F6FA"},center:{flex:1,alignItems:"center",justifyContent:"center"},header:{minHeight:70,backgroundColor:"#fff",borderBottomWidth:1,borderBottomColor:"#E5E7ED",paddingHorizontal:10,flexDirection:"row",alignItems:"center",gap:8},icon:{width:42,height:42,alignItems:"center",justifyContent:"center"},headerTitle:{fontSize:18,fontWeight:"900",color:"#17213C"},meta:{fontSize:11,color:"#7B8498",marginTop:2},addTop:{width:42,height:42,borderRadius:13,backgroundColor:"#6D45FF",alignItems:"center",justifyContent:"center"},content:{padding:16,paddingBottom:100},heading:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginVertical:8},title:{fontSize:25,fontWeight:"900",color:"#17213C"},count:{fontWeight:"900",color:"#6D45FF",fontSize:17},card:{backgroundColor:"#fff",borderWidth:1,borderColor:"#E1E4EC",borderRadius:18,padding:15,marginBottom:12},cardTitle:{fontSize:17,fontWeight:"900",color:"#17213C",marginBottom:4},sub:{fontSize:11.5,color:"#7B8498",marginTop:2},between:{flexDirection:"row",alignItems:"flex-start",gap:12},label:{fontSize:12,fontWeight:"800",color:"#5C667B",marginBottom:6},input:{minHeight:45,borderWidth:1,borderColor:"#DDE1EA",borderRadius:12,backgroundColor:"#fff",paddingHorizontal:11,color:"#17213C"},chips:{flexDirection:"row",flexWrap:"wrap",gap:7,marginBottom:12},chip:{borderRadius:18,paddingHorizontal:11,paddingVertical:8,backgroundColor:"#EEF0F5"},chipOn:{backgroundColor:"#EEE9FF",borderWidth:1,borderColor:"#6D45FF"},chipText:{fontSize:11.5,fontWeight:"800",color:"#596378"},chipTextOn:{color:"#5437DD"},seats:{flexDirection:"row",flexWrap:"wrap",gap:6,marginBottom:12},seat:{paddingHorizontal:9,paddingVertical:7,borderRadius:10,backgroundColor:"#EEF0F5"},seatOn:{backgroundColor:"#6D45FF"},seatText:{fontSize:10.5,color:"#596378"},seatTextOn:{color:"#fff",fontWeight:"800"},row:{flexDirection:"row",gap:9},half:{flex:1},toggle:{minHeight:48,flexDirection:"row",alignItems:"center",borderBottomWidth:1,borderBottomColor:"#EEF0F4",marginBottom:10},primary:{minHeight:50,borderRadius:14,backgroundColor:"#6D45FF",alignItems:"center",justifyContent:"center"},primaryFlex:{flex:1,minHeight:48,borderRadius:13,backgroundColor:"#6D45FF",alignItems:"center",justifyContent:"center"},primaryText:{color:"#fff",fontWeight:"900"},actions:{flexDirection:"row",flexWrap:"wrap",gap:7,marginTop:12},small:{paddingHorizontal:10,paddingVertical:8,borderRadius:10,backgroundColor:"#F2F3F7"},smallText:{fontSize:11,fontWeight:"800",color:"#364057"},edit:{marginTop:12,paddingTop:12,borderTopWidth:1,borderTopColor:"#ECEEF3"},deleteBtn:{flex:1,minHeight:48,borderRadius:13,borderWidth:1,borderColor:"#FDA29B",backgroundColor:"#FFFBFA",alignItems:"center",justifyContent:"center"},deleteText:{color:"#B42318",fontWeight:"900"},empty:{backgroundColor:"#fff",borderRadius:16,padding:24,alignItems:"center",marginBottom:12},emptyText:{color:"#8A92A3"}});
