import Link from "next/link";
import {notFound} from "next/navigation";
import {AdminShell} from "@/components/admin-shell";
import {ExternalTicketImportManager} from "@/components/external-ticket-import-manager";
import {requireEventAccess} from "@/lib/auth";
import {db} from "@/lib/db";
import {localeTag,resolveStaffLocale} from "@/lib/i18n";
import {ensureExternalTicketStorage} from "@/lib/external-ticket-storage";
import {ensureExternalCustomerProfileColumns} from "@/lib/external-customer-profiles";
import {ensureOrganizationIntegrationsTable} from "@/lib/organization-integrations";

export const dynamic="force-dynamic";
type SourceRow={id:string;name:string;sourceKey:string;platformKey:string|null;total:number|bigint;used:number|bigint;cancelled:number|bigint;lastImportedAt:Date|string|null;valueCardCreatedTotal:number|bigint;valueCardLastCreated:number|bigint;valueCardLastExisting:number|bigint;valueCardLastSkipped:number|bigint;valueCardLastFailed:number|bigint;valueCardLastSyncedAt:Date|string|null};
type ImportedTicketRow={id:string;externalTicketId:string;externalOrderId:string|null;holderName:string|null;phone:string|null;email:string|null;ticketType:string|null;status:string;firstName:string|null;lastName:string|null;birthDate:Date|string|null;city:string|null;gender:string|null};
type IntegrationRow={enabled:boolean;credentialsEncrypted:string|null};
const copy={
ru:{title:"Внешние продажи",intro:"Atlas Scanner принимает родные и импортированные билеты одним потоком.",back:"Назад к билетам",saved:"Сохранено в Atlas",loaded:"Загруженные билеты",help:(n:number)=>`Это read-only записи. Их импорт не запускает оплату, approve, отправку билетов или рассылки Atlas. Показано ${n} записей.`,first:"Имя",last:"Фамилия",phone:"Телефон",email:"Email",birth:"Дата рождения",city:"Город",gender:"Пол",order:"Заказ",ticket:"Билет / Barcode",status:"Статус",empty:"Импортированных билетов пока нет.",male:"Мужчина",female:"Женщина"},
he:{title:"מכירות חיצוניות",intro:"Atlas Scanner סורק כרטיסים של Atlas וכרטיסים מיובאים באותו תהליך.",back:"חזרה לכרטיסים",saved:"נשמר ב-Atlas",loaded:"כרטיסים שיובאו",help:(n:number)=>`אלו רשומות read-only. הייבוא לא מפעיל תשלום, אישור הזמנה, שליחת כרטיסים או דיוור של Atlas. מוצגות ${n} רשומות.`,first:"שם פרטי",last:"שם משפחה",phone:"טלפון",email:"Email",birth:"תאריך לידה",city:"עיר",gender:"מין",order:"הזמנה",ticket:"כרטיס / Barcode",status:"סטטוס",empty:"עדיין אין כרטיסים מיובאים.",male:"גבר",female:"אישה"},
en:{title:"External sales",intro:"Atlas Scanner handles native and imported tickets in one scanning flow.",back:"Back to tickets",saved:"Stored in Atlas",loaded:"Imported tickets",help:(n:number)=>`These are read-only records. Import does not trigger payment, approval, ticket delivery, or Atlas marketing messages. Showing ${n} records.`,first:"First name",last:"Last name",phone:"Phone",email:"Email",birth:"Birth date",city:"City",gender:"Gender",order:"Order",ticket:"Ticket / Barcode",status:"Status",empty:"No imported tickets yet.",male:"Male",female:"Female"}
} as const;
function genderLabel(value:string|null,t:{male:string;female:string}){if(value==="MALE")return t.male;if(value==="FEMALE")return t.female;return"-";}
function dateLabel(value:Date|string|null,tag:string){if(!value)return"-";const date=new Date(value);if(Number.isNaN(date.getTime()))return String(value);return new Intl.DateTimeFormat(tag,{day:"2-digit",month:"2-digit",year:"numeric",timeZone:"UTC"}).format(date);}
export default async function ExternalTicketsPage({params}:{params:Promise<{id:string}>}){
 const{id:eventId}=await params;const staff=await requireEventAccess("TICKET_MANAGE",eventId);const locale=resolveStaffLocale({memberOverride:staff.interfaceLocaleOverride,userPreference:staff.preferredLocale,organizationDefault:staff.organization?.defaultStaffLocale});const text=copy[locale];const tag=localeTag(locale);await Promise.all([ensureExternalTicketStorage(),ensureOrganizationIntegrationsTable(),ensureExternalCustomerProfileColumns()]);const event=await db.event.findUnique({where:{id:eventId},select:{id:true,title:true,organizationId:true}});if(!event)notFound();
 const[rows,valueCardRows,importedTickets]=await Promise.all([db.$queryRawUnsafe<SourceRow[]>(`SELECT s."id",s."name",s."sourceKey",s."platformKey",s."valueCardCreatedTotal",s."valueCardLastCreated",s."valueCardLastExisting",s."valueCardLastSkipped",s."valueCardLastFailed",s."valueCardLastSyncedAt",(SELECT COUNT(*) FROM "ExternalTicket" t WHERE t."sourceId"=s."id") AS "total",(SELECT COUNT(*) FROM "ExternalTicket" t WHERE t."sourceId"=s."id" AND t."status"='USED') AS "used",(SELECT COUNT(*) FROM "ExternalTicket" t WHERE t."sourceId"=s."id" AND t."status"='CANCELLED') AS "cancelled",(SELECT MAX(b."importedAt") FROM "ExternalTicketImportBatch" b WHERE b."sourceId"=s."id") AS "lastImportedAt" FROM "ExternalTicketSource" s WHERE s."eventId"=$1 ORDER BY s."createdAt" ASC`,eventId),db.$queryRawUnsafe<IntegrationRow[]>(`SELECT "enabled","credentialsEncrypted" FROM "OrganizationIntegration" WHERE "organizationId"=$1 AND "provider"='VALUECARD' LIMIT 1`,event.organizationId),db.$queryRawUnsafe<ImportedTicketRow[]>(`SELECT t."id",t."externalTicketId",t."externalOrderId",t."holderName",t."phone",t."email",t."ticketType",t."status",c."firstName",c."lastName",c."birthDate",c."city",c."gender" FROM "ExternalTicket" t LEFT JOIN "ExternalCustomer" c ON c."id"=t."customerId" WHERE t."eventId"=$1 ORDER BY t."createdAt" DESC, t."externalOrderId" NULLS LAST, t."externalTicketId" LIMIT 250`,eventId)]);
 const sources=rows.map(row=>({id:row.id,name:row.name,sourceKey:row.sourceKey,platformKey:row.platformKey,total:Number(row.total||0),used:Number(row.used||0),cancelled:Number(row.cancelled||0),lastImportedAt:row.lastImportedAt?new Date(row.lastImportedAt).toISOString():null,valueCardCreatedTotal:Number(row.valueCardCreatedTotal||0),valueCardLastCreated:Number(row.valueCardLastCreated||0),valueCardLastExisting:Number(row.valueCardLastExisting||0),valueCardLastSkipped:Number(row.valueCardLastSkipped||0),valueCardLastFailed:Number(row.valueCardLastFailed||0),valueCardLastSyncedAt:row.valueCardLastSyncedAt?new Date(row.valueCardLastSyncedAt).toISOString():null}));const valueCardEnabled=Boolean(valueCardRows[0]?.enabled&&valueCardRows[0]?.credentialsEncrypted);
 return <AdminShell><div className="row between" style={{alignItems:"flex-start",gap:16,flexWrap:"wrap"}}><div><span className="eyebrow">Imported tickets</span><h1>{text.title}</h1><p className="muted">{event.title} · {text.intro}</p></div><Link className="btn secondary" href={`/office/events/${eventId}?tab=tickets`}>{text.back}</Link></div><ExternalTicketImportManager eventId={eventId} sources={sources} valueCardEnabled={valueCardEnabled}/><section className="panel stack" style={{marginTop:18}}><div><span className="eyebrow">{text.saved}</span><h2>{text.loaded}</h2><p className="muted">{text.help(importedTickets.length)}</p></div><div className="table-wrap"><table><thead><tr><th>{text.first}</th><th>{text.last}</th><th>{text.phone}</th><th>{text.email}</th><th>{text.birth}</th><th>{text.city}</th><th>{text.gender}</th><th>{text.order}</th><th>{text.ticket}</th><th>{text.status}</th></tr></thead><tbody>{importedTickets.map(ticket=><tr key={ticket.id}><td>{ticket.firstName||ticket.holderName?.trim().split(/\s+/)[0]||"-"}</td><td>{ticket.lastName||ticket.holderName?.trim().split(/\s+/).slice(1).join(" ")||"-"}</td><td><bdi>{ticket.phone||"-"}</bdi></td><td><bdi>{ticket.email||"-"}</bdi></td><td><bdi>{dateLabel(ticket.birthDate,tag)}</bdi></td><td>{ticket.city||"-"}</td><td>{genderLabel(ticket.gender,text)}</td><td><bdi>{ticket.externalOrderId||"-"}</bdi></td><td><strong><bdi>{ticket.externalTicketId}</bdi></strong></td><td><span className="pill"><bdi>{ticket.status}</bdi></span></td></tr>)}{!importedTickets.length&&<tr><td colSpan={10}>{text.empty}</td></tr>}</tbody></table></div></section></AdminShell>;
}
