import Link from "next/link";
import {revalidatePath} from "next/cache";
import {PlatformShell} from "@/components/platform-shell";
import {ensureDemoOrganizerPlatform,requirePlatformAdmin} from "@/lib/auth";
import {db} from "@/lib/db";
import {eventDate,money} from "@/lib/format";
import {getSearchShowcaseEventIds,SEARCH_SHOWCASE_LIMIT,setSearchShowcaseEvent} from "@/lib/search-showcase";
import {getServerI18n} from "@/lib/server-locale";

export const dynamic="force-dynamic";
async function updateSearchShowcase(formData:FormData){"use server";await requirePlatformAdmin();const eventId=String(formData.get("eventId")??"");const featured=String(formData.get("featured")??"")==="true";if(!eventId)return;await setSearchShowcaseEvent(eventId,featured);revalidatePath("/platform/events");revalidatePath("/");}
const copy={ru:{title:"Все мероприятия",help:"Полный список мероприятий всех организаторов платформы. Здесь же выбираются квадратные карточки для блока «Популярные мероприятия» в поиске.",search:"В ПОИСКЕ",event:"Мероприятие",organizer:"Организатор",dateVenue:"Дата и площадка",status:"Статус",sales:"Продажи",featured:"Популярное в поиске",remove:"Убрать из популярных",full:"Выбрано 8 из 8",add:"Добавить в популярные",open:"Открыть сайт"},he:{title:"כל האירועים",help:"רשימת כל האירועים של כל המפיקים בפלטפורמה. כאן גם בוחרים את הכרטיסים המרובעים שמופיעים באזור האירועים הפופולריים בחיפוש.",search:"בחיפוש",event:"אירוע",organizer:"מפיק",dateVenue:"תאריך ומקום",status:"סטטוס",sales:"מכירות",featured:"פופולרי בחיפוש",remove:"הסרה מהפופולריים",full:"נבחרו 8 מתוך 8",add:"הוספה לפופולריים",open:"פתיחת האתר"},en:{title:"All events",help:"A complete list of events across all organizers. This is also where the square cards shown in the Popular Events search section are selected.",search:"IN SEARCH",event:"Event",organizer:"Organizer",dateVenue:"Date and venue",status:"Status",sales:"Sales",featured:"Popular in search",remove:"Remove from popular",full:"8 of 8 selected",add:"Add to popular",open:"Open site"}} as const;
export default async function PlatformEvents(){await ensureDemoOrganizerPlatform();const[{locale},events,featuredEventIds]=await Promise.all([getServerI18n(),db.event.findMany({include:{organization:true,venue:true,categories:true,orders:{where:{status:"PAID"},select:{totalMinor:true}}},orderBy:{startsAt:"desc"}}),getSearchShowcaseEventIds()]);const t=copy[locale];const featuredSet=new Set(featuredEventIds);const showcaseFull=featuredEventIds.length>=SEARCH_SHOWCASE_LIMIT;return <PlatformShell><div className="platform-heading"><div><span className="eyebrow">Atlas Platform Admin</span><h1>{t.title}</h1><p>{t.help}</p></div><span className="platform-admin-badge">{t.search} {featuredEventIds.length}/{SEARCH_SHOWCASE_LIMIT}</span></div><div className="table-wrap"><table><thead><tr><th>{t.event}</th><th>{t.organizer}</th><th>{t.dateVenue}</th><th>{t.status}</th><th>{t.sales}</th><th>{t.featured}</th><th></th></tr></thead><tbody>{events.map(event=>{const revenue=event.orders.reduce((sum,order)=>sum+order.totalMinor,0);const featured=featuredSet.has(event.id);const cannotAdd=event.status!=="PUBLISHED"||(!featured&&showcaseFull);return <tr key={event.id}><td><strong>{event.title}</strong><br/><small dir="ltr"><bdi>/{event.slug}</bdi></small></td><td><Link href={`/platform/organizers/${event.organizationId}`}>{event.organization.name}</Link></td><td><bdi>{eventDate(event.startsAt,locale)}</bdi><br/><small>{event.venue.name}, {event.venue.city}</small></td><td><span className="pill"><bdi>{event.status}</bdi></span></td><td><bdi>{money(revenue,"ILS",locale)}</bdi></td><td><form action={updateSearchShowcase}><input type="hidden" name="eventId" value={event.id}/><input type="hidden" name="featured" value={featured?"false":"true"}/><button className={featured?"btn":"btn secondary"} type="submit" disabled={cannotAdd}>{featured?t.remove:showcaseFull?t.full:t.add}</button></form></td><td>{event.status==="PUBLISHED"&&<Link className="btn secondary" href={`/events/${event.slug}`} target="_blank">{t.open}</Link>}</td></tr>})}</tbody></table></div></PlatformShell>}
