import { randomUUID } from "node:crypto";
import { after, NextResponse } from "next/server";
import { z } from "zod";
import { db } from "@/lib/db";
import { getGuestLinkSettings, isGuestListPromoter, verifyGuestManagementToken } from "@/lib/guest-links";
import { orderNumber, ticketCode } from "@/lib/ticketing";
import { guestFieldKeys, parseGuestFields } from "@/lib/event-guest-fields";
import { sendOrderTicketEmail } from "@/lib/order-email";
import { sendApprovalRequestReceivedEmail } from "@/lib/order-status-email";
import { saveCustomerDemographics } from "@/lib/customer-demographics";
import { assertInventoryAvailable, createReservation, releaseReservation } from "@/lib/reservation";
import { normalizeLocale, type Locale } from "@/lib/i18n";

const addSchema=z.object({action:z.literal("add"),customer:z.record(z.string(),z.string().max(250))});
const removeSchema=z.object({action:z.literal("remove"),token:z.string().min(10),orderId:z.string().min(1)});
const visitSchema=z.object({action:z.literal("visit"),sessionId:z.string().min(8).max(100)});
function normalizePhone(value:string){const digits=value.replace(/\D/g,"");if(!digits)return "";if(digits.startsWith("972"))return `+${digits}`;if(digits.startsWith("0"))return `+972${digits.slice(1)}`;return `+972${digits}`;}

const copy={
 ru:{unavailable:"Гостевой список не найден или сейчас недоступен",required:"Заполните все обязательные поля",email:"Укажите корректный email для отправки билета",limit:"Лимит гостей исчерпан",seats:"Выбранные для этой ссылки места закончились",category:"Для списка нет доступной категории билета",seatTaken:"Это место только что занял другой покупатель",tickets:"Бесплатные билеты закончились",token:"Ссылка управления недействительна",guest:"Гость не найден",used:"Нельзя удалить гостя после прохода",action:"Неизвестное действие",failed:"Не удалось выполнить действие"},
 he:{unavailable:"רשימת האורחים לא נמצאה או שאינה זמינה כרגע",required:"יש למלא את כל שדות החובה",email:"יש להזין כתובת Email תקינה לשליחת הכרטיס",limit:"מכסת האורחים מלאה",seats:"המקומות שהוקצו לקישור הזה אזלו",category:"אין קטגוריית כרטיס זמינה לרשימה הזו",seatTaken:"המקום הזה נתפס כרגע על ידי רוכש אחר",tickets:"הכרטיסים החינמיים אזלו",token:"קישור הניהול אינו תקף",guest:"האורח לא נמצא",used:"לא ניתן להסיר אורח לאחר הכניסה",action:"פעולה לא מוכרת",failed:"לא ניתן להשלים את הפעולה"},
 en:{unavailable:"The guest list was not found or is currently unavailable",required:"Complete all required fields",email:"Enter a valid email address for ticket delivery",limit:"The guest limit has been reached",seats:"The seats assigned to this link are no longer available",category:"No ticket category is available for this guest list",seatTaken:"Another buyer has just taken this seat",tickets:"Free tickets are sold out",token:"The management link is invalid",guest:"Guest not found",used:"A guest cannot be removed after check-in",action:"Unknown action",failed:"Could not complete the action"}
} as const;
type ErrorKey=keyof typeof copy.ru;
function fail(key:ErrorKey):never{throw new Error(`GUEST_${key.toUpperCase()}`)}
function localizedError(error:unknown,locale:Locale){const raw=error instanceof Error?error.message:"";const prefix="GUEST_";if(raw.startsWith(prefix)){const key=raw.slice(prefix.length).toLowerCase() as ErrorKey;if(key in copy[locale])return copy[locale][key];}return copy[locale].failed;}

export async function POST(req:Request,{params}:{params:Promise<{code:string}>}){
 let responseLocale:Locale="ru";
 try{
  const {code}=await params;const body=await req.json();responseLocale=normalizeLocale(body?.locale);
  const link=await db.promoterLink.findUnique({where:{code:code.toUpperCase()},include:{promoter:true,event:{include:{categories:true}},category:true,table:{include:{category:true}},orders:{where:{status:{notIn:["CANCELLED","REJECTED"]}},include:{items:true,tickets:true}}}});
  const now=new Date();if(!link||!link.active||!isGuestListPromoter(link.promoter.name)||(link.startsAt&&link.startsAt>now)||(link.endsAt&&link.endsAt<now))fail("unavailable");
  responseLocale=normalizeLocale(link.event.customerCommunicationLocale);
  if(body.action==="visit"){const input=visitSchema.parse(body);await db.promoterLinkVisit.upsert({where:{linkId_sessionId:{linkId:link.id,sessionId:input.sessionId}},update:{},create:{linkId:link.id,sessionId:input.sessionId,userAgent:req.headers.get("user-agent")}});return NextResponse.json({ok:true});}
  if(body.action==="add"){
   const input=addSchema.parse(body);const settings=await getGuestLinkSettings(link.id);const fields=parseGuestFields(link.event.description);const customer=input.customer;for(const key of guestFieldKeys)if(fields[key].visible&&fields[key].required&&!String(customer[key]||"").trim())fail("required");
   const gender=z.enum(["MALE","FEMALE"]).parse(customer.gender);const email=String(customer.email||"").trim().toLowerCase();if(!z.string().email().safeParse(email).success)fail("email");
   const firstName=(customer.firstName||"").trim();const lastName=(customer.lastName||"").trim();const fullName=`${firstName} ${lastName}`.trim();const phone=normalizePhone(customer.phone||"");const profilePhone=phone||`guest:${randomUUID()}`;const birthDate=customer.birthDate?new Date(customer.birthDate):new Date("1900-01-01T00:00:00.000Z");const requiresApproval=link.event.salesMode==="APPROVAL_REQUIRED";const communicationLocale=responseLocale;
   const order=await db.$transaction(async tx=>{
    await tx.$queryRawUnsafe(`SELECT "id" FROM "PromoterLink" WHERE "id"=$1 FOR UPDATE`,link.id);const fresh=await tx.promoterLink.findUnique({where:{id:link.id},select:{active:true,startsAt:true,endsAt:true,guestLimit:true}});const txNow=new Date();if(!fresh||!fresh.active||(fresh.startsAt&&fresh.startsAt>txNow)||(fresh.endsAt&&fresh.endsAt<txNow))fail("unavailable");
    const activeOrders=await tx.order.findMany({where:{promoterLinkId:link.id,status:{notIn:["CANCELLED","REJECTED"]}},select:{items:{select:{quantity:true,seatId:true}}}});const used=activeOrders.flatMap(item=>item.items).reduce((sum,item)=>sum+item.quantity,0);const limit=fresh.guestLimit??link.table?.seats??link.category?.capacity??link.event.categories[0]?.capacity??0;if(used>=limit)fail("limit");
    let selectedSeat:null|{id:string;tableId:string;categoryId:string}=null;let category=link.category??link.table?.category??link.event.categories.find(item=>!item.hidden&&item.sold<item.capacity)??null;
    if(settings.seatIds.length){
      const assigned=new Set(activeOrders.flatMap(order=>order.items.map(item=>item.seatId).filter((id):id is string=>Boolean(id))));const seats=await tx.seat.findMany({where:{id:{in:settings.seatIds},status:"AVAILABLE"},include:{table:true},orderBy:{position:"asc"}});const claims=await tx.$queryRawUnsafe<Array<{seatId:string|null}>>(`SELECT "seatId" FROM "ReservationClaim" WHERE "seatId" = ANY($1::text[])`,settings.seatIds).catch(()=>[]);const claimed=new Set(claims.map(item=>item.seatId).filter((id):id is string=>Boolean(id)));const candidate=seats.find(seat=>!assigned.has(seat.id)&&!claimed.has(seat.id)&&Boolean(seat.categoryId??seat.table.categoryId));if(!candidate)fail("seats");const categoryId=(candidate.categoryId??candidate.table.categoryId)!;category=link.event.categories.find(item=>item.id===categoryId)??null;if(!category)fail("category");selectedSeat={id:candidate.id,tableId:candidate.tableId,categoryId};
    }
    if(!category)fail("category");
    if(requiresApproval){const latestCategory=await tx.ticketCategory.findUnique({where:{id:category.id},select:{sold:true,capacity:true,name:true}});if(!latestCategory)fail("category");const reservationItems=[{categoryId:category.id,quantity:1,seatId:selectedSeat?.id??null,tableId:null}];await assertInventoryAvailable({items:reservationItems,capacities:new Map([[category.id,{sold:latestCategory.sold,capacity:latestCategory.capacity,name:latestCategory.name}]]),executor:tx});
      const guest=await tx.guestProfile.upsert({where:{organizationId_phone:{organizationId:link.event.organizationId,phone:profilePhone}},create:{organizationId:link.event.organizationId,firstName,lastName,phone:profilePhone,email,birthDate,city:customer.city||"",facebook:customer.facebook||"",instagram:customer.instagram||""},update:{firstName,lastName,email,birthDate,city:customer.city||"",facebook:customer.facebook||"",instagram:customer.instagram||""}});const created=await tx.order.create({data:{publicId:orderNumber(),idempotencyKey:randomUUID(),customerName:fullName,customerFirstName:firstName,customerLastName:lastName,customerPhone:phone,customerEmail:email,customerBirthDate:customer.birthDate?birthDate:null,customerCity:customer.city||null,customerFacebook:customer.facebook||null,customerInstagram:customer.instagram||null,guestId:guest.id,totalMinor:0,currency:category.currency,status:"PENDING_APPROVAL",salesFlow:"APPROVAL",communicationLocale,eventId:link.eventId,promoterLinkId:link.id,items:{create:[{quantity:1,unitPriceMinor:0,categoryName:category.name,tableId:selectedSeat?.tableId??null,seatId:selectedSeat?.id??null}]}},include:{tickets:true}});await createReservation({orderId:created.id,items:reservationItems,ttlMinutes:24*60,executor:tx});return created;
    }
    if(selectedSeat){const claimedSeat=await tx.seat.updateMany({where:{id:selectedSeat.id,status:"AVAILABLE"},data:{status:"RESERVED"}});if(claimedSeat.count!==1)fail("seatTaken");}
    const capacityClaim=await tx.ticketCategory.updateMany({where:{id:category.id,sold:{lt:category.capacity}},data:{sold:{increment:1}}});if(capacityClaim.count!==1)fail("tickets");const guest=await tx.guestProfile.upsert({where:{organizationId_phone:{organizationId:link.event.organizationId,phone:profilePhone}},create:{organizationId:link.event.organizationId,firstName,lastName,phone:profilePhone,email,birthDate,city:customer.city||"",facebook:customer.facebook||"",instagram:customer.instagram||""},update:{firstName,lastName,email,birthDate,city:customer.city||"",facebook:customer.facebook||"",instagram:customer.instagram||""}});return tx.order.create({data:{publicId:orderNumber(),idempotencyKey:randomUUID(),customerName:fullName,customerFirstName:firstName,customerLastName:lastName,customerPhone:phone,customerEmail:email,customerBirthDate:customer.birthDate?birthDate:null,customerCity:customer.city||null,customerFacebook:customer.facebook||null,customerInstagram:customer.instagram||null,guestId:guest.id,totalMinor:0,currency:category.currency,status:"PAID",salesFlow:"DIRECT",communicationLocale,eventId:link.eventId,promoterLinkId:link.id,items:{create:[{quantity:1,unitPriceMinor:0,categoryName:category.name,tableId:selectedSeat?.tableId??null,seatId:selectedSeat?.id??null}]},tickets:{create:[{publicCode:ticketCode(),holderName:fullName,categoryId:category.id}]}},include:{tickets:true}});
   });
   await saveCustomerDemographics({orderId:order.id,guestId:order.guestId,gender,birthDate:customer.birthDate?birthDate:null});after(async()=>{try{if(requiresApproval){await sendApprovalRequestReceivedEmail(order.publicId);console.info("[guest-approval-email] sent",{orderId:order.publicId,recipient:email});}else{const delivery=await sendOrderTicketEmail(order.publicId);console.info("[guest-ticket-email] sent",{orderId:order.publicId,recipient:email,resendId:delivery.id});}}catch(error){const message=error instanceof Error?error.message:"EMAIL_DELIVERY_FAILED";console.error(requiresApproval?"[guest-approval-email] failed":"[guest-ticket-email] failed",{orderId:order.publicId,recipient:email,message});}});return NextResponse.json({ok:true,orderId:order.id,publicId:order.publicId,status:order.status,emailQueued:true},{status:201});
  }
  if(body.action==="remove"){
   if(!verifyGuestManagementToken(link.id,String(body.token||"")))fail("token");const input=removeSchema.parse(body);const order=link.orders.find(item=>item.id===input.orderId);if(!order)fail("guest");if(order.tickets.some(ticket=>ticket.status==="USED"))fail("used");const quantity=order.items.reduce((sum,item)=>sum+item.quantity,0);const seatIds=order.items.map(item=>item.seatId).filter((id):id is string=>Boolean(id));const categoryId=order.tickets[0]?.categoryId;await db.$transaction(async tx=>{await releaseReservation(order.id,tx);await tx.ticket.updateMany({where:{orderId:order.id},data:{status:"CANCELLED"}});await tx.order.update({where:{id:order.id},data:{status:"CANCELLED"}});if(categoryId)await tx.ticketCategory.updateMany({where:{id:categoryId,sold:{gte:quantity}},data:{sold:{decrement:quantity}}});if(seatIds.length)await tx.seat.updateMany({where:{id:{in:seatIds},status:"RESERVED"},data:{status:"AVAILABLE"}});});return NextResponse.json({ok:true});
  }
  fail("action");
 }catch(error){const message=localizedError(error,responseLocale);console.error("[guest-list-api]",{message:error instanceof Error?error.message:"UNKNOWN"});return NextResponse.json({error:message},{status:400});}
}
