"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { useLocale } from "@/components/locale-provider";
import { localeTag } from "@/lib/i18n";

const copy={
ru:{saveError:"Не удалось сохранить решение",emailSent:" Клиенту отправлен email об отмене и возврате.",emailFailed:" Возврат выполнен, но email не отправлен:",refundOk:"HYP подтвердил возврат",ticketsCancelled:"Билеты и QR-коды отменены.",rejectedSent:"Заявка отклонена. Клиенту отправлен email с решением.",rejectedFailed:"Заявка отклонена, но email не отправлен:",rejected:"Заявка отклонена.",eyebrow:"Решение организатора",title:"Выберите сумму возврата",help:"Atlas считает стандартное удержание как 5% стоимости заказа или 100 ₪, что меньше.",standard:"Вернуть",standardHelp:"Стандартный сценарий.",held:"удерживаются из суммы клиента.",full:"Вернуть полные",fullHelp:"Клиент получает всю сумму. Комиссию",organizerPays:"берёт на себя организатор.",custom:"Другая сумма",customHelp:"Для добровольного возврата по решению организатора.",note:"Комментарий к решению, необязательно",notePh:"Комментарий клиенту",orderAmount:"Сумма заказа",refund:"Возврат клиенту",customerHold:"Удержание из клиента",organizerFee:"Комиссия за счёт организатора",locked:"По этой заявке решение уже принято. Текущий статус:",processing:"Возвращаем через HYP...",approve:"Одобрить и вернуть деньги",reject:"Отклонить",after:"После одобрения Atlas сразу отправит возврат в HYP. Только после успешного ответа HYP заказ и QR-коды будут отменены, места вернутся в продажу, а клиент получит email с фактической суммой возврата."},
he:{saveError:"לא הצלחנו לשמור את ההחלטה",emailSent:" נשלח ללקוח מייל על הביטול וההחזר.",emailFailed:" ההחזר בוצע, אך המייל לא נשלח:",refundOk:"HYP אישרה החזר",ticketsCancelled:"הכרטיסים וקודי ה־QR בוטלו.",rejectedSent:"הבקשה נדחתה. נשלח ללקוח מייל עם ההחלטה.",rejectedFailed:"הבקשה נדחתה, אך המייל לא נשלח:",rejected:"הבקשה נדחתה.",eyebrow:"החלטת המפיק",title:"בחירת סכום ההחזר",help:"Atlas מחשבת את דמי הביטול הסטנדרטיים כ־5% מערך ההזמנה או 100 ₪, הנמוך מביניהם.",standard:"החזר",standardHelp:"המסלול הסטנדרטי.",held:"ינוכו מסכום הלקוח.",full:"החזר מלא",fullHelp:"הלקוח מקבל את מלוא הסכום. עמלה של",organizerPays:"תחול על המפיק.",custom:"סכום אחר",customHelp:"להחזר וולונטרי לפי החלטת המפיק.",note:"הערה להחלטה, לא חובה",notePh:"הערה ללקוח",orderAmount:"סכום ההזמנה",refund:"החזר ללקוח",customerHold:"ניכוי מהלקוח",organizerFee:"עמלה על חשבון המפיק",locked:"כבר התקבלה החלטה בבקשה הזו. הסטטוס הנוכחי:",processing:"מבצעים החזר דרך HYP...",approve:"אישור והחזר כספי",reject:"דחייה",after:"לאחר האישור Atlas תשלח מיד את ההחזר ל־HYP. רק לאחר תשובה מוצלחת הכרטיסים וקודי ה־QR יבוטלו, המקומות יחזרו למכירה והלקוח יקבל מייל עם סכום ההחזר בפועל."},
en:{saveError:"Could not save the decision",emailSent:" The customer was emailed about the cancellation and refund.",emailFailed:" The refund succeeded, but the email was not sent:",refundOk:"HYP confirmed a refund of",ticketsCancelled:"Tickets and QR codes were cancelled.",rejectedSent:"Request rejected. The customer was emailed the decision.",rejectedFailed:"Request rejected, but the email was not sent:",rejected:"Request rejected.",eyebrow:"Organizer decision",title:"Choose refund amount",help:"Atlas calculates the standard cancellation deduction as 5% of the order value or ₪100, whichever is lower.",standard:"Refund",standardHelp:"Standard scenario.",held:"is deducted from the customer's amount.",full:"Refund full",fullHelp:"The customer receives the full amount. The",organizerPays:"fee is paid by the organizer.",custom:"Custom amount",customHelp:"For a voluntary refund at the organizer's discretion.",note:"Decision note, optional",notePh:"Comment for customer",orderAmount:"Order amount",refund:"Customer refund",customerHold:"Customer deduction",organizerFee:"Organizer-paid fee",locked:"A decision has already been made on this request. Current status:",processing:"Refunding through HYP...",approve:"Approve and refund",reject:"Reject",after:"After approval, Atlas immediately sends the refund to HYP. Only after a successful HYP response are the order and QR codes cancelled, seats returned to sale, and the customer emailed the actual refund amount."}
} as const;

export function CancellationReviewPrototype({id,orderAmountMinor,statutoryFeeMinor,status}:{id:string;orderAmountMinor:number;statutoryFeeMinor:number;status:string}){
  const {locale}=useLocale();const text=copy[locale];const router=useRouter();const orderAmount=orderAmountMinor/100;const statutoryFee=statutoryFeeMinor/100;const [mode,setMode]=useState<"standard"|"full"|"custom">("standard");const [custom,setCustom]=useState(Math.max(0,orderAmount-statutoryFee));const [note,setNote]=useState("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const refund=useMemo(()=>mode==="standard"?orderAmount-statutoryFee:mode==="full"?orderAmount:Math.max(0,Math.min(orderAmount,custom)),[mode,custom,orderAmount,statutoryFee]);const organizerCharge=Math.max(0,refund-(orderAmount-statutoryFee));const locked=status!=="NEW";
  const money=(value:number)=>value.toLocaleString(localeTag(locale),{minimumFractionDigits:2,maximumFractionDigits:2})+" ₪";
  async function decide(action:"APPROVE"|"REJECT"){setBusy(true);setMessage("");try{const response=await fetch(`/api/office/cancellations/${id}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,refundAmountMinor:Math.round(refund*100),note})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||text.saveError);if(action==="APPROVE"){const emailText=body.refund?.emailSent?text.emailSent:body.refund?.emailError?` ${text.emailFailed} ${body.refund.emailError}`:"";setMessage(`${text.refundOk} ${money(body.refundAmountMinor/100)}. ${text.ticketsCancelled}${emailText}`);}else{setMessage(body.emailSent?text.rejectedSent:body.emailError?`${text.rejectedFailed} ${body.emailError}`:text.rejected);}router.refresh();}catch(error){setMessage(error instanceof Error?error.message:text.saveError);}finally{setBusy(false);}}
  return <div className="stack"><section className="panel stack"><div><span className="eyebrow">{text.eyebrow}</span><h2 style={{marginBottom:6}}>{text.title}</h2><p className="muted">{text.help}</p></div>
    <label className="panel" style={{display:"flex",gap:12,alignItems:"flex-start",cursor:locked?"default":"pointer",borderColor:mode==="standard"?"#111827":undefined}}><input disabled={locked} type="radio" checked={mode==="standard"} onChange={()=>setMode("standard")}/><div><strong>{text.standard} <bdi>{money(orderAmount-statutoryFee)}</bdi></strong><div className="muted">{text.standardHelp} <bdi>{money(statutoryFee)}</bdi> {text.held}</div></div></label>
    <label className="panel" style={{display:"flex",gap:12,alignItems:"flex-start",cursor:locked?"default":"pointer",borderColor:mode==="full"?"#111827":undefined}}><input disabled={locked} type="radio" checked={mode==="full"} onChange={()=>setMode("full")}/><div><strong>{text.full} <bdi>{money(orderAmount)}</bdi></strong><div className="muted">{text.fullHelp} <bdi>{money(statutoryFee)}</bdi> {text.organizerPays}</div></div></label>
    <label className="panel" style={{display:"flex",gap:12,alignItems:"flex-start",cursor:locked?"default":"pointer",borderColor:mode==="custom"?"#111827":undefined}}><input disabled={locked} type="radio" checked={mode==="custom"} onChange={()=>setMode("custom")}/><div style={{flex:1}}><strong>{text.custom}</strong><div className="muted" style={{marginBottom:8}}>{text.customHelp}</div>{mode==="custom"&&<input dir="ltr" style={{textAlign:"left"}} disabled={locked} className="input" type="number" min={0.01} max={orderAmount} step="0.01" value={custom} onChange={e=>setCustom(Number(e.target.value))}/>}</div></label>
    <div className="field"><label>{text.note}</label><textarea disabled={locked} rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder={text.notePh}/></div></section>
    <section className="panel stack"><div className="row between"><span className="muted">{text.orderAmount}</span><strong><bdi>{money(orderAmount)}</bdi></strong></div><div className="row between"><span className="muted">{text.refund}</span><strong><bdi>{money(refund)}</bdi></strong></div><div className="row between"><span className="muted">{text.customerHold}</span><strong><bdi>{money(Math.max(0,orderAmount-refund))}</bdi></strong></div><div className="row between"><span className="muted">{text.organizerFee}</span><strong><bdi>{money(organizerCharge)}</bdi></strong></div><hr style={{border:0,borderTop:"1px solid #e5e7eb"}}/>{locked?<div className="toast">{text.locked} <bdi>{status}</bdi>.</div>:<div className="row" style={{gap:10,flexWrap:"wrap"}}><button className="btn dark" disabled={busy} type="button" onClick={()=>void decide("APPROVE")}>{busy?text.processing:text.approve}</button><button className="btn secondary" disabled={busy} type="button" onClick={()=>void decide("REJECT")}>{text.reject}</button></div>}{message&&<div className="toast">{message}</div>}{!locked&&<p className="muted" style={{fontSize:12,marginBottom:0}}>{text.after}</p>}</section></div>;
}
