"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { eventDate, money } from "@/lib/format";
import { useLocale } from "@/components/locale-provider";
import { israelCities } from "@/lib/israel-cities";
import type { GuestFieldConfig, GuestFieldKey } from "@/lib/event-guest-fields";
import type { Locale } from "@/lib/i18n";
import styles from "./checkout-form.module.css";

const CART_STORAGE_KEY="atlas-persistent-cart-v2";
const copy={
 ru:{checkout:"Оформление заказа",contact:"Контактные данные",fullName:"Полное имя",email:"Email",country:"Страна",phone:"Телефон",payment:"Способ оплаты",secure:"Защищённая оплата HYP",paymentLoading:"Загружаем доступные способы оплаты…",paymentWaiting:"Введите имя, фамилию, email и телефон - оплата появится автоматически.",promo:"Промокод",promoPlaceholder:"Например, ATLAS10",total:"Итого",serviceFee:"Сервисный сбор",gender:"Пол",male:"Мужчина",female:"Женщина",preferNot:"Предпочитаю не указывать",other:"Другое",chooseGender:"Выберите пол",error:"Не удалось подготовить оплату",expired:"Время истекло",expiredBody:"Срок удержания билетов истёк. Попробовать зарезервировать выбранные билеты снова?",rehold:"Удержать билеты снова",cancel:"Отмена",close:"Закрыть",choose:"Выбрать",detailsError:"Не удалось сохранить дополнительные данные.",phoneError:"Проверьте номер телефона"},
 he:{checkout:"תשלום",contact:"פרטי קשר",fullName:"שם מלא",email:"Email",country:"מדינה",phone:"טלפון",payment:"אמצעי תשלום",secure:"תשלום מאובטח HYP",paymentLoading:"טוענים אמצעי תשלום זמינים…",paymentWaiting:"הזינו שם פרטי, שם משפחה, Email וטלפון - התשלום יופיע אוטומטית.",promo:"קוד הטבה",promoPlaceholder:"לדוגמה ATLAS10",total:"סה״כ",serviceFee:"עמלת שירות",gender:"מגדר",male:"זכר",female:"נקבה",preferNot:"מעדיף/ה לא לציין",other:"אחר",chooseGender:"בחרו מגדר",error:"לא ניתן להכין את התשלום",expired:"הזמן הסתיים",expiredBody:"זמן שמירת הכרטיסים הסתיים. לנסות לשמור את הכרטיסים שבחרתם שוב?",rehold:"שמירת הכרטיסים מחדש",cancel:"ביטול",close:"סגירה",choose:"בחירה",detailsError:"לא ניתן לשמור את הפרטים הנוספים.",phoneError:"יש להזין מספר טלפון תקין"},
 en:{checkout:"Checkout",contact:"Contact details",fullName:"Full name",email:"Email address",country:"Country",phone:"Phone number",payment:"Payment method",secure:"Secure HYP payment",paymentLoading:"Loading available payment methods…",paymentWaiting:"Enter your first name, last name, email and phone - payment will appear automatically.",promo:"Promo code",promoPlaceholder:"For example, ATLAS10",total:"Total",serviceFee:"Service fee",gender:"Gender",male:"Male",female:"Female",preferNot:"Prefer not to say",other:"Other",chooseGender:"Select gender",error:"Could not prepare payment",expired:"Timer expired",expiredBody:"Your ticket hold has expired. Would you like to try reserving the selected tickets again?",rehold:"Re-hold my tickets",cancel:"Cancel",close:"Close",choose:"Choose",detailsError:"Could not save the additional details.",phoneError:"Enter a valid phone number"}
} as const;
const labels:Record<GuestFieldKey,Record<Locale,string>>={firstName:{ru:"Имя",he:"שם פרטי",en:"First name"},lastName:{ru:"Фамилия",he:"שם משפחה",en:"Last name"},phone:{ru:"Телефон",he:"טלפון",en:"Phone"},email:{ru:"Email",he:"Email",en:"Email"},birthDate:{ru:"Дата рождения",he:"תאריך לידה",en:"Date of birth"},city:{ru:"Город проживания",he:"עיר מגורים",en:"City"},facebook:{ru:"Facebook",he:"Facebook",en:"Facebook"},instagram:{ru:"Instagram",he:"Instagram",en:"Instagram"}};
const months={ru:["Январь","Февраль","Март","Апрель","Май","Июнь","Июль","Август","Сентябрь","Октябрь","Ноябрь","Декабрь"],he:["ינואר","פברואר","מרץ","אפריל","מאי","יוני","יולי","אוגוסט","ספטמבר","אוקטובר","נובמבר","דצמבר"],en:["January","February","March","April","May","June","July","August","September","October","November","December"]} as const;
const countries=[
 {iso:"IL",flag:"🇮🇱",name:"Israel",dial:"+972"},{iso:"US",flag:"🇺🇸",name:"United States",dial:"+1"},{iso:"CA",flag:"🇨🇦",name:"Canada",dial:"+1"},{iso:"GB",flag:"🇬🇧",name:"United Kingdom",dial:"+44"},{iso:"DE",flag:"🇩🇪",name:"Germany",dial:"+49"},{iso:"FR",flag:"🇫🇷",name:"France",dial:"+33"},{iso:"IT",flag:"🇮🇹",name:"Italy",dial:"+39"},{iso:"ES",flag:"🇪🇸",name:"Spain",dial:"+34"},{iso:"PT",flag:"🇵🇹",name:"Portugal",dial:"+351"},{iso:"NL",flag:"🇳🇱",name:"Netherlands",dial:"+31"},{iso:"BE",flag:"🇧🇪",name:"Belgium",dial:"+32"},{iso:"CH",flag:"🇨🇭",name:"Switzerland",dial:"+41"},{iso:"AT",flag:"🇦🇹",name:"Austria",dial:"+43"},{iso:"PL",flag:"🇵🇱",name:"Poland",dial:"+48"},{iso:"CZ",flag:"🇨🇿",name:"Czechia",dial:"+420"},{iso:"HU",flag:"🇭🇺",name:"Hungary",dial:"+36"},{iso:"RO",flag:"🇷🇴",name:"Romania",dial:"+40"},{iso:"GR",flag:"🇬🇷",name:"Greece",dial:"+30"},{iso:"CY",flag:"🇨🇾",name:"Cyprus",dial:"+357"},{iso:"UA",flag:"🇺🇦",name:"Ukraine",dial:"+380"},{iso:"RU",flag:"🇷🇺",name:"Russia",dial:"+7"},{iso:"GE",flag:"🇬🇪",name:"Georgia",dial:"+995"},{iso:"AM",flag:"🇦🇲",name:"Armenia",dial:"+374"},{iso:"AZ",flag:"🇦🇿",name:"Azerbaijan",dial:"+994"},{iso:"TR",flag:"🇹🇷",name:"Turkey",dial:"+90"},{iso:"AE",flag:"🇦🇪",name:"United Arab Emirates",dial:"+971"},{iso:"IN",flag:"🇮🇳",name:"India",dial:"+91"},{iso:"CN",flag:"🇨🇳",name:"China",dial:"+86"},{iso:"HK",flag:"🇭🇰",name:"Hong Kong",dial:"+852"},{iso:"JP",flag:"🇯🇵",name:"Japan",dial:"+81"},{iso:"KR",flag:"🇰🇷",name:"South Korea",dial:"+82"},{iso:"TH",flag:"🇹🇭",name:"Thailand",dial:"+66"},{iso:"AU",flag:"🇦🇺",name:"Australia",dial:"+61"},{iso:"NZ",flag:"🇳🇿",name:"New Zealand",dial:"+64"},{iso:"BR",flag:"🇧🇷",name:"Brazil",dial:"+55"},{iso:"AR",flag:"🇦🇷",name:"Argentina",dial:"+54"},{iso:"MX",flag:"🇲🇽",name:"Mexico",dial:"+52"},{iso:"ZA",flag:"🇿🇦",name:"South Africa",dial:"+27"},{iso:"IS",flag:"🇮🇸",name:"Iceland",dial:"+354"},{iso:"GY",flag:"🇬🇾",name:"Guyana",dial:"+592"},{iso:"HT",flag:"🇭🇹",name:"Haiti",dial:"+509"},{iso:"HN",flag:"🇭🇳",name:"Honduras",dial:"+504"}
] as const;
const uuidPattern=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function birthDateToIso(value:string){if(/^\d{4}-\d{2}-\d{2}$/.test(value)){const [y,mo,d]=value.split("-").map(Number);const date=new Date(Date.UTC(y,mo-1,d));if(date.getUTCFullYear()!==y||date.getUTCMonth()!==mo-1||date.getUTCDate()!==d||date.getTime()>Date.now()||y<1900)return"";return value;}return"";}
function validEmail(value:string){return/^\S+@\S+\.\S+$/.test(value.trim());}
function validPhone(value:string){return value.replace(/\D/g,"").length>=9;}
function readExpiry(eventSlug:string,eventTitle:string){try{const raw=localStorage.getItem(CART_STORAGE_KEY);if(!raw)return 0;const parsed=JSON.parse(raw);const group=parsed?.groups?.find((g:{eventSlug?:string;eventTitle?:string})=>g.eventSlug===eventSlug||g.eventTitle===eventTitle);return Number(group?.expiresAt)||0;}catch{return 0;}}
function writeExpiry(eventSlug:string,eventTitle:string,expiresAt:number){try{const raw=localStorage.getItem(CART_STORAGE_KEY);if(!raw)return;const parsed=JSON.parse(raw);if(!Array.isArray(parsed?.groups))return;parsed.groups=parsed.groups.map((g:{eventSlug?:string;eventTitle?:string})=>(g.eventSlug===eventSlug||g.eventTitle===eventTitle)?{...g,expiresAt}:g);localStorage.setItem(CART_STORAGE_KEY,JSON.stringify(parsed));window.dispatchEvent(new Event("atlas-cart-change"));}catch{}}
function removeCartGroup(eventSlug:string,eventTitle:string){try{const raw=localStorage.getItem(CART_STORAGE_KEY);if(!raw)return;const parsed=JSON.parse(raw);if(!Array.isArray(parsed?.groups))return;parsed.groups=parsed.groups.filter((g:{eventSlug?:string;eventTitle?:string})=>g.eventSlug!==eventSlug&&g.eventTitle!==eventTitle);if(parsed.groups.length)localStorage.setItem(CART_STORAGE_KEY,JSON.stringify(parsed));else localStorage.removeItem(CART_STORAGE_KEY);window.dispatchEvent(new Event("atlas-cart-change"));}catch{}}
function clock(ms:number){const value=Math.max(0,ms);const m=Math.floor(value/60000),s=Math.floor((value%60000)/1000);return`${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`;}
function ticketWord(quantity:number,locale:Locale){if(locale==="he")return quantity===1?"כרטיס":"כרטיסים";if(locale==="en")return quantity===1?"ticket":"tickets";const n10=quantity%10,n100=quantity%100;return n10===1&&n100!==11?"билет":n10>=2&&n10<=4&&(n100<12||n100>14)?"билета":"билетов";}

type CheckoutItem={categoryId:string;quantity:number;tableId?:string|null;seatIds:string[]};
type CheckoutSummaryItem={label:string;amount:number;quantity:number};
type CheckoutFormProps={eventId:string;eventSlug:string;categoryId:string;quantity:number;tableId?:string;seatIds?:string[];items?:CheckoutItem[];subtotal:number;serviceFee:number;total:number;serviceFeePayer:"BUYER"|"ORGANIZER";title:string;label:string;posterUrl:string;startsAt:string;summaryItems:CheckoutSummaryItem[];salesMode:"INSTANT"|"APPROVAL_REQUIRED";approvalInstructions?:string|null;referralCode?:string;promoterLabel?:string;recoveryToken?:string;guestFields:GuestFieldConfig};
type RecoveryCustomer={firstName?:string;lastName?:string;email?:string;phone?:string;gender?:string};

export function CheckoutForm(props:CheckoutFormProps){
 const router=useRouter();const{locale}=useLocale();const text=copy[locale];
 const[firstName,setFirstName]=useState("");const[lastName,setLastName]=useState("");const[email,setEmail]=useState("");const[phone,setPhone]=useState("");const[promo,setPromo]=useState("");const[gender,setGender]=useState("");const[genderOpen,setGenderOpen]=useState(false);const[countryIso,setCountryIso]=useState("IL");const[countryOpen,setCountryOpen]=useState(false);const[phoneTouched,setPhoneTouched]=useState(false);const[birthOpen,setBirthOpen]=useState(false);
 const[extras,setExtras]=useState<Record<string,string>>({});const[paymentUrl,setPaymentUrl]=useState("");const[orderId,setOrderId]=useState("");const[,setPaymentReady]=useState(false);const[,setDetailsReady]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[now,setNow]=useState(()=>Date.now());const[expiresAt,setExpiresAt]=useState(0);const[expiredOpen,setExpiredOpen]=useState(false);const[reholding,setReholding]=useState(false);const[cancelling,setCancelling]=useState(false);const[cancelled,setCancelled]=useState(false);
 const today=new Date();const initialBirth=extras.birthDate?extras.birthDate.split("-").map(Number):[1990,1,1];const[birthYear,setBirthYear]=useState(initialBirth[0]||1990);const[birthMonth,setBirthMonth]=useState(initialBirth[1]||1);const[birthDay,setBirthDay]=useState(initialBirth[2]||1);
 const approvalRequired=props.salesMode==="APPROVAL_REQUIRED";const hasOrganizerQuestion=approvalRequired&&Boolean(props.approvalInstructions?.trim());const visible=(Object.keys(props.guestFields) as GuestFieldKey[]).filter(k=>props.guestFields[k].visible);const extraKeys=visible.filter(k=>!["firstName","lastName","email","phone"].includes(k));const otherExtraKeys=extraKeys.filter(k=>k!=="birthDate");const showBirthDate=extraKeys.includes("birthDate");
 const tokenRef=useRef("");const orderKeyRef=useRef("");const startingRef=useRef(false);const iframeRef=useRef<HTMLIFrameElement|null>(null);const contactCaptureRef=useRef<number|null>(null);const detailsTimerRef=useRef<number|null>(null);const genderRef=useRef<HTMLDivElement|null>(null);const countryRef=useRef<HTMLDivElement|null>(null);const birthRef=useRef<HTMLDivElement|null>(null);
 const selectedCountry=countries.find(c=>c.iso===countryIso)||countries[0];const fullPhone=`${selectedCountry.dial}${phone.replace(/\D/g,"")}`;const localPhoneValid=phone.replace(/\D/g,"").length>=7;const phoneInvalid=phoneTouched&&phone.length>0&&!localPhoneValid;
 const years=Array.from({length:today.getFullYear()-1899},(_,i)=>today.getFullYear()-i);const daysInBirthMonth=new Date(birthYear,birthMonth,0).getDate();const days=Array.from({length:daysInBirthMonth},(_,i)=>i+1);
 function token(){if(tokenRef.current)return tokenRef.current;const key=`atlas-abandon-${props.eventId}-${props.categoryId}-${props.tableId||props.seatIds?.join("-")||"general"}`;const recovery=props.recoveryToken&&uuidPattern.test(props.recoveryToken)?props.recoveryToken:"";const existing=sessionStorage.getItem(key);const value=recovery||existing||crypto.randomUUID();sessionStorage.setItem(key,value);tokenRef.current=value;return value;}
 function orderKey(){if(!orderKeyRef.current)orderKeyRef.current=crypto.randomUUID();return orderKeyRef.current;}
 function customer():RecoveryCustomer{return{firstName:firstName.trim(),lastName:lastName.trim(),email,phone:fullPhone,gender};}
 function capture(stage:"CHECKOUT_OPENED"|"CONTACTS_ENTERED"|"PAYMENT_STARTED",data:RecoveryCustomer={}){void fetch("/api/checkout/abandon",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token:token(),eventId:props.eventId,categoryId:props.categoryId,quantity:props.quantity,amountMinor:props.total,stage,checkoutUrl:window.location.href,customer:data,metadata:{tableId:props.tableId||null,seatIds:props.seatIds||[],items:props.items||null,label:props.label,referralCode:props.referralCode||null}}),keepalive:true}).catch(()=>undefined);}
 const contactReady=firstName.trim().length>=2&&lastName.trim().length>=2&&validEmail(email)&&validPhone(fullPhone)&&localPhoneValid;
 const requiredExtrasReady=useMemo(()=>extraKeys.every(key=>{if(!props.guestFields[key].required)return true;const value=extras[key]||"";return key==="birthDate"?Boolean(birthDateToIso(value)):value.trim().length>0;})&&Boolean(gender),[extraKeys,extras,gender,props.guestFields]);
 const remaining=Math.max(0,(expiresAt||now)-now);
 useEffect(()=>{capture("CHECKOUT_OPENED");const stored=readExpiry(props.eventSlug,props.title);setExpiresAt(stored||Date.now()+15*60*1000);const id=window.setInterval(()=>setNow(Date.now()),1000);return()=>{clearInterval(id);if(contactCaptureRef.current)clearTimeout(contactCaptureRef.current);if(detailsTimerRef.current)clearTimeout(detailsTimerRef.current);};},[]);
 useEffect(()=>{const close=(event:MouseEvent)=>{const target=event.target as Node;if(genderOpen&&genderRef.current&&!genderRef.current.contains(target))setGenderOpen(false);if(countryOpen&&countryRef.current&&!countryRef.current.contains(target))setCountryOpen(false);if(birthOpen&&birthRef.current&&!birthRef.current.contains(target))setBirthOpen(false)};const esc=(event:KeyboardEvent)=>{if(event.key==="Escape"){setGenderOpen(false);setCountryOpen(false);setBirthOpen(false)}};document.addEventListener("mousedown",close);document.addEventListener("keydown",esc);return()=>{document.removeEventListener("mousedown",close);document.removeEventListener("keydown",esc);};},[genderOpen,countryOpen,birthOpen]);
 useEffect(()=>{if(!cancelled&&expiresAt&&now>=expiresAt)setExpiredOpen(true);},[now,expiresAt,cancelled]);
 useEffect(()=>{if(cancelled||!contactReady||paymentUrl||startingRef.current||expiredOpen)return;const id=window.setTimeout(()=>void startPayment(),500);return()=>clearTimeout(id);},[contactReady,paymentUrl,expiredOpen,cancelled,countryIso]);
 useEffect(()=>{if(!contactReady||cancelled)return;if(contactCaptureRef.current)clearTimeout(contactCaptureRef.current);contactCaptureRef.current=window.setTimeout(()=>capture("CONTACTS_ENTERED",customer()),500);},[firstName,lastName,email,phone,countryIso,contactReady,cancelled]);
 useEffect(()=>{if(cancelled||!paymentUrl||!orderId||!requiredExtrasReady)return;if(detailsTimerRef.current)clearTimeout(detailsTimerRef.current);detailsTimerRef.current=window.setTimeout(()=>void saveDetails(),450);return()=>{if(detailsTimerRef.current)clearTimeout(detailsTimerRef.current);};},[paymentUrl,orderId,requiredExtrasReady,extras,gender,cancelled]);
 async function startPayment(){if(cancelled||startingRef.current||paymentUrl||!contactReady)return;startingRef.current=true;setBusy(true);setError("");try{const name={firstName:firstName.trim(),lastName:lastName.trim()};const payload:Record<string,string>={firstName:name.firstName,lastName:name.lastName,email:email.trim(),phone:fullPhone};for(const key of extraKeys){const raw=extras[key]||"";payload[key]=key==="birthDate"?(birthDateToIso(raw)||"1900-01-01"):(raw||"-");}const idempotencyKey=orderKey();capture("PAYMENT_STARTED",{...name,email,phone:fullPhone,gender});const endpoint=props.items?.length?"/api/checkout/cart":"/api/checkout";const response=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({eventId:props.eventId,categoryId:props.categoryId,quantity:props.quantity,tableId:props.tableId||null,seatIds:props.seatIds||undefined,items:props.items,promoCode:promo||undefined,referralCode:props.referralCode||undefined,customer:payload,payment:{method:"CARD"},locale,idempotencyKey,abandonToken:token()})});const data=await response.json();if(!response.ok)throw new Error(data.error||text.error);if(data.paymentUrl){setOrderId(data.orderId);setPaymentUrl(data.paymentUrl);setPaymentReady(false);return;}router.push(`/orders/${data.orderId}?locale=${locale}`);}catch(e){setError(e instanceof Error?e.message:text.error);}finally{setBusy(false);startingRef.current=false;}}
 async function saveDetails(){if(cancelled||!orderId||!requiredExtrasReady)return;setError("");try{const birthDate=extras.birthDate?birthDateToIso(extras.birthDate):"";const demo=await fetch(`/api/orders/${orderId}/demographics`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({idempotencyKey:orderKey(),gender,birthDate})});if(!demo.ok)throw new Error(text.detailsError);const details=await fetch(`/api/orders/${orderId}/checkout-details`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({idempotencyKey:orderKey(),city:extras.city||"",facebook:extras.facebook||"",instagram:extras.instagram||""})});if(!details.ok)throw new Error(text.detailsError);setDetailsReady(true);}catch(e){setDetailsReady(false);setError(e instanceof Error?e.message:text.detailsError);}}
 function handleFrameLoad(){setPaymentReady(true);try{const href=iframeRef.current?.contentWindow?.location.href;if(!href)return;const url=new URL(href);if(url.origin===window.location.origin&&(url.pathname.startsWith("/orders/")||url.pathname==="/payments/hyp/result"))window.location.assign(url.toString());}catch{}}
 async function rehold(){if(reholding||cancelling)return;setReholding(true);setError("");try{const items=props.items?.length?props.items:[{categoryId:props.categoryId,quantity:props.quantity,tableId:props.tableId||null,seatIds:props.seatIds||[]}];const response=await fetch("/api/cart/hold",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({eventId:props.eventId,items})});const data=await response.json();if(!response.ok)throw new Error(data.error||text.error);const next=data.expiresAt?new Date(data.expiresAt).getTime():Date.now()+15*60*1000;writeExpiry(props.eventSlug,props.title,next);setCancelled(false);setExpiresAt(next);setNow(Date.now());setExpiredOpen(false);}catch(e){setError(e instanceof Error?e.message:text.error);}finally{setReholding(false);}}
 async function cancelExpired(){if(cancelling||reholding)return;setCancelling(true);setCancelled(true);setExpiredOpen(false);setExpiresAt(0);removeCartGroup(props.eventSlug,props.title);try{await fetch("/api/cart/hold/release",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({eventSlug:props.eventSlug}),keepalive:true});}catch{}finally{router.replace(`/events/${props.eventSlug}`);}}
 function setExtra(key:string,value:string){setDetailsReady(false);setExtras(prev=>({...prev,[key]:value}));}
 function chooseGender(value:string){setDetailsReady(false);setGender(value);setGenderOpen(false);}
 function commitBirthDate(){const safeDay=Math.min(birthDay,new Date(birthYear,birthMonth,0).getDate());const iso=`${birthYear}-${String(birthMonth).padStart(2,"0")}-${String(safeDay).padStart(2,"0")}`;setBirthDay(safeDay);setExtra("birthDate",iso);setBirthOpen(false);}
 const singleFeeNote=props.serviceFeePayer==="BUYER"&&props.serviceFee>0&&props.summaryItems.length===1;
 const genderOptions=[{value:"MALE",label:text.male},{value:"FEMALE",label:text.female},{value:"PREFER_NOT_TO_SAY",label:text.preferNot},{value:"OTHER",label:text.other}];
 const genderLabel=genderOptions.find(option=>option.value===gender)?.label||text.chooseGender;
 const birthLabel=extras.birthDate?(()=>{const [y,m,d]=extras.birthDate.split("-");return locale==="he"?`${d}.${m}.${y}`:`${d}.${m}.${y}`})():locale==="ru"?"ДД.ММ.ГГГГ":locale==="he"?"יום.חודש.שנה":"DD.MM.YYYY";

 const contactBlock=<div className={styles.contactBlock}><h2 className={styles.sectionTitle}>{text.contact}</h2><div className={styles.contactCard}>
  <div className={styles.detailsRow}>
   <div className={styles.field}><label>{labels.firstName[locale]} *</label><input value={firstName} onChange={e=>setFirstName(e.target.value)} autoComplete="given-name"/></div>
   <div className={styles.field}><label>{labels.lastName[locale]} *</label><input value={lastName} onChange={e=>setLastName(e.target.value)} autoComplete="family-name"/></div>
  </div>
  <div className={styles.field}><label>{text.email}</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></div>
  <div className={styles.phoneField} ref={countryRef}>
   <label>{text.phone}</label><div className={`${styles.phoneControl}${phoneInvalid?` ${styles.phoneControlInvalid}`:""}`}><button type="button" className={styles.flagButton} onClick={()=>setCountryOpen(v=>!v)} aria-haspopup="listbox" aria-expanded={countryOpen}><span>{selectedCountry.flag}</span><span className={styles.flagChevron}>⌄</span></button><span className={styles.dialCode}>{selectedCountry.dial}</span><input type="tel" value={phone} onBlur={()=>setPhoneTouched(true)} onChange={e=>{setPhoneTouched(true);setPhone(e.target.value.replace(/[^\d\s-]/g,""))}} autoComplete="tel-national" placeholder="52 556 5457"/></div>
   {countryOpen&&<div className={styles.countryMenu} role="listbox">{countries.map(c=><button type="button" key={c.iso} className={`${styles.countryOption}${c.iso===countryIso?` ${styles.countryOptionActive}`:""}`} onClick={()=>{setCountryIso(c.iso);setCountryOpen(false)}}><span>{c.flag}</span><span>{c.name}</span><span>{c.dial}</span></button>)}</div>}
   {phoneInvalid&&<div className={styles.phoneError}><span>×</span>{text.phoneError}</div>}
  </div>
  {paymentUrl&&<div className={styles.fadeIn}>
   <div className={styles.detailsRow}>
    {showBirthDate?<div className={`${styles.field} ${styles.birthField}`} ref={birthRef}><label>{labels.birthDate[locale]}{props.guestFields.birthDate?.required?" *":""}</label><button type="button" className={styles.birthTrigger} onClick={()=>setBirthOpen(v=>!v)}><span>{birthLabel}</span><span className={styles.calendarIcon}>▣</span></button>{birthOpen&&<div className={styles.birthMenu}><div className={styles.birthMenuTitle}>{labels.birthDate[locale]}</div><div className={styles.birthColumns}><div className={styles.birthColumn}>{years.map(y=><button type="button" key={y} className={y===birthYear?styles.birthActive:""} onClick={()=>setBirthYear(y)}>{y}</button>)}</div><div className={styles.birthColumn}>{months[locale].map((m,i)=><button type="button" key={m} className={i+1===birthMonth?styles.birthActive:""} onClick={()=>setBirthMonth(i+1)}>{m}</button>)}</div><div className={styles.birthColumn}>{days.map(d=><button type="button" key={d} className={d===birthDay?styles.birthActive:""} onClick={()=>setBirthDay(d)}>{d}</button>)}</div></div><div className={styles.birthActions}><button type="button" className={styles.birthCancel} onClick={()=>setBirthOpen(false)}>{text.cancel}</button><button type="button" className={styles.birthChoose} onClick={commitBirthDate}>{text.choose}</button></div></div>}</div>:<div className={styles.field}/>} 
    <div className={`${styles.field} ${styles.genderField}`} ref={genderRef}><label>{text.gender} *</label><button type="button" className={`${styles.genderTrigger}${genderOpen?` ${styles.genderTriggerOpen}`:""}`} onClick={()=>setGenderOpen(open=>!open)} aria-haspopup="listbox" aria-expanded={genderOpen}><span>{genderLabel}</span><span className={styles.genderChevron}>⌄</span></button>{genderOpen&&<div className={styles.genderMenu} role="listbox">{genderOptions.map(option=><button type="button" key={option.value} className={`${styles.genderOption}${gender===option.value?` ${styles.genderOptionActive}`:""}`} onClick={()=>chooseGender(option.value)} role="option" aria-selected={gender===option.value}>{option.label}</button>)}</div>}</div>
   </div>
   {otherExtraKeys.map(key=><div className={styles.field} key={key}><label>{labels[key][locale]}{props.guestFields[key].required?" *":""}</label>{key==="city"?<><input list="checkout-cities" value={extras[key]||""} onChange={e=>setExtra(key,e.target.value)}/><datalist id="checkout-cities">{israelCities.map(city=><option value={city} key={city}/>)}</datalist></>:<input value={extras[key]||""} onChange={e=>setExtra(key,e.target.value)} placeholder={key==="instagram"?(locale==="he"?"שם משתמש אינסטגרם (לא קישור)":locale==="ru"?"Имя пользователя Instagram (не ссылка)":"Instagram username (not a link)"):""}/>}</div>)}
   {!approvalRequired&&<div className={`${styles.field} ${styles.promo}`}><label>{text.promo}</label><input value={promo} onChange={e=>setPromo(e.target.value.toUpperCase())} placeholder={text.promoPlaceholder}/></div>}
   {hasOrganizerQuestion&&<div className={styles.field}><label>{props.approvalInstructions}</label><textarea rows={4}/></div>}
  </div>}
 </div></div>;

 const summaryBlock=<div className={styles.summary}><div className={styles.summaryTop}><img className={styles.poster} src={props.posterUrl} alt=""/><div className={styles.eventInfo}><h2>{props.title}</h2><p className={styles.eventDate}>{eventDate(new Date(props.startsAt),locale)}</p><p className={styles.ticketCount}>{props.quantity} {ticketWord(props.quantity,locale)}</p></div></div><div className={styles.summaryItems}>{props.summaryItems.map((item,index)=><div className={styles.summaryItem} key={`${item.label}-${index}`}><div><div className={styles.seatLabel}>{item.label}</div>{item.quantity>1&&<div className={styles.seatMeta}>{item.quantity} {ticketWord(item.quantity,locale)}</div>}</div><div className={styles.itemPrice}>{money(item.amount,"ILS",locale)}{singleFeeNote&&<span className={styles.feeNote}>{locale==="ru"?`включая сервисный сбор ${money(props.serviceFee,"ILS",locale)}`:locale==="he"?`כולל עמלת שירות ${money(props.serviceFee,"ILS",locale)}`:`incl. ${money(props.serviceFee,"ILS",locale)} service fee`}</span>}</div></div>)}</div>{props.serviceFeePayer==="BUYER"&&props.serviceFee>0&&props.summaryItems.length>1&&<div className={`${styles.line} ${styles.serviceFee}`}><span>{text.serviceFee}</span><strong>{money(props.serviceFee,"ILS",locale)}</strong></div>}<div className={`${styles.line} ${styles.total}`}><strong>{text.total}</strong><strong>{money(props.total,"ILS",locale)}</strong></div></div>;
 const paymentBlock=<div className={styles.paymentWrap}><h2 className={styles.sectionTitle}>{text.payment}</h2>{!contactReady&&!paymentUrl?<div className={styles.wait}>{text.paymentWaiting}</div>:<div className={`${styles.paymentCard} ${styles.fadeIn}`}>{busy&&!paymentUrl&&<div className={styles.paymentLoading}>{text.paymentLoading}</div>}{paymentUrl&&<iframe ref={iframeRef} src={paymentUrl} title={text.payment} allow="payment" onLoad={handleFrameLoad} className={styles.paymentFrame}/>}</div>}</div>;
 return <div className={styles.checkout}><section className={styles.leftColumn}><h1 className={styles.title}>{text.checkout}</h1>{contactBlock}{error&&<div className={styles.error}>{error}</div>}</section><aside className={styles.rightColumn}><div className={styles.timer}><strong>{clock(remaining)}</strong></div>{summaryBlock}{paymentBlock}</aside>{expiredOpen&&<div className={styles.modalBackdrop} role="dialog" aria-modal="true" aria-label={text.expired}><div className={styles.modal}><div className={styles.modalHead}>{text.expired}<button type="button" className={styles.close} onClick={cancelExpired} disabled={cancelling||reholding} aria-label={text.close}>×</button></div><div className={styles.modalBody}><p>{text.expiredBody}</p><button type="button" className={styles.primary} onClick={rehold} disabled={reholding||cancelling}>{reholding?"…":text.rehold}</button><button type="button" className={styles.secondary} onClick={cancelExpired} disabled={cancelling||reholding}>{cancelling?"…":text.cancel}</button></div></div></div>}</div>;
}