"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { money } from "@/lib/format";
import { useLocale } from "@/components/locale-provider";
import { israelCities } from "@/lib/israel-cities";
import type { GuestFieldConfig, GuestFieldKey } from "@/lib/event-guest-fields";
import type { Locale } from "@/lib/i18n";

const text={
ru:{title:"Оформление заказа",request:"Заявка на билет",contact:"Данные гостя",promo:"Промокод",pay:"Безопасная оплата",payInfo:"После оформления заказа вы перейдёте на защищённую страницу Hyp.",review:"Сначала проверка организатором",reviewInfo:"После отправки заявки организатор рассмотрит её.",send:"Отправить заявку",confirm:"Перейти к безопасной оплате",sending:"Создаём заказ…",order:"Ваш заказ",qty:"Количество",total:"Итого",extra:"Дополнительная информация",error:"Не удалось отправить данные"},
he:{title:"תשלום",request:"בקשה לכרטיס",contact:"פרטי האורח",promo:"קוד הטבה",pay:"תשלום מאובטח",payInfo:"לאחר יצירת ההזמנה תועברו לעמוד התשלום המאובטח של Hyp.",review:"תחילה בדיקת המפיק",reviewInfo:"לאחר שליחת הבקשה המפיק יבדוק אותה.",send:"שליחת הבקשה",confirm:"מעבר לתשלום מאובטח",sending:"יוצרים הזמנה…",order:"ההזמנה שלך",qty:"כמות",total:"סה״כ",extra:"מידע נוסף",error:"לא ניתן לשלוח את הנתונים"},
en:{title:"Checkout",request:"Ticket request",contact:"Guest details",promo:"Promo code",pay:"Secure payment",payInfo:"After creating the order, you will be redirected to Hyp’s secure payment page.",review:"Organizer review first",reviewInfo:"The organizer will review your request first.",send:"Submit request",confirm:"Continue to secure payment",sending:"Creating order…",order:"Your order",qty:"Quantity",total:"Total",extra:"Additional information",error:"Could not submit the details"}
};
const labels:Record<GuestFieldKey,Record<Locale,string>>={firstName:{ru:"Имя",he:"שם פרטי",en:"First name"},lastName:{ru:"Фамилия",he:"שם משפחה",en:"Last name"},phone:{ru:"Телефон",he:"טלפון",en:"Phone"},email:{ru:"Email",he:"Email",en:"Email"},birthDate:{ru:"Дата рождения",he:"תאריך לידה",en:"Date of birth"},city:{ru:"Город",he:"עיר",en:"City"},facebook:{ru:"Facebook",he:"Facebook",en:"Facebook"},instagram:{ru:"Instagram",he:"Instagram",en:"Instagram"}};
type Props={eventId:string;categoryId:string;quantity:number;tableId?:string;seatIds?:string[];total:number;title:string;label:string;salesMode:"INSTANT"|"APPROVAL_REQUIRED";approvalInstructions?:string|null;referralCode?:string;promoterLabel?:string;guestFields:GuestFieldConfig};
export function CheckoutFormFinal(p:Props){const router=useRouter();const {locale}=useLocale();const t=text[locale];const review=p.salesMode==="APPROVAL_REQUIRED";const fields=(Object.keys(p.guestFields) as GuestFieldKey[]).filter(k=>p.guestFields[k].visible);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [promo,setPromo]=useState("");async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);const customer=Object.fromEntries(fields.map(k=>[k,String(f.get(k)||"")]));const r=await fetch("/api/checkout",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({eventId:p.eventId,categoryId:p.categoryId,quantity:p.quantity,tableId:p.tableId||null,seatIds:p.seatIds||undefined,promoCode:promo||undefined,referralCode:p.referralCode||undefined,eligibilityAnswer:f.get("eligibilityAnswer")||undefined,customer,payment:{method:"CARD"},locale,idempotencyKey:crypto.randomUUID()})});const d=await r.json();if(!r.ok){setError(d.error||t.error);setBusy(false);return}if(d.paymentUrl){location.assign(d.paymentUrl);return}router.push(`/orders/${d.orderId}?locale=${locale}`)}return <form onSubmit={submit} className={`checkout ${busy?"loading":""}`}><section><span className="eyebrow">{review?t.request:t.title}</span><h1>{t.contact}</h1><div className="panel form">{p.promoterLabel&&<div className="panel"><strong>{p.promoterLabel}</strong></div>}{fields.map(k=><div className="field" key={k}><label>{labels[k][locale]}{p.guestFields[k].required?" *":""}</label><input className="input" name={k} type={k==="phone"?"tel":k==="email"?"email":k==="birthDate"?"date":"text"} required={p.guestFields[k].required} list={k==="city"?"israel-cities":undefined}/>{k==="city"&&<datalist id="israel-cities">{israelCities.map(c=><option value={c} key={c}/>)}</datalist>}</div>)}{review?<div className="field"><label>{p.approvalInstructions||t.extra}</label><textarea name="eligibilityAnswer" rows={4} required/></div>:<div className="field"><label>{t.promo}</label><input className="input" value={promo} onChange={e=>setPromo(e.target.value.toUpperCase())}/></div>}<div className="panel"><strong>{review?t.review:t.pay}</strong><p className="muted">{review?t.reviewInfo:t.payInfo}</p></div>{error&&<div className="toast">{error}</div>}<button className="btn dark" disabled={busy}>{busy?t.sending:review?t.send:t.confirm}</button></div></section><aside className="panel summary"><span className="pill">{t.order}</span><h2>{p.title}</h2><p>{p.label}</p><div className="row between"><span className="muted">{t.qty}</span><strong>{p.quantity}</strong></div><hr/><div className="row between"><strong>{t.total}</strong><strong style={{fontSize:25}}>{money(p.total,"ILS",locale)}</strong></div></aside></form>}
