"use client";

import { useEffect,useRef,useState } from "react";
import { useRouter } from "next/navigation";
import { money } from "@/lib/format";
import { useLocale } from "@/components/locale-provider";
import { israelCities } from "@/lib/israel-cities";
import type { GuestFieldConfig,GuestFieldKey } from "@/lib/event-guest-fields";
import type { Locale } from "@/lib/i18n";
import styles from "./checkout-form.module.css";

type CheckoutItem={categoryId:string;quantity:number;tableId?:string|null;seatIds:string[]};
type Props={eventId:string;categoryId:string;quantity:number;tableId?:string;seatIds?:string[];items?:CheckoutItem[];subtotal:number;serviceFee:number;total:number;serviceFeePayer:"BUYER"|"ORGANIZER";title:string;label:string;salesMode:"INSTANT"|"APPROVAL_REQUIRED";approvalInstructions?:string|null;referralCode?:string;promoterLabel?:string;recoveryToken?:string;guestFields:GuestFieldConfig};
type PaymentResponse={error?:string;orderId?:string;paymentUrl?:string;status?:string};

const labels:Record<GuestFieldKey,Record<Locale,string>>={firstName:{ru:"Имя",he:"שם פרטי",en:"First name"},lastName:{ru:"Фамилия",he:"שם משפחה",en:"Last name"},phone:{ru:"Телефон",he:"טלפון",en:"Phone"},email:{ru:"Email",he:"Email",en:"Email"},birthDate:{ru:"Дата рождения",he:"תאריך לידה",en:"Date of birth"},city:{ru:"Город проживания",he:"עיר מגורים",en:"City"},facebook:{ru:"Facebook",he:"Facebook",en:"Facebook"},instagram:{ru:"Instagram",he:"Instagram",en:"Instagram"}};
const types:Partial<Record<GuestFieldKey,string>>={phone:"tel",email:"email"};
const copy={
 ru:{checkout:"Оформление заказа",request:"Заявка на билет",contact:"Контактные данные",payment:"Способ оплаты",secure:"Защищено HYP",loading:"Загружаем безопасную оплату…",locked:"Заполните обязательные данные выше, чтобы активировать оплату",saveError:"Не удалось сохранить данные покупателя",prepareError:"Не удалось подготовить оплату",promo:"Промокод",apply:"Применить",promoHint:"После применения сумма оплаты обновится здесь же",gender:"Пол",choose:"Выберите пол",male:"Мужчина",female:"Женщина",order:"Ваш заказ",requested:"Запрашиваемый билет",quantity:"Количество",total:"Итого к оплате",approval:"Списание произойдёт только после одобрения организатором",cardSafe:"Номер карты, CVV и данные кошелька вводятся только в защищённой форме HYP. Atlas их не получает.",fallback:"Открыть оплату отдельно"},
 he:{checkout:"תשלום",request:"בקשה לכרטיס",contact:"פרטי קשר",payment:"אמצעי תשלום",secure:"מאובטח על ידי HYP",loading:"טוענים תשלום מאובטח…",locked:"מלאו את שדות החובה למעלה כדי להפעיל את התשלום",saveError:"לא ניתן לשמור את פרטי הלקוח",prepareError:"לא ניתן להכין את התשלום",promo:"קוד הטבה",apply:"החל",promoHint:"לאחר ההחלה הסכום יתעדכן כאן",gender:"מגדר",choose:"בחרו מגדר",male:"גבר",female:"אישה",order:"ההזמנה שלך",requested:"הכרטיס המבוקש",quantity:"כמות",total:"סה״כ לתשלום",approval:"החיוב יתבצע רק לאחר אישור המפיק",cardSafe:"מספר כרטיס, CVV ופרטי הארנק מוזנים רק בטופס המאובטח של HYP. Atlas אינו מקבל אותם.",fallback:"פתח תשלום בנפרד"},
 en:{checkout:"Checkout",request:"Ticket request",contact:"Contact details",payment:"Payment method",secure:"Secured by HYP",loading:"Loading secure payment…",locked:"Complete the required details above to activate payment",saveError:"Could not save customer details",prepareError:"Could not prepare payment",promo:"Promo code",apply:"Apply",promoHint:"After applying, the amount updates here",gender:"Gender",choose:"Select gender",male:"Male",female:"Female",order:"Your order",requested:"Requested ticket",quantity:"Quantity",total:"Total to pay",approval:"Your card will only be charged after organizer approval",cardSafe:"Card number, CVV and wallet data are entered only inside HYP's secure form. Atlas never receives them.",fallback:"Open payment separately"}
};
const birthDateError:Record<Locale,string>={ru:"Введите дату в формате ДД.ММ.ГГГГ",he:"יש להזין תאריך בפורמט DD.MM.YYYY",en:"Enter the date as DD.MM.YYYY"};
function formatBirthDate(value:string){const digits=value.replace(/\D/g,"").slice(0,8);return[digits.slice(0,2),digits.slice(2,4),digits.slice(4,8)].filter(Boolean).join(".");}
function birthDateToIso(value:string){const m=/^(\d{2})\.(\d{2})\.(\d{4})$/.exec(value);if(!m)return"";const d=Number(m[1]),mo=Number(m[2]),y=Number(m[3]);const date=new Date(Date.UTC(y,mo-1,d));if(y<1900||date.getTime()>Date.now()||date.getUTCFullYear()!==y||date.getUTCMonth()!==mo-1||date.getUTCDate()!==d)return"";return`${m[3]}-${m[2]}-${m[1]}`;}
function provisionalCustomer(){const id=crypto.randomUUID();const phone=`050${String(Math.floor(Math.random()*10000000)).padStart(7,"0")}`;return{firstName:"Checkout",lastName:"Guest",phone,email:`checkout-${id}@atlas-one.co`,birthDate:"1900-01-01",city:"Pending",facebook:"pending",instagram:"pending",gender:"MALE"};}

export function CheckoutFormV2(props:Props){
 const router=useRouter();const{locale}=useLocale();const t=copy[locale];const approval=props.salesMode==="APPROVAL_REQUIRED";const visible=(Object.keys(props.guestFields) as GuestFieldKey[]).filter(k=>props.guestFields[k].visible);const hasQuestion=approval&&Boolean(props.approvalInstructions?.trim());
 const formRef=useRef<HTMLFormElement|null>(null);const frameRef=useRef<HTMLIFrameElement|null>(null);const saveTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const preparing=useRef(false);const [paymentUrl,setPaymentUrl]=useState("");const[paymentReady,setPaymentReady]=useState(false);const[orderId,setOrderId]=useState("");const[idempotencyKey,setIdempotencyKey]=useState(()=>crypto.randomUUID());const[paymentUnlocked,setPaymentUnlocked]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[promo,setPromo]=useState("");const[appliedPromo,setAppliedPromo]=useState("");

 function payloadCustomer(form:FormData){return{firstName:String(form.get("firstName")||""),lastName:String(form.get("lastName")||""),phone:String(form.get("phone")||""),email:String(form.get("email")||""),birthDate:String(form.get("birthDate")||"")?birthDateToIso(String(form.get("birthDate"))):"",city:String(form.get("city")||""),facebook:String(form.get("facebook")||""),instagram:String(form.get("instagram")||"")};}
 function handleBirthDateInput(e:React.FormEvent<HTMLInputElement>){const input=e.currentTarget;const formatted=formatBirthDate(input.value);if(input.value!==formatted)input.value=formatted;input.setCustomValidity(!formatted||birthDateToIso(formatted)?"":birthDateError[locale]);}
 async function prepare(nextPromo=appliedPromo,key=idempotencyKey){if(preparing.current)return;preparing.current=true;setBusy(true);setError("");try{const endpoint=props.items?.length?"/api/checkout/cart":"/api/checkout";const response=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({eventId:props.eventId,categoryId:props.categoryId,quantity:props.quantity,tableId:props.tableId||null,seatIds:props.seatIds||undefined,items:props.items,promoCode:nextPromo||undefined,referralCode:props.referralCode||undefined,eligibilityAnswer:hasQuestion?"Pending customer response":undefined,customer:provisionalCustomer(),payment:{method:"CARD"},locale,idempotencyKey:key})});const data:PaymentResponse=await response.json();if(!response.ok||!data.paymentUrl||!data.orderId){setError(data.error||t.prepareError);return;}setOrderId(data.orderId);setPaymentReady(false);setPaymentUrl(data.paymentUrl);}catch{setError(t.prepareError);}finally{setBusy(false);preparing.current=false;}}
 async function saveDetails(){const form=formRef.current;if(!form||!orderId||!form.checkValidity()){setPaymentUnlocked(false);return;}const fd=new FormData(form);const customer=payloadCustomer(fd);if(visible.includes("birthDate")&&customer.birthDate===""){setPaymentUnlocked(false);return;}setError("");try{const contact=await fetch(`/api/orders/${orderId}/checkout-contact`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...customer,idempotencyKey,eligibilityAnswer:hasQuestion?String(fd.get("eligibilityAnswer")||""):""})});if(!contact.ok){const data=await contact.json().catch(()=>({}));setError(data.error||t.saveError);setPaymentUnlocked(false);return;}const demographics=await fetch(`/api/orders/${orderId}/demographics`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({idempotencyKey,gender:String(fd.get("gender")||""),birthDate:customer.birthDate})});if(!demographics.ok){setError(t.saveError);setPaymentUnlocked(false);return;}setPaymentUnlocked(true);}catch{setError(t.saveError);setPaymentUnlocked(false);}}
 function scheduleSave(){if(saveTimer.current)clearTimeout(saveTimer.current);setPaymentUnlocked(false);saveTimer.current=setTimeout(()=>void saveDetails(),450);}
 async function applyPromo(){const normalized=promo.trim().toUpperCase();if(normalized===appliedPromo)return;setPaymentUnlocked(false);setBusy(true);try{if(orderId)await fetch(`/api/orders/${orderId}/checkout-contact`,{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({idempotencyKey})});const key=crypto.randomUUID();setIdempotencyKey(key);setOrderId("");setPaymentUrl("");setPaymentReady(false);setAppliedPromo(normalized);await prepare(normalized,key);}finally{setBusy(false);}}
 function frameLoaded(){setPaymentReady(true);const frame=frameRef.current;if(!frame)return;try{const href=frame.contentWindow?.location.href;if(!href)return;const url=new URL(href);if(url.origin===window.location.origin&&(url.pathname.startsWith("/orders/")||url.pathname==="/payments/hyp/result"))window.location.assign(url.toString());}catch{}}
 useEffect(()=>{void prepare("",idempotencyKey);return()=>{if(saveTimer.current)clearTimeout(saveTimer.current);};},[]);

 return <form ref={formRef} onInput={scheduleSave} onChange={scheduleSave} onSubmit={e=>e.preventDefault()} className={styles.checkoutShell}>
  <main className={styles.mainColumn}>
   <header className={styles.header}><span className="eyebrow">{approval?t.request:t.checkout}</span><h1>{t.contact}</h1></header>
   <section className={`panel form ${styles.formCard}`}>
    {props.promoterLabel&&<div className={`panel ${styles.promoterBox}`}><strong>{props.promoterLabel}</strong></div>}
    {visible.map(key=><div className="field" key={key}><label>{labels[key][locale]}{props.guestFields[key].required?" *":""}</label><input className="input" name={key} type={types[key]||"text"} required={props.guestFields[key].required} minLength={key==="firstName"||key==="lastName"?2:undefined} list={key==="city"?"israel-cities":undefined} autoComplete={key==="firstName"?"given-name":key==="lastName"?"family-name":key==="phone"?"tel":key==="email"?"email":key==="birthDate"?"bday":key==="city"?"address-level2":"off"} inputMode={key==="birthDate"?"numeric":undefined} maxLength={key==="birthDate"?10:undefined} pattern={key==="birthDate"?"\\d{2}\\.\\d{2}\\.\\d{4}":undefined} onInput={key==="birthDate"?handleBirthDateInput:undefined} placeholder={key==="phone"?"054-1234567":key==="instagram"?"@username":key==="birthDate"?(locale==="ru"?"ДД.ММ.ГГГГ":"DD.MM.YYYY"):undefined}/>{key==="city"&&<datalist id="israel-cities">{israelCities.map(city=><option value={city} key={city}/>)}</datalist>}</div>)}
    {!approval&&<div className="field"><label>{t.promo}</label><div style={{display:"grid",gridTemplateColumns:"1fr auto",gap:8}}><input className="input" value={promo} onChange={e=>setPromo(e.target.value.toUpperCase())}/><button type="button" className="btn secondary" onClick={()=>void applyPromo()} disabled={busy}>{t.apply}</button></div><small className="muted">{t.promoHint}</small></div>}
    <div className="field"><label>{t.gender} *</label><select className="input" name="gender" required defaultValue=""><option value="" disabled>{t.choose}</option><option value="MALE">{t.male}</option><option value="FEMALE">{t.female}</option></select></div>
    {hasQuestion&&<div className="field"><label>{props.approvalInstructions}</label><textarea name="eligibilityAnswer" rows={4} required/></div>}
   </section>

   <section className={`panel ${styles.paymentCard} ${paymentUrl?styles.paymentActive:""}`}>
    <div className={styles.paymentHeader}><div className={styles.paymentTitle}><span className={styles.lockBadge}>🔒</span><div><strong>{t.payment}</strong><div className={styles.secureLabel}>{t.secure}</div></div></div></div>
    <p className="muted" style={{margin:0}}>{approval?t.approval:t.cardSafe}</p>
    <div className={styles.paymentStage} style={{position:"relative"}}>
     {!paymentUrl?<div className={styles.paymentPlaceholder}><div className={styles.placeholderInner}><span className={styles.placeholderIcon}>🔒</span><strong>{t.loading}</strong></div></div>:
      <div className={styles.frameWrap} style={{position:"relative"}}>
       {!paymentReady&&<div className={`muted ${styles.paymentPlaceholder}`}><div className={styles.placeholderInner}><strong>{t.loading}</strong></div></div>}
       <iframe ref={frameRef} src={paymentUrl} title={t.payment} onLoad={frameLoaded} allow="payment" className={styles.paymentFrame} style={{display:paymentReady?"block":"none"}}/>
       {paymentReady&&!paymentUnlocked&&<div style={{position:"absolute",inset:0,zIndex:5,display:"grid",placeItems:"center",background:"rgba(248,250,252,.72)",backdropFilter:"blur(1.5px)",padding:24,textAlign:"center",borderRadius:14,cursor:"not-allowed"}}><div className="panel" style={{maxWidth:430,boxShadow:"0 12px 36px rgba(15,23,42,.12)"}}><strong>{t.locked}</strong></div></div>}
      </div>}
    </div>
    {paymentUrl&&<a href={paymentUrl} target="_blank" rel="noopener noreferrer" className={`muted ${styles.fallback}`}>{t.fallback}</a>}
    {error&&<div className={`toast ${styles.error}`}>{error}</div>}
   </section>
  </main>
  <aside className={`panel ${styles.summary}`}><span className="pill">{approval?t.requested:t.order}</span><h2>{props.title}</h2><p className="muted">{props.label}</p><div className="row between"><span className="muted">{t.quantity}</span><strong>{props.quantity}</strong></div><hr className={styles.divider}/><div className={styles.totalRow}><strong>{t.total}</strong><span className={styles.totalPrice}>{money(props.total,"ILS",locale)}</span></div></aside>
 </form>;
}
