"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

type SourceEvent={id:string;title:string;startsAt:string;venueName:string;city:string;address:string};
export function CloneEventForm({events}:{events:SourceEvent[]}){
  const router=useRouter();const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);const date=(name:string)=>new Date(String(f.get(name))).toISOString();const response=await fetch("/api/admin/events/clone",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sourceEventId:f.get("sourceEventId"),title:f.get("title"),slug:f.get("slug"),startsAt:date("startsAt"),doorsOpenAt:date("doorsOpenAt"),salesStart:date("salesStart"),salesEnd:date("salesEnd"),venueName:f.get("venueName"),city:f.get("city"),address:f.get("address"),copyGuestLists:f.get("copyGuestLists")==="on",copyPromoters:f.get("copyPromoters")==="on"})});const data=await response.json();if(!response.ok){setError(data.error||"Не удалось скопировать мероприятие");setBusy(false);return;}router.push(`/office/events/${data.id}`);router.refresh();}
  if(!events.length)return <div className="toast">Сначала создайте хотя бы одно мероприятие.</div>;
  return <form className="panel form" onSubmit={submit}><h2>Скопировать существующее мероприятие</h2><p className="muted">Будут скопированы билеты, цены, схема, столы, места, анкета гостя и дизайн билета. Старые заказы, оплаты, гости и сканирования не копируются.</p><div className="field"><label>Исходное мероприятие</label><select name="sourceEventId" required>{events.map(event=><option key={event.id} value={event.id}>{event.title} · {new Date(event.startsAt).toLocaleDateString("ru-RU")}</option>)}</select></div><div className="form-grid two"><div className="field"><label>Новое название</label><input className="input" name="title" required/></div><div className="field"><label>Новый адрес страницы</label><input className="input" name="slug" pattern="[a-z0-9-]+" required/></div></div><div className="form-grid two"><div className="field"><label>Начало мероприятия</label><input className="input" type="datetime-local" name="startsAt" required/></div><div className="field"><label>Открытие дверей</label><input className="input" type="datetime-local" name="doorsOpenAt" required/></div></div><div className="form-grid two"><div className="field"><label>Начало продаж</label><input className="input" type="datetime-local" name="salesStart" required/></div><div className="field"><label>Окончание продаж</label><input className="input" type="datetime-local" name="salesEnd" required/></div></div><div className="form-grid two"><div className="field"><label>Площадка</label><input className="input" name="venueName" required/></div><div className="field"><label>Город</label><input className="input" name="city" required/></div></div><div className="field"><label>Адрес</label><input className="input" name="address" required/></div><label className="option"><span><strong>Скопировать гостевые списки</strong><small>Названия, столы и лимиты сохранятся, но будут созданы новые безопасные ссылки.</small></span><input type="checkbox" name="copyGuestLists" defaultChecked/></label><label className="option"><span><strong>Скопировать ссылки промоутеров</strong><small>Комиссии, квоты и назначения сохранятся с новыми ссылками.</small></span><input type="checkbox" name="copyPromoters" defaultChecked/></label>{error&&<div className="toast">{error}</div>}<button className="btn" disabled={busy}>{busy?"Копируем...":"Создать копию мероприятия"}</button></form>;
}
