"use client";

import {useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {defaultGuestFields,guestFieldKeys,type GuestFieldConfig,type GuestFieldKey} from "@/lib/event-guest-fields";
import {eventTypeLabels,eventTypeValues,type EventType} from "@/lib/event-type";
import type {Locale} from "@/lib/i18n";
import styles from "./create-event-form.module.css";

type TabId="details"|"sales"|"buyer"|"review";
type AdmissionMode="GENERAL_ADMISSION"|"RESERVED_SEATING";
type PricingMode="FIXED"|"SCHEDULED";
const tabs:Array<{id:TabId;label:string}>=[{id:"details",label:"О мероприятии"},{id:"sales",label:"Продажа"},{id:"buyer",label:"Оформление заказа"},{id:"review",label:"Проверка и запуск"}];
const fieldLabels:Record<GuestFieldKey,string>={firstName:"Имя",lastName:"Фамилия",phone:"Телефон",email:"Email",birthDate:"Дата рождения",city:"Город проживания",facebook:"Facebook",instagram:"Instagram"};

export function CreateEventForm(){
 const router=useRouter();
 const[busy,setBusy]=useState(false),[error,setError]=useState("");
 const[activeTab,setActiveTab]=useState<TabId>("details"),[invalidTabs,setInvalidTabs]=useState<TabId[]>([]);
 const[admissionMode,setAdmissionMode]=useState<AdmissionMode>("GENERAL_ADMISSION");
 const[pricingMode,setPricingMode]=useState<PricingMode>("FIXED");
 const[salesMode,setSalesMode]=useState<"INSTANT"|"APPROVAL_REQUIRED">("INSTANT");
 const[customerLocale,setCustomerLocale]=useState<Locale>("ru");
 const[guestFields,setGuestFields]=useState<GuestFieldConfig>(defaultGuestFields);
 const[eventTypes,setEventTypes]=useState<EventType[]>([]);
 const activeIndex=tabs.findIndex(tab=>tab.id===activeTab);
 const progress=Math.round(((activeIndex+1)/tabs.length)*100);
 const activeLabel=useMemo(()=>tabs[activeIndex]?.label??"",[activeIndex]);

 function toggleType(type:EventType){setEventTypes(current=>current.includes(type)?current.filter(item=>item!==type):[...current,type]);}
 function updateField(key:GuestFieldKey,part:"visible"|"required",value:boolean){setGuestFields(current=>({...current,[key]:{...current[key],[part]:value,...(part==="visible"&&!value?{required:false}:{})}}));}
 function go(tab:TabId){setActiveTab(tab);window.scrollTo({top:0,behavior:"smooth"});}
 function next(){if(activeIndex<tabs.length-1)go(tabs[activeIndex+1].id);}
 function previous(){if(activeIndex>0)go(tabs[activeIndex-1].id);}
 function validate(form:HTMLFormElement){
  const invalid=Array.from(form.elements).filter((el):el is HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement=>el instanceof HTMLInputElement||el instanceof HTMLTextAreaElement||el instanceof HTMLSelectElement).filter(el=>!el.checkValidity());
  const tabsWithErrors=Array.from(new Set(invalid.map(el=>el.closest<HTMLElement>("[data-tab]")?.dataset.tab).filter(Boolean))) as TabId[];
  if(!eventTypes.length&&!tabsWithErrors.includes("details"))tabsWithErrors.unshift("details");
  setInvalidTabs(tabsWithErrors);
  if(!eventTypes.length){go("details");setError("Выберите хотя бы один тип мероприятия");return false;}
  if(invalid.length){const first=invalid[0];const tab=first.closest<HTMLElement>("[data-tab]")?.dataset.tab as TabId|undefined;if(tab)go(tab);setTimeout(()=>{first.focus();first.reportValidity();},0);return false;}
  return true;
 }
 async function submit(event:React.FormEvent<HTMLFormElement>){
  event.preventDefault();if(!validate(event.currentTarget))return;setBusy(true);setError("");
  try{
   const form=new FormData(event.currentTarget);let posterUrl="/assets/noa-live-tel-aviv.png";const poster=form.get("poster");
   if(poster instanceof File&&poster.size){const upload=new FormData();upload.set("poster",poster);const r=await fetch("/api/uploads",{method:"POST",body:upload});const d=await r.json();if(!r.ok)throw new Error(d.error||"Ошибка загрузки афиши");posterUrl=d.url;}
   const date=(name:string)=>new Date(String(form.get(name))).toISOString();
   const description=`${String(form.get("description")||"")}\n<!--ATLAS_EVENT_TYPES:${eventTypes.join(",")}-->`;
   const payload={title:form.get("title"),slug:form.get("slug"),description,primaryLanguage:form.get("primaryLanguage"),catalogVisibility:form.get("catalogVisibility"),customerCommunicationLocale:form.get("customerCommunicationLocale"),startsAt:date("startsAt"),doorsOpenAt:date("doorsOpenAt"),venueName:form.get("venueName"),city:form.get("city"),address:form.get("address"),mapEnabled:admissionMode==="RESERVED_SEATING",salesMode,...(salesMode==="APPROVAL_REQUIRED"?{approvalInstructions:String(form.get("approvalInstructions")||"")}:{}) ,posterUrl,categoryName:form.get("categoryName"),categoryDescription:form.get("categoryDescription"),categoryColor:form.get("categoryColor"),priceMinor:Math.round(Number(form.get("price"))*100),capacity:Number(form.get("capacity")),pricingMode,salesStart:date("salesStart"),salesEnd:date("salesEnd"),earlyBirdPriceMinor:pricingMode==="SCHEDULED"?Math.round(Number(form.get("earlyBirdPrice"))*100):undefined,earlyBirdEndsAt:pricingMode==="SCHEDULED"?date("earlyBirdEndsAt"):undefined,maxPerOrder:Number(form.get("maxPerOrder")),guestFields};
   const response=await fetch("/api/admin/events",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error||"Не удалось создать мероприятие");
   router.push(admissionMode==="RESERVED_SEATING"?`/office/events/${data.id}#venue-map`:`/office/events/${data.id}`);router.refresh();
  }catch(e){setError(e instanceof Error?e.message:"Ошибка");setBusy(false);}
 }
 return <form onSubmit={submit} noValidate className={`${styles.wizardShell} ${busy?"loading":""}`}>
  <nav className={styles.tabBar} aria-label="Разделы создания мероприятия">{tabs.map((tab,index)=><button key={tab.id} type="button" className={`${styles.tabButton} ${activeTab===tab.id?styles.tabButtonActive:""}`} onClick={()=>go(tab.id)}><span className={styles.tabIndex}>{String(index+1).padStart(2,"0")}</span><span>{tab.label}</span>{invalidTabs.includes(tab.id)&&<i className={styles.tabError}/>}</button>)}</nav>
  <div className={styles.contentGrid}><div className={styles.panelViewport}>
   <section data-tab="details" className={`panel form wizard-section ${activeTab!=="details"?styles.tabPanelInactive:""}`}><div className="wizard-heading"><span>01</span><div><h2>О мероприятии</h2><p>Что увидит покупатель и по каким фильтрам найдёт событие.</p></div></div>
    <div className="field"><label>Название мероприятия</label><input className="input" name="title" required/></div><div className="field"><label>Адрес страницы</label><input className="input" name="slug" pattern="[a-z0-9-]+" required placeholder="event-name-2026"/></div><div className="field"><label>Описание</label><textarea name="description" rows={5} required minLength={20}/></div>
    <div className="field"><label>Тип мероприятия — можно выбрать несколько</label><div className="choice-grid">{eventTypeValues.map(type=><button key={type} type="button" className={`choice-card ${eventTypes.includes(type)?"selected":""}`} onClick={()=>toggleType(type)}><strong>{eventTypeLabels.ru[type]}</strong><small>{eventTypes.includes(type)?"Выбрано":"Добавить в фильтры"}</small></button>)}</div><small className="muted">Например, событие может одновременно отображаться в фильтрах «Концерт» и «Комедия».</small></div>
    <div className="form-grid three"><div className="field"><label>Основной язык контента</label><select name="primaryLanguage" defaultValue="" required onChange={event=>{const suggested=event.target.value.toLowerCase();if(suggested==="ru"||suggested==="he"||suggested==="en")setCustomerLocale(suggested);}}><option value="" disabled>Выберите язык</option><option value="RU">Русский</option><option value="HE">Иврит</option><option value="EN">Английский</option><option value="AR">Арабский</option><option value="MULTILINGUAL">Несколько языков</option><option value="NO_LANGUAGE_BARRIER">Без языкового барьера</option><option value="OTHER">Другой</option></select></div><div className="field"><label>Язык покупателей и сообщений</label><select name="customerCommunicationLocale" value={customerLocale} required onChange={event=>setCustomerLocale(event.target.value as Locale)}><option value="ru">Русский</option><option value="he">עברית</option><option value="en">English</option></select><small className="muted">Checkout, билеты, email, SMS, возвраты и напоминания.</small></div><div className="field"><label>Видимость в каталоге</label><select name="catalogVisibility" defaultValue="TARGETED"><option value="TARGETED">Подходящей аудитории</option><option value="PUBLIC">Всем</option><option value="DIRECT_ONLY">Только по ссылке</option></select></div></div>
    <div className="field"><label>Афиша</label><input className="input" name="poster" type="file" accept="image/jpeg,image/png,image/webp"/></div><div className="form-grid two"><div className="field"><label>Начало</label><input className="input" name="startsAt" type="datetime-local" required/></div><div className="field"><label>Открытие дверей</label><input className="input" name="doorsOpenAt" type="datetime-local" required/></div></div><div className="form-grid two"><div className="field"><label>Площадка</label><input className="input" name="venueName" required/></div><div className="field"><label>Город</label><input className="input" name="city" required/></div></div><div className="field"><label>Адрес</label><input className="input" name="address" required/></div>
   </section>
   <section data-tab="sales" className={`panel form wizard-section ${activeTab!=="sales"?styles.tabPanelInactive:""}`}><div className="wizard-heading"><span>02</span><div><h2>Продажа</h2><p>Формат выбора, билет, цена и схема зала.</p></div></div><div className="choice-grid"><button type="button" className={`choice-card ${admissionMode==="GENERAL_ADMISSION"?"selected":""}`} onClick={()=>setAdmissionMode("GENERAL_ADMISSION")}><strong>Без схемы зала</strong><small>Тип и количество билетов.</small></button><button type="button" className={`choice-card ${admissionMode==="RESERVED_SEATING"?"selected":""}`} onClick={()=>setAdmissionMode("RESERVED_SEATING")}><strong>С выбором мест</strong><small>Столы, диваны, ряды и места.</small></button></div>
    {admissionMode==="RESERVED_SEATING"&&<div id="venue-map" className="panel" style={{background:"#f8fafc"}}><span className="eyebrow">Карта зала</span><h3>Схема является частью этого раздела</h3><p className="muted">Сначала создаётся черновик и первая категория билета, затем редактор откроет карту здесь же в рабочем пространстве мероприятия. Места должны быть назначены существующим категориям билетов.</p><div className="row"><span className="pill">1. Создать категории</span><span className="pill">2. Построить карту</span><span className="pill">3. Назначить билеты местам</span></div></div>}
    <div className="form-grid three"><div className="field"><label>Название билета</label><input className="input" name="categoryName" defaultValue="General Admission" required/></div><div className="field"><label>Количество</label><input className="input" name="capacity" type="number" min="1" required/></div><div className="field"><label>Цвет</label><input className="input" name="categoryColor" type="color" defaultValue="#2563EB"/></div></div><div className="field"><label>Что входит</label><textarea name="categoryDescription" rows={2}/></div>
    <div className="pricing-switch"><button type="button" className={pricingMode==="FIXED"?"active":""} onClick={()=>setPricingMode("FIXED")}>Фиксированная цена</button><button type="button" className={pricingMode==="SCHEDULED"?"active":""} onClick={()=>setPricingMode("SCHEDULED")}>Изменение цены</button></div>{pricingMode==="FIXED"?<div className="field"><label>Цена, ₪</label><input className="input" name="price" type="number" min="0" step="0.01" required/></div>:<div className="form-grid three"><div className="field"><label>Ранняя цена</label><input className="input" name="earlyBirdPrice" type="number" min="0" step="0.01" required/></div><div className="field"><label>До</label><input className="input" name="earlyBirdEndsAt" type="date" required/></div><div className="field"><label>Основная цена</label><input className="input" name="price" type="number" min="0" step="0.01" required/></div></div>}<div className="form-grid three"><div className="field"><label>Начало продаж</label><input className="input" name="salesStart" type="date" required/></div><div className="field"><label>Конец продаж</label><input className="input" name="salesEnd" type="date" required/></div><div className="field"><label>Максимум в заказе</label><input className="input" name="maxPerOrder" type="number" min="1" max="20" defaultValue="10" required/></div></div>
   </section>
   <section data-tab="buyer" className={`panel form wizard-section ${activeTab!=="buyer"?styles.tabPanelInactive:""}`}><div className="wizard-heading"><span>03</span><div><h2>Оформление заказа</h2><p>Выдача билета и данные покупателя.</p></div></div><label className="option"><span><strong>Сразу после оплаты</strong><small>Автоматический QR-билет.</small></span><input type="radio" checked={salesMode==="INSTANT"} onChange={()=>setSalesMode("INSTANT")}/></label><label className="option"><span><strong>После одобрения</strong><small>Сначала заявка.</small></span><input type="radio" checked={salesMode==="APPROVAL_REQUIRED"} onChange={()=>setSalesMode("APPROVAL_REQUIRED")}/></label>{salesMode==="APPROVAL_REQUIRED"&&<div className="field"><label>Инструкция покупателю</label><textarea name="approvalInstructions" rows={2}/></div>}<div className="table-wrap"><table><thead><tr><th>Поле</th><th>Показывать</th><th>Обязательно</th></tr></thead><tbody>{guestFieldKeys.map(key=><tr key={key}><td>{fieldLabels[key]}</td><td><input type="checkbox" checked={guestFields[key].visible} disabled={key==="firstName"||key==="phone"} onChange={e=>updateField(key,"visible",e.target.checked)}/></td><td><input type="checkbox" checked={guestFields[key].required} disabled={!guestFields[key].visible||key==="firstName"||key==="phone"} onChange={e=>updateField(key,"required",e.target.checked)}/></td></tr>)}</tbody></table></div>
   </section>
   <section data-tab="review" className={`panel form wizard-section ${activeTab!=="review"?styles.tabPanelInactive:""}`}><div className="wizard-heading"><span>04</span><div><h2>Проверка и запуск</h2><p>Финальная проверка перед созданием черновика.</p></div></div><div className="summary-list"><p><strong>Типы:</strong> {eventTypes.length?eventTypes.map(type=>eventTypeLabels.ru[type]).join(", "):"не выбраны"}</p><p><strong>Формат:</strong> {admissionMode==="RESERVED_SEATING"?"с выбором мест":"без схемы"}</p><p><strong>Цена:</strong> {pricingMode==="SCHEDULED"?"изменяется по расписанию":"фиксированная"}</p><p><strong>Выдача:</strong> {salesMode==="APPROVAL_REQUIRED"?"после одобрения":"сразу после оплаты"}</p></div>{admissionMode==="RESERVED_SEATING"&&<div className="toast">После создания черновика автоматически откроется рабочая область карты для назначения категорий местам.</div>}
   </section>
  </div><aside className={`panel ${styles.summary}`}><div><span className="eyebrow">Создание мероприятия</span><h3>{activeLabel}</h3></div><div className={styles.summaryList}><div className={styles.summaryItem}><span>Типы</span><strong>{eventTypes.length?eventTypes.length:"не выбраны"}</strong></div><div className={styles.summaryItem}><span>Формат</span><strong>{admissionMode==="RESERVED_SEATING"?"С местами":"Без схемы"}</strong></div><div className={styles.summaryItem}><span>Выдача</span><strong>{salesMode==="APPROVAL_REQUIRED"?"После одобрения":"Сразу"}</strong></div></div><div><div className="row between"><small className="muted">Прогресс</small><strong>{progress}%</strong></div><div className={styles.progressTrack}><div className={styles.progressValue} style={{width:`${progress}%`}}/></div></div></aside></div>
  {error&&<div className="toast">{error}</div>}<div className={styles.footerNav}><button type="button" className={styles.secondaryButton} onClick={previous} disabled={activeIndex===0}>Назад</button><div className={styles.footerActions}>{activeIndex<tabs.length-1?<button type="button" className="btn" onClick={next}>Далее</button>:<button className="btn" disabled={busy}>{busy?"Создаём...":"Создать черновик"}</button>}</div></div>
 </form>;
}
