"use client";

import { useMemo, useRef, useState } from "react";
import { Bot, Loader2, Mic, Send, Square, X } from "lucide-react";
import { useLocale } from "@/components/locale-provider";
import styles from "./event-ai-assistant.module.css";

type EventContext={id:string;title:string;status:string;salesMode:string;startsAt:string;venue:string;categories:Array<{id:string;name:string;priceMinor:number;capacity:number;sold:number;pricingMode:string}>};
type PlanItem={id:string;title:string;detail:string;selectable:boolean};type Plan={summary:string;changes:PlanItem[];mode:"demo"|"live"};
const copy={
 ru:{partner:"ваш рабочий партнёр",talk:"Поговорить с Atlas",looked:"Atlas уже посмотрел мероприятие",see:"Я вижу настройки, билеты и режим продаж.",context:"Контекст мероприятия загружен",seats:"мест",listening:"Atlas слушает",listeningHelp:"Говорите. Нажмите «Стоп», когда закончите.",transcribing:"Распознаю голос",transcribingHelp:"Текст появится в поле ввода.",working:"Atlas работает над задачей",workingHelp:"Проверяю данные мероприятия и готовлю результат.",suggests:"Atlas предлагает",placeholder:"Напишите Atlas, что нужно сделать…",stop:"Остановить запись",record:"Записать голосом",recordHint:"Идёт запись. При этом текстовое поле остаётся доступным.",hint:"Enter - отправить · голос можно остановить той же кнопкой.",askError:"Atlas не смог обработать запрос",voiceError:"Не удалось распознать голос",recordError:"Не удалось начать запись. Попробуйте ещё раз.",emptyRecord:"Запись получилась пустой. Проверьте микрофон и попробуйте ещё раз.",permissionError:"Браузер не дал доступ к микрофону или запись не запустилась."},
 he:{partner:"השותף שלכם לעבודה",talk:"לדבר עם Atlas",looked:"Atlas כבר בדקה את האירוע",see:"אני רואה את ההגדרות, הכרטיסים ושיטת המכירה.",context:"פרטי האירוע נטענו",seats:"מקומות",listening:"Atlas מקשיבה",listeningHelp:"דברו ולחצו על ״עצירה״ כשתסיימו.",transcribing:"מתמללת את ההקלטה",transcribingHelp:"הטקסט יופיע בשדה ההקלדה.",working:"Atlas עובדת על הבקשה",workingHelp:"בודקת את נתוני האירוע ומכינה תשובה.",suggests:"ההצעה של Atlas",placeholder:"כתבו ל־Atlas מה תרצו לעשות…",stop:"עצירת הקלטה",record:"הקלטה קולית",recordHint:"ההקלטה פעילה. אפשר להמשיך להשתמש גם בשדה הטקסט.",hint:"Enter - שליחה · לחיצה נוספת על כפתור הקול תעצור את ההקלטה.",askError:"Atlas לא הצליחה לעבד את הבקשה",voiceError:"לא הצלחנו לתמלל את ההקלטה",recordError:"לא הצלחנו להתחיל את ההקלטה. נסו שוב.",emptyRecord:"ההקלטה ריקה. בדקו את המיקרופון ונסו שוב.",permissionError:"הדפדפן לא אישר גישה למיקרופון או שההקלטה לא התחילה."},
 en:{partner:"your work partner",talk:"Talk to Atlas",looked:"Atlas has reviewed the event",see:"I can see the settings, tickets, and sales mode.",context:"Event context loaded",seats:"seats",listening:"Atlas is listening",listeningHelp:"Speak, then press Stop when you are done.",transcribing:"Transcribing voice",transcribingHelp:"The text will appear in the input field.",working:"Atlas is working on the task",workingHelp:"Reviewing the event data and preparing a result.",suggests:"Atlas suggests",placeholder:"Tell Atlas what you want to do…",stop:"Stop recording",record:"Record voice",recordHint:"Recording is active. The text field remains available.",hint:"Enter - send · press the voice button again to stop recording.",askError:"Atlas could not process the request",voiceError:"Could not transcribe voice",recordError:"Could not start recording. Try again.",emptyRecord:"The recording is empty. Check the microphone and try again.",permissionError:"The browser did not allow microphone access or recording could not start."}
} as const;
function dateLocale(locale:"ru"|"he"|"en"){return locale==="he"?"he-IL":locale==="en"?"en-IL":"ru-IL";}

export function EventAtlasAssistant({event}:{event:EventContext}){
 const{locale,dir}=useLocale();const text=copy[locale];const[open,setOpen]=useState(false);const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);const[recording,setRecording]=useState(false);const[transcribing,setTranscribing]=useState(false);const[error,setError]=useState("");const[plan,setPlan]=useState<Plan|null>(null);const recorderRef=useRef<MediaRecorder|null>(null);const streamRef=useRef<MediaStream|null>(null);const chunksRef=useRef<Blob[]>([]);
 const categorySummary=useMemo(()=>event.categories.map(item=>`${item.name}: ${item.capacity} ${text.seats}`).join(" · "),[event.categories,text.seats]);
 function releaseMicrophone(){streamRef.current?.getTracks().forEach(track=>track.stop());streamRef.current=null;recorderRef.current=null;setRecording(false);}
 async function ask(){const prompt=message.trim();if(!prompt||busy)return;setBusy(true);setError("");setPlan(null);try{const response=await fetch(`/api/admin/events/${event.id}/ai-assistant`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({prompt,locale})});const data=await response.json();if(!response.ok)throw new Error(data.error||text.askError);setPlan(data.plan);}catch(cause){setError(cause instanceof Error?cause.message:text.askError);}finally{setBusy(false)}}
 async function transcribe(blob:Blob){setTranscribing(true);setError("");try{const form=new FormData();form.append("audio",new File([blob],"atlas-voice.webm",{type:blob.type||"audio/webm"}));form.append("language",locale);const response=await fetch(`/api/admin/events/${event.id}/ai-assistant/transcribe`,{method:"POST",body:form});const data=await response.json();if(!response.ok)throw new Error(data.error||text.voiceError);setMessage(current=>current.trim()?`${current.trim()} ${data.text}`:data.text);}catch(cause){setError(cause instanceof Error?cause.message:text.voiceError);}finally{setTranscribing(false)}}
 async function startRecording(){if(recording||transcribing||busy)return;setError("");try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});streamRef.current=stream;const supported=["audio/webm;codecs=opus","audio/webm","audio/mp4"].find(type=>MediaRecorder.isTypeSupported(type));const recorder=supported?new MediaRecorder(stream,{mimeType:supported}):new MediaRecorder(stream);recorderRef.current=recorder;chunksRef.current=[];recorder.ondataavailable=e=>{if(e.data.size>0)chunksRef.current.push(e.data)};recorder.onerror=()=>{releaseMicrophone();setError(text.recordError)};recorder.onstop=()=>{const blob=new Blob(chunksRef.current,{type:recorder.mimeType||"audio/webm"});releaseMicrophone();if(blob.size>0)void transcribe(blob);else setError(text.emptyRecord)};recorder.start(250);setRecording(true);}catch{releaseMicrophone();setError(text.permissionError)}}
 function stopRecording(){const recorder=recorderRef.current;if(recorder?.state==="recording")recorder.stop();else releaseMicrophone();}
 function close(){if(recording)stopRecording();else releaseMicrophone();setOpen(false);}
 return <><section className={styles.hero} dir={dir}><div className={styles.topline}><div className={styles.brandMark}><strong>Atlas</strong><span>{text.partner}</span></div><button className={styles.openButton} type="button" onClick={()=>setOpen(true)}>{text.talk}</button></div><div className={styles.main}><div><h2 className={styles.title}>{text.looked}</h2><p className={styles.description}>{text.see}</p></div></div></section>{open&&<div className={styles.overlay} role="dialog" aria-modal="true"><aside className={styles.drawer} dir={dir}><header className={styles.drawerHeader}><div className={styles.drawerBrand}><span className={styles.iconBox}><Bot size={22}/></span><div><strong>Atlas</strong><small>{event.title}</small></div></div><button type="button" className={styles.closeButton} onClick={close} aria-label="Close"><X size={19}/></button></header><div className={styles.drawerBody}><div className={styles.context}><div><strong>{text.context}</strong><p>{event.venue} · <bdi>{new Date(event.startsAt).toLocaleString(dateLocale(locale))}</bdi><br/>{categorySummary}</p></div></div>{recording&&<div className={styles.loading}><Loader2 className="spin" size={20}/><div><strong>{text.listening}</strong><span>{text.listeningHelp}</span></div></div>}{transcribing&&<div className={styles.loading}><Loader2 className="spin" size={20}/><div><strong>{text.transcribing}</strong><span>{text.transcribingHelp}</span></div></div>}{busy&&<div className={styles.loading}><Loader2 className="spin" size={20}/><div><strong>{text.working}</strong><span>{text.workingHelp}</span></div></div>}{error&&<div className={styles.error}>{error}</div>}{plan&&<div className={styles.plan}><div className={styles.planIntro}><div><strong>{text.suggests}</strong><p>{plan.summary}</p></div><span>{plan.mode==="live"?"LIVE":"DEMO"}</span></div>{plan.changes.map(item=><div className={styles.change} key={item.id}><div><strong>{item.title}</strong><p>{item.detail}</p></div></div>)}</div>}</div><footer className={styles.drawerFooter}><div className={styles.composer}><textarea value={message} onChange={e=>setMessage(e.target.value)} rows={3} placeholder={text.placeholder} disabled={busy||transcribing}/><button className={styles.micButton} type="button" onClick={recording?stopRecording:startRecording} disabled={busy||transcribing} title={recording?text.stop:text.record}>{recording?<Square size={19}/>:<Mic size={20}/>}</button><button className={styles.sendButton} type="button" onClick={()=>void ask()} disabled={busy||transcribing||!message.trim()}>{busy?<Loader2 className="spin" size={18}/>:<Send size={18}/>}</button></div><small className={styles.hint}>{recording?text.recordHint:text.hint}</small></footer></aside></div>}</>;
}
