"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { useLocale } from "@/components/locale-provider";

type Props={eventId:string;initialMode:"INSTANT"|"APPROVAL_REQUIRED";initialInstructions:string|null;initialRejectionMessage:string};
const copy={ru:{saved:"Изменения сохранены",error:"Не удалось сохранить изменения",eyebrow:"Покупатель и оформление",title:"Способ продажи",instant:"Автоматическая покупка",instantHelp:"После оплаты клиент сразу получает билет и QR-код.",approval:"Только после одобрения",approvalHelp:"Сначала заявка, затем разрешение на оплату и получение билета.",instructions:"Что клиент должен указать в заявке",rejection:"Сообщение клиенту при отказе",save:"Сохранить способ продажи"},he:{saved:"השינויים נשמרו",error:"לא הצלחנו לשמור את השינויים",eyebrow:"רוכש ותהליך ההזמנה",title:"אופן המכירה",instant:"רכישה אוטומטית",instantHelp:"לאחר התשלום הלקוח מקבל מיד כרטיס וקוד QR.",approval:"רק לאחר אישור",approvalHelp:"קודם נשלחת בקשה, לאחר מכן ניתן אישור לתשלום ולהנפקת הכרטיס.",instructions:"מה הלקוח צריך לציין בבקשה",rejection:"הודעה ללקוח במקרה של דחייה",save:"שמירת אופן המכירה"},en:{saved:"Changes saved",error:"Could not save changes",eyebrow:"Buyer and checkout",title:"Sales flow",instant:"Instant purchase",instantHelp:"After payment, the customer immediately receives the ticket and QR code.",approval:"Approval required",approvalHelp:"A request is submitted first, then payment and ticket delivery are enabled after approval.",instructions:"What the customer should include in the request",rejection:"Message shown to the customer when rejected",save:"Save sales flow"}} as const;
export function EventSalesModeManager({eventId,initialMode,initialInstructions,initialRejectionMessage}:Props){const {locale}=useLocale();const text=copy[locale];const router=useRouter();const[mode,setMode]=useState(initialMode);const[instructions,setInstructions]=useState(initialInstructions??"");const[rejectionMessage,setRejectionMessage]=useState(initialRejectionMessage);const[message,setMessage]=useState("");async function save(){setMessage("");const response=await fetch(`/api/admin/events/${eventId}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"sales",salesMode:mode,askApprovalQuestion:mode==="APPROVAL_REQUIRED"&&Boolean(instructions.trim()),approvalInstructions:mode==="APPROVAL_REQUIRED"?instructions:undefined,rejectionMessage})});setMessage(response.ok?text.saved:text.error);if(response.ok)router.refresh()}return <section className="panel form"><span className="eyebrow">{text.eyebrow}</span><h2>{text.title}</h2><div className="choice-grid compact"><button type="button" className={`choice-card ${mode==="INSTANT"?"selected":""}`} onClick={()=>setMode("INSTANT")}><i>⚡</i><strong>{text.instant}</strong><small>{text.instantHelp}</small></button><button type="button" className={`choice-card ${mode==="APPROVAL_REQUIRED"?"selected":""}`} onClick={()=>setMode("APPROVAL_REQUIRED")}><i>✓</i><strong>{text.approval}</strong><small>{text.approvalHelp}</small></button></div>{mode==="APPROVAL_REQUIRED"&&<><div className="field"><label>{text.instructions}</label><textarea rows={3} value={instructions} onChange={event=>setInstructions(event.target.value)}/></div><div className="field"><label>{text.rejection}</label><textarea rows={4} value={rejectionMessage} onChange={event=>setRejectionMessage(event.target.value)}/></div></>}<button type="button" className="btn" onClick={()=>void save()}>{text.save}</button>{message&&<div className="toast" role="status">{message}</div>}</section>;}
