"use client";

import { useMemo, useState } from "react";

type SourceSummary={id:string;name:string;sourceKey:string;platformKey:string|null;total:number;used:number;cancelled:number;lastImportedAt:string|null;valueCardCreatedTotal:number;valueCardLastCreated:number;valueCardLastExisting:number;valueCardLastSkipped:number;valueCardLastFailed:number;valueCardLastSyncedAt:string|null};
type Mapping=Partial<Record<"scanCode"|"externalTicketId"|"externalOrderId"|"holderName"|"firstName"|"lastName"|"phone"|"email"|"birthDate"|"city"|"gender"|"ticketType"|"price"|"priceMinor"|"currency"|"status"|"organizerConsent",string>>;
type ConsentMode="NONE"|"ALL"|"COLUMN";
type Preview={fileName:string;rowCount:number;delimiter:string;headers:string[];detectedMapping:Mapping;requiresMapping:boolean;sample:Record<string,string>[]};
type ImportResult={ok:boolean;rowCount:number;processedCount:number;insertedCount:number;updatedCount:number;errorCount:number;errors?:Array<{row:number;error:string}>;source?:{id:string;name:string;sourceKey:string;platformKey:string|null};customerSync?:{customers:number;created:number;updated:number}};
type ValueCardBatch={ok:boolean;processed:number;created:number;existing:number;skipped:number;failed:number;errors?:Array<{ticketId:string;reason:string}>;nextCursor:string|null};
type ValueCardTotals={created:number;existing:number;skipped:number;failed:number};

const mappingFields:Array<{key:keyof Mapping;label:string;required?:boolean}>=[
 {key:"scanCode",label:"QR / Barcode",required:true},{key:"externalTicketId",label:"ID билета"},{key:"externalOrderId",label:"ID заказа"},{key:"holderName",label:"Полное имя"},{key:"firstName",label:"Имя"},{key:"lastName",label:"Фамилия"},{key:"phone",label:"Телефон"},{key:"email",label:"Email"},{key:"birthDate",label:"Дата рождения"},{key:"city",label:"Город"},{key:"gender",label:"Пол"},{key:"ticketType",label:"Тип билета"},{key:"price",label:"Цена"},{key:"currency",label:"Валюта"},{key:"status",label:"Статус"},
];

export function ExternalTicketImportManager({eventId,sources,valueCardEnabled}:{eventId:string;sources:SourceSummary[];valueCardEnabled:boolean}){
 const [selectedSourceId,setSelectedSourceId]=useState(sources[0]?.id||"NEW");
 const selectedSource=useMemo(()=>sources.find(source=>source.id===selectedSourceId)||null,[sources,selectedSourceId]);
 const [sourceName,setSourceName]=useState("");const [platformKey,setPlatformKey]=useState("OTHER");const [file,setFile]=useState<File|null>(null);const [preview,setPreview]=useState<Preview|null>(null);const [mapping,setMapping]=useState<Mapping>({});const [consentMode,setConsentMode]=useState<ConsentMode>("NONE");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [result,setResult]=useState<ImportResult|null>(null);const [valueCardBusySource,setValueCardBusySource]=useState("");const [valueCardError,setValueCardError]=useState("");const [valueCardResult,setValueCardResult]=useState<ValueCardTotals|null>(null);
 const effectiveName=selectedSource?.name||sourceName.trim();
 const importBlockReason=!mapping.scanCode?"Выберите колонку QR / Barcode.":!effectiveName?"Укажите название источника.":consentMode==="COLUMN"&&!mapping.organizerConsent?"Укажите колонку согласия.":"";

 async function previewFile(){if(!file)return setError("Выберите CSV файл");setBusy(true);setError("");setResult(null);try{const form=new FormData();form.set("file",file);const response=await fetch(`/api/office/events/${eventId}/external-tickets/preview`,{method:"POST",body:form});const data=await response.json() as Preview&{error?:string};if(!response.ok)throw new Error(data.error||"Не удалось прочитать файл");setPreview(data);setMapping(data.detectedMapping||{});setConsentMode(data.detectedMapping?.organizerConsent?"COLUMN":"NONE");}catch(cause){setPreview(null);setError(cause instanceof Error?cause.message:"Ошибка чтения файла");}finally{setBusy(false);}}
 async function runImport(){if(!file||!preview)return setError("Сначала проверьте файл");if(!mapping.scanCode)return setError("Выберите QR / Barcode");if(!effectiveName)return setError("Укажите название источника");if(consentMode==="COLUMN"&&!mapping.organizerConsent)return setError("Выберите колонку согласия");setBusy(true);setError("");setResult(null);setValueCardResult(null);setValueCardError("");try{const form=new FormData();form.set("file",file);form.set("sourceName",effectiveName);form.set("platformKey",selectedSource?.platformKey||platformKey);form.set("consentMode",consentMode);if(selectedSource)form.set("sourceKey",selectedSource.sourceKey);const mappingForImport=consentMode==="COLUMN"?mapping:{...mapping,organizerConsent:undefined};form.set("mapping",JSON.stringify(mappingForImport));const response=await fetch(`/api/office/events/${eventId}/external-tickets/import`,{method:"POST",body:form});const data=await response.json() as ImportResult&{error?:string};if(!response.ok)throw new Error(data.error||"Импорт не выполнен");setResult(data);}catch(cause){setError(cause instanceof Error?cause.message:"Ошибка импорта");}finally{setBusy(false);}}
 async function syncValueCard(sourceId:string){if(!valueCardEnabled||!sourceId||valueCardBusySource)return;setValueCardBusySource(sourceId);setValueCardError("");setValueCardResult(null);const totals:ValueCardTotals={created:0,existing:0,skipped:0,failed:0};let afterId:string|null=null;try{do{const response=await fetch(`/api/office/events/${eventId}/external-tickets/valuecard-sync`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sourceId,afterId})});const data=await response.json() as ValueCardBatch&{error?:string};if(!response.ok)throw new Error(data.error||"Не удалось синхронизировать ValueCard");totals.created+=data.created;totals.existing+=data.existing;totals.skipped+=data.skipped;totals.failed+=data.failed;afterId=data.nextCursor;}while(afterId);setValueCardResult(totals);setTimeout(()=>window.location.reload(),900);}catch(cause){setValueCardError(cause instanceof Error?cause.message:"Ошибка синхронизации ValueCard");}finally{setValueCardBusySource("");}}
 const importedSourceId=result?.source?.id||selectedSource?.id||"";const consentIncluded=consentMode==="ALL"||(consentMode==="COLUMN"&&Boolean(mapping.organizerConsent));
 return <div className="stack">
  {sources.length>0&&<section className="panel stack"><div><span className="eyebrow">Импортированные продажи</span><h2>Загруженные базы</h2><p className="muted">Эти данные read-only: Atlas не отправляет по ним билеты, письма и не запускает оплату или approve.</p></div><div className="stats">{sources.map(source=><div className="stat" key={source.id}><span className="muted">Imported</span><strong>{source.name}</strong><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:8,margin:"10px 0"}}><div><small className="muted">Билеты</small><b style={{display:"block",fontSize:22}}>{source.total}</b></div><div><small className="muted">Вошли</small><b style={{display:"block",fontSize:22}}>{source.used}</b></div><div><small className="muted">Отменены</small><b style={{display:"block",fontSize:22}}>{source.cancelled}</b></div><div><small className="muted">Новых ValueCard</small><b style={{display:"block",fontSize:22}}>{source.valueCardCreatedTotal}</b></div></div>{source.valueCardLastSyncedAt&&<small className="muted">Последняя синхронизация ValueCard: +{source.valueCardLastCreated} новых · {source.valueCardLastExisting} уже были{source.valueCardLastFailed?` · ${source.valueCardLastFailed} ошибок`:""} · {new Date(source.valueCardLastSyncedAt).toLocaleString("ru-RU")}</small>}{source.lastImportedAt&&<small className="muted">Последний импорт: {new Date(source.lastImportedAt).toLocaleString("ru-RU")}</small>}{valueCardEnabled&&<button className="btn secondary" type="button" disabled={Boolean(valueCardBusySource)} onClick={()=>void syncValueCard(source.id)}>{valueCardBusySource===source.id?"Синхронизируем...":"Синхронизировать с ValueCard"}</button>}</div>)}</div></section>}
  <section className="panel stack"><div><span className="eyebrow">Импорт</span><h2>Добавить базу продаж</h2><p className="muted">CSV/TXT импортируется как тихая read-only база для списка заказов и сканера.</p></div>
   {sources.length>0&&<label>База<select className="input" value={selectedSourceId} onChange={event=>{setSelectedSourceId(event.target.value);setPreview(null);setResult(null);}}>{sources.map(source=><option key={source.id} value={source.id}>{source.name}</option>)}<option value="NEW">+ Новая база</option></select></label>}
   {(!sources.length||selectedSourceId==="NEW")&&<div className="grid two"><label>Формат<select className="input" value={platformKey} onChange={event=>setPlatformKey(event.target.value)}><option value="EVENTER">Eventer</option><option value="BRAVO">Bravo</option><option value="WIX">Wix</option><option value="GOOUT">GoOut</option><option value="OTHER">Другой</option></select></label><label>Название базы<input className="input" value={sourceName} onChange={event=>setSourceName(event.target.value)} placeholder="Например продажи до перехода в Atlas"/></label></div>}
   <label>Файл<input className="input" type="file" accept=".csv,.txt,text/csv,text/plain" onChange={event=>{setFile(event.target.files?.[0]||null);setPreview(null);setResult(null);setError("");setConsentMode("NONE");}}/></label>
   <div className="row"><button className="btn secondary" type="button" disabled={!file||busy} onClick={()=>void previewFile()}>{busy?"Проверяем...":"Проверить файл"}</button>{file&&<span className="muted">{file.name}</span>}</div>
   {error&&<div className="toast"><strong>Не удалось продолжить</strong><p>{error}</p></div>}
   {preview&&<div className="stack"><div className="stats"><div className="stat"><span className="muted">Строк</span><strong>{preview.rowCount}</strong></div><div className="stat"><span className="muted">QR найден</span><strong>{mapping.scanCode?"Да":"Нет"}</strong></div><div className="stat"><span className="muted">Режим</span><strong>Read-only</strong></div></div>
    <section className="panel stack"><div><span className="eyebrow">Сопоставление</span><h3>Данные билета и клиента</h3></div><div className="grid two">{mappingFields.map(field=><label key={field.key}>{field.label}{field.required?" *":""}<select className="input" value={mapping[field.key]||""} onChange={event=>setMapping(current=>({...current,[field.key]:event.target.value||undefined}))}><option value="">Не импортировать</option>{preview.headers.map(header=><option key={header} value={header}>{header}</option>)}</select></label>)}</div>
     {valueCardEnabled&&<div className="toast stack"><strong>Согласие клиента для ValueCard</strong><label>Как учитывать согласие<select className="input" value={consentMode} onChange={event=>{const mode=event.target.value as ConsentMode;setConsentMode(mode);if(mode!=="COLUMN")setMapping(current=>({...current,organizerConsent:undefined}));}}><option value="NONE">Не передавать согласие</option><option value="ALL">Все клиенты в этом файле дали согласие</option><option value="COLUMN">Согласие указано в колонке</option></select></label>{consentMode==="COLUMN"&&<label>Колонка с согласием<select className="input" value={mapping.organizerConsent||""} onChange={event=>setMapping(current=>({...current,organizerConsent:event.target.value||undefined}))}><option value="">Выберите колонку</option>{preview.headers.map(header=><option key={header} value={header}>{header}</option>)}</select></label>}</div>}
    </section>
    {importBlockReason&&<div className="toast"><strong>Нужно проверить настройку</strong><p>{importBlockReason}</p></div>}
    <button className="btn" type="button" disabled={busy} onClick={()=>void runImport()}>{busy?"Импортируем...":`Импортировать ${preview.rowCount} билетов`}</button>
   </div>}
   {result&&<div className="toast"><strong>Импорт завершён</strong><p>Билетов новых: {result.insertedCount} · обновлено: {result.updatedCount} · ошибок: {result.errorCount}</p>{result.customerSync&&<p>Уникальных клиентов по телефону: {result.customerSync.customers} · новых профилей: {result.customerSync.created} · обновлено профилей: {result.customerSync.updated}</p>}{result.errorCount>0&&<p className="muted">Первые ошибки: {result.errors?.slice(0,3).map(item=>`строка ${item.row}: ${item.error}`).join("; ")}</p>}{valueCardEnabled&&consentIncluded&&importedSourceId&&<button className="btn" type="button" disabled={Boolean(valueCardBusySource)} onClick={()=>void syncValueCard(importedSourceId)}>{valueCardBusySource?"Синхронизируем...":"Синхронизировать клиентов с ValueCard"}</button>}<button className="btn secondary" type="button" onClick={()=>window.location.reload()}>Обновить данные</button></div>}
   {valueCardError&&<div className="toast"><strong>ValueCard</strong><p>{valueCardError}</p></div>}{valueCardResult&&<div className="toast"><strong>ValueCard завершён</strong><p>Добавлено: {valueCardResult.created} · уже были: {valueCardResult.existing} · пропущено: {valueCardResult.skipped} · ошибок: {valueCardResult.failed}</p></div>}
  </section>
 </div>;
}
