"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

type GuestRow={id:string;publicId:string;name:string;email:string;phone:string;tickets:number;used:number};
type Props={list:{id:string;label:string;active:boolean;publicPath:string;managePath:string;guestLimit:number;maxPerOrder:number;showAttendees:boolean;seatPoolLocked:boolean;startsAt:string|null;endsAt:string|null};guests:GuestRow[]};

function localDateTime(value:string|null){if(!value)return"";const d=new Date(value);const offset=d.getTimezoneOffset();return new Date(d.getTime()-offset*60000).toISOString().slice(0,16);}

export function GuestListDetailManager({list,guests}:Props){
 const router=useRouter();const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[copied,setCopied]=useState("");
 const origin=typeof window==="undefined"?"":window.location.origin;const publicUrl=`${origin}${list.publicPath}`;const manageUrl=`${origin}${list.managePath}`;
 async function post(payload:unknown){setBusy(true);setError("");try{const response=await fetch("/api/admin/guest-links",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok){setError(data.error||"Ошибка");return false}router.refresh();return true}finally{setBusy(false)}}
 async function copy(value:string,key:string){await navigator.clipboard.writeText(value);setCopied(key);window.setTimeout(()=>setCopied(""),1600)}
 async function remove(){if(!window.confirm(`Удалить гостевую ссылку «${list.label}»?`))return;const ok=await post({action:"delete",linkId:list.id});if(ok)router.push("/office/guest-lists")}
 return <div style={{display:"grid",gap:24}}>
  <div className="panel"><div className="row between"><div><span className="eyebrow">Ссылки</span><h2 style={{marginBottom:4}}>Доступ к гостевой ссылке</h2></div><span className="pill" style={list.active?{background:"#dcfae6",color:"#067647"}:{}}>{list.active?"Активна":"Отключена"}</span></div>
   <div style={{display:"grid",gap:14,marginTop:18}}><div><strong>Ссылка для гостей</strong><code style={{display:"block",marginTop:6,wordBreak:"break-all"}}>{publicUrl}</code><div className="row" style={{gap:8,marginTop:8,flexWrap:"wrap"}}><button className="btn secondary" type="button" onClick={()=>void copy(publicUrl,"public")}>{copied==="public"?"Скопировано":"Копировать"}</button><a className="btn secondary" href={list.publicPath} target="_blank" rel="noreferrer">Открыть как гость</a></div></div><div><strong>Ссылка управления</strong><p className="muted" style={{margin:"4px 0"}}>Через неё организатор видит участников и может вручную добавить гостя. Содержит защищённый token.</p><code style={{display:"block",wordBreak:"break-all"}}>{manageUrl}</code><div className="row" style={{gap:8,marginTop:8,flexWrap:"wrap"}}><button className="btn secondary" type="button" onClick={()=>void copy(manageUrl,"manage")}>{copied==="manage"?"Скопировано":"Копировать"}</button><a className="btn secondary" href={list.managePath} target="_blank" rel="noreferrer">Управление / добавить гостя</a></div></div></div>
   <div className="row" style={{gap:8,marginTop:16,flexWrap:"wrap"}}><button className="btn" disabled={busy} onClick={()=>void post({action:"toggle",linkId:list.id,active:!list.active})}>{list.active?"Отключить ссылку":"Включить ссылку"}</button><button className="btn secondary" disabled={busy} onClick={()=>void remove()}>Удалить</button></div>{error&&<div className="toast" style={{marginTop:12}}>{error}</div>}
  </div>

  <details className="panel"><summary style={{cursor:"pointer",fontWeight:700,fontSize:18}}>Настройки ссылки</summary><form style={{display:"grid",gap:14,marginTop:18}} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await post({action:"update",linkId:list.id,displayName:String(f.get("displayName")||""),guestLimit:Number(f.get("guestLimit")||list.guestLimit),maxPerOrder:Number(f.get("maxPerOrder")||1),showAttendees:f.get("showAttendees")==="on",startsAt:f.get("startsAt")||null,endsAt:f.get("endsAt")||null})}}>
   <div className="field"><label>Название ссылки</label><input className="input" name="displayName" defaultValue={list.label} required minLength={2}/></div><div className="row" style={{gap:14,flexWrap:"wrap"}}><div className="field" style={{flex:"1 1 160px"}}><label>Лимит гостей</label><input className="input" name="guestLimit" type="number" min="1" defaultValue={list.guestLimit} readOnly={list.seatPoolLocked}/>{list.seatPoolLocked&&<small className="muted">Для выбранных мест лимит равен количеству мест.</small>}</div><div className="field" style={{flex:"1 1 160px"}}><label>Макс. за одну регистрацию</label><input className="input" name="maxPerOrder" type="number" min="1" max="100" defaultValue={list.maxPerOrder}/></div></div><label className="row" style={{gap:10,alignItems:"center"}}><input name="showAttendees" type="checkbox" defaultChecked={list.showAttendees}/><strong>Показывать гостям, кто уже записался</strong></label><div className="row" style={{gap:14,flexWrap:"wrap"}}><div className="field" style={{flex:"1 1 220px"}}><label>Действует с</label><input className="input" name="startsAt" type="datetime-local" defaultValue={localDateTime(list.startsAt)}/></div><div className="field" style={{flex:"1 1 220px"}}><label>Действует до</label><input className="input" name="endsAt" type="datetime-local" defaultValue={localDateTime(list.endsAt)}/></div></div>{error&&<div className="toast">{error}</div>}<button className="btn dark" disabled={busy}>{busy?"Сохраняем...":"Сохранить настройки"}</button>
  </form></details>

  <div className="panel"><div className="row between"><div><span className="eyebrow">Гости</span><h2 style={{marginBottom:4}}>Участники ссылки</h2></div><span className="pill">{guests.length} заказов</span></div><div className="table-wrap" style={{marginTop:16}}><table><thead><tr><th>Гость</th><th>Контакты</th><th>Билеты</th><th>Прошли</th><th>Заказ</th></tr></thead><tbody>{guests.map(g=><tr key={g.id}><td><strong>{g.name}</strong></td><td>{g.phone}<br/><small>{g.email}</small></td><td>{g.tickets}</td><td>{g.used}</td><td><a href={`/office/orders/${g.publicId}`}>{g.publicId}</a></td></tr>)}{!guests.length&&<tr><td colSpan={5}>По этой ссылке пока нет гостей.</td></tr>}</tbody></table></div></div>
 </div>
}
