"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useLocale } from "@/components/locale-provider";
import type { GuestFieldConfig, GuestFieldKey } from "@/lib/event-guest-fields";

type Guest={id:string;name:string;phone:string|null;ticketStatus:string};
type ActionResponse={error?:string;emailQueued?:boolean;publicId?:string;status?:string;paymentUrl?:string};
const labels:Record<GuestFieldKey,string>={firstName:"Имя",lastName:"Фамилия",phone:"Телефон",email:"Email",birthDate:"Дата рождения",city:"Город проживания",facebook:"Facebook",instagram:"Instagram"};
const types:Partial<Record<GuestFieldKey,string>>={email:"email",phone:"tel"};
const SESSION_TTL_MS=30*60*1000;
function sessionFor(key:string){const now=Date.now();try{const raw=localStorage.getItem(key);if(raw){const parsed=JSON.parse(raw) as {id?:unknown;lastSeen?:unknown};if(typeof parsed.id==="string"&&typeof parsed.lastSeen==="number"&&now-parsed.lastSeen<SESSION_TTL_MS){localStorage.setItem(key,JSON.stringify({id:parsed.id,lastSeen:now}));return parsed.id;}}}catch{}const id=crypto.randomUUID();localStorage.setItem(key,JSON.stringify({id,lastSeen:now}));return id;}
function birthDateFromForm(form:FormData){
  const day=String(form.get("birthDay")||"").trim();
  const month=String(form.get("birthMonth")||"").trim();
  const year=String(form.get("birthYear")||"").trim();
  if(!day&&!month&&!year)return "";
  if(!/^\d{1,2}$/.test(day)||!/^\d{1,2}$/.test(month)||!/^\d{4}$/.test(year))throw new Error("Введите дату рождения полностью: день, месяц и год");
  const d=Number(day),m=Number(month),y=Number(year);const date=new Date(Date.UTC(y,m-1,d));
  if(y<1900||y>new Date().getFullYear()||date.getUTCFullYear()!==y||date.getUTCMonth()!==m-1||date.getUTCDate()!==d)throw new Error("Проверьте дату рождения");
  return `${String(y).padStart(4,"0")}-${String(m).padStart(2,"0")}-${String(d).padStart(2,"0")}`;
}

export function GuestListPage({code,token,title,eventTitle,eventId,categoryId,seatId,seatPoolActive,requiresPayment,allocation,limit,guestCount,guests,canManage,showAttendees,fields}:{code:string;token:string;title:string;eventTitle:string;eventId:string;categoryId:string|null;seatId:string|null;seatPoolActive:boolean;requiresPayment:boolean;allocation:string;limit:number;guestCount:number;guests:Guest[];canManage:boolean;showAttendees:boolean;fields:GuestFieldConfig}){
  const router=useRouter();const{locale}=useLocale();const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[success,setSuccess]=useState("");
  useEffect(()=>{const sessionId=sessionFor(`atlas-guest-session-${code}`);void fetch(`/api/guest-lists/${code}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"visit",sessionId})}).catch(()=>undefined);},[code]);
  async function send(body:Record<string,unknown>){setBusy(true);setError("");setSuccess("");try{const response=await fetch(`/api/guest-lists/${code}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const raw=await response.text();let data:ActionResponse={};try{data=raw?JSON.parse(raw):{};}catch{}if(!response.ok){setError(data.error||`Не удалось выполнить действие (${response.status})`);router.refresh();return false;}if(body.action==="add")setSuccess(data.status==="PENDING_APPROVAL"?"Заявка отправлена организатору на подтверждение.":`Регистрация подтверждена. Билет ${data.publicId||""} создан и будет отправлен на email.`);else setSuccess("Гость удалён");router.refresh();return true;}catch{setError("Сервер не ответил. Проверьте соединение и попробуйте ещё раз.");return false;}finally{setBusy(false);}}
  async function register(customer:Record<string,string>){
    if(!requiresPayment)return send({action:"add",customer});
    if(!categoryId||(seatPoolActive&&!seatId)){setError("Для этой ссылки больше нет доступных мест.");router.refresh();return false;}
    setBusy(true);setError("");setSuccess("");
    try{const response=await fetch("/api/checkout",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({eventId,categoryId,quantity:1,tableId:null,seatIds:seatId?[seatId]:undefined,customer,payment:{method:"CARD"},locale,referralCode:code,idempotencyKey:crypto.randomUUID()})});const raw=await response.text();let data:ActionResponse={};try{data=raw?JSON.parse(raw):{};}catch{}if(!response.ok){setError(data.error||`Не удалось начать оплату (${response.status})`);router.refresh();return false;}if(!data.paymentUrl){setError("Платёжная страница не была создана.");return false;}window.location.assign(data.paymentUrl);return true;}catch{setError("Не удалось открыть оплату. Проверьте соединение и попробуйте ещё раз.");return false;}finally{setBusy(false);}
  }
  const configured=(Object.keys(fields) as GuestFieldKey[]).filter(key=>fields[key].visible);const visible=configured.includes("email")?configured:[...configured,"email" as GuestFieldKey];const showRoster=canManage||showAttendees;const hasCapacity=guestCount<limit&&(!seatPoolActive||Boolean(seatId&&categoryId));
  return <main className="shell"><section className="panel" style={{maxWidth:720,margin:"28px auto"}}><span className="eyebrow">ATLAS GUEST LIST</span><h1>{title}</h1><p><strong>{eventTitle}</strong><br/><span className="muted">{allocation}</span></p>
    {showRoster&&<div className="stats"><div className="stat"><span className="muted">Записано</span><strong>{guestCount}</strong></div><div className="stat"><span className="muted">Осталось</span><strong>{Math.max(0,limit-guestCount)}</strong></div></div>}
    {hasCapacity?<form className="form panel" onSubmit={async e=>{e.preventDefault();setError("");const form=e.currentTarget;const f=new FormData(form);try{const customer:Record<string,string>={...Object.fromEntries(visible.filter(key=>key!=="birthDate").map(key=>[key,String(f.get(key)||"")])),gender:String(f.get("gender")||"")};if(visible.includes("birthDate"))customer.birthDate=birthDateFromForm(f);const ok=await register(customer);if(ok&&!requiresPayment)form.reset();}catch(err){setError(err instanceof Error?err.message:"Проверьте дату рождения");}}}><h2>Записаться</h2><p className="muted">Заполните данные. {requiresPayment?"После этого откроется безопасная оплата. Если мероприятие требует подтверждения, после авторизации заявка поступит организатору.":"Если мероприятие требует подтверждения, заявка сначала поступит организатору. В автоматическом режиме билет будет создан сразу."}</p>{visible.map(key=>{const required=key==="email"||fields[key]?.required;if(key==="birthDate")return <div className="field" key={key}><label>{labels[key]}{required?" *":" - необязательно"}</label><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1.35fr",gap:8}}><input className="input" name="birthDay" inputMode="numeric" autoComplete="bday-day" placeholder="ДД" aria-label="День рождения" maxLength={2} pattern="[0-9]{1,2}" required={required} disabled={busy}/><input className="input" name="birthMonth" inputMode="numeric" autoComplete="bday-month" placeholder="ММ" aria-label="Месяц рождения" maxLength={2} pattern="[0-9]{1,2}" required={required} disabled={busy}/><input className="input" name="birthYear" inputMode="numeric" autoComplete="bday-year" placeholder="ГГГГ" aria-label="Год рождения" maxLength={4} pattern="[0-9]{4}" required={required} disabled={busy}/></div><small className="muted">Например: 15 / 08 / 1990</small></div>;return <div className="field" key={key}><label>{labels[key]}{required?" *":" - необязательно"}</label><input className="input" name={key} type={types[key]||"text"} required={required} disabled={busy}/></div>;})}<div className="field"><label>Пол *</label><select className="input" name="gender" required disabled={busy} defaultValue=""><option value="" disabled>Выберите пол</option><option value="MALE">Мужчина</option><option value="FEMALE">Женщина</option></select></div>{error&&<div className="toast" role="alert">{error}</div>}{success&&<div className="toast" role="status">{success}</div>}<button className="btn" disabled={busy}>{busy?"Отправляем...":requiresPayment?"Продолжить к оплате":"Продолжить"}</button></form>:<div className="toast" role="status">Для этой ссылки больше нет доступных мест.</div>}
    {showRoster?<><h2 className="section-title">{canManage?"Список гостей":"Кто уже записался"}</h2><div className="table-wrap"><table><thead><tr><th>Гость</th>{canManage&&<th>Телефон</th>}<th>Статус</th>{canManage&&<th/>}</tr></thead><tbody>{guests.map(guest=><tr key={guest.id}><td><strong>{guest.name}</strong></td>{canManage&&<td>{guest.phone}</td>}<td><span className="pill">{guest.ticketStatus==="PENDING_APPROVAL"?"Ожидает подтверждения":guest.ticketStatus==="USED"?"Прошёл":"Подтверждён"}</span></td>{canManage&&<td><button type="button" className="btn secondary" disabled={busy||guest.ticketStatus==="USED"} onClick={()=>void send({action:"remove",token,orderId:guest.id})}>Удалить</button></td>}</tr>)}{!guests.length&&<tr><td colSpan={canManage?4:2}>Пока никто не записан.</td></tr>}</tbody></table></div></>:<p className="muted">Список участников скрыт организатором.</p>}
  </section></main>;
}
