"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { GuestSeatPoolPicker } from "@/components/guest-seat-pool-picker";

type GuestLink={id:string;label:string;code:string;active:boolean;allocation:string;priceLabel:string;limit:number;used:number;maxPerOrder:number;showAttendees:boolean;startsAt:string|null;endsAt:string|null;publicPath:string;managePath:string};
type MapSeat={id:string;label:string;position:number;status:"AVAILABLE"|"RESERVED"|"BLOCKED";categoryId:string|null};
type MapObject={id:string;label:string;objectType:string;priceMode:"WHOLE_TABLE"|"PER_SEAT";x:number;y:number;width:number;height:number;rotation:number;seats:number;categoryId:string|null;reserved:boolean;seatItems:MapSeat[]};
type Props={eventId:string;categories:Array<{id:string;name:string;priceMinor:number}>;tables:Array<{id:string;label:string;seats:number;categoryId:string|null}>;mapObjects:MapObject[];existingLinks:GuestLink[]};

function localDateTime(value:string|null){if(!value)return"";const d=new Date(value);const offset=d.getTimezoneOffset();return new Date(d.getTime()-offset*60000).toISOString().slice(0,16);}

export function GuestLinkManager({eventId,categories,tables,mapObjects,existingLinks}:Props){
 const router=useRouter();
 const[allocationType,setAllocationType]=useState<"EVENT"|"CATEGORY"|"TABLE"|"SEATS">("EVENT");
 const[selectedSeatIds,setSelectedSeatIds]=useState<string[]>([]);
 const[priceMode,setPriceMode]=useState<"FULL"|"FREE"|"CUSTOM">("FREE");
 const[busy,setBusy]=useState<string|null>(null);const[error,setError]=useState("");const[copied,setCopied]=useState("");
 const[editing,setEditing]=useState<string|null>(null);
 const origin=typeof window==="undefined"?"":window.location.origin;

 async function api(body:Record<string,unknown>,key:string){setBusy(key);setError("");try{const response=await fetch("/api/admin/guest-links",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||"Не удалось выполнить действие");router.refresh();return data;}catch(e){setError(e instanceof Error?e.message:"Ошибка");return null;}finally{setBusy(null)}}
 async function copy(value:string,key:string){await navigator.clipboard.writeText(value);setCopied(key);setTimeout(()=>setCopied(""),1400)}
 async function create(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);if(allocationType==="SEATS"&&!selectedSeatIds.length){setError("Выберите хотя бы одно место на карте");return;}const limit=allocationType==="SEATS"?selectedSeatIds.length:Number(form.get("limit"));const data=await api({eventId,displayName:String(form.get("displayName")||""),allocationType,seatIds:allocationType==="SEATS"?selectedSeatIds:undefined,categoryId:allocationType==="CATEGORY"?form.get("categoryId"):null,tableId:allocationType==="TABLE"?form.get("tableId"):null,priceMode,customPriceMinor:priceMode==="CUSTOM"?Math.round(Number(form.get("customPrice"))*100):null,guestLimit:limit,maxPerOrder:allocationType==="SEATS"?1:Number(form.get("maxPerOrder"))||1,showAttendees:form.get("showAttendees")==="on",startsAt:form.get("startsAt")||null,endsAt:form.get("endsAt")||null,code:form.get("code")||undefined},"create");if(data){event.currentTarget.reset();setAllocationType("EVENT");setSelectedSeatIds([]);setPriceMode("FREE");}}
 async function save(link:GuestLink,event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const data=await api({action:"update",linkId:link.id,displayName:String(form.get("displayName")||""),guestLimit:Number(form.get("limit")),maxPerOrder:Number(form.get("maxPerOrder")),showAttendees:form.get("showAttendees")==="on",startsAt:form.get("startsAt")||null,endsAt:form.get("endsAt")||null},`save-${link.id}`);if(data)setEditing(null)}
 async function remove(link:GuestLink){if(!window.confirm(`Удалить гостевую ссылку «${link.label}»?`))return;await api({action:"delete",linkId:link.id},`delete-${link.id}`)}

 return <div className="form" style={{gap:20}}>
  {error&&<div className="toast" role="alert">{error}</div>}
  <section className="panel form">
   <div className="row between"><div><span className="eyebrow">Гостевые ссылки</span><h2>Активные и сохранённые ссылки</h2><p className="muted">Ссылка остаётся рабочей, пока вы её не отключите или не удалите. Здесь можно управлять лимитом, видимостью списка и сроком действия.</p></div><span className="pill">{existingLinks.length}</span></div>
   {existingLinks.length===0?<p className="muted">Гостевых ссылок пока нет.</p>:existingLinks.map(link=><article className="panel" key={link.id} style={{padding:18}}>
    <div className="row between" style={{gap:12,alignItems:"flex-start"}}><div><div className="row" style={{gap:8,flexWrap:"wrap"}}><strong>{link.label}</strong><span className="pill">{link.active?"Активна":"Отключена"}</span><span className="pill">{link.used}/{link.limit}</span></div><p className="muted" style={{margin:"6px 0 0"}}>{link.allocation} · {link.priceLabel} · код {link.code}</p></div><button type="button" className="btn secondary" onClick={()=>setEditing(editing===link.id?null:link.id)}>{editing===link.id?"Закрыть":"Настроить"}</button></div>
    <div className="form-grid two" style={{marginTop:14}}><div className="field"><label>Ссылка для гостей</label><div className="row" style={{gap:8}}><input className="input" readOnly value={`${origin}${link.publicPath}`} onFocus={e=>e.currentTarget.select()}/><button type="button" className="btn secondary" onClick={()=>void copy(`${origin}${link.publicPath}`,`${link.id}-public`)}>{copied===`${link.id}-public`?"Скопировано":"Копировать"}</button></div></div><div className="field"><label>Ссылка управления</label><div className="row" style={{gap:8}}><input className="input" readOnly value={`${origin}${link.managePath}`} onFocus={e=>e.currentTarget.select()}/><button type="button" className="btn secondary" onClick={()=>void copy(`${origin}${link.managePath}`,`${link.id}-manage`)}>{copied===`${link.id}-manage`?"Скопировано":"Копировать"}</button></div></div></div>
    <div className="row" style={{gap:8,flexWrap:"wrap",marginTop:12}}><a className="btn secondary" href={link.publicPath} target="_blank" rel="noreferrer">Открыть как гость</a><a className="btn secondary" href={link.managePath} target="_blank" rel="noreferrer">Управление / добавить гостя</a><button type="button" className="btn secondary" disabled={busy!==null} onClick={()=>void api({action:"toggle",linkId:link.id,active:!link.active},`toggle-${link.id}`)}>{busy===`toggle-${link.id}`?"Сохраняю...":link.active?"Отключить":"Включить"}</button><button type="button" className="btn secondary" disabled={busy!==null} onClick={()=>void remove(link)}>{busy===`delete-${link.id}`?"Удаляю...":"Удалить"}</button></div>
    {editing===link.id&&<form className="form" style={{marginTop:16}} onSubmit={e=>void save(link,e)}><div className="form-grid two"><div className="field"><label>Название</label><input className="input" name="displayName" defaultValue={link.label} required/></div><div className="field"><label>Лимит приглашённых</label><input className="input" name="limit" type="number" min={Math.max(1,link.used)} defaultValue={link.limit} required/></div><div className="field"><label>Максимум за одну регистрацию</label><input className="input" name="maxPerOrder" type="number" min="1" max="100" defaultValue={link.maxPerOrder} required/></div><div className="field"><label className="row" style={{gap:10,alignItems:"center"}}><input name="showAttendees" type="checkbox" defaultChecked={link.showAttendees}/><strong>Показывать гостям, кто уже записался</strong></label></div><div className="field"><label>Активна с</label><input className="input" name="startsAt" type="datetime-local" defaultValue={localDateTime(link.startsAt)}/></div><div className="field"><label>Активна до</label><input className="input" name="endsAt" type="datetime-local" defaultValue={localDateTime(link.endsAt)}/></div></div><button className="btn" disabled={busy!==null}>{busy===`save-${link.id}`?"Сохраняю...":"Сохранить изменения"}</button></form>}
   </article>)}
  </section>

  <section className="panel form"><span className="eyebrow">Новая ссылка</span><h2>Создать гостевую ссылку</h2><p className="muted">Выберите, какие билеты или места доступны по ссылке, их цену и количество. Продажи через промоутеров находятся в отдельном модуле и здесь не создаются.</p>
   <form className="form" onSubmit={create}><div className="form-grid two"><div className="field"><label>Название ссылки</label><input className="input" name="displayName" required placeholder="VIP friends / Стол друзей / Free entry"/></div><div className="field"><label>Короткий код - необязательно</label><input className="input" name="code" pattern="[A-Za-z0-9_-]{3,40}" placeholder="VIPFRIENDS"/></div></div>
    <div className="field"><label>Какие билеты доступны</label><select value={allocationType} onChange={e=>{const next=e.target.value as typeof allocationType;setAllocationType(next);if(next!=="SEATS")setSelectedSeatIds([])}}><option value="EVENT">Любые билеты мероприятия</option><option value="CATEGORY">Определённая категория билета</option>{tables.length>0&&<option value="TABLE">Определённый стол</option>}{mapObjects.some(item=>item.priceMode==="PER_SEAT"&&item.seatItems.some(seat=>seat.status==="AVAILABLE"))&&<option value="SEATS">Конкретные места с карты</option>}</select></div>
    {allocationType==="CATEGORY"&&<div className="field"><label>Категория</label><select name="categoryId" required>{categories.map(item=><option key={item.id} value={item.id}>{item.name} · {(item.priceMinor/100).toFixed(2)} ₪</option>)}</select></div>}
    {allocationType==="TABLE"&&<div className="field"><label>Стол</label><select name="tableId" required>{tables.map(item=><option key={item.id} value={item.id}>{item.label} · {item.seats} мест</option>)}</select></div>}
    {allocationType==="SEATS"&&<GuestSeatPoolPicker objects={mapObjects} selected={selectedSeatIds} onChange={setSelectedSeatIds}/>} 
    <div className="form-grid two"><div className="field"><label>Цена</label><select value={priceMode} onChange={e=>setPriceMode(e.target.value as typeof priceMode)}><option value="FREE">Бесплатно - 0 ₪</option><option value="FULL">Обычная цена билета</option><option value="CUSTOM">Своя цена</option></select></div>{priceMode==="CUSTOM"&&<div className="field"><label>Цена, ₪</label><input className="input" name="customPrice" type="number" min="0" step="0.01" required/></div>}</div>
    {allocationType==="SEATS"?<div className="field"><label>Количество приглашений</label><input className="input" readOnly value={selectedSeatIds.length}/><small className="muted">Равно количеству выбранных мест.</small></div>:<div className="form-grid two"><div className="field"><label>Количество приглашений по ссылке</label><input className="input" name="limit" type="number" min="1" max="10000" defaultValue="1" required/></div><div className="field"><label>Максимум билетов за одну регистрацию</label><input className="input" name="maxPerOrder" type="number" min="1" max="100" defaultValue="1" required/></div></div>}
    <div className="field"><label className="row" style={{alignItems:"center",gap:10}}><input name="showAttendees" type="checkbox"/><strong>Показывать гостям, кто уже записался</strong></label><small className="muted">Если выключено, участники не видят друг друга. Организатор всё равно видит полный список через ссылку управления.</small></div>
    <div className="form-grid two"><div className="field"><label>Активна с - необязательно</label><input className="input" name="startsAt" type="datetime-local"/></div><div className="field"><label>Активна до - необязательно</label><input className="input" name="endsAt" type="datetime-local"/></div></div>
    <button className="btn" disabled={busy!==null}>{busy==="create"?"Создаю...":"Создать гостевую ссылку"}</button>
   </form>
  </section>
 </div>
}
