"use client";

import { useState } from "react";
import { useLocale } from "@/components/locale-provider";

type SalesLink = { id:string; label:string; code:string; kind:"GUEST"|"SALES"; allocation:string; priceLabel:string; limit:number|null; publicPath:string; managePath?:string|null };
type Props={eventId:string;categories:Array<{id:string;name:string;priceMinor:number}>;tables:Array<{id:string;label:string;seats:number;categoryId:string|null}>;existingLinks:SalesLink[]};

const copy={
  ru:{createError:"Не удалось создать канал",copied:"Скопировано",copy:"Копировать",eyebrow:"Ссылки и источники",title:"Каналы продаж",help:"Создавайте отдельные ссылки для Facebook, Instagram, партнёров, друзей, VIP-списков и других источников.",guestAccess:"гостевой доступ",sales:"продажи",publicLink:"Публичная ссылка",manageLink:"Ссылка управления",newChannel:"Создать новый канал",ticketSales:"Продажа билетов",guest:"Гостевой доступ",channelName:"Название канала",channelPlaceholder:"Facebook / Партнёр Алекс / VIP friends",shortCode:"Короткий код — необязательно",availableTickets:"Какие билеты доступны",allTickets:"Все билеты мероприятия",oneCategory:"Одна категория билетов",specificTable:"Конкретный стол",category:"Категория",table:"Стол",seats:"мест",linkPrice:"Цена по ссылке",regularPrice:"Обычная цена билета",free:"Бесплатно — 0 ₪",special:"Специальная цена",specialPrice:"Специальная цена, ₪",guestLimit:"Лимит приглашённых",salesLimit:"Общий лимит продаж — необязательно",maxOrder:"Максимум в одном заказе",starts:"Начало действия — необязательно",ends:"Окончание действия — необязательно",creating:"Создаём...",create:"Создать канал",created:"✓ Канал создан"},
  he:{createError:"לא ניתן ליצור ערוץ",copied:"הועתק",copy:"העתקה",eyebrow:"קישורים ומקורות",title:"ערוצי מכירה",help:"צרו קישורים נפרדים ל-Facebook, Instagram, שותפים, חברים, רשימות VIP ומקורות נוספים.",guestAccess:"גישה לאורחים",sales:"מכירות",publicLink:"קישור ציבורי",manageLink:"קישור ניהול",newChannel:"יצירת ערוץ חדש",ticketSales:"מכירת כרטיסים",guest:"גישה לאורחים",channelName:"שם הערוץ",channelPlaceholder:"Facebook / שותף אלכס / VIP friends",shortCode:"קוד קצר — לא חובה",availableTickets:"אילו כרטיסים זמינים",allTickets:"כל כרטיסי האירוע",oneCategory:"קטגוריית כרטיסים אחת",specificTable:"שולחן מסוים",category:"קטגוריה",table:"שולחן",seats:"מקומות",linkPrice:"מחיר דרך הקישור",regularPrice:"מחיר כרטיס רגיל",free:"חינם — 0 ₪",special:"מחיר מיוחד",specialPrice:"מחיר מיוחד, ₪",guestLimit:"מגבלת מוזמנים",salesLimit:"מגבלת מכירות כוללת — לא חובה",maxOrder:"מקסימום בהזמנה אחת",starts:"תחילת תוקף — לא חובה",ends:"סיום תוקף — לא חובה",creating:"יוצר...",create:"יצירת ערוץ",created:"✓ הערוץ נוצר"},
  en:{createError:"Could not create channel",copied:"Copied",copy:"Copy",eyebrow:"Links and sources",title:"Sales channels",help:"Create separate links for Facebook, Instagram, partners, friends, VIP lists and other sources.",guestAccess:"guest access",sales:"sales",publicLink:"Public link",manageLink:"Management link",newChannel:"Create a new channel",ticketSales:"Ticket sales",guest:"Guest access",channelName:"Channel name",channelPlaceholder:"Facebook / Partner Alex / VIP friends",shortCode:"Short code — optional",availableTickets:"Available tickets",allTickets:"All event tickets",oneCategory:"One ticket category",specificTable:"Specific table",category:"Category",table:"Table",seats:"seats",linkPrice:"Price through this link",regularPrice:"Regular ticket price",free:"Free — 0 ₪",special:"Special price",specialPrice:"Special price, ₪",guestLimit:"Guest limit",salesLimit:"Total sales limit — optional",maxOrder:"Maximum per order",starts:"Starts — optional",ends:"Ends — optional",creating:"Creating...",create:"Create channel",created:"✓ Channel created"}
} as const;

export function GuestLinkManager({eventId,categories,tables,existingLinks}:Props){
  const{locale}=useLocale();const text=copy[locale];
  const [kind,setKind]=useState<"SALES"|"GUEST">("SALES");
  const [allocationType,setAllocationType]=useState<"EVENT"|"CATEGORY"|"TABLE">("EVENT");
  const [priceMode,setPriceMode]=useState<"FULL"|"FREE"|"CUSTOM">("FULL");
  const [busy,setBusy]=useState(false);const[error,setError]=useState("");const[copied,setCopied]=useState("");
  const[result,setResult]=useState<{publicPath:string;managePath?:string|null}|null>(null);
  async function copyValue(value:string,key:string){await navigator.clipboard.writeText(value);setCopied(key);window.setTimeout(()=>setCopied(""),1600)}
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");setResult(null);const form=new FormData(event.currentTarget);const response=await fetch("/api/admin/guest-links",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({eventId,displayName:form.get("displayName"),kind,allocationType,categoryId:allocationType==="CATEGORY"?form.get("categoryId"):null,tableId:allocationType==="TABLE"?form.get("tableId"):null,priceMode,customPriceMinor:priceMode==="CUSTOM"?Math.round(Number(form.get("customPrice"))*100):null,guestLimit:Number(form.get("limit"))||null,maxPerOrder:Number(form.get("maxPerOrder"))||10,startsAt:form.get("startsAt")||null,endsAt:form.get("endsAt")||null,code:form.get("code")||undefined})});const data=await response.json();setBusy(false);if(!response.ok)return setError(data.error||text.createError);setResult({publicPath:data.publicPath,managePath:data.managePath})}
  const origin=typeof window==="undefined"?"":window.location.origin;
  const CopyRow=({label,value,copyKey}:{label:string;value:string;copyKey:string})=><div className="field"><label>{label}</label><div className="row" style={{gap:8}}><input className="input" readOnly value={value} onFocus={e=>e.currentTarget.select()}/><button type="button" className="btn secondary" onClick={()=>void copyValue(value,copyKey)}>{copied===copyKey?text.copied:text.copy}</button></div></div>;
  return <section className="panel form"><span className="eyebrow">{text.eyebrow}</span><h2>{text.title}</h2><p className="muted">{text.help}</p>
    {existingLinks.length>0&&<div className="form">{existingLinks.map(link=><details className="panel" key={link.id}><summary><strong>{link.label}</strong> · {link.kind==="GUEST"?text.guestAccess:text.sales} · {link.allocation} · {link.priceLabel}</summary><div style={{marginTop:14}}><CopyRow label={text.publicLink} value={`${origin}${link.publicPath}`} copyKey={`${link.id}-public`}/>{link.managePath&&<CopyRow label={text.manageLink} value={`${origin}${link.managePath}`} copyKey={`${link.id}-manage`}/>}</div></details>)}</div>}
    <h3>{text.newChannel}</h3><div className="pricing-switch"><button type="button" className={kind==="SALES"?"active":""} onClick={()=>setKind("SALES")}>{text.ticketSales}</button><button type="button" className={kind==="GUEST"?"active":""} onClick={()=>{setKind("GUEST");setPriceMode("FREE")}}>{text.guest}</button></div>
    <form onSubmit={submit} className="form"><div className="form-grid two"><div className="field"><label>{text.channelName}</label><input className="input" name="displayName" required placeholder={text.channelPlaceholder}/></div><div className="field"><label>{text.shortCode}</label><input className="input" name="code" pattern="[A-Za-z0-9_-]{3,40}" placeholder="FACEBOOK"/></div></div>
      <div className="field"><label>{text.availableTickets}</label><select value={allocationType} onChange={e=>setAllocationType(e.target.value as typeof allocationType)}><option value="EVENT">{text.allTickets}</option><option value="CATEGORY">{text.oneCategory}</option>{tables.length>0&&<option value="TABLE">{text.specificTable}</option>}</select></div>
      {allocationType==="CATEGORY"&&<div className="field"><label>{text.category}</label><select name="categoryId" required>{categories.map(item=><option key={item.id} value={item.id}>{item.name} · {(item.priceMinor/100).toFixed(2)} ₪</option>)}</select></div>}
      {allocationType==="TABLE"&&<div className="field"><label>{text.table}</label><select name="tableId" required>{tables.map(item=><option key={item.id} value={item.id}>{item.label} · {item.seats} {text.seats}</option>)}</select></div>}
      {kind==="SALES"&&<><div className="field"><label>{text.linkPrice}</label><select value={priceMode} onChange={e=>setPriceMode(e.target.value as typeof priceMode)}><option value="FULL">{text.regularPrice}</option><option value="FREE">{text.free}</option><option value="CUSTOM">{text.special}</option></select></div>{priceMode==="CUSTOM"&&<div className="field"><label>{text.specialPrice}</label><input className="input" name="customPrice" type="number" min="0" step="0.01" required/></div>}</>}
      <div className="form-grid two"><div className="field"><label>{kind==="GUEST"?text.guestLimit:text.salesLimit}</label><input className="input" name="limit" type="number" min="1" max="10000" required={kind==="GUEST"}/></div><div className="field"><label>{text.maxOrder}</label><input className="input" name="maxPerOrder" type="number" min="1" max="100" defaultValue="10" required/></div></div>
      <div className="form-grid two"><div className="field"><label>{text.starts}</label><input className="input" name="startsAt" type="datetime-local"/></div><div className="field"><label>{text.ends}</label><input className="input" name="endsAt" type="datetime-local"/></div></div>
      {error&&<div className="toast">{error}</div>}<button className="btn" disabled={busy}>{busy?text.creating:text.create}</button></form>
    {result&&<div className="panel"><strong>{text.created}</strong><CopyRow label={text.publicLink} value={`${origin}${result.publicPath}`} copyKey="new-public"/>{result.managePath&&<CopyRow label={text.manageLink} value={`${origin}${result.managePath}`} copyKey="new-manage"/>}</div>}
  </section>;
}
