"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

type GuestRow={id:string;publicId:string;name:string;email:string;phone:string;tickets:number;used:number};
type Props={list:{id:string;label:string;active:boolean;publicUrl:string;manageUrl:string;guestLimit:number|null;maxPerOrder:number;startsAt:string|null;endsAt:string|null};guests:GuestRow[]};

export function GuestListDetailManager({list,guests}:Props){
 const router=useRouter();const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[copied,setCopied]=useState("");
 async function post(payload:unknown){setBusy(true);setError("");const response=await fetch("/api/admin/guest-links",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await response.json();setBusy(false);if(!response.ok){setError(data.error||"Ошибка");return false}router.refresh();return true}
 async function copy(value:string,key:string){await navigator.clipboard.writeText(value);setCopied(key);window.setTimeout(()=>setCopied(""),1600)}
 return <div style={{display:"grid",gap:24}}>
  <div className="panel"><div className="row between"><div><span className="eyebrow">Ссылки</span><h2 style={{marginBottom:4}}>Доступ к гостевому списку</h2></div><span className="pill" style={list.active?{background:"#dcfae6",color:"#067647"}:{}}>{list.active?"Активен":"Отключён"}</span></div>
   <div style={{display:"grid",gap:14,marginTop:18}}><div><strong>Публичная ссылка</strong><code style={{display:"block",marginTop:6,wordBreak:"break-all"}}>{list.publicUrl}</code><button className="btn" style={{marginTop:8}} type="button" onClick={()=>void copy(list.publicUrl,"public")}>{copied==="public"?"Скопировано":"Копировать публичную ссылку"}</button></div><div><strong>Ссылка управления</strong><p className="muted" style={{margin:"4px 0"}}>Эту ссылку получает только человек, который управляет списком. Она содержит защищённый token.</p><code style={{display:"block",wordBreak:"break-all"}}>{list.manageUrl}</code><button className="btn" style={{marginTop:8}} type="button" onClick={()=>void copy(list.manageUrl,"manage")}>{copied==="manage"?"Скопировано":"Копировать ссылку управления"}</button></div></div>
   <div className="row" style={{gap:8,marginTop:16}}><button className="btn" disabled={busy} onClick={()=>void post({action:"toggle",linkId:list.id,active:!list.active})}>{list.active?"Отключить список":"Включить список"}</button></div>
  </div>

  <details className="panel"><summary style={{cursor:"pointer",fontWeight:700,fontSize:18}}>Настройки списка</summary><form style={{display:"grid",gap:14,marginTop:18}} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await post({action:"update",linkId:list.id,displayName:f.get("displayName"),guestLimit:f.get("guestLimit")?Number(f.get("guestLimit")):null,maxPerOrder:Number(f.get("maxPerOrder")||1),startsAt:f.get("startsAt")?new Date(String(f.get("startsAt"))).toISOString():null,endsAt:f.get("endsAt")?new Date(String(f.get("endsAt"))).toISOString():null})}}>
   <div className="field"><label>Название списка</label><input className="input" name="displayName" defaultValue={list.label} required minLength={2}/></div><div className="row" style={{gap:14,flexWrap:"wrap"}}><div className="field" style={{flex:"1 1 160px"}}><label>Лимит гостей</label><input className="input" name="guestLimit" type="number" min="1" defaultValue={list.guestLimit??""}/></div><div className="field" style={{flex:"1 1 160px"}}><label>Макс. за одно добавление</label><input className="input" name="maxPerOrder" type="number" min="1" max="100" defaultValue={list.maxPerOrder}/></div></div><div className="row" style={{gap:14,flexWrap:"wrap"}}><div className="field" style={{flex:"1 1 220px"}}><label>Действует с</label><input className="input" name="startsAt" type="datetime-local" defaultValue={list.startsAt?.slice(0,16)??""}/></div><div className="field" style={{flex:"1 1 220px"}}><label>Действует до</label><input className="input" name="endsAt" type="datetime-local" defaultValue={list.endsAt?.slice(0,16)??""}/></div></div>{error&&<div className="toast">{error}</div>}<button className="btn dark" disabled={busy}>{busy?"Сохраняем...":"Сохранить настройки"}</button>
  </form></details>

  <div className="panel"><div className="row between"><div><span className="eyebrow">Гости</span><h2 style={{marginBottom:4}}>Участники списка</h2></div><span className="pill">{guests.length} заказов</span></div><div className="table-wrap" style={{marginTop:16}}><table><thead><tr><th>Гость</th><th>Контакты</th><th>Билеты</th><th>Прошли</th><th>Заказ</th></tr></thead><tbody>{guests.map(g=><tr key={g.id}><td><strong>{g.name}</strong></td><td>{g.phone}<br/><small>{g.email}</small></td><td>{g.tickets}</td><td>{g.used}</td><td><a href={`/office/orders/${g.publicId}`}>{g.publicId}</a></td></tr>)}{!guests.length&&<tr><td colSpan={5}>В этом списке пока нет гостей.</td></tr>}</tbody></table></div></div>
 </div>
}
