"use client";

import { useMemo, useState } from "react";
import { useLocale } from "@/components/locale-provider";
import { localeTag } from "@/lib/i18n";

type Channel="EMAIL"|"SMS"|"WHATSAPP";
type Customer={guestId:string|null;name:string;email:string;phone:string;city:string|null;orders:number;totalMinor:number;consents:Partial<Record<Channel,"GRANTED"|"REVOKED"|"UNKNOWN">>;suppressed:Channel[];fullySuppressed:boolean};
const labels:Record<Channel,string>={EMAIL:"Email",SMS:"SMS",WHATSAPP:"WhatsApp"};const defaultRates:Record<Channel,number>={EMAIL:2,SMS:18,WHATSAPP:25};
const copy={
ru:{proof:"Подтверждено организатором в Atlas Office",reason:"Запрос клиента на исключение из рекламных рассылок",error:"Не удалось сохранить изменение",granted:"Согласие сохранено с записью в журнале.",suppressed:"Клиент исключён только из маркетинга. История покупок сохранена.",generic:"Ошибка",segment:"Сегментация и стоимость",estimate:"Предварительный расчёт кампании",noSend:"Без отправки",channel:"Канал",city:"Город",allCities:"Все города",minOrders:"Минимум заказов",testRate:"Тестовая ставка",perMessage:"за сообщение",found:"Найдено",allowed:"Разрешено",excluded:"Исключено",cost:"Оценка",costHelp:"до НДС, без резервирования",demoHelp:"Пока используются демонстрационные ставки. Перед запуском провайдера тарифы будут задаваться суперюзером отдельно для каждого канала и организатора.",consents:"Согласия и отписки",status:"Управление маркетинговым статусом",customers:"клиентов",columns:["Клиент","Покупки","Email","SMS","WhatsApp","Действия"],noCrm:"Нет CRM-карточки",unsubscribed:"Отписан",grantedStatus:"Разрешено",noConsent:"Нет согласия",allow:"Разрешить",unsubscribe:"Отписать",unsubscribeAll:"Отписать от всего маркетинга",manual:"Ручная фиксация согласия допустима только когда организатор действительно располагает доказательством. Atlas сохраняет источник, версию текста и сотрудника, выполнившего действие."},
he:{proof:"האישור תועד על ידי המפיק ב־Atlas Office",reason:"בקשת הלקוח להסרה מדיוור שיווקי",error:"לא הצלחנו לשמור את השינוי",granted:"האישור נשמר ותועד ביומן.",suppressed:"הלקוח הוסר משיווק בלבד. היסטוריית הרכישות נשמרה.",generic:"שגיאה",segment:"פילוח ועלות",estimate:"הערכת קמפיין",noSend:"ללא שליחה",channel:"ערוץ",city:"עיר",allCities:"כל הערים",minOrders:"מינימום הזמנות",testRate:"תעריף בדיקה",perMessage:"להודעה",found:"נמצאו",allowed:"מורשים",excluded:"הוחרגו",cost:"הערכה",costHelp:"לפני מע״מ, ללא שריון",demoHelp:"כרגע נעשה שימוש בתעריפי הדגמה. לפני הפעלת ספק, התעריפים יוגדרו בנפרד לכל ערוץ ומפיק.",consents:"הסכמות והסרות",status:"ניהול סטטוס שיווקי",customers:"לקוחות",columns:["לקוח","רכישות","Email","SMS","WhatsApp","פעולות"],noCrm:"אין כרטיס CRM",unsubscribed:"הוסר",grantedStatus:"מאושר",noConsent:"אין הסכמה",allow:"אישור",unsubscribe:"הסרה",unsubscribeAll:"הסרה מכל השיווק",manual:"יש לתעד הסכמה ידנית רק כאשר למפיק יש הוכחה אמיתית. Atlas שומרת את המקור, גרסת הטקסט והעובד שביצע את הפעולה."},
en:{proof:"Confirmed by organizer in Atlas Office",reason:"Customer requested removal from marketing",error:"Could not save the change",granted:"Consent saved and recorded in the audit log.",suppressed:"Customer removed from marketing only. Purchase history was preserved.",generic:"Error",segment:"Segmentation and cost",estimate:"Campaign estimate",noSend:"No sending",channel:"Channel",city:"City",allCities:"All cities",minOrders:"Minimum orders",testRate:"Test rate",perMessage:"per message",found:"Found",allowed:"Allowed",excluded:"Excluded",cost:"Estimate",costHelp:"before VAT, no reservation",demoHelp:"Demo rates are currently used. Before provider launch, rates will be configured separately for each channel and organizer.",consents:"Consents and unsubscribes",status:"Marketing status management",customers:"customers",columns:["Customer","Purchases","Email","SMS","WhatsApp","Actions"],noCrm:"No CRM profile",unsubscribed:"Unsubscribed",grantedStatus:"Allowed",noConsent:"No consent",allow:"Allow",unsubscribe:"Unsubscribe",unsubscribeAll:"Unsubscribe from all marketing",manual:"Manual consent should be recorded only when the organizer actually has evidence. Atlas stores the source, text version, and staff member who performed the action."}
} as const;

export function MarketingAudienceManager({customers}:{customers:Customer[]}){
  const {locale}=useLocale();const text=copy[locale];
  const [channel,setChannel]=useState<Channel>("EMAIL");const [city,setCity]=useState("");const [minOrders,setMinOrders]=useState(1);const [busy,setBusy]=useState<string|null>(null);const [notice,setNotice]=useState("");const [rows,setRows]=useState(customers);
  const filtered=useMemo(()=>rows.filter(customer=>(!city||customer.city===city)&&customer.orders>=minOrders),[rows,city,minOrders]);const eligible=filtered.filter(customer=>customer.guestId&&customer.consents[channel]==="GRANTED"&&!customer.fullySuppressed&&!customer.suppressed.includes(channel));const excluded=filtered.length-eligible.length;const estimatedCost=eligible.length*defaultRates[channel];const cities=[...new Set(rows.map(customer=>customer.city).filter((value):value is string=>Boolean(value)))].sort();
  const currency=(minor:number)=>(minor/100).toLocaleString(localeTag(locale),{style:"currency",currency:"ILS"});
  async function act(customer:Customer,action:"GRANT"|"SUPPRESS",targetChannel:Channel|null=channel){if(!customer.guestId)return;const key=`${customer.guestId}-${action}-${targetChannel??"ALL"}`;setBusy(key);setNotice("");try{const response=await fetch("/api/admin/marketing/consents",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(action==="GRANT"?{action,guestId:customer.guestId,channel:targetChannel,consentTextVersion:"organizer-proof-v1",proofNote:text.proof}:{action,guestId:customer.guestId,channel:targetChannel,reason:text.reason})});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||text.error);setRows(current=>current.map(row=>{if(row.guestId!==customer.guestId)return row;if(action==="GRANT"&&targetChannel)return{...row,consents:{...row.consents,[targetChannel]:"GRANTED"}};if(targetChannel)return{...row,consents:{...row.consents,[targetChannel]:"REVOKED"},suppressed:[...new Set([...row.suppressed,targetChannel])]};return{...row,fullySuppressed:true,consents:{EMAIL:"REVOKED",SMS:"REVOKED",WHATSAPP:"REVOKED"}};}));setNotice(action==="GRANT"?text.granted:text.suppressed);}catch(error){setNotice(error instanceof Error?error.message:text.generic);}finally{setBusy(null);}}
  return <><div className="card"><div className="row between"><div><span className="eyebrow">{text.segment}</span><h2>{text.estimate}</h2></div><span className="pill">{text.noSend}</span></div><div className="grid-2"><label>{text.channel}<select value={channel} onChange={event=>setChannel(event.target.value as Channel)}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>{text.city}<select value={city} onChange={event=>setCity(event.target.value)}><option value="">{text.allCities}</option>{cities.map(item=><option key={item}>{item}</option>)}</select></label><label>{text.minOrders}<input dir="ltr" style={{textAlign:"left"}} type="number" min={1} value={minOrders} onChange={event=>setMinOrders(Math.max(1,Number(event.target.value)||1))}/></label><div><span className="muted">{text.testRate}</span><h3><bdi>{currency(defaultRates[channel])}</bdi> {text.perMessage}</h3></div></div><div className="stats"><div className="stat"><span className="muted">{text.found}</span><strong>{filtered.length}</strong></div><div className="stat"><span className="muted">{text.allowed}</span><strong>{eligible.length}</strong></div><div className="stat"><span className="muted">{text.excluded}</span><strong>{excluded}</strong></div><div className="stat"><span className="muted">{text.cost}</span><strong><bdi>{currency(estimatedCost)}</bdi></strong><small>{text.costHelp}</small></div></div><p className="muted">{text.demoHelp}</p></div>
  <div className="card"><div className="row between"><div><span className="eyebrow">{text.consents}</span><h2>{text.status}</h2></div><span className="pill">{rows.length} {text.customers}</span></div>{notice&&<p>{notice}</p>}<div className="table-wrap"><table><thead><tr>{text.columns.map(column=><th key={column}>{column}</th>)}</tr></thead><tbody>{rows.slice(0,50).map(customer=><tr key={customer.guestId??`${customer.email}-${customer.phone}`}><td><strong>{customer.name}</strong><br/><small><bdi>{customer.email||customer.phone}</bdi></small>{!customer.guestId&&<><br/><small>{text.noCrm}</small></>}</td><td>{customer.orders}</td>{(["EMAIL","SMS","WHATSAPP"] as Channel[]).map(item=><td key={item}><span className="pill">{customer.fullySuppressed||customer.suppressed.includes(item)?text.unsubscribed:customer.consents[item]==="GRANTED"?text.grantedStatus:text.noConsent}</span></td>)}<td><div className="row"><button className="btn secondary" disabled={!customer.guestId||Boolean(busy)} onClick={()=>act(customer,"GRANT",channel)}>{busy===`${customer.guestId}-GRANT-${channel}`?"...":`${text.allow} ${labels[channel]}`}</button><button className="btn secondary" disabled={!customer.guestId||Boolean(busy)} onClick={()=>act(customer,"SUPPRESS",channel)}>{`${text.unsubscribe} ${labels[channel]}`}</button><button className="btn secondary" disabled={!customer.guestId||Boolean(busy)} onClick={()=>act(customer,"SUPPRESS",null)}>{text.unsubscribeAll}</button></div></td></tr>)}</tbody></table></div><p className="muted">{text.manual}</p></div></>;
}
