"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { CloneEventForm } from "@/components/clone-event-form";
import { useLocale } from "@/components/locale-provider";

type SourceEvent={id:string;title:string;startsAt:string;venueName:string;city:string;address:string};
const copy={ru:{error:"Не удалось создать черновик",back:"← Назад к выбору",eyebrow:"Начало работы",title:"Как создать мероприятие?",help:"В обоих случаях откроется один и тот же редактор с четырьмя разделами. Копия не публикуется автоматически.",opening:"Открываем редактор…",new:"Создать с нуля",newHelp:"Atlas создаст технический черновик и сразу откроет полную настройку, включая карту.",copy:"Скопировать существующее",copyHelp:"Скопировать данные, затем пройти все вкладки и изменить нужные настройки."},he:{error:"לא הצלחנו ליצור טיוטה",back:"← חזרה לבחירה",eyebrow:"תחילת עבודה",title:"איך ליצור אירוע?",help:"בשני המקרים ייפתח אותו עורך עם ארבעה אזורים. עותק חדש לא מתפרסם אוטומטית.",opening:"פותחים את העורך…",new:"יצירה מאפס",newHelp:"Atlas תיצור טיוטה טכנית ותפתח מיד את כל ההגדרות, כולל מפת האולם.",copy:"שכפול אירוע קיים",copyHelp:"העתיקו את הנתונים, עברו על כל הלשוניות ושנו את ההגדרות הדרושות."},en:{error:"Could not create draft",back:"← Back to choices",eyebrow:"Getting started",title:"How do you want to create the event?",help:"Both options open the same editor with four sections. A duplicated event is never published automatically.",opening:"Opening editor…",new:"Create from scratch",newHelp:"Atlas creates a technical draft and immediately opens the full setup, including the map.",copy:"Duplicate existing event",copyHelp:"Copy the data, then review every tab and change the required settings."}} as const;
export function NewEventEntry({events}:{events:SourceEvent[]}){const {locale}=useLocale();const text=copy[locale];const router=useRouter();const[mode,setMode]=useState<""|"new"|"copy">("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");async function create(){setMode("new");setBusy(true);setError("");const response=await fetch("/api/admin/events/draft",{method:"POST"});const data=await response.json().catch(()=>({}));if(!response.ok){setError(data.error||text.error);setBusy(false);return}router.push(`/office/events/${data.id}?tab=about&setup=1`);router.refresh()}if(mode==="copy")return <div><button type="button" className="btn dark" onClick={()=>setMode("")}>{text.back}</button><div style={{marginTop:18}}><CloneEventForm events={events}/></div></div>;return <div className="panel form"><span className="eyebrow">{text.eyebrow}</span><h2>{text.title}</h2><p className="muted">{text.help}</p><div className="choice-grid"><button type="button" className="choice-card" onClick={()=>void create()} disabled={busy}><i>＋</i><strong>{busy?text.opening:text.new}</strong><small>{text.newHelp}</small></button><button type="button" className="choice-card" onClick={()=>setMode("copy")}><i>⧉</i><strong>{text.copy}</strong><small>{text.copyHelp}</small></button></div>{error&&<div className="toast">{error}</div>}</div>;}
