"use client";

import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { useLocale } from "@/components/locale-provider";

type DocumentState = { provided:boolean; name:string|null; updatedAt:string|null };
const copy={
  ru:{storage:"Хранилище документов ещё не подключено в Vercel.",large:"Файл слишком большой. Максимум 4 МБ.",error:"Не удалось загрузить документ.",saved:"Документ сохранён",uploaded:"✓ Загружен",required:"Требуется",updated:"Обновлён",privacy:"PDF, JPG или PNG. Документ хранится приватно и доступен только авторизованному организатору и Atlas.",download:"Скачать",uploading:"Загрузка...",eyebrow:"Документы для выплат",title:"Банк и налогообложение",help:"Эти документы не блокируют регистрацию. Они обязательны только до первой выплаты.",bank:"Банковские реквизиты / אישור ניהול חשבון",tax:"ניכוי מס במקור / налоговый документ"},
  he:{storage:"אחסון המסמכים עדיין לא הוגדר ב־Vercel.",large:"הקובץ גדול מדי. הגודל המרבי הוא 4 MB.",error:"לא הצלחנו להעלות את המסמך.",saved:"המסמך נשמר",uploaded:"✓ הועלה",required:"נדרש",updated:"עודכן",privacy:"PDF, JPG או PNG. המסמך נשמר באופן פרטי ונגיש רק למפיק מורשה ול־Atlas.",download:"הורדה",uploading:"מעלים...",eyebrow:"מסמכים לתשלום",title:"בנק ומיסוי",help:"המסמכים האלה אינם חוסמים את ההרשמה. הם נדרשים רק לפני התשלום הראשון.",bank:"אישור ניהול חשבון / פרטי בנק",tax:"ניכוי מס במקור / אישור מס"},
  en:{storage:"Document storage is not configured in Vercel yet.",large:"The file is too large. Maximum size is 4 MB.",error:"Could not upload the document.",saved:"Document saved",uploaded:"✓ Uploaded",required:"Required",updated:"Updated",privacy:"PDF, JPG, or PNG. The document is stored privately and is available only to the authorized organizer and Atlas.",download:"Download",uploading:"Uploading...",eyebrow:"Payout documents",title:"Bank and tax",help:"These documents do not block registration. They are required only before the first payout.",bank:"Bank account confirmation / אישור ניהול חשבון",tax:"Tax withholding certificate / ניכוי מס במקור"}
} as const;

export function OrganizerDocumentsForm({organizationId,bank,tax}:{organizationId:string;bank:DocumentState;tax:DocumentState}) {
  const {locale}=useLocale();const text=copy[locale];
  const router=useRouter();const bankRef=useRef<HTMLInputElement>(null);const taxRef=useRef<HTMLInputElement>(null);const [busy,setBusy]=useState<"bank"|"tax"|null>(null);const [message,setMessage]=useState("");
  async function upload(kind:"bank"|"tax",file:File|null){if(!file)return;setBusy(kind);setMessage("");const body=new FormData();body.set("kind",kind);body.set("file",file);const response=await fetch(`/api/organizer-documents/${organizationId}`,{method:"POST",body});const data=await response.json().catch(()=>({}));setBusy(null);if(!response.ok){setMessage(data.error==="BLOB_NOT_CONFIGURED"?text.storage:data.error==="FILE_TOO_LARGE"?text.large:text.error);return;}setMessage(text.saved);if(kind==="bank"&&bankRef.current)bankRef.current.value="";if(kind==="tax"&&taxRef.current)taxRef.current.value="";router.refresh();}
  function card(kind:"bank"|"tax",title:string,state:DocumentState,ref:React.RefObject<HTMLInputElement|null>){return <div className="platform-document-card"><div><span className={`platform-document-status ${state.provided?"ready":"missing"}`}>{state.provided?text.uploaded:text.required}</span><h3>{title}</h3>{state.name?<p><strong><bdi>{state.name}</bdi></strong>{state.updatedAt&&<><br/><small className="muted">{text.updated} <bdi>{state.updatedAt}</bdi></small></>}</p>:<p className="muted">{text.privacy}</p>}</div><div className="row" style={{flexWrap:"wrap"}}><input ref={ref} type="file" accept="application/pdf,image/jpeg,image/png" disabled={busy!==null} onChange={event=>upload(kind,event.target.files?.[0]??null)} style={{maxWidth:280}}/>{state.provided&&<a className="btn secondary" href={`/api/organizer-documents/${organizationId}/${kind}`}>{text.download}</a>}</div>{busy===kind&&<small className="muted">{text.uploading}</small>}</div>}
  return <section className="platform-section-card"><div><span className="eyebrow">{text.eyebrow}</span><h2>{text.title}</h2><p className="muted">{text.help}</p></div><div className="platform-documents-grid">{card("bank",text.bank,bank,bankRef)}{card("tax",text.tax,tax,taxRef)}</div>{message&&<div className="toast" style={{marginTop:14}}>{message}</div>}</section>;
}
