"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { useLocale } from "@/components/locale-provider";
import type { PricingMarketingIntensity, PricingMarketingStrategy } from "@/lib/ticket-pricing-strategy";

const copy={
 ru:{eyebrow:"Маркетинг цены",title:"Стратегия продаж",intro:"Создавайте срочность без обязательного раскрытия слабых продаж. По умолчанию клиент видит этап, таймер и следующую цену, но не видит, сколько билетов уже продано.",empty:"Сначала создайте хотя бы одну категорию билетов.",intensity:"Интенсивность маркетинга",countdown:"Показывать обратный отсчёт",countdownHelp:"Например: «Цена повысится через 2 дня».",next:"Показывать следующую цену",nextHelp:"Клиент понимает финансовую выгоду покупки сейчас.",stage:"Показывать ограниченность текущего этапа",stageHelp:"Формулировка без общей статистики: «Текущий этап заканчивается скоро».",remaining:"Показывать общий остаток билетов",remainingHelp:"Включайте только когда эта цифра помогает продажам.",sold:"Показывать количество проданных билетов",soldHelp:"По умолчанию выключено. Используйте только для сильного социального доказательства.",fixedHelp:"У этой категории фиксированная цена, поэтому таймер и следующая цена появятся только после настройки этапов цены.",saving:"Сохраняем...",save:"Сохранить стратегию",saved:"✓ Стратегия сохранена",error:"Не удалось сохранить стратегию",levels:{CALM:["Спокойный","Показываем только этап цены и, при наличии, таймер."],STANDARD:["Стандартный","Таймер и следующая цена без раскрытия количества продаж."],ACTIVE:["Активный","Добавляем ощущение ограниченности текущего этапа, но не показываем общие продажи."],MAXIMUM:["Максимальный","Можно дополнительно показать остаток и социальное доказательство."]}},
 he:{eyebrow:"כלי קידום למחיר",title:"אסטרטגיית מכירה",intro:"צרו תחושת דחיפות בלי לחשוף נתוני מכירה שלא משרתים אתכם. כברירת מחדל הקהל יראה את תקופת המחיר, ספירה לאחור ואת המחיר הבא — בלי לראות כמה כרטיסים כבר נמכרו.",empty:"כדי להגדיר אסטרטגיית מכירה, צרו קודם לפחות קטגוריית כרטיסים אחת.",intensity:"רמת הדחיפות השיווקית",countdown:"הצגת ספירה לאחור",countdownHelp:"לדוגמה: ״המחיר יעלה בעוד יומיים״.",next:"הצגת המחיר הבא",nextHelp:"כך הקהל מבין מה הוא חוסך כשהוא קונה עכשיו.",stage:"הדגשת סיום תקופת המחיר הנוכחית",stageHelp:"מסר שיוצר דחיפות בלי לחשוף נתוני מכירה כוללים: ״תקופת המחיר הנוכחית מסתיימת בקרוב״.",remaining:"הצגת מספר הכרטיסים שנותרו",remainingHelp:"הפעילו רק כשהמספר הזה מחזק את החלטת הרכישה.",sold:"הצגת מספר הכרטיסים שנמכרו",soldHelp:"כבוי כברירת מחדל. הפעילו רק כשנתון המכירות יוצר הוכחה חברתית חזקה.",fixedHelp:"לקטגוריה הזו יש מחיר קבוע. ספירה לאחור והמחיר הבא יוצגו רק לאחר שתגדירו תקופות מחיר.",saving:"שומרים את האסטרטגיה...",save:"שמירת האסטרטגיה",saved:"✓ האסטרטגיה נשמרה",error:"לא הצלחנו לשמור את האסטרטגיה",levels:{CALM:["עדינה","מציגים את תקופת המחיר, ובמידת הצורך גם ספירה לאחור."],STANDARD:["מאוזנת","מציגים ספירה לאחור ואת המחיר הבא, בלי לחשוף את היקף המכירות."],ACTIVE:["דחופה","מדגישים שתקופת המחיר עומדת להסתיים, בלי להציג נתוני מכירה כוללים."],MAXIMUM:["מלאה","אפשר להציג גם מלאי שנותר ונתוני מכירה כהוכחה חברתית."]}},
 en:{eyebrow:"Price promotion",title:"Sales strategy",intro:"Create urgency without exposing sales figures that do not help conversion. By default, buyers see the current price period, a countdown and the next price — but not how many tickets have sold.",empty:"Create at least one ticket category before setting a sales strategy.",intensity:"Marketing urgency",countdown:"Show a countdown",countdownHelp:"For example: “Price increases in 2 days.”",next:"Show the next price",nextHelp:"This makes the savings from buying now clear.",stage:"Highlight that the current price period is ending",stageHelp:"Creates urgency without showing total sales: “The current price period ends soon.”",remaining:"Show tickets remaining",remainingHelp:"Enable this only when the number supports the buying decision.",sold:"Show tickets sold",soldHelp:"Off by default. Enable only when the sales figure provides strong social proof.",fixedHelp:"This category currently has a fixed price. Countdown and next-price messaging will appear after price periods are configured.",saving:"Saving strategy...",save:"Save strategy",saved:"✓ Strategy saved",error:"We couldn’t save the strategy",levels:{CALM:["Subtle","Show the current price period and a countdown when relevant."],STANDARD:["Balanced","Show a countdown and the next price without revealing sales volume."],ACTIVE:["Urgent","Emphasize that the current price period is ending without showing total sales."],MAXIMUM:["Full","Optionally show remaining inventory and sales figures as social proof."]}}
} as const;

type CategoryStrategy={id:string;name:string;pricingMode:"FIXED"|"SCHEDULED";strategy:PricingMarketingStrategy};
export function PricingStrategyManager({eventId,categories}:{eventId:string;categories:CategoryStrategy[]}){
 const router=useRouter();const{locale}=useLocale();const text=copy[locale];const[busyId,setBusyId]=useState("");const[message,setMessage]=useState("");const[values,setValues]=useState<Record<string,PricingMarketingStrategy>>(Object.fromEntries(categories.map(c=>[c.id,c.strategy])));
 function patch(id:string,value:Partial<PricingMarketingStrategy>){setValues(current=>({...current,[id]:{...current[id],...value}}));}
 async function save(categoryId:string){setBusyId(categoryId);setMessage("");const response=await fetch(`/api/admin/events/${eventId}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"pricingStrategy",categoryId,...values[categoryId]})});const data=await response.json();setBusyId("");setMessage(response.ok?text.saved:data.error||text.error);if(response.ok)router.refresh();window.setTimeout(()=>setMessage(""),2800);}
 return <section className="panel form"><span className="eyebrow">{text.eyebrow}</span><h2>{text.title}</h2><p className="muted">{text.intro}</p>{categories.length===0?<div className="toast">{text.empty}</div>:categories.map(category=>{const strategy=values[category.id];return <details className="panel" key={category.id} open={categories.length===1}><summary><strong>{category.name}</strong> · {text.levels[strategy.intensity][0]}</summary><div className="form" style={{marginTop:16}}><div className="field"><label>{text.intensity}</label><select value={strategy.intensity} onChange={event=>{const intensity=event.target.value as PricingMarketingIntensity;patch(category.id,{intensity,showCountdown:true,showNextPrice:intensity!=="CALM",showStageRemaining:intensity==="ACTIVE"||intensity==="MAXIMUM",showTotalRemaining:intensity==="MAXIMUM"?strategy.showTotalRemaining:false,showSoldCount:intensity==="MAXIMUM"?strategy.showSoldCount:false});}}>{(Object.keys(text.levels) as PricingMarketingIntensity[]).map(key=><option key={key} value={key}>{text.levels[key][0]}</option>)}</select><small className="muted">{text.levels[strategy.intensity][1]}</small></div><label className="option"><span><strong>{text.countdown}</strong><small>{text.countdownHelp}</small></span><input type="checkbox" checked={strategy.showCountdown} onChange={e=>patch(category.id,{showCountdown:e.target.checked})}/></label><label className="option"><span><strong>{text.next}</strong><small>{text.nextHelp}</small></span><input type="checkbox" checked={strategy.showNextPrice} onChange={e=>patch(category.id,{showNextPrice:e.target.checked})}/></label><label className="option"><span><strong>{text.stage}</strong><small>{text.stageHelp}</small></span><input type="checkbox" checked={strategy.showStageRemaining} onChange={e=>patch(category.id,{showStageRemaining:e.target.checked})}/></label><label className="option"><span><strong>{text.remaining}</strong><small>{text.remainingHelp}</small></span><input type="checkbox" checked={strategy.showTotalRemaining} onChange={e=>patch(category.id,{showTotalRemaining:e.target.checked})}/></label><label className="option"><span><strong>{text.sold}</strong><small>{text.soldHelp}</small></span><input type="checkbox" checked={strategy.showSoldCount} onChange={e=>patch(category.id,{showSoldCount:e.target.checked})}/></label>{category.pricingMode==="FIXED"&&<p className="muted">{text.fixedHelp}</p>}<button type="button" className="btn" disabled={busyId===category.id} onClick={()=>void save(category.id)}>{busyId===category.id?text.saving:text.save}</button></div></details>;})}{message&&<div className="toast save-feedback" role="status">{message}</div>}</section>;
}