"use client";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type EventItem={id:string;title:string;status:string};
type Assignment={id:string;eventId:string;eventTitle:string;eventSlug:string;eventStatus:string;code:string;label:string;active:boolean;clicks:number;checkouts:number;abandoned:number;recovered:number;orders:number;tickets:number;revenue:number};
type Promoter={id:string;name:string;email:string;phone:string|null;active:boolean;autoAssignAllEvents:boolean;defaultCommissionBps:number};
function money(minor:number){return new Intl.NumberFormat("he-IL",{style:"currency",currency:"ILS",maximumFractionDigits:0}).format(minor/100)}
function runtimeUrl(slug:string,code:string){if(typeof window==="undefined")return `https://www.atlas-one.co/events/${slug}?channel=${encodeURIComponent(code)}`;const origin=window.location.hostname.endsWith("vercel.app")?window.location.origin:"https://www.atlas-one.co";return `${origin}/events/${slug}?channel=${encodeURIComponent(code)}`}

export function PromoterV2Detail({promoter,events,assignments,accountState}:{promoter:Promoter;events:EventItem[];assignments:Assignment[];accountState:string}){
 const router=useRouter();const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[success,setSuccess]=useState("");const[auto,setAuto]=useState(promoter.autoAssignAllEvents);const[copied,setCopied]=useState<string|null>(null);
 const available=useMemo(()=>events.filter(e=>!assignments.some(a=>a.eventId===e.id)),[events,assignments]);const[eventId,setEventId]=useState(available[0]?.id||"");
 async function post(payload:unknown){setBusy(true);setError("");setSuccess("");try{const r=await fetch("/api/admin/promoters-v2",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok){setError(d.error||"Ошибка");return false}router.refresh();return true}catch{setError("Не удалось выполнить действие");return false}finally{setBusy(false)}}
 async function assign(){if(!eventId)return;const title=events.find(e=>e.id===eventId)?.title||"мероприятие";if(await post({action:"assign",promoterId:promoter.id,eventId}))setSuccess(`Назначено: ${title}`)}
 async function toggleAuto(value:boolean){const old=auto;setAuto(value);if(!(await post({action:"automation",promoterId:promoter.id,value})))setAuto(old);else setSuccess(value?"Автодобавление включено":"Автодобавление выключено")}
 async function setActive(value:boolean){if(await post({action:"setActive",promoterId:promoter.id,active:value}))setSuccess(value?"Промоутер восстановлен":"Промоутер архивирован")}
 async function invite(){if(await post({action:"invite",promoterId:promoter.id,force:true}))setSuccess(accountState==="ACTIVE"?"Письмо активации отправлено повторно":"Welcome-письмо отправлено")}
 async function copy(a:Assignment){const url=runtimeUrl(a.eventSlug,a.code);await navigator.clipboard.writeText(url);setCopied(a.id);setTimeout(()=>setCopied(null),1400)}
 const accountLabel=accountState==="ACTIVE"?"Активирован":accountState==="PENDING"?"Ожидает активации":"Не активирован";
 return <div style={{display:"grid",gap:20}}>
  <div className="panel"><div className="row between"><div><span className="eyebrow">Профиль</span><h2 style={{marginBottom:4}}>{promoter.name}</h2><p className="muted" style={{margin:0}}>{promoter.email}{promoter.phone?` · ${promoter.phone}`:""} · комиссия по умолчанию {(promoter.defaultCommissionBps/100).toFixed(2)}%</p></div><span className="pill">{promoter.active?"Активен":"Архивирован"}</span></div></div>
  <div className="panel"><div className="row between" style={{gap:12,alignItems:"flex-start"}}><div><span className="eyebrow">Promoter Portal</span><h2 style={{marginBottom:4}}>Защищённый кабинет</h2><p className="muted" style={{margin:0}}>Статус аккаунта: <strong>{accountLabel}</strong>. Вход выполняется по email и личному паролю промоутера.</p></div><button className="btn" disabled={busy||!promoter.active} onClick={()=>void invite()}>{accountState==="ACTIVE"?"Отправить активацию заново":"Отправить Welcome"}</button></div></div>
  <div className="panel"><span className="eyebrow">Автоматизация</span><h2>Новые мероприятия</h2><label className="row" style={{gap:10}}><input type="checkbox" checked={auto} disabled={busy} onChange={e=>void toggleAuto(e.target.checked)}/><span>Автоматически назначать этого промоутера на новые мероприятия</span></label></div>
  <div className="panel"><div className="row between"><div><span className="eyebrow">Мероприятия</span><h2>Назначения и ссылки</h2></div><span className="pill">{assignments.length} назначено</span></div>
   {available.length>0&&<div className="row" style={{gap:10,alignItems:"end",flexWrap:"wrap",marginTop:14}}><div className="field" style={{margin:0,minWidth:280}}><label>Добавить мероприятие</label><select value={eventId} onChange={e=>setEventId(e.target.value)}>{available.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></div><button className="btn dark" disabled={busy||!eventId} onClick={()=>void assign()}>Назначить</button></div>}
   {error&&<div className="toast" style={{marginTop:12}}>{error}</div>}{success&&<div className="toast" style={{marginTop:12}}>{success}</div>}
   <div style={{display:"grid",gap:12,marginTop:18}}>{assignments.map(a=><div key={a.id} style={{border:"1px solid #e5e7eb",borderRadius:14,padding:16}}><div className="row between" style={{alignItems:"flex-start",gap:12}}><div><strong>{a.eventTitle}</strong><div className="muted">{a.eventStatus==="PUBLISHED"?"Опубликовано":"Черновик"}</div><code style={{display:"block",marginTop:8,wordBreak:"break-all"}}>{runtimeUrl(a.eventSlug,a.code)}</code></div><span className="pill">{a.eventStatus==="PUBLISHED"?"Ссылка активна":"После публикации"}</span></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(90px,1fr))",gap:8,marginTop:12}}>{[["Клики",a.clicks],["Checkout",a.checkouts],["Abandoned",a.abandoned],["Recovered",a.recovered],["Заказы",a.orders],["Билеты",a.tickets]].map(([k,v])=><div className="stat" key={String(k)}><span className="muted">{k}</span><strong>{v}</strong></div>)}<div className="stat"><span className="muted">Выручка</span><strong>{money(a.revenue)}</strong></div></div><div className="row" style={{gap:8,marginTop:12}}>{a.eventStatus==="PUBLISHED"?<button className="btn" onClick={()=>void copy(a)}>{copied===a.id?"Скопировано":"Копировать ссылку"}</button>:<button className="btn" disabled>Ссылка после публикации</button>}</div></div>)}{!assignments.length&&<p className="muted">Мероприятия пока не назначены.</p>}</div>
  </div>
  <div className="panel" style={{borderColor:"#fda29b"}}><h2>{promoter.active?"Архивировать промоутера":"Восстановить промоутера"}</h2><p className="muted">Физическое удаление запрещено. История кликов, checkout и продаж сохраняется.</p><button className="btn" disabled={busy} onClick={()=>void setActive(!promoter.active)}>{promoter.active?"Архивировать":"Восстановить"}</button></div>
 </div>
}
