"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

type Assignment={id:string;eventId:string;eventTitle:string;eventStatus:string;shareUrl:string;emailStatus:string;sentAt:string|null;active:boolean};
type EventOption={id:string;title:string};

export function PromoterOperationalManager({promoterId,email,autoAssignAllEvents,events,assignments}:{promoterId:string;email:string|null;autoAssignAllEvents:boolean;events:EventOption[];assignments:Assignment[]}){
 const router=useRouter();
 const[busyAction,setBusyAction]=useState<string|null>(null);const[error,setError]=useState("");const[success,setSuccess]=useState("");const[copied,setCopied]=useState<string|null>(null);const[auto,setAuto]=useState(autoAssignAllEvents);
 const available=events.filter(e=>!assignments.some(a=>a.eventId===e.id));const[eventId,setEventId]=useState(available[0]?.id||"");
 useEffect(()=>setAuto(autoAssignAllEvents),[autoAssignAllEvents]);
 useEffect(()=>{if(!available.some(e=>e.id===eventId))setEventId(available[0]?.id||"")},[assignments,eventId,available]);
 async function post(payload:unknown,action:string){setBusyAction(action);setError("");setSuccess("");try{const r=await fetch("/api/admin/promoters",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload),cache:"no-store"});const data=await r.json().catch(()=>({}));if(!r.ok){setError(data.error||`Ошибка ${r.status}`);return false}router.refresh();return true}catch{setError("Не удалось связаться с сервером. Обновите страницу и повторите.");return false}finally{setBusyAction(null)}}
 async function toggleAutomation(next:boolean){const previous=auto;setAuto(next);const ok=await post({action:"automation",promoterId,autoAssignAllEvents:next},"automation");if(!ok)setAuto(previous);else setSuccess(next?"Автодобавление включено.":"Автодобавление выключено.")}
 async function assign(){if(!eventId)return;const title=events.find(e=>e.id===eventId)?.title||"мероприятие";const ok=await post({action:"assignEvent",promoterId,eventId},"assign");if(ok)setSuccess(`Промоутер назначен на «${title}». Персональная ссылка создана.`)}
 async function resend(linkId:string){const ok=await post({action:"resendEmail",linkId},`resend:${linkId}`);if(ok)setSuccess("Письмо со ссылкой отправлено повторно.")}
 async function copy(url:string,id:string){await navigator.clipboard.writeText(url);setCopied(id);window.setTimeout(()=>setCopied(null),1400)}
 return <div style={{display:"grid",gap:20}}>
  <div className="panel"><span className="eyebrow">Автоматизация</span><h2 style={{marginBottom:8}}>Как назначать промоутера</h2><label className="row" style={{gap:10,alignItems:"flex-start"}}><input type="checkbox" checked={auto} disabled={busyAction!==null} onChange={e=>void toggleAutomation(e.target.checked)}/><span><strong>Автоматически добавлять ко всем новым мероприятиям</strong><br/><small className="muted">При публикации нового мероприятия Atlas создаст персональную ссылку и отправит её на {email||"email промоутера"}.</small></span></label></div>
  <div className="panel"><div className="row between"><div><span className="eyebrow">Мероприятия</span><h2 style={{marginBottom:4}}>Назначения промоутера</h2><p className="muted" style={{margin:0}}>Выберите мероприятие один раз. Atlas сам создаст персональную ссылку.</p></div><span className="pill">{assignments.length} назначено</span></div>
   {available.length>0?<div className="row" style={{gap:10,marginTop:16,alignItems:"end",flexWrap:"wrap"}}><div className="field" style={{margin:0,minWidth:280}}><label>Добавить мероприятие</label><select value={eventId} onChange={e=>setEventId(e.target.value)}>{available.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></div><button className="btn dark" disabled={busyAction!==null||!eventId} onClick={()=>void assign()}>{busyAction==="assign"?"Назначаем...":"Назначить мероприятие"}</button></div>:<p className="muted" style={{marginTop:16}}>Все доступные мероприятия уже назначены этому промоутеру.</p>}
   {!email&&<div className="toast" style={{marginTop:14}}>У промоутера нет email. Ссылка будет создана, но письмо отправить нельзя.</div>}{error&&<div className="toast" style={{marginTop:14}}>{error}</div>}{success&&<div className="toast" style={{marginTop:14}}>{success}</div>}
   <div className="table-wrap" style={{marginTop:18}}><table><thead><tr><th>Мероприятие</th><th>Персональная ссылка</th><th>Email</th><th>Действия</th></tr></thead><tbody>{assignments.map(a=><tr key={a.id}><td><strong>{a.eventTitle}</strong><br/><small>{a.eventStatus==="PUBLISHED"?"Опубликовано":"Черновик"}</small></td><td><code style={{wordBreak:"break-all"}}>{a.shareUrl}</code></td><td>{a.emailStatus==="SENT"?<><strong style={{color:"#067647"}}>Отправлено</strong>{a.sentAt&&<><br/><small>{new Date(a.sentAt).toLocaleString("ru-RU")}</small></>}</>:a.eventStatus!=="PUBLISHED"?<span className="muted">Будет отправлено после публикации</span>:a.emailStatus==="ERROR"?<strong style={{color:"#b42318"}}>Ошибка отправки</strong>:<span className="muted">Не отправлено</span>}</td><td><div className="row" style={{gap:6,flexWrap:"wrap"}}><button className="btn" type="button" onClick={()=>void copy(a.shareUrl,a.id)}>{copied===a.id?"Скопировано":"Копировать"}</button>{a.eventStatus==="PUBLISHED"&&email&&<button className="btn" type="button" disabled={busyAction!==null} onClick={()=>void resend(a.id)}>{busyAction===`resend:${a.id}`?"Отправляем...":"Отправить повторно"}</button>}</div></td></tr>)}{!assignments.length&&<tr><td colSpan={4}>Промоутер пока не назначен ни на одно мероприятие.</td></tr>}</tbody></table></div>
  </div>
 </div>;
}
