"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

type EventOption={id:string;title:string;slug:string;categories:Array<{id:string;name:string}>;tables:Array<{id:string;label:string}>};
type LinkItem={id:string;label:string;active:boolean;eventId:string;eventTitle:string;shareUrl:string;allocationType:"EVENT"|"CATEGORY"|"TABLE";categoryId:string|null;tableId:string|null;guestLimit:number|null;maxPerOrder:number;customPriceMinor:number|null;commissionBps:number;exclusive:boolean;startsAt:string|null;endsAt:string|null;clicks:number;checkout:number;abandoned:number;recovered:number;orders:number;tickets:number;revenue:number;conversion:number};

function localDateTime(value:string|null){if(!value)return "";const d=new Date(value);const pad=(n:number)=>String(n).padStart(2,"0");return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;}
function isoOrNull(value:FormDataEntryValue|null){const text=String(value||"").trim();return text?new Date(text).toISOString():null;}
function money(minor:number){return new Intl.NumberFormat("he-IL",{style:"currency",currency:"ILS",maximumFractionDigits:0}).format(minor/100);}

function EditLinkForm({link,event,promoterId,busy,onSave}:{link:LinkItem;event:EventOption|undefined;promoterId:string;busy:boolean;onSave:(payload:unknown)=>Promise<boolean>}){
  const [allocationType,setAllocationType]=useState<LinkItem["allocationType"]>(link.allocationType);
  return <form style={{display:"grid",gap:12,marginTop:16,paddingTop:16,borderTop:"1px solid #e5e7eb"}} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await onSave({action:"editLink",linkId:link.id,promoterId,eventId:link.eventId,label:f.get("label"),allocationType,categoryId:allocationType==="CATEGORY"?f.get("categoryId"):null,tableId:allocationType==="TABLE"?f.get("tableId"):null,guestLimit:f.get("guestLimit")?Number(f.get("guestLimit")):null,maxPerOrder:Number(f.get("maxPerOrder")||10),customPriceMinor:f.get("price")?Math.round(Number(f.get("price"))*100):null,commissionPercent:Number(f.get("commission")||0),exclusive:f.get("exclusive")==="on",startsAt:isoOrNull(f.get("startsAt")),endsAt:isoOrNull(f.get("endsAt"))});}}>
    <div className="field"><label>Название ссылки</label><input className="input" name="label" defaultValue={link.label} required minLength={2}/></div>
    <div className="field"><label>Мероприятие</label><input className="input" value={link.eventTitle} disabled/><small className="muted">Ссылка навсегда остаётся привязана к этому мероприятию.</small></div>
    <div className="field"><label>Что продаёт ссылка</label><select value={allocationType} onChange={e=>setAllocationType(e.target.value as LinkItem["allocationType"])}><option value="EVENT">Всё мероприятие</option><option value="CATEGORY">Категория билетов</option><option value="TABLE">Конкретный стол / объект</option></select></div>
    {allocationType==="CATEGORY"&&<div className="field"><label>Категория</label><select name="categoryId" defaultValue={link.categoryId||""} required>{event?.categories.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></div>}
    {allocationType==="TABLE"&&<div className="field"><label>Стол / объект</label><select name="tableId" defaultValue={link.tableId||""} required>{event?.tables.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></div>}
    <div className="row" style={{gap:12,flexWrap:"wrap"}}><div className="field" style={{flex:"1 1 140px"}}><label>Квота</label><input className="input" name="guestLimit" type="number" min="1" defaultValue={link.guestLimit??""}/></div><div className="field" style={{flex:"1 1 140px"}}><label>Макс. в заказе</label><input className="input" name="maxPerOrder" type="number" min="1" max="50" defaultValue={link.maxPerOrder}/></div><div className="field" style={{flex:"1 1 140px"}}><label>Спеццена, ₪</label><input className="input" name="price" type="number" min="0.01" step="0.01" defaultValue={link.customPriceMinor?link.customPriceMinor/100:""}/></div><div className="field" style={{flex:"1 1 140px"}}><label>Комиссия, %</label><input className="input" name="commission" type="number" min="0" max="100" step="0.01" defaultValue={(link.commissionBps/100).toFixed(2)}/></div></div>
    <div className="row" style={{gap:12,flexWrap:"wrap"}}><div className="field" style={{flex:"1 1 220px"}}><label>Начало действия</label><input className="input" name="startsAt" type="datetime-local" defaultValue={localDateTime(link.startsAt)}/></div><div className="field" style={{flex:"1 1 220px"}}><label>Окончание действия</label><input className="input" name="endsAt" type="datetime-local" defaultValue={localDateTime(link.endsAt)}/></div></div>
    <label className="row"><input name="exclusive" type="checkbox" defaultChecked={link.exclusive}/> Эксклюзивно закрепить выбранный инвентарь</label>
    <button className="btn dark" disabled={busy}>Сохранить изменения</button>
  </form>;
}

export function PromoterDetailManager({promoter,events,links}:{promoter:{id:string;name:string;active:boolean;defaultCommissionBps:number};events:EventOption[];links:LinkItem[]}){
  const router=useRouter();const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [copied,setCopied]=useState<string|null>(null);
  async function post(payload:unknown){setBusy(true);setError("");const response=await fetch("/api/admin/promoters",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await response.json();setBusy(false);if(!response.ok){setError(data.error||"Ошибка");return false;}router.refresh();return true;}
  async function copy(url:string,id:string){await navigator.clipboard.writeText(url);setCopied(id);window.setTimeout(()=>setCopied(null),1600);}

  return <div style={{display:"grid",gap:24}}>
    <div className="panel"><div className="row between"><div><span className="eyebrow">Ссылки продаж</span><h2 style={{marginBottom:4}}>Персональные ссылки промоутера</h2><p className="muted" style={{margin:0}}>Новые ссылки создаются автоматически, когда вы назначаете промоутера на мероприятие выше. Здесь настраиваются уже созданные ссылки.</p></div><span className="pill">{links.filter(link=>link.active).length} активных</span></div>
      <div style={{display:"grid",gap:14,marginTop:18}}>{links.map(link=><div key={link.id} style={{border:"1px solid #e5e7eb",borderRadius:14,padding:16}}>
        <div className="row between" style={{gap:16,alignItems:"flex-start"}}><div><strong>{link.eventTitle}</strong><div className="muted" style={{marginTop:3}}>{link.label}</div><code style={{display:"block",marginTop:8,wordBreak:"break-all"}}>{link.shareUrl}</code></div><span className="pill" style={link.active?{background:"#dcfae6",color:"#067647"}:{background:"#f2f4f7",color:"#475467"}}>{link.active?"Активна":"Выключена"}</span></div>
        <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(95px,1fr))",gap:8,marginTop:14}}>{[["Клики",link.clicks],["Checkout",link.checkout],["Abandon",link.abandoned],["Recovered",link.recovered],["Заказы",link.orders],["Билеты",link.tickets]].map(([name,value])=><div className="stat" key={String(name)}><span className="muted">{name}</span><strong style={{fontSize:20}}>{value}</strong></div>)}<div className="stat"><span className="muted">Выручка</span><strong style={{fontSize:20}}>{money(link.revenue)}</strong></div><div className="stat"><span className="muted">Конверсия</span><strong style={{fontSize:20}}>{link.conversion.toFixed(1)}%</strong></div></div>
        <div className="row" style={{gap:8,marginTop:14,flexWrap:"wrap"}}><button className="btn" type="button" onClick={()=>void copy(link.shareUrl,link.id)}>{copied===link.id?"Скопировано":"Копировать ссылку"}</button><button className="btn" type="button" disabled={busy} onClick={()=>void post({action:"toggle",linkId:link.id,active:!link.active})}>{link.active?"Выключить":"Включить"}</button></div>
        <details style={{marginTop:12}}><summary style={{cursor:"pointer",fontWeight:600}}>Настроить ссылку</summary><EditLinkForm link={link} event={events.find(e=>e.id===link.eventId)} promoterId={promoter.id} busy={busy} onSave={post}/></details>
      </div>)}{!links.length&&<p className="muted">Ссылок пока нет. Назначьте промоутера на мероприятие в блоке «Назначения промоутера» выше.</p>}</div>{error&&<div className="toast" style={{marginTop:12}}>{error}</div>}
    </div>

    <div className="panel" style={{borderColor:"#fda29b"}}><h2>{promoter.active?"Архивировать промоутера":"Промоутер архивирован"}</h2><p className="muted">История кликов, заказов, выручки и комиссий сохраняется. При архивировании все активные ссылки отключаются.</p><button className="btn" disabled={busy} onClick={()=>void post({action:"archivePromoter",promoterId:promoter.id,active:!promoter.active})}>{promoter.active?"Архивировать":"Восстановить промоутера"}</button>{error&&<div className="toast" style={{marginTop:12}}>{error}</div>}</div>
  </div>;
}
