"use client";
import { useState } from "react";

type EventItem={id:string;title:string;status:string};
export function PromoterV2Create({events}:{events:EventItem[]}){
 const[step,setStep]=useState(1);const[busy,setBusy]=useState(false);const[error,setError]=useState("");
 const[name,setName]=useState("");const[email,setEmail]=useState("");const[phone,setPhone]=useState("");const[commission,setCommission]=useState("0");const[auto,setAuto]=useState(false);const[selected,setSelected]=useState<string[]>([]);
 function toggle(id:string){setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}
 async function create(){setBusy(true);setError("");try{const r=await fetch("/api/admin/promoters-v2",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create",name,email,phone,commissionPercent:Number(commission)||0,autoAssignAllEvents:auto,eventIds:selected})});const d=await r.json();if(!r.ok){setError(d.error||"Не удалось создать промоутера");return}window.location.assign(`/office/promoters/${d.promoter.id}`)}catch{setError("Не удалось создать промоутера")}finally{setBusy(false)}}
 return <div className="panel" style={{maxWidth:760}}>
  <div className="row" style={{gap:8,marginBottom:18}}><span className="pill">{step===1?"1. Данные":"✓ Данные"}</span><span className="pill">{step===2?"2. Мероприятия":"2. Мероприятия"}</span></div>
  {step===1?<div style={{display:"grid",gap:14}}><div><span className="eyebrow">Новый промоутер</span><h2>Данные промоутера</h2><p className="muted">Пока вы не нажмёте «Продолжить», Atlas ничего не создаёт.</p></div><div className="field"><label>Имя и фамилия</label><input className="input" value={name} onChange={e=>setName(e.target.value)} minLength={2}/></div><div className="field"><label>Email</label><input className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)}/></div><div className="field"><label>Телефон</label><input className="input" value={phone} onChange={e=>setPhone(e.target.value)}/></div><div className="field"><label>Комиссия по умолчанию, %</label><input className="input" type="number" min="0" max="100" step="0.01" value={commission} onChange={e=>setCommission(e.target.value)}/></div><label className="row" style={{gap:9}}><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/><span>Автоматически назначать на новые мероприятия</span></label><button className="btn dark" disabled={name.trim().length<2||!email.includes("@")} onClick={()=>setStep(2)}>Продолжить</button></div>:
  <div style={{display:"grid",gap:14}}><div><span className="eyebrow">Новый промоутер</span><h2>Назначить мероприятия</h2><p className="muted">Можно выбрать несколько мероприятий сразу или сохранить промоутера без назначения и добавить их позже.</p></div><div style={{display:"grid",gap:8,maxHeight:360,overflow:"auto"}}>{events.map(e=><label key={e.id} className="row" style={{gap:10,padding:10,border:"1px solid #e5e7eb",borderRadius:10}}><input type="checkbox" checked={selected.includes(e.id)} onChange={()=>toggle(e.id)}/><span style={{flex:1}}><strong>{e.title}</strong><br/><small className="muted">{e.status==="PUBLISHED"?"Опубликовано":"Черновик"}</small></span></label>)}</div>{error&&<div className="toast">{error}</div>}<div className="row" style={{gap:8}}><button className="btn" disabled={busy} onClick={()=>setStep(1)}>Назад</button><button className="btn dark" disabled={busy} onClick={()=>void create()}>{busy?"Создаём...":"Создать промоутера"}</button></div></div>}
 </div>
}
