"use client";

import {FormEvent,useState} from "react";
import {useLocale} from "@/components/locale-provider";

type Mode="login"|"activate"|"forgot"|"reset";
const copy={
 ru:{error:"Не удалось выполнить действие",done:"Готово",resetSent:"Если аккаунт существует, письмо для восстановления отправлено.",errors:{PASSWORD_TOO_SHORT:"Пароль должен содержать минимум 8 символов.",PROMOTER_ACTIVATION_INVALID:"Ссылка активации недействительна или истекла.",PROMOTER_LOGIN_INVALID:"Неверный email или пароль.",PROMOTER_ACCESS_DISABLED:"Доступ к кабинету отключён.",PROMOTER_RESET_INVALID:"Ссылка восстановления недействительна или истекла.",INVALID_INPUT:"Проверьте введённые данные.",PROMOTER_AUTH_FAILED:"Не удалось выполнить действие. Попробуйте ещё раз."},title:{login:"Вход для промоутера",activate:"Создайте пароль",forgot:"Восстановление доступа",reset:"Новый пароль"},button:{login:"Войти",activate:"Активировать аккаунт",forgot:"Отправить письмо",reset:"Сохранить новый пароль"},help:{login:"Используйте email и пароль, созданный при активации.",activate:"Это одноразовая активация. После неё вход будет только по email и вашему паролю.",forgot:"Укажите email вашего аккаунта промоутера.",reset:"Придумайте новый пароль минимум из 8 символов."},password:"Пароль",wait:"Подождите...",forgot:"Забыли пароль?",back:"Вернуться ко входу"},
 he:{error:"לא הצלחנו להשלים את הפעולה",done:"הפעולה הושלמה",resetSent:"אם קיים חשבון עם הכתובת הזו, נשלח אליו מייל לשחזור הגישה.",errors:{PASSWORD_TOO_SHORT:"הסיסמה חייבת לכלול לפחות 8 תווים.",PROMOTER_ACTIVATION_INVALID:"קישור ההפעלה אינו תקף או שפג תוקפו.",PROMOTER_LOGIN_INVALID:"כתובת האימייל או הסיסמה אינם נכונים.",PROMOTER_ACCESS_DISABLED:"הגישה לפורטל הושבתה.",PROMOTER_RESET_INVALID:"קישור שחזור הסיסמה אינו תקף או שפג תוקפו.",INVALID_INPUT:"בדקו את הפרטים שהוזנו.",PROMOTER_AUTH_FAILED:"לא הצלחנו להשלים את הפעולה. נסו שוב."},title:{login:"כניסת פרומוטר",activate:"יצירת סיסמה",forgot:"שחזור גישה",reset:"סיסמה חדשה"},button:{login:"כניסה",activate:"הפעלת החשבון",forgot:"שליחת מייל",reset:"שמירת הסיסמה החדשה"},help:{login:"השתמשו ב-Email ובסיסמה שנוצרה בזמן הפעלת החשבון.",activate:"זוהי הפעלה חד-פעמית. לאחר מכן הכניסה תהיה באמצעות Email והסיסמה האישית בלבד.",forgot:"הזינו את כתובת ה-Email של חשבון הפרומוטר.",reset:"בחרו סיסמה חדשה הכוללת לפחות 8 תווים."},password:"סיסמה",wait:"נא להמתין...",forgot:"שכחתם סיסמה?",back:"חזרה לכניסה"},
 en:{error:"We could not complete the action",done:"Done",resetSent:"If an account exists for this email, a recovery message has been sent.",errors:{PASSWORD_TOO_SHORT:"Password must contain at least 8 characters.",PROMOTER_ACTIVATION_INVALID:"The activation link is invalid or has expired.",PROMOTER_LOGIN_INVALID:"Incorrect email or password.",PROMOTER_ACCESS_DISABLED:"Access to the portal has been disabled.",PROMOTER_RESET_INVALID:"The password reset link is invalid or has expired.",INVALID_INPUT:"Check the information you entered.",PROMOTER_AUTH_FAILED:"We could not complete the action. Please try again."},title:{login:"Promoter sign in",activate:"Create your password",forgot:"Recover access",reset:"New password"},button:{login:"Sign in",activate:"Activate account",forgot:"Send email",reset:"Save new password"},help:{login:"Use the email and password created during activation.",activate:"This is a one-time activation. Afterward, sign-in will use only your email and personal password.",forgot:"Enter the email address for your promoter account.",reset:"Create a new password with at least 8 characters."},password:"Password",wait:"Please wait...",forgot:"Forgot password?",back:"Back to sign in"}
} as const;

export function PromoterAuthForm({mode,token}:{mode:Mode;token?:string}){
 const{locale}=useLocale();const t=copy[locale];const dir=locale==="he"?"rtl":"ltr";const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError("");setMessage("");const form=new FormData(event.currentTarget);const payload:Record<string,unknown>={action:mode,locale};if(mode==="login"||mode==="forgot")payload.email=String(form.get("email")||"");if(mode==="login"||mode==="activate"||mode==="reset")payload.password=String(form.get("password")||"");if(mode==="activate"||mode==="reset")payload.token=token||"";const response=await fetch("/api/promoter/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await response.json().catch(()=>({}));setLoading(false);if(!response.ok){const code=String(data.errorCode||"PROMOTER_AUTH_FAILED") as keyof typeof t.errors;setError(t.errors[code]||t.error);return;}if(data.redirect){window.location.assign(data.redirect);return;}setMessage(data.messageCode==="PROMOTER_RESET_SENT"?t.resetSent:t.done);}
 return <div lang={locale==="he"?"he-IL":locale==="ru"?"ru-IL":"en-IL"} dir={dir} style={{minHeight:"100vh",display:"grid",placeItems:"center",background:"#f4f5f7",padding:24,fontFamily:"Arial,sans-serif"}}><div style={{width:"100%",maxWidth:430,background:"white",borderRadius:20,padding:30,boxShadow:"0 20px 60px rgba(16,24,40,.08)"}}><div style={{fontSize:13,letterSpacing:".12em",textTransform:"uppercase",color:"#667085",marginBottom:8}}>Atlas One · Promoter</div><h1 style={{fontSize:28,margin:"0 0 8px"}}>{t.title[mode]}</h1><p style={{color:"#667085",lineHeight:1.5}}>{t.help[mode]}</p><form onSubmit={submit}>{(mode==="login"||mode==="forgot")&&<label style={{display:"block",marginTop:18}}>Email<input name="email" type="email" dir="ltr" required autoComplete="email" style={{display:"block",width:"100%",boxSizing:"border-box",padding:12,border:"1px solid #d0d5dd",borderRadius:10,marginTop:7,textAlign:"left"}}/></label>}{(mode==="login"||mode==="activate"||mode==="reset")&&<label style={{display:"block",marginTop:18}}>{t.password}<input name="password" type="password" dir="ltr" required minLength={mode==="login"?1:8} autoComplete={mode==="login"?"current-password":"new-password"} style={{display:"block",width:"100%",boxSizing:"border-box",padding:12,border:"1px solid #d0d5dd",borderRadius:10,marginTop:7,textAlign:"left"}}/></label>}{error&&<div style={{marginTop:16,padding:11,borderRadius:10,background:"#fef3f2",color:"#b42318"}}>{error}</div>}{message&&<div style={{marginTop:16,padding:11,borderRadius:10,background:"#ecfdf3",color:"#067647"}}>{message}</div>}<button disabled={loading} style={{width:"100%",marginTop:22,padding:13,border:0,borderRadius:10,background:"#ff5c45",color:"white",fontWeight:700,cursor:"pointer"}}>{loading?t.wait:t.button[mode]}</button></form>{mode==="login"&&<div style={{marginTop:18,textAlign:"center"}}><a href="/promoter/forgot-password" style={{color:"#344054"}}>{t.forgot}</a></div>}{mode!=="login"&&mode!=="activate"&&<div style={{marginTop:18,textAlign:"center"}}><a href="/promoter/login" style={{color:"#344054"}}>{t.back}</a></div>}</div></div>;
}
