"use client";

import { useState } from "react";
import { useLocale } from "@/components/locale-provider";

type LegacyProps={events?:unknown;promoters?:unknown;showLinkForm?:boolean};
const copy={ru:{missing:"Промоутер создан, но Atlas не получил его ID. Обновите страницу и откройте его из списка.",createError:"Не удалось создать промоутера",finishError:"Не удалось завершить создание промоутера. Обновите страницу и проверьте список.",title:"Новый промоутер",help:"После создания Atlas отправит Welcome-письмо для активации защищённого кабинета и сразу откроет карточку промоутера.",name:"Имя и фамилия",email:"Email *",emailHelp:"На этот адрес придёт одноразовая ссылка активации кабинета и дальнейшие уведомления о мероприятиях.",phone:"Телефон",commission:"Комиссия по умолчанию, %",auto:"Автоматически добавлять ко всем новым мероприятиям",autoHelp:"При публикации нового мероприятия Atlas создаст персональную ссылку и отправит её этому промоутеру.",busy:"Создаём...",add:"Добавить промоутера"},he:{missing:"המפיק נוצר, אך Atlas לא קיבלה את המזהה שלו. רעננו את העמוד ופתחו אותו מהרשימה.",createError:"לא הצלחנו ליצור את המקדם",finishError:"לא הצלחנו להשלים את יצירת המקדם. רעננו את העמוד ובדקו את הרשימה.",title:"מקדם חדש",help:"לאחר היצירה Atlas תשלח מייל פתיחה להפעלת האזור המאובטח ותפתח מיד את כרטיס המקדם.",name:"שם מלא",email:"Email *",emailHelp:"לכתובת הזו תישלח קישור חד־פעמי להפעלת החשבון ובהמשך גם עדכונים על אירועים.",phone:"טלפון",commission:"עמלה ברירת מחדל, %",auto:"להוסיף אוטומטית לכל אירוע חדש",autoHelp:"בעת פרסום אירוע חדש Atlas תיצור קישור אישי ותשלח אותו למקדם הזה.",busy:"יוצרים...",add:"הוספת מקדם"},en:{missing:"The promoter was created, but Atlas did not receive its ID. Refresh the page and open it from the list.",createError:"Could not create promoter",finishError:"Could not finish creating the promoter. Refresh the page and check the list.",title:"New promoter",help:"After creation, Atlas sends a welcome email to activate the secure workspace and opens the promoter profile.",name:"Full name",email:"Email *",emailHelp:"A one-time account activation link and future event notifications will be sent to this address.",phone:"Phone",commission:"Default commission, %",auto:"Automatically add to all new events",autoHelp:"When a new event is published, Atlas creates a personal link and sends it to this promoter.",busy:"Creating...",add:"Add promoter"}} as const;

export function PromoterManager(_props:LegacyProps) {
  const {locale}=useLocale();const text=copy[locale];const[error,setError]=useState("");const[busy,setBusy]=useState(false);
  function openPromoter(id:unknown){if(typeof id!=="string"||!id){setError(text.missing);return;}window.location.assign(`/office/promoters/${encodeURIComponent(id)}`);}
  async function sendWelcome(promoterId:string){try{await fetch("/api/admin/promoters/account",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({promoterId,force:false})});}catch{}}
  async function submit(form:HTMLFormElement){const f=new FormData(form);setBusy(true);setError("");try{const response=await fetch("/api/admin/promoters",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"promoter",name:f.get("name"),email:f.get("email"),phone:f.get("phone"),commissionPercent:Number(f.get("commission")||0),autoAssignAllEvents:f.get("autoAssignAllEvents")==="on"})});const data=await response.json();if(response.status===409&&data.existingId){openPromoter(data.existingId);return;}if(!response.ok){setError(data.error||text.createError);setBusy(false);return;}if(typeof data.id==="string")await sendWelcome(data.id);openPromoter(data.id);}catch{setError(text.finishError);setBusy(false);}}
  return <div className="promoter-manager"><div className="panel form"><h2>{text.title}</h2><p className="muted">{text.help}</p><form onSubmit={e=>{e.preventDefault();void submit(e.currentTarget)}}><div className="field"><label>{text.name}</label><input className="input" name="name" required minLength={2}/></div><div className="field"><label>{text.email}</label><input className="input" dir="ltr" style={{textAlign:"left"}} name="email" type="email" required/><small className="muted">{text.emailHelp}</small></div><div className="field"><label>{text.phone}</label><input className="input" dir="ltr" style={{textAlign:"left""}} name="phone" type="tel"/></div><div className="field"><label>{text.commission}</label><input className="input" dir="ltr" style={{textAlign:"left"}} name="commission" type="number" min="0" max="100" step="0.01" defaultValue="0"/></div><label className="row" style={{gap:8,alignItems:"flex-start"}}><input name="autoAssignAllEvents" type="checkbox"/><span><strong>{text.auto}</strong><br/><small className="muted">{text.autoHelp}</small></span></label>{error&&<div className="toast">{error}</div>}<button className="btn dark" disabled={busy}>{busy?text.busy:text.add}</button></form></div></div>;
}
