"use client";
import { useState } from "react";
import { useLocale } from "@/components/locale-provider";

type EventItem={id:string;title:string;status:string};
const copy={
 ru:{data:"Данные",events:"Мероприятия",new:"Новый промоутер",dataTitle:"Данные промоутера",dataHelp:"Пока вы не нажмёте «Продолжить», Atlas ничего не создаёт.",name:"Имя и фамилия",email:"Email",phone:"Телефон",commission:"Комиссия по умолчанию, %",auto:"Автоматически назначать на новые мероприятия",next:"Продолжить",eventsTitle:"Назначить мероприятия",eventsHelp:"Можно выбрать несколько мероприятий сразу или сохранить промоутера без назначения и добавить их позже.",published:"Опубликовано",draft:"Черновик",back:"Назад",busy:"Создаём...",create:"Создать промоутера",error:"Не удалось создать промоутера"},
 he:{data:"פרטים",events:"אירועים",new:"מקדם חדש",dataTitle:"פרטי המקדם",dataHelp:"Atlas לא תיצור דבר עד שתלחצו על ״המשך״.",name:"שם מלא",email:"Email",phone:"טלפון",commission:"עמלה ברירת מחדל, %",auto:"לשייך אוטומטית לאירועים חדשים",next:"המשך",eventsTitle:"שיוך אירועים",eventsHelp:"אפשר לבחור כמה אירועים יחד, או ליצור את המקדם ללא שיוך ולהוסיף אירועים בהמשך.",published:"פורסם",draft:"טיוטה",back:"חזרה",busy:"יוצרים...",create:"יצירת מקדם",error:"לא הצלחנו ליצור את המקדם"},
 en:{data:"Details",events:"Events",new:"New promoter",dataTitle:"Promoter details",dataHelp:"Atlas creates nothing until you press Continue.",name:"Full name",email:"Email",phone:"Phone",commission:"Default commission, %",auto:"Automatically assign to new events",next:"Continue",eventsTitle:"Assign events",eventsHelp:"Select several events at once, or create the promoter without assignments and add them later.",published:"Published",draft:"Draft",back:"Back",busy:"Creating...",create:"Create promoter",error:"Could not create promoter"}
} as const;
export function PromoterV2Create({events}:{events:EventItem[]}){
 const{locale}=useLocale();const text=copy[locale];const[step,setStep]=useState(1);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[name,setName]=useState("");const[email,setEmail]=useState("");const[phone,setPhone]=useState("");const[commission,setCommission]=useState("0");const[auto,setAuto]=useState(false);const[selected,setSelected]=useState<string[]>([]);
 function toggle(id:string){setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}
 async function create(){setBusy(true);setError("");try{const r=await fetch("/api/admin/promoters-v2",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create",name,email,phone,commissionPercent:Number(commission)||0,autoAssignAllEvents:auto,eventIds:selected})});const d=await r.json();if(!r.ok){setError(d.error||text.error);return}window.location.assign(`/office/promoters/${d.promoter.id}`)}catch{setError(text.error)}finally{setBusy(false)}}
 const ltr={direction:"ltr" as const,textAlign:"left" as const};
 return <div className="panel" style={{maxWidth:760}}><div className="row" style={{gap:8,marginBottom:18}}><span className="pill">{step===1?`1. ${text.data}`:`✓ ${text.data}`}</span><span className="pill">2. {text.events}</span></div>{step===1?<div style={{display:"grid",gap:14}}><div><span className="eyebrow">{text.new}</span><h2>{text.dataTitle}</h2><p className="muted">{text.dataHelp}</p></div><div className="field"><label>{text.name}</label><input className="input" value={name} onChange={e=>setName(e.target.value)} minLength={2}/></div><div className="field"><label>{text.email}</label><input className="input" dir="ltr" style={ltr} type="email" value={email} onChange={e=>setEmail(e.target.value)}/></div><div className="field"><label>{text.phone}</label><input className="input" dir="ltr" style={ltr} value={phone} onChange={e=>setPhone(e.target.value)}/></div><div className="field"><label>{text.commission}</label><input className="input" dir="ltr" style={ltr} type="number" min="0" max="100" step="0.01" value={commission} onChange={e=>setCommission(e.target.value)}/></div><label className="row" style={{gap:9}}><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/><span>{text.auto}</span></label><button className="btn dark" disabled={name.trim().length<2||!email.includes("@")} onClick={()=>setStep(2)}>{text.next}</button></div>:<div style={{display:"grid",gap:14}}><div><span className="eyebrow">{text.new}</span><h2>{text.eventsTitle}</h2><p className="muted">{text.eventsHelp}</p></div><div style={{display:"grid",gap:8,maxHeight:360,overflow:"auto"}}>{events.map(e=><label key={e.id} className="row" style={{gap:10,padding:10,border:"1px solid #e5e7eb",borderRadius:10}}><input type="checkbox" checked={selected.includes(e.id)} onChange={()=>toggle(e.id)}/><span style={{flex:1}}><strong>{e.title}</strong><br/><small className="muted">{e.status==="PUBLISHED"?text.published:text.draft}</small></span></label>)}</div>{error&&<div className="toast">{error}</div>}<div className="row" style={{gap:8}}><button className="btn" disabled={busy} onClick={()=>setStep(1)}>{text.back}</button><button className="btn dark" disabled={busy} onClick={()=>void create()}>{busy?text.busy:text.create}</button></div></div>}</div>
}
