"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { Check, Clock3, Search, TicketCheck, UserRoundCheck, X } from "lucide-react";
import { money } from "@/lib/format";

type RequestItem={name:string;quantity:number};
type RequestRecord={id:string;publicId:string;customerName:string;customerEmail:string;customerPhone:string;answer:string|null;status:string;eventTitle:string;eventDate:string;createdAt:string;totalMinor:number;items:RequestItem[]};

export function RequestInbox({initialRequests}:{initialRequests:RequestRecord[]}){
  const [requests,setRequests]=useState(initialRequests);const [filter,setFilter]=useState<"pending"|"approved"|"rejected"|"all">("pending");const [query,setQuery]=useState("");const [busy,setBusy]=useState("");const [error,setError]=useState("");
  const counts={pending:requests.filter(item=>item.status==="PENDING_APPROVAL").length,approved:requests.filter(item=>item.status==="AWAITING_PAYMENT").length,rejected:requests.filter(item=>item.status==="REJECTED").length};
  const visible=useMemo(()=>requests.filter(item=>(filter==="all"||(filter==="pending"&&item.status==="PENDING_APPROVAL")||(filter==="approved"&&item.status==="AWAITING_PAYMENT")||(filter==="rejected"&&item.status==="REJECTED"))&&`${item.customerName} ${item.customerPhone} ${item.eventTitle}`.toLowerCase().includes(query.toLowerCase())),[requests,filter,query]);
  async function decide(item:RequestRecord,action:"approve"|"reject"){setBusy(item.id);setError("");const response=await fetch(`/api/admin/orders/${item.publicId}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action,note:action==="approve"?"Одобрено в Atlas Office":"Заявка отклонена организатором"})});const data=await response.json();if(!response.ok){setError(data.error||"Не удалось обработать заявку");setBusy("");return;}setRequests(current=>current.map(record=>record.id===item.id?{...record,status:action==="approve"?"AWAITING_PAYMENT":"REJECTED"}:record));setBusy("")}
  return <><div className="request-kpis"><button className={filter==="pending"?"active":""} onClick={()=>setFilter("pending")}><Clock3/><span>Ожидают решения</span><strong>{counts.pending}</strong></button><button className={filter==="approved"?"active":""} onClick={()=>setFilter("approved")}><TicketCheck/><span>Одобрены</span><strong>{counts.approved}</strong></button><button className={filter==="rejected"?"active":""} onClick={()=>setFilter("rejected")}><X/><span>Отклонены</span><strong>{counts.rejected}</strong></button></div><div className="request-toolbar"><label><Search size={17}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Имя, телефон или мероприятие"/></label><button onClick={()=>setFilter("all")}>Показать все</button></div>{error&&<div className="toast">{error}</div>}<div className="request-grid">{visible.map(item=><article className="request-card" key={item.id}><header><div className="request-avatar">{item.customerName.split(" ").map(part=>part[0]).slice(0,2).join("")}</div><div><strong>{item.customerName}</strong><a href={`tel:${item.customerPhone}`}>{item.customerPhone}</a></div><span className={`request-status ${item.status.toLowerCase()}`}>{item.status==="PENDING_APPROVAL"?"Ожидает":item.status==="AWAITING_PAYMENT"?"Одобрена":"Отклонена"}</span></header><div className="request-event"><small>{item.eventTitle}</small><strong>{item.items.map(ticket=>`${ticket.name} × ${ticket.quantity}`).join(", ")}</strong><span>{money(item.totalMinor)}</span></div><blockquote><small>Ответ клиента</small>{item.answer||"Дополнительная информация не указана"}</blockquote><footer><small>Получена {new Date(item.createdAt).toLocaleString("ru-RU")}</small><Link href={`/office/orders/${item.publicId}`}>Подробнее</Link></footer>{item.status==="PENDING_APPROVAL"&&<div className="request-actions"><button disabled={busy===item.id} className="approve" onClick={()=>void decide(item,"approve")}><Check size={18}/>{busy===item.id?"Обрабатываем…":"Одобрить"}</button><button disabled={busy===item.id} className="reject" onClick={()=>void decide(item,"reject")}><X size={18}/>Отклонить</button></div>}</article>)}{visible.length===0&&<div className="office-empty"><UserRoundCheck size={38}/><h3>В этой категории заявок нет</h3><p>Новые запросы клиентов появятся здесь автоматически.</p></div>}</div></>;
}
