/* eslint-disable @next/next/no-img-element -- organizer-provided local assets use intrinsic canvas sizing */
import Image from "next/image";
import Link from "next/link";
import { WalletCards } from "lucide-react";
import type { TicketDesign,TicketElement } from "@/lib/ticket-template-types";

type Data={eventTitle:string;date:string;time:string;venue:string;address:string;customerName:string;ticketType:string;orderNumber:string;ticketCode:string};
function value(item:TicketElement,data:Data){const values:Record<string,string>={EVENT_TITLE:data.eventTitle,EVENT_DATE:data.date,EVENT_TIME:data.time,VENUE:data.venue,ADDRESS:data.address,CUSTOMER_NAME:data.customerName,TICKET_TYPE:data.ticketType,ORDER_NUMBER:data.orderNumber,TICKET_CODE:data.ticketCode,CUSTOM:item.content};return values[item.binding]??item.content}
export function TicketCard({ticket,qr,design,event,orderNumber,walletReady}:{ticket:{id:string;publicCode:string;status:string;holderName:string;category:{name:string}};qr:string;design:TicketDesign;event:{title:string;startsAt:Date;venue:{name:string;address:string}};orderNumber:string;walletReady:boolean}){const date=event.startsAt.toLocaleDateString("ru-RU",{day:"numeric",month:"long",year:"numeric"});const time=event.startsAt.toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"});const data={eventTitle:event.title,date,time,venue:event.venue.name,address:event.venue.address,customerName:ticket.holderName,ticketType:ticket.category.name,orderNumber,ticketCode:ticket.publicCode};return <article className="customer-ticket-wrap"><div className="customer-ticket" style={{backgroundColor:design.backgroundColor,backgroundImage:design.backgroundUrl?`linear-gradient(#08142677,#081426bb),url(${design.backgroundUrl})`:undefined}}>{design.logoUrl&&<img className="customer-ticket-logo" src={design.logoUrl} alt="Логотип организатора"/>}{design.elements.filter(item=>!item.hidden).map(item=><div key={item.id} className="customer-ticket-element" style={{left:`${item.x}%`,top:`${item.y}%`,width:`${item.width}%`,height:`${item.height}%`,fontSize:item.fontSize,color:item.color,textAlign:item.align,fontWeight:item.bold?800:400}}>{item.binding==="QR"?<Image src={qr} alt="Ticket QR code" width={260} height={260} unoptimized/>:item.binding==="IMAGE"?<img src={item.content} alt="Оформление билета"/>:<span>{value(item,data)}</span>}</div>)}</div><div className="ticket-delivery-actions"><Link className="btn secondary" href={`/api/tickets/${ticket.id}/pdf`}>Скачать PDF</Link>{walletReady?<Link className="apple-wallet-button" href={`/api/wallet/tickets/${ticket.id}`}><WalletCards size={20}/><span><small>Добавить в</small>Apple Wallet</span></Link>:<span className="wallet-unavailable" title="Добавьте Apple Wallet сертификаты в окружение"><WalletCards size={18}/>Apple Wallet будет доступен после подключения сертификата</span>}</div></article>}
