"use client";
/* eslint-disable @next/next/no-img-element -- uploaded artwork must preserve the ticket canvas crop */
import { useRef,useState } from "react";
import { useRouter } from "next/navigation";
import { AlignCenter,AlignLeft,AlignRight,Bold,CalendarDays,Copy,ImagePlus,MapPin,Plus,QrCode,RotateCcw,Save,Trash2,Type,Upload,UserRound } from "lucide-react";
import type { TicketBinding,TicketDesign,TicketElement } from "@/lib/ticket-template-types";

type EventData={id:string;title:string;startsAt:string;venue:string;address:string;ticketType:string};
const bindings:{value:TicketBinding;label:string;icon:typeof Type}[]=[{value:"EVENT_TITLE",label:"Название события",icon:Type},{value:"EVENT_DATE",label:"Дата",icon:CalendarDays},{value:"EVENT_TIME",label:"Время",icon:CalendarDays},{value:"VENUE",label:"Площадка",icon:MapPin},{value:"ADDRESS",label:"Адрес",icon:MapPin},{value:"CUSTOMER_NAME",label:"Имя гостя",icon:UserRound},{value:"TICKET_TYPE",label:"Тип билета",icon:Type},{value:"ORDER_NUMBER",label:"Номер заказа",icon:Type},{value:"TICKET_CODE",label:"Код билета",icon:Type},{value:"QR",label:"QR-код",icon:QrCode}];
const bindingLabel=Object.fromEntries(bindings.map(item=>[item.value,item.label]));
const previewValue=(item:TicketElement,event:EventData)=>{const date=new Date(event.startsAt);const values:Partial<Record<TicketBinding,string>>={EVENT_TITLE:event.title,EVENT_DATE:date.toLocaleDateString("ru-RU",{day:"numeric",month:"long",year:"numeric"}),EVENT_TIME:date.toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"}),VENUE:event.venue,ADDRESS:event.address,CUSTOMER_NAME:"Igor Levin",TICKET_TYPE:event.ticketType,ORDER_NUMBER:"ATL-92K8-4M2A",TICKET_CODE:"ATL-TKT-8F2K-92MA"};return item.binding==="CUSTOM"?item.content:values[item.binding]??item.content};

export function TicketDesigner({event,initialDesign}:{event:EventData;initialDesign:TicketDesign}){
  const router=useRouter();const[design,setDesign]=useState(initialDesign);const[selectedId,setSelectedId]=useState(initialDesign.elements[0]?.id??"");const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);const drag=useRef<{id:string;dx:number;dy:number}|null>(null);
  const selected=design.elements.find(item=>item.id===selectedId);
  function updateElement(patch:Partial<TicketElement>){setDesign(current=>({...current,elements:current.elements.map(item=>item.id===selectedId?{...item,...patch}:item)}))}
  function add(binding:TicketBinding,content=""){const item:TicketElement={id:crypto.randomUUID(),binding,x:10,y:45,width:80,height:binding==="QR"?24:8,content,fontSize:binding==="CUSTOM"?18:14,color:design.textColor,align:"left",bold:binding==="CUSTOM",hidden:false};setDesign(current=>({...current,elements:[...current.elements,item]}));setSelectedId(item.id)}
  async function upload(file:File,purpose:"element"|"background"|"logo"){const form=new FormData();form.set("image",file);const response=await fetch("/api/uploads",{method:"POST",body:form});const result=await response.json();if(!response.ok){setMessage(result.error);return}if(purpose==="background")setDesign(current=>({...current,backgroundUrl:result.url}));else if(purpose==="logo")setDesign(current=>({...current,logoUrl:result.url}));else add("IMAGE",result.url)}
  async function save(){setBusy(true);setMessage("");const response=await fetch(`/api/admin/events/${event.id}/ticket-template`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(design)});const result=await response.json();setMessage(response.ok?`Шаблон сохранён. Билетов для Wallet обновлено: ${result.updatedWalletPasses}`:result.error);setBusy(false);if(response.ok)router.refresh()}
  return <><div className="office-page-heading"><div><span className="eyebrow">Ticket studio</span><h1>Редактор билета</h1><p>Создайте единый дизайн для экрана, PDF и Apple Wallet.</p></div><div className="row"><button className="btn secondary" onClick={()=>setDesign(initialDesign)}><RotateCcw size={17}/>Сбросить</button><button className="btn" disabled={busy} onClick={()=>void save()}><Save size={17}/>{busy?"Сохраняем…":"Сохранить"}</button></div></div>
  <div className="ticket-studio"><aside className="ticket-tools"><h3>Добавить</h3><button onClick={()=>add("CUSTOM","Новый текст")}><Type/>Текст</button><label><ImagePlus/><span>Фотография</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file,"element")}}/></label>{bindings.map(item=>{const Icon=item.icon;return <button key={item.value} onClick={()=>add(item.value)}><Icon/>{item.label}</button>})}<h3>Оформление</h3><label><Upload/><span>Фон билета</span><input type="file" accept="image/*" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file,"background")}}/></label><label><Upload/><span>Логотип</span><input type="file" accept="image/*" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file,"logo")}}/></label><div className="ticket-color-row"><label>Фон<input type="color" value={design.backgroundColor} onChange={e=>setDesign({...design,backgroundColor:e.target.value})}/></label><label>Акцент<input type="color" value={design.accentColor} onChange={e=>setDesign({...design,accentColor:e.target.value})}/></label></div></aside>
  <main className="ticket-canvas-wrap"><div className="ticket-device"><div className="ticket-canvas" style={{backgroundColor:design.backgroundColor,backgroundImage:design.backgroundUrl?`linear-gradient(#08142688,#081426bb),url(${design.backgroundUrl})`:undefined}} onClick={()=>setSelectedId("")} onPointerMove={e=>{if(!drag.current)return;const rect=e.currentTarget.getBoundingClientRect();const x=Math.max(0,Math.min(100-design.elements.find(i=>i.id===drag.current?.id)!.width,(e.clientX-rect.left)/rect.width*100-drag.current.dx));const y=Math.max(0,Math.min(100-design.elements.find(i=>i.id===drag.current?.id)!.height,(e.clientY-rect.top)/rect.height*100-drag.current.dy));setDesign(current=>({...current,elements:current.elements.map(item=>item.id===drag.current?.id?{...item,x,y}:item)}))}} onPointerUp={e=>{drag.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId)}}>{design.logoUrl&&<img className="ticket-studio-logo" src={design.logoUrl} alt="Logo"/>}{design.elements.filter(item=>!item.hidden).map(item=><button key={item.id} className={`ticket-design-element ${item.id===selectedId?"selected":""}`} style={{left:`${item.x}%`,top:`${item.y}%`,width:`${item.width}%`,height:`${item.height}%`,fontSize:item.fontSize,color:item.color,textAlign:item.align,fontWeight:item.bold?800:400}} onClick={e=>{e.stopPropagation();setSelectedId(item.id)}} onPointerDown={e=>{e.stopPropagation();const rect=e.currentTarget.parentElement!.getBoundingClientRect();drag.current={id:item.id,dx:(e.clientX-rect.left)/rect.width*100-item.x,dy:(e.clientY-rect.top)/rect.height*100-item.y};e.currentTarget.parentElement!.setPointerCapture(e.pointerId)}}>{item.binding==="QR"?<span className="ticket-qr-placeholder"><QrCode/><small>Уникальный QR</small></span>:item.binding==="IMAGE"?<img src={item.content} alt="Ticket decoration"/>:<span>{previewValue(item,event)}</span>}</button>)}</div></div><div className="ticket-safe-note">Пунктирная зона — безопасное поле. QR и важные данные не размещайте у края.</div></main>
  <aside className="ticket-properties">{selected?<><div className="row between"><div><small>Выбран элемент</small><h3>{bindingLabel[selected.binding]??(selected.binding==="IMAGE"?"Фотография":"Текст")}</h3></div><button className="icon-btn" onClick={()=>{setDesign(current=>({...current,elements:current.elements.filter(item=>item.id!==selected.id)}));setSelectedId("")}}><Trash2/></button></div>{selected.binding==="CUSTOM"&&<label className="field"><span>Текст</span><textarea rows={3} value={selected.content} onChange={e=>updateElement({content:e.target.value})}/></label>}<div className="property-pair"><label className="field"><span>Ширина</span><input className="input" type="number" min="5" max="100" value={Math.round(selected.width)} onChange={e=>updateElement({width:Number(e.target.value)})}/></label><label className="field"><span>Высота</span><input className="input" type="number" min="3" max="100" value={Math.round(selected.height)} onChange={e=>updateElement({height:Number(e.target.value)})}/></label></div>{!(["QR","IMAGE"] as TicketBinding[]).includes(selected.binding)&&<><div className="property-pair"><label className="field"><span>Размер</span><input className="input" type="number" min="8" max="54" value={selected.fontSize} onChange={e=>updateElement({fontSize:Number(e.target.value)})}/></label><label className="field"><span>Цвет</span><input className="input color-input" type="color" value={selected.color} onChange={e=>updateElement({color:e.target.value})}/></label></div><div className="ticket-format"><button className={selected.bold?"active":""} onClick={()=>updateElement({bold:!selected.bold})}><Bold/></button><button className={selected.align==="left"?"active":""} onClick={()=>updateElement({align:"left"})}><AlignLeft/></button><button className={selected.align==="center"?"active":""} onClick={()=>updateElement({align:"center"})}><AlignCenter/></button><button className={selected.align==="right"?"active":""} onClick={()=>updateElement({align:"right"})}><AlignRight/></button></div></>}<button className="btn secondary full" onClick={()=>{const clone={...selected,id:crypto.randomUUID(),x:Math.min(95,selected.x+3),y:Math.min(95,selected.y+3)};setDesign(current=>({...current,elements:[...current.elements,clone]}));setSelectedId(clone.id)}}><Copy size={16}/>Дублировать</button></>:<div className="office-empty"><Plus/><h3>Выберите элемент</h3><p>Нажмите на объект в билете или добавьте новый слева.</p></div>}</aside></div>{message&&<div className="toast ticket-studio-toast">{message}</div>}</>;
}
