import type { Metadata } from "next";
import { ContentPage, Section } from "@/components/content-page";
import { getServerI18n } from "@/lib/server-locale";
import type { Locale } from "@/lib/i18n";

const copy={
  ru:{meta:"Условия использования Atlas One",description:"Условия покупки билетов и использования платформы Atlas One.",title:"Условия использования",intro:"Основные правила использования Atlas One покупателями и организаторами.",sections:[["Покупка билета","Покупатель обязан указывать корректные данные и проверять дату, место, категорию и количество билетов перед оплатой."],["Роль организатора","Организатор отвечает за проведение события, программу, допуск, перенос или отмену мероприятия и специальные правила посещения."],["Электронный билет","QR-код уникален. Его нельзя публиковать или передавать неизвестным лицам. Первый успешный проход может погасить билет."],["Изменения","Условия могут обновляться. К конкретному заказу применяются условия, действовавшие на момент покупки, если закон не требует иного."]]},
  he:{meta:"תנאי השימוש של Atlas One",description:"התנאים לרכישת כרטיסים ולשימוש בפלטפורמת Atlas One.",title:"תנאי שימוש",intro:"הכללים המרכזיים לשימוש ב-Atlas One על ידי רוכשי כרטיסים ומפיקים.",sections:[["רכישת כרטיס","על הרוכשים למסור פרטים נכונים ולבדוק לפני התשלום את התאריך, המקום, סוג הכרטיס והכמות."],["אחריות המפיק","המפיק אחראי לקיום האירוע, לתוכן, לתנאי הכניסה, לשינוי מועד או לביטול ולכללים מיוחדים החלים במקום."],["כרטיס דיגיטלי","קוד ה-QR הוא ייחודי. אין לפרסם אותו או להעביר אותו לאדם לא מוכר. הסריקה התקינה הראשונה עשויה לממש את הכרטיס."],["עדכונים לתנאים","התנאים עשויים להתעדכן. על הזמנה מסוימת יחולו התנאים שהיו בתוקף במועד הרכישה, אלא אם הדין מחייב אחרת."]]},
  en:{meta:"Atlas One terms of use",description:"Terms for purchasing tickets and using the Atlas One platform.",title:"Terms of use",intro:"The main rules for ticket buyers and organizers using Atlas One.",sections:[["Buying a ticket","Buyers must provide accurate information and check the date, venue, category, and quantity before payment."],["Organizer responsibility","The organizer is responsible for holding the event, its program, admission, rescheduling or cancellation, and any special attendance rules."],["Digital ticket","The QR code is unique. Do not publish it or share it with unknown people. The first successful admission may redeem the ticket."],["Changes","These terms may be updated. An order remains subject to the terms in effect when it was purchased unless the law requires otherwise."]]},
} satisfies Record<Locale,{meta:string;description:string;title:string;intro:string;sections:string[][]}>;
export async function generateMetadata():Promise<Metadata>{const{locale}=await getServerI18n();const text=copy[locale];return{title:text.meta,description:text.description,alternates:{canonical:"/terms"}};}
export default async function TermsPage(){const{locale}=await getServerI18n();const text=copy[locale];return <ContentPage eyebrow="Legal" title={text.title} intro={text.intro}>{text.sections.map(([title,body])=><Section key={title} title={title}><p>{body}</p></Section>)}</ContentPage>}
