import { Ionicons } from "@expo/vector-icons";
import { useLocalSearchParams, useRouter } from "expo-router";
import * as SecureStore from "expo-secure-store";
import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

const API = (process.env.EXPO_PUBLIC_API_BASE_URL || "https://www.atlas-one.co").replace(/\/$/, "");
const TOKEN_KEY = "atlas-office-session";
type Binding = "CUSTOM"|"EVENT_TITLE"|"EVENT_DATE"|"EVENT_TIME"|"VENUE"|"ADDRESS"|"CUSTOMER_NAME"|"TICKET_TYPE"|"ORDER_NUMBER"|"TICKET_CODE"|"QR"|"IMAGE";
type Element = { id:string; binding:Binding; x:number; y:number; width:number; height:number; content:string; fontSize:number; color:string; align:"left"|"center"|"right"; bold:boolean; hidden:boolean };
type Design = { name:string; backgroundColor:string; accentColor:string; textColor:string; logoUrl:string|null; backgroundUrl:string|null; elements:Element[] };
type Payload = { event:{id:string;title:string;startsAt:string;venue:string;address:string;ticketType:string}; design:Design };
const BINDINGS: Array<{id:Binding;label:string}> = [
  {id:"CUSTOM",label:"Текст"},{id:"EVENT_TITLE",label:"Название события"},{id:"EVENT_DATE",label:"Дата"},{id:"EVENT_TIME",label:"Время"},{id:"VENUE",label:"Площадка"},{id:"ADDRESS",label:"Адрес"},{id:"CUSTOMER_NAME",label:"Имя гостя"},{id:"TICKET_TYPE",label:"Тип билета"},{id:"ORDER_NUMBER",label:"Номер заказа"},{id:"TICKET_CODE",label:"Код билета"},{id:"QR",label:"QR-код"},{id:"IMAGE",label:"Изображение"},
];
async function headers(){const token=await SecureStore.getItemAsync(TOKEN_KEY);return {"content-type":"application/json",...(token?{authorization:`Bearer ${token}`}:{})};}
async function request<T>(id:string,method="GET",body?:unknown){const r=await fetch(`${API}/api/mobile/events/${encodeURIComponent(id)}/ticket-template`,{method,headers:await headers(),body:body?JSON.stringify(body):undefined});const text=await r.text();let data:any={};try{data=text?JSON.parse(text):{}}catch{}if(!r.ok)throw new Error(data.error||`HTTP_${r.status}`);return data as T;}
function clamp(n:number,min:number,max:number){return Math.max(min,Math.min(max,n));}
function nextElement(binding:Binding,index:number,textColor:string):Element{return {id:`m-${Date.now()}-${index}`,binding,x:10,y:10+index*7,width:binding==="QR"?28:80,height:binding==="QR"?26:binding==="IMAGE"?18:8,content:binding==="CUSTOM"?"Новый текст":"",fontSize:14,color:textColor,align:"left",bold:binding==="CUSTOM",hidden:false};}

export default function TicketDesignScreen(){
  const router=useRouter();const {id}=useLocalSearchParams<{id:string}>();const eventId=String(id||"");
  const[payload,setPayload]=useState<Payload|null>(null);const[design,setDesign]=useState<Design|null>(null);const[busy,setBusy]=useState(false);const[selected,setSelected]=useState<string|null>(null);
  useEffect(()=>{request<Payload>(eventId).then((p)=>{setPayload(p);setDesign(p.design);setSelected(p.design.elements[0]?.id||null)}).catch((e)=>Alert.alert("Не удалось открыть дизайн",e.message));},[eventId]);
  const item=useMemo(()=>design?.elements.find((x)=>x.id===selected)||null,[design,selected]);
  if(!payload||!design)return <SafeAreaView style={s.center}><ActivityIndicator size="large"/></SafeAreaView>;
  function patchDesign(part:Partial<Design>){setDesign((d)=>d?{...d,...part}:d)}
  function patchItem(part:Partial<Element>){if(!selected)return;setDesign((d)=>d?{...d,elements:d.elements.map((x)=>x.id===selected?{...x,...part}:x)}:d)}
  function add(binding:Binding){const el=nextElement(binding,design.elements.length,design.textColor);patchDesign({elements:[...design.elements,el]});setSelected(el.id)}
  function remove(){if(!item||item.binding==="QR")return;patchDesign({elements:design.elements.filter((x)=>x.id!==item.id)});setSelected(design.elements.find((x)=>x.id!==item.id)?.id||null)}
  async function save(){setBusy(true);try{const result=await request<{updatedWalletPasses:number}>(eventId,"PUT",design);Alert.alert("Сохранено",`Дизайн обновлён. Wallet-билетов обновлено: ${result.updatedWalletPasses}.`)}catch(e){Alert.alert("Не удалось сохранить",e instanceof Error?e.message:"Ошибка")}finally{setBusy(false)}}
  return <SafeAreaView style={s.safe} edges={["top"]}>
    <View style={s.header}><TouchableOpacity style={s.icon} onPress={()=>router.back()}><Ionicons name="chevron-back" size={27} color="#17213C"/></TouchableOpacity><View style={{flex:1}}><Text style={s.headerTitle}>Дизайн билета</Text><Text style={s.meta} numberOfLines={1}>{payload.event.title}</Text></View><TouchableOpacity disabled={busy} style={s.saveTop} onPress={save}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.saveTopText}>Сохранить</Text>}</TouchableOpacity></View>
    <ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
      <Text style={s.section}>Предпросмотр</Text>
      <View style={[s.ticket,{backgroundColor:design.backgroundColor}]}>
        {!!design.logoUrl&&<Text style={s.logoHint}>LOGO</Text>}
        {design.elements.filter((x)=>!x.hidden).map((x)=><TouchableOpacity key={x.id} onPress={()=>setSelected(x.id)} style={[s.previewItem,{left:`${clamp(x.x,0,95)}%`,top:`${clamp(x.y,0,95)}%`,width:`${clamp(x.width,5,100)}%`,minHeight:x.binding==="QR"?54:24,borderColor:selected===x.id?design.accentColor:"transparent"}]}><Text style={{color:x.color,fontSize:clamp(x.fontSize,8,32),fontWeight:x.bold?"900":"500",textAlign:x.align}} numberOfLines={2}>{x.binding==="QR"?"▣ QR":x.binding==="CUSTOM"?(x.content||"Текст"):BINDINGS.find((b)=>b.id===x.binding)?.label}</Text></TouchableOpacity>)}
      </View>

      <View style={s.card}><Text style={s.cardTitle}>Оформление</Text><Field label="Название шаблона"><TextInput style={s.input} value={design.name} onChangeText={(name)=>patchDesign({name})}/></Field><View style={s.row}><View style={s.half}><Field label="Фон #HEX"><TextInput style={s.input} value={design.backgroundColor} onChangeText={(backgroundColor)=>patchDesign({backgroundColor})} autoCapitalize="characters"/></Field></View><View style={s.half}><Field label="Акцент #HEX"><TextInput style={s.input} value={design.accentColor} onChangeText={(accentColor)=>patchDesign({accentColor})} autoCapitalize="characters"/></Field></View></View><Field label="Цвет текста #HEX"><TextInput style={s.input} value={design.textColor} onChangeText={(textColor)=>patchDesign({textColor})} autoCapitalize="characters"/></Field><Field label="URL логотипа"><TextInput style={s.input} value={design.logoUrl||""} onChangeText={(v)=>patchDesign({logoUrl:v.trim()||null})} autoCapitalize="none"/></Field><Field label="URL фонового изображения"><TextInput style={s.input} value={design.backgroundUrl||""} onChangeText={(v)=>patchDesign({backgroundUrl:v.trim()||null})} autoCapitalize="none"/></Field></View>

      <View style={s.card}><Text style={s.cardTitle}>Добавить элемент</Text><View style={s.chips}>{BINDINGS.map((b)=><TouchableOpacity key={b.id} style={s.chip} onPress={()=>add(b.id)}><Text style={s.chipText}>+ {b.label}</Text></TouchableOpacity>)}</View></View>

      {item&&<View style={s.card}><View style={s.between}><Text style={s.cardTitle}>{BINDINGS.find((b)=>b.id===item.binding)?.label||item.binding}</Text>{item.binding!=="QR"&&<TouchableOpacity onPress={remove}><Text style={s.delete}>Удалить</Text></TouchableOpacity>}</View>{item.binding==="CUSTOM"||item.binding==="IMAGE"?<Field label={item.binding==="IMAGE"?"URL изображения":"Текст"}><TextInput style={[s.input,item.binding==="CUSTOM"&&s.multi]} multiline={item.binding==="CUSTOM"} value={item.content} onChangeText={(content)=>patchItem({content})}/></Field>:null}<View style={s.grid}><Num label="X %" value={item.x} onChange={(x)=>patchItem({x:clamp(x,0,100)})}/><Num label="Y %" value={item.y} onChange={(y)=>patchItem({y:clamp(y,0,100)})}/><Num label="Ширина %" value={item.width} onChange={(width)=>patchItem({width:clamp(width,5,100)})}/><Num label="Высота %" value={item.height} onChange={(height)=>patchItem({height:clamp(height,3,100)})}/><Num label="Шрифт" value={item.fontSize} onChange={(fontSize)=>patchItem({fontSize:clamp(fontSize,8,54)})}/></View><Field label="Цвет"><TextInput style={s.input} value={item.color} onChangeText={(color)=>patchItem({color})} autoCapitalize="characters"/></Field><Text style={s.label}>Выравнивание</Text><View style={s.chips}>{(["left","center","right"] as const).map((a)=><TouchableOpacity key={a} style={[s.chip,item.align===a&&s.chipOn]} onPress={()=>patchItem({align:a})}><Text style={[s.chipText,item.align===a&&s.chipTextOn]}>{a==="left"?"Слева":a==="center"?"По центру":"Справа"}</Text></TouchableOpacity>)}</View><Toggle label="Жирный" value={item.bold} onChange={(bold)=>patchItem({bold})}/><Toggle label="Скрыть элемент" value={item.hidden} onChange={(hidden)=>patchItem({hidden})}/></View>}
    </ScrollView>
  </SafeAreaView>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <View style={{marginBottom:12}}><Text style={s.label}>{label}</Text>{children}</View>}
function Num({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <View style={s.num}><Text style={s.label}>{label}</Text><TextInput style={s.input} keyboardType="decimal-pad" value={String(Math.round(value))} onChangeText={(v)=>onChange(Number(v||0))}/></View>}
function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <View style={s.toggle}><Text style={{flex:1,color:"#344054",fontWeight:"700"}}>{label}</Text><Switch value={value} onValueChange={onChange}/></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#F5F6FA"},center:{flex:1,alignItems:"center",justifyContent:"center"},header:{minHeight:70,backgroundColor:"#fff",borderBottomWidth:1,borderBottomColor:"#E5E7ED",paddingHorizontal:10,flexDirection:"row",alignItems:"center",gap:8},icon:{width:42,height:42,alignItems:"center",justifyContent:"center"},headerTitle:{fontSize:18,fontWeight:"900",color:"#17213C"},meta:{fontSize:11,color:"#7B8498",marginTop:2},saveTop:{minWidth:92,height:42,borderRadius:13,backgroundColor:"#6D45FF",alignItems:"center",justifyContent:"center",paddingHorizontal:12},saveTopText:{color:"#fff",fontWeight:"900"},content:{padding:16,paddingBottom:100},section:{fontSize:25,fontWeight:"900",color:"#17213C",marginBottom:12},ticket:{height:430,borderRadius:22,overflow:"hidden",position:"relative",marginBottom:16,borderWidth:1,borderColor:"#DCE0E8"},logoHint:{position:"absolute",top:16,right:16,color:"#fff",opacity:.7,fontWeight:"900"},previewItem:{position:"absolute",borderWidth:2,borderRadius:6,padding:3},card:{backgroundColor:"#fff",borderWidth:1,borderColor:"#E1E4EC",borderRadius:18,padding:15,marginBottom:13},cardTitle:{fontSize:17,fontWeight:"900",color:"#17213C",marginBottom:10},label:{fontSize:12,fontWeight:"800",color:"#5C667B",marginBottom:6},input:{minHeight:46,borderWidth:1,borderColor:"#DDE1EA",borderRadius:12,backgroundColor:"#fff",paddingHorizontal:11,color:"#17213C"},multi:{minHeight:80,paddingTop:10},row:{flexDirection:"row",gap:9},half:{flex:1},chips:{flexDirection:"row",flexWrap:"wrap",gap:7,marginBottom:8},chip:{borderRadius:18,paddingHorizontal:11,paddingVertical:8,backgroundColor:"#EEF0F5"},chipOn:{backgroundColor:"#EEE9FF",borderWidth:1,borderColor:"#6D45FF"},chipText:{fontSize:11.5,fontWeight:"800",color:"#586277"},chipTextOn:{color:"#5437DD"},between:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},delete:{color:"#B42318",fontWeight:"900"},grid:{flexDirection:"row",flexWrap:"wrap",gap:8,marginBottom:8},num:{width:"31%"},toggle:{minHeight:46,borderBottomWidth:1,borderBottomColor:"#EEF0F4",flexDirection:"row",alignItems:"center"}});
