"use client";

import {useState} from "react";
import {useLocale} from "@/components/locale-provider";
import {localeConfig} from "@/lib/i18n";

type EventOption={id:string;title:string;startsAt:string;status:string;organization:string};
const copy={ru:{saveError:"Не удалось сохранить",saved:"Бегущая строка сохранена.",error:"Ошибка сохранения",available:"Доступные мероприятия",availableHelp:"Можно добавить только опубликованные мероприятия.",add:"Добавить",allAdded:"Все опубликованные мероприятия уже добавлены.",shown:"Показываются на главной",orderHelp:"Порядок сверху вниз соответствует порядку в строке.",saving:"Сохраняем...",save:"Сохранить",remove:"Убрать",empty:"Список пуст. Бегущая строка на главной будет скрыта."},he:{saveError:"לא ניתן לשמור",saved:"שורת האירועים נשמרה.",error:"שגיאה בשמירה",available:"אירועים זמינים",availableHelp:"אפשר להוסיף רק אירועים שפורסמו.",add:"הוספה",allAdded:"כל האירועים שפורסמו כבר נוספו.",shown:"מוצגים בעמוד הבית",orderHelp:"הסדר מלמעלה למטה הוא סדר ההצגה בשורה.",saving:"שומרים...",save:"שמירה",remove:"הסרה",empty:"הרשימה ריקה. שורת האירועים בעמוד הבית תוסתר."},en:{saveError:"Could not save",saved:"Event marquee saved.",error:"Save failed",available:"Available events",availableHelp:"Only published events can be added.",add:"Add",allAdded:"All published events have already been added.",shown:"Shown on homepage",orderHelp:"Top-to-bottom order matches the marquee order.",saving:"Saving...",save:"Save",remove:"Remove",empty:"The list is empty. The homepage marquee will be hidden."}} as const;
export function MarqueeEditor({available,initialSelected}:{available:EventOption[];initialSelected:string[]}){const{locale}=useLocale();const t=copy[locale];const[selected,setSelected]=useState(initialSelected);const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");const selectedSet=new Set(selected);const move=(index:number,direction:-1|1)=>{const next=[...selected];const target=index+direction;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setSelected(next);};const save=async()=>{setSaving(true);setMessage("");try{const response=await fetch("/api/platform/homepage/marquee",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({eventIds:selected})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||t.saveError);setMessage(t.saved);}catch(error){setMessage(error instanceof Error?error.message:t.error);}finally{setSaving(false);}};const byId=new Map(available.map(event=>[event.id,event]));return <div className="form-grid two" style={{alignItems:"start"}}><section className="panel"><h2>{t.available}</h2><p className="muted">{t.availableHelp}</p><div style={{display:"grid",gap:10}}>{available.filter(event=>!selectedSet.has(event.id)).map(event=><div className="row between" key={event.id}><div><strong>{event.title}</strong><br/><small>{event.organization} · <bdi>{new Date(event.startsAt).toLocaleDateString(localeConfig[locale].tag,{timeZone:"Asia/Jerusalem"})}</bdi></small></div><button className="btn secondary" type="button" onClick={()=>setSelected([...selected,event.id])}>{t.add}</button></div>)}{available.every(event=>selectedSet.has(event.id))&&<p className="muted">{t.allAdded}</p>}</div></section><section className="panel"><div className="row between"><div><h2 style={{marginBottom:4}}>{t.shown}</h2><p className="muted" style={{margin:0}}>{t.orderHelp}</p></div><button className="btn" type="button" disabled={saving} onClick={save}>{saving?t.saving:t.save}</button></div>{message&&<div className="toast" style={{marginTop:12}}>{message}</div>}<div style={{display:"grid",gap:10,marginTop:16}}>{selected.map((id,index)=>{const event=byId.get(id);if(!event)return null;return <div className="row between" key={id}><div><strong>{index+1}. {event.title}</strong><br/><small>{event.organization}</small></div><div className="row" style={{gap:6}}><button className="btn secondary" type="button" disabled={index===0} onClick={()=>move(index,-1)}>↑</button><button className="btn secondary" type="button" disabled={index===selected.length-1} onClick={()=>move(index,1)}>↓</button><button className="btn secondary" type="button" onClick={()=>setSelected(selected.filter(item=>item!==id))}>{t.remove}</button></div></div>})}{selected.length===0&&<p className="muted">{t.empty}</p>}</div></section></div>}
