import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin-shell";
import { PromoterV2Detail } from "@/components/promoter-v2-detail";
import { requirePermission } from "@/lib/auth";
import { resolveStaffLocale } from "@/lib/i18n";
import { db } from "@/lib/db";
import { money } from "@/lib/format";
import { refreshAbandonedCheckoutStatuses } from "@/lib/abandoned-maintenance";
import { getPromoterV2 } from "@/lib/promoter-v2";
import { promoterV2AssignmentAnalytics } from "@/lib/promoter-v2-analytics";
import { promoterAccountV2State } from "@/lib/promoter-auth-v2";

export const dynamic="force-dynamic";
const PERIOD_VALUES=["7d","30d","month","all"] as const;type PeriodKey=(typeof PERIOD_VALUES)[number];
const copy={
 ru:{back:"← Промоутеры",active:"Активен",archived:"Архивирован",period:"Период",apply:"Применить",clicks:"Клики",checkouts:"Checkout",abandoned:"Abandoned",recovered:"Recovered",orders:"Заказы",tickets:"билетов",revenue:"Выручка",conversion:"конверсия",noManage:"У вас есть доступ к аналитике, но нет прав на управление промоутером.",periods:{"7d":"7 дней","30d":"30 дней",month:"Этот месяц",all:"Всё время"}},
 he:{back:"← מקדמים",active:"פעיל",archived:"בארכיון",period:"תקופה",apply:"החלה",clicks:"קליקים",checkouts:"Checkout",abandoned:"Abandoned",recovered:"Recovered",orders:"הזמנות",tickets:"כרטיסים",revenue:"הכנסות",conversion:"המרה",noManage:"יש לכם גישה לנתוני הניתוח, אך אין הרשאה לנהל את המקדם.",periods:{"7d":"7 ימים","30d":"30 ימים",month:"החודש",all:"כל התקופה"}},
 en:{back:"← Promoters",active:"Active",archived:"Archived",period:"Period",apply:"Apply",clicks:"Clicks",checkouts:"Checkout",abandoned:"Abandoned",recovered:"Recovered",orders:"Orders",tickets:"tickets",revenue:"Revenue",conversion:"conversion",noManage:"You can view analytics but do not have permission to manage this promoter.",periods:{"7d":"7 days","30d":"30 days",month:"This month",all:"All time"}}
} as const;
function start(period:PeriodKey){const now=new Date();if(period==="all")return undefined;if(period==="month")return new Date(now.getFullYear(),now.getMonth(),1);const d=new Date(now);d.setHours(0,0,0,0);d.setDate(d.getDate()-(period==="7d"?6:29));return d;}

export default async function PromoterDetailPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|undefined>>}){
 const staff=await requirePermission("ANALYTICS_VIEW");const locale=resolveStaffLocale({memberOverride:staff.interfaceLocaleOverride,userPreference:staff.preferredLocale,organizationDefault:staff.organization?.defaultStaffLocale});const text=copy[locale];const{id}=await params;const query=await searchParams;const promoter=await getPromoterV2(id);if(!promoter)notFound();if(staff.role!=="ADMIN"&&staff.organizationId!==promoter.organizationId)notFound();
 const period=PERIOD_VALUES.includes(query.period as PeriodKey)?query.period as PeriodKey:"30d";const from=start(period);await refreshAbandonedCheckoutStatuses();const allowed=staff.eventAccess.map(x=>x.eventId);const events=await db.event.findMany({where:{organizationId:promoter.organizationId,...(staff.role!=="ADMIN"&&allowed.length?{id:{in:allowed}}:{})},select:{id:true,title:true,status:true},orderBy:{startsAt:"desc"}});const[assignments,accountState]=await Promise.all([promoterV2AssignmentAnalytics(promoter.id,from),promoterAccountV2State(promoter.id)]);const clicks=assignments.reduce((s,x)=>s+x.clicks,0),checkouts=assignments.reduce((s,x)=>s+x.checkouts,0),abandoned=assignments.reduce((s,x)=>s+x.abandoned,0),recovered=assignments.reduce((s,x)=>s+x.recovered,0),orders=assignments.reduce((s,x)=>s+x.orders,0),tickets=assignments.reduce((s,x)=>s+x.tickets,0),revenue=assignments.reduce((s,x)=>s+x.revenue,0),conversion=clicks?orders/clicks*100:0;const label=text.periods[period];
 return <AdminShell><div className="office-page-heading"><div><Link href="/office/promoters">{text.back}</Link><span className="eyebrow">Promoter V2</span><h1>{promoter.name}</h1><p className="muted"><bdi>{promoter.email}</bdi>{promoter.phone?<><span> · </span><bdi>{promoter.phone}</bdi></>:null}</p></div><span className="pill">{promoter.active?text.active:text.archived}</span></div><form className="panel" method="get" style={{display:"flex",gap:12,alignItems:"end",flexWrap:"wrap",marginBottom:24}}><div className="field" style={{margin:0,minWidth:180}}><label>{text.period}</label><select name="period" defaultValue={period}>{PERIOD_VALUES.map(value=><option key={value} value={value}>{text.periods[value]}</option>)}</select></div><button className="btn dark">{text.apply}</button></form><div className="stats"><div className="stat"><span className="muted">{text.clicks}</span><strong>{clicks}</strong><small>{label}</small></div><div className="stat"><span className="muted">{text.checkouts}</span><strong>{checkouts}</strong><small>{label}</small></div><div className="stat"><span className="muted">{text.abandoned}</span><strong>{abandoned}</strong><small>{label}</small></div><div className="stat"><span className="muted">{text.recovered}</span><strong>{recovered}</strong><small>{label}</small></div><div className="stat"><span className="muted">{text.orders}</span><strong>{orders}</strong><small>{tickets} {text.tickets}</small></div><div className="stat"><span className="muted">{text.revenue}</span><strong><bdi>{money(revenue)}</bdi></strong><small>{text.conversion} <bdi>{conversion.toFixed(1)}%</bdi></small></div></div>{staff.permissionSet.has("EVENT_MANAGE")?<div style={{marginTop:24}}><PromoterV2Detail promoter={{id:promoter.id,name:promoter.name,email:promoter.email,phone:promoter.phone,active:promoter.active,autoAssignAllEvents:promoter.autoAssignAllEvents,defaultCommissionBps:promoter.defaultCommissionBps}} events={events.map(e=>({id:e.id,title:e.title,status:e.status}))} assignments={assignments} accountState={accountState}/></div>:<div className="panel" style={{marginTop:24}}><p className="muted">{text.noManage}</p></div>}</AdminShell>;
}
