import type { Metadata } from "next";
import { ContentPage, Section } from "@/components/content-page";
import { getServerI18n } from "@/lib/server-locale";
import type { Locale } from "@/lib/i18n";

const copy={
  ru:{meta:"Политика конфиденциальности",description:"Как Atlas One обрабатывает персональные данные покупателей и организаторов.",title:"Политика конфиденциальности",intro:"Основные принципы обработки данных в Atlas One.",sections:[["Какие данные мы используем","Контактные данные, сведения заказа, ответы на вопросы организатора, технические журналы и данные, необходимые для поддержки и предотвращения злоупотреблений."],["Платёжные данные","Данные банковской карты вводятся на защищённой странице платёжного провайдера и не хранятся Atlas One."],["Зачем нужны данные","Для оформления и доставки билета, поддержки, возвратов, безопасности, аналитики и выполнения юридических обязательств."],["Ваши права","Вы можете обратиться в поддержку по вопросам доступа, исправления или удаления данных в пределах, допускаемых законом."]]},
  he:{meta:"מדיניות הפרטיות",description:"כיצד Atlas One מטפלת במידע אישי של רוכשי כרטיסים ומפיקים.",title:"מדיניות הפרטיות",intro:"העקרונות המרכזיים שלפיהם Atlas One מטפלת במידע.",sections:[["איזה מידע משמש אותנו","פרטי קשר, פרטי הזמנה, תשובות לשאלות שהגדיר המפיק, יומנים טכניים ומידע הדרוש לתמיכה ולמניעת שימוש לרעה."],["פרטי תשלום","פרטי כרטיס האשראי מוזנים בעמוד המאובטח של ספק התשלומים ואינם נשמרים ב-Atlas One."],["למה המידע נחוץ","כדי להשלים ולמסור כרטיסים, לספק תמיכה, לטפל בביטולים, לשמור על אבטחה, לבצע ניתוחים ולעמוד בחובות על פי דין."],["הזכויות שלכם","ניתן לפנות לתמיכה בבקשה לעיין במידע, לתקן אותו או למחוק אותו, בכפוף להוראות הדין."]]},
  en:{meta:"Privacy policy",description:"How Atlas One handles personal data belonging to ticket buyers and organizers.",title:"Privacy policy",intro:"The main principles governing how Atlas One handles data.",sections:[["Data we use","Contact details, order information, answers to organizer questions, technical logs, and data needed for support and abuse prevention."],["Payment data","Card details are entered on the payment provider's secure page and are not stored by Atlas One."],["Why we need data","To process and deliver tickets, provide support, handle cancellations, maintain security, run analytics, and meet legal obligations."],["Your rights","You can contact support to request access, correction, or deletion where permitted by law."]]},
} satisfies Record<Locale,{meta:string;description:string;title:string;intro:string;sections:string[][]}>;
export async function generateMetadata():Promise<Metadata>{const{locale}=await getServerI18n();const text=copy[locale];return{title:text.meta,description:text.description,alternates:{canonical:"/privacy"}};}
export default async function PrivacyPage(){const{locale}=await getServerI18n();const text=copy[locale];return <ContentPage eyebrow="Legal" title={text.title} intro={text.intro}>{text.sections.map(([title,body])=><Section key={title} title={title}><p>{body}</p></Section>)}</ContentPage>}
