import {requirePromoterV2} from "@/lib/promoter-auth-v2";
import {promoterV2AssignmentAnalytics} from "@/lib/promoter-v2-analytics";
import {db} from "@/lib/db";
import {money} from "@/lib/format";
import {getServerI18n} from "@/lib/server-locale";
import {localeConfig} from "@/lib/i18n";

function publicOrigin(){if(process.env.VERCEL_ENV==="preview"&&process.env.VERCEL_URL)return `https://${process.env.VERCEL_URL}`;return(process.env.PUBLIC_APP_URL||"https://www.atlas-one.co").replace(/\/$/,"")}
const copy={ru:{eyebrow:"Мои назначения",title:"Мероприятия",help:"Для продвижения используйте персональную ссылку конкретного мероприятия.",active:"Активна",inactive:"Неактивна",clicks:"Клики",checkout:"Checkout",abandoned:"Abandoned",recovered:"Recovered",orders:"Заказы",tickets:"Билеты",sales:"Продажи",link:"Персональная ссылка",afterPublish:"Ссылка активируется после публикации мероприятия",empty:"Пока нет назначенных мероприятий."},he:{eyebrow:"ההקצאות שלי",title:"אירועים",help:"לקידום האירוע השתמשו בקישור האישי של האירוע הרלוונטי.",active:"פעיל",inactive:"לא פעיל",clicks:"קליקים",checkout:"Checkout",abandoned:"נטישות",recovered:"חזרו לרכישה",orders:"הזמנות",tickets:"כרטיסים",sales:"מכירות",link:"קישור אישי",afterPublish:"הקישור יופעל לאחר פרסום האירוע",empty:"עדיין לא הוקצו אירועים."},en:{eyebrow:"My assignments",title:"Events",help:"Use the event-specific personal link when promoting an event.",active:"Active",inactive:"Inactive",clicks:"Clicks",checkout:"Checkout",abandoned:"Abandoned",recovered:"Recovered",orders:"Orders",tickets:"Tickets",sales:"Sales",link:"Personal link",afterPublish:"The link becomes active after the event is published",empty:"No events are assigned yet."}} as const;
export default async function PromoterEventsPage(){const[promoter,{locale}]=await Promise.all([requirePromoterV2(),getServerI18n()]);const t=copy[locale];const assignments=await promoterV2AssignmentAnalytics(promoter.id);const events=await db.event.findMany({where:{id:{in:assignments.map(a=>a.eventId)}},include:{venue:true}});const byId=new Map(events.map(e=>[e.id,e]));const origin=publicOrigin();const dateLocale=localeConfig[locale].tag;return <><div><div style={{fontSize:13,textTransform:"uppercase",letterSpacing:".12em",color:"#667085"}}>{t.eyebrow}</div><h1 style={{fontSize:34,margin:"8px 0"}}>{t.title}</h1><p style={{color:"#667085"}}>{t.help}</p></div><div style={{display:"grid",gap:16,marginTop:24}}>{assignments.map(a=>{const event=byId.get(a.eventId);const shareUrl=`${origin}/events/${a.eventSlug}?channel=${encodeURIComponent(a.code)}`;return <div key={a.id} style={{background:"white",border:"1px solid #eaecf0",borderRadius:18,padding:22}}><div style={{display:"flex",justifyContent:"space-between",gap:16,flexWrap:"wrap"}}><div><h2 style={{margin:"0 0 6px"}}>{a.eventTitle}</h2><div style={{color:"#667085"}}>{event?<><bdi>{event.startsAt.toLocaleString(dateLocale,{timeZone:"Asia/Jerusalem"})}</bdi> · {event.venue.name}, {event.venue.city}</>:null}</div></div><span style={{alignSelf:"start",padding:"6px 10px",borderRadius:999,background:a.active&&a.eventStatus==="PUBLISHED"?"#dcfae6":"#f2f4f7",color:a.active&&a.eventStatus==="PUBLISHED"?"#067647":"#475467"}}>{a.eventStatus==="PUBLISHED"&&a.active?t.active:t.inactive}</span></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(110px,1fr))",gap:10,marginTop:18}}>{[[t.clicks,a.clicks],[t.checkout,a.checkouts],[t.abandoned,a.abandoned],[t.recovered,a.recovered],[t.orders,a.orders],[t.tickets,a.tickets],[t.sales,money(a.revenue,"ILS",locale)]].map(([l,v])=><div key={String(l)} style={{background:"#f8fafc",borderRadius:12,padding:14}}><div style={{fontSize:12,color:"#667085"}}>{l}</div><strong style={{display:"block",fontSize:20,marginTop:4}}>{v}</strong></div>)}</div><div style={{marginTop:18,padding:14,background:"#f8fafc",borderRadius:12,wordBreak:"break-all"}}><div style={{fontSize:12,color:"#667085",marginBottom:6}}>{t.link}</div>{a.eventStatus==="PUBLISHED"?<a href={shareUrl} target="_blank" rel="noreferrer" dir="ltr" style={{textAlign:"left",display:"inline-block"}}>{shareUrl}</a>:<span style={{color:"#667085"}}>{t.afterPublish}</span>}</div></div>})}{!assignments.length&&<div style={{background:"white",borderRadius:16,padding:24}}>{t.empty}</div>}</div></>}
