import { requirePromoter } from "@/lib/promoter-auth";
import { db } from "@/lib/db";
import { money } from "@/lib/format";

const PUBLIC_ORIGIN=(process.env.PUBLIC_APP_URL||"https://www.atlas-one.co").replace(/\/$/,"");

export default async function PromoterEventsPage(){
 const promoter=await requirePromoter();
 const links=await db.promoterLink.findMany({where:{promoterId:promoter.id},include:{event:{include:{venue:true}},visits:true,orders:{where:{status:'PAID'},include:{items:true}}},orderBy:{event:{startsAt:'desc'}}});
 return <><div><div style={{fontSize:13,textTransform:'uppercase',letterSpacing:'.12em',color:'#667085'}}>Мои назначения</div><h1 style={{fontSize:34,margin:'8px 0'}}>Мероприятия</h1><p style={{color:'#667085'}}>Для продвижения используйте только персональную ссылку конкретного мероприятия.</p></div><div style={{display:'grid',gap:16,marginTop:24}}>{links.map(link=>{const tickets=link.orders.reduce((s,o)=>s+o.items.reduce((x,i)=>x+i.quantity,0),0);const revenue=link.orders.reduce((s,o)=>s+o.totalMinor,0);const shareUrl=`${PUBLIC_ORIGIN}/events/${link.event.slug}?channel=${encodeURIComponent(link.code)}`;return <div key={link.id} style={{background:'white',border:'1px solid #eaecf0',borderRadius:18,padding:22}}><div style={{display:'flex',justifyContent:'space-between',gap:16,flexWrap:'wrap'}}><div><h2 style={{margin:'0 0 6px'}}>{link.event.title}</h2><div style={{color:'#667085'}}>{link.event.startsAt.toLocaleString('ru-RU')} · {link.event.venue.name}, {link.event.venue.city}</div></div><span style={{alignSelf:'start',padding:'6px 10px',borderRadius:999,background:link.active?'#dcfae6':'#f2f4f7',color:link.active?'#067647':'#475467'}}>{link.active?'Активна':'Отключена'}</span></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(120px,1fr))',gap:10,marginTop:18}}>{[['Клики',link.visits.length],['Заказы',link.orders.length],['Билеты',tickets],['Продажи',money(revenue)]].map(([l,v])=><div key={String(l)} style={{background:'#f8fafc',borderRadius:12,padding:14}}><div style={{fontSize:12,color:'#667085'}}>{l}</div><strong style={{display:'block',fontSize:20,marginTop:4}}>{v}</strong></div>)}</div><div style={{marginTop:18,padding:14,background:'#f8fafc',borderRadius:12,wordBreak:'break-all'}}><div style={{fontSize:12,color:'#667085',marginBottom:6}}>Персональная ссылка</div><a href={shareUrl} target='_blank' rel='noreferrer'>{shareUrl}</a></div></div>})}{!links.length&&<div style={{background:'white',borderRadius:16,padding:24}}>Пока нет назначенных мероприятий.</div>}</div></>;
}
