import { requirePromoterV2 } from "@/lib/promoter-auth-v2";
import { promoterV2AssignmentAnalytics } from "@/lib/promoter-v2-analytics";
import { db } from "@/lib/db";
import { money } from "@/lib/format";

function publicOrigin(){if(process.env.VERCEL_ENV==="preview"&&process.env.VERCEL_URL)return `https://${process.env.VERCEL_URL}`;return(process.env.PUBLIC_APP_URL||"https://www.atlas-one.co").replace(/\/$/,"")}

export default async function PromoterEventsPage(){
 const promoter=await requirePromoterV2();
 const assignments=await promoterV2AssignmentAnalytics(promoter.id);
 const events=await db.event.findMany({where:{id:{in:assignments.map(a=>a.eventId)}},include:{venue:true}});const byId=new Map(events.map(e=>[e.id,e]));const origin=publicOrigin();
 return <><div><div style={{fontSize:13,textTransform:"uppercase",letterSpacing:".12em",color:"#667085"}}>Мои назначения</div><h1 style={{fontSize:34,margin:"8px 0"}}>Мероприятия</h1><p style={{color:"#667085"}}>Для продвижения используйте персональную ссылку конкретного мероприятия.</p></div><div style={{display:"grid",gap:16,marginTop:24}}>{assignments.map(a=>{const event=byId.get(a.eventId);const shareUrl=`${origin}/events/${a.eventSlug}?channel=${encodeURIComponent(a.code)}`;return <div key={a.id} style={{background:"white",border:"1px solid #eaecf0",borderRadius:18,padding:22}}><div style={{display:"flex",justifyContent:"space-between",gap:16,flexWrap:"wrap"}}><div><h2 style={{margin:"0 0 6px"}}>{a.eventTitle}</h2><div style={{color:"#667085"}}>{event?`${event.startsAt.toLocaleString("ru-RU")} · ${event.venue.name}, ${event.venue.city}`:""}</div></div><span style={{alignSelf:"start",padding:"6px 10px",borderRadius:999,background:a.active&&a.eventStatus==="PUBLISHED"?"#dcfae6":"#f2f4f7",color:a.active&&a.eventStatus==="PUBLISHED"?"#067647":"#475467"}}>{a.eventStatus==="PUBLISHED"&&a.active?"Активна":"Неактивна"}</span></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(110px,1fr))",gap:10,marginTop:18}}>{[["Клики",a.clicks],["Checkout",a.checkouts],["Abandoned",a.abandoned],["Recovered",a.recovered],["Заказы",a.orders],["Билеты",a.tickets],["Продажи",money(a.revenue)]].map(([l,v])=><div key={String(l)} style={{background:"#f8fafc",borderRadius:12,padding:14}}><div style={{fontSize:12,color:"#667085"}}>{l}</div><strong style={{display:"block",fontSize:20,marginTop:4}}>{v}</strong></div>)}</div><div style={{marginTop:18,padding:14,background:"#f8fafc",borderRadius:12,wordBreak:"break-all"}}><div style={{fontSize:12,color:"#667085",marginBottom:6}}>Персональная ссылка</div>{a.eventStatus==="PUBLISHED"?<a href={shareUrl} target="_blank" rel="noreferrer">{shareUrl}</a>:<span style={{color:"#667085"}}>Ссылка активируется после публикации мероприятия</span>}</div></div>})}{!assignments.length&&<div style={{background:"white",borderRadius:16,padding:24}}>Пока нет назначенных мероприятий.</div>}</div></>;
}
