import { NextResponse } from "next/server";
import { z } from "zod";
import { db } from "@/lib/db";
import { requirePermission } from "@/lib/auth";
import { allPermissions } from "@/lib/permissions";
import { writeAudit } from "@/lib/audit";

const schema=z.object({staffRole:z.enum(["OWNER","ADMIN","EVENT_MANAGER","APPROVER","CHECKIN","ANALYST","CUSTOM"]),jobTitle:z.string().max(100).nullable().optional(),active:z.boolean(),permissions:z.array(z.enum(allPermissions as [typeof allPermissions[number],...typeof allPermissions])),eventIds:z.array(z.string()).max(100)});
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){try{const actor=await requirePermission("TEAM_MANAGE");const {id}=await params;const input=schema.parse(await request.json());const member=await db.user.findUniqueOrThrow({where:{id},include:{permissions:true}});if(member.organizationId!==actor.organizationId)throw new Error("Сотрудник другой организации");if(member.staffRole==="OWNER"&&(input.staffRole!=="OWNER"||!input.active))throw new Error("Владельца нельзя отключить или понизить");const eventCount=await db.event.count({where:{id:{in:input.eventIds},organizationId:actor.organizationId!}});if(eventCount!==new Set(input.eventIds).size)throw new Error("Некоторые мероприятия недоступны");await db.$transaction(async tx=>{await tx.permissionGrant.deleteMany({where:{userId:id}});await tx.eventStaffAccess.deleteMany({where:{userId:id}});await tx.user.update({where:{id},data:{staffRole:input.staffRole,jobTitle:input.jobTitle||null,active:input.active,role:input.staffRole==="CHECKIN"?"CHECKIN":"ORGANIZER",permissions:{create:(input.staffRole==="OWNER"?allPermissions:input.permissions).map(permission=>({permission}))},eventAccess:{create:input.eventIds.map(eventId=>({eventId}))}}})});await writeAudit(actor,{action:"TEAM_PERMISSIONS_UPDATED",entityType:"User",entityId:id,summary:`Изменены права сотрудника ${member.name}`,metadata:{permissions:input.permissions,eventIds:input.eventIds,active:input.active}});return NextResponse.json({ok:true})}catch(error){const message=error instanceof Error?error.message:"Ошибка";return NextResponse.json({error:message==="FORBIDDEN"?"Недостаточно прав":message},{status:message==="FORBIDDEN"?403:400})}}
