import {requirePromoterV2} from "@/lib/promoter-auth-v2";
import {listAssignmentsV2} from "@/lib/promoter-v2";
import {db} from "@/lib/db";
import {money} from "@/lib/format";
import {getServerI18n} from "@/lib/server-locale";
import {localeConfig} from "@/lib/i18n";

type SaleRow={id:string;createdAt:Date;eventTitle:string;totalMinor:number;tickets:number};
const copy={ru:{eyebrow:"Мои продажи",title:"Продажи",help:"Показываются только оплаченные заказы, атрибутированные вашим V2 channel-ссылкам. Персональные данные покупателей скрыты.",date:"Дата",event:"Мероприятие",tickets:"Билеты",amount:"Сумма",empty:"Продаж пока нет."},he:{eyebrow:"המכירות שלי",title:"מכירות",help:"מוצגות רק הזמנות ששולמו ושויכו לקישורי ה-channel שלך. פרטי הרוכשים אינם מוצגים.",date:"תאריך",event:"אירוע",tickets:"כרטיסים",amount:"סכום",empty:"עדיין אין מכירות."},en:{eyebrow:"My sales",title:"Sales",help:"Only paid orders attributed to your V2 channel links are shown. Buyer personal data is hidden.",date:"Date",event:"Event",tickets:"Tickets",amount:"Amount",empty:"No sales yet."}} as const;
export default async function PromoterSalesPage(){const[promoter,{locale}]=await Promise.all([requirePromoterV2(),getServerI18n()]);const t=copy[locale];const assignments=await listAssignmentsV2(promoter.id);const codes=assignments.map(a=>a.code);const orders=codes.length?await db.$queryRawUnsafe<SaleRow[]>(`SELECT o."id",o."createdAt",e."title" AS "eventTitle",o."totalMinor",COALESCE(SUM(oi."quantity"),0)::int AS "tickets" FROM "Order" o JOIN "Referral" r ON r."id"=o."referralId" JOIN "Event" e ON e."id"=o."eventId" LEFT JOIN "OrderItem" oi ON oi."orderId"=o."id" WHERE o."status"='PAID' AND UPPER(r."code")=ANY($1::text[]) GROUP BY o."id",e."title" ORDER BY o."createdAt" DESC LIMIT 200`,codes.map(c=>c.toUpperCase())):[];return <><div><div style={{fontSize:13,textTransform:"uppercase",letterSpacing:".12em",color:"#667085"}}>{t.eyebrow}</div><h1 style={{fontSize:34,margin:"8px 0"}}>{t.title}</h1><p style={{color:"#667085"}}>{t.help}</p></div><div style={{marginTop:24,background:"white",border:"1px solid #eaecf0",borderRadius:16,overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr>{[t.date,t.event,t.tickets,t.amount].map(h=><th key={h} style={{textAlign:"start",padding:14,borderBottom:"1px solid #eaecf0",color:"#667085",fontSize:12}}>{h}</th>)}</tr></thead><tbody>{orders.map(o=><tr key={o.id}><td style={{padding:14,borderBottom:"1px solid #f2f4f7"}}><bdi>{o.createdAt.toLocaleString(localeConfig[locale].tag,{timeZone:"Asia/Jerusalem"})}</bdi></td><td style={{padding:14,borderBottom:"1px solid #f2f4f7"}}>{o.eventTitle}</td><td style={{padding:14,borderBottom:"1px solid #f2f4f7"}}>{o.tickets}</td><td style={{padding:14,borderBottom:"1px solid #f2f4f7"}}><strong><bdi>{money(o.totalMinor,"ILS",locale)}</bdi></strong></td></tr>)}{!orders.length&&<tr><td colSpan={4} style={{padding:22,color:"#667085"}}>{t.empty}</td></tr>}</tbody></table></div></>}
